### ISSUE TITLE
Title header does not fit into bar with increased font size

### ISSUE THREAD

**Issue by doompadee** [CDrummond/lms-material#1000]
The text information of the secondary bar is clipped with increased font size. This happens on multiple screens for me with Firefox zoom factor set to 133%  and "Zoom text only" is enabled.

Please see attached screenshot, upper left corner.

**Comment by doompadee** [comment]
Screenshot

**Comment by CDrummond** [comment]
...and as Firefox warns you, this can break some sites - as it does here.

**Comment by doompadee** [comment]
It's not a given and could be addressed. Would you be open for a PR?

I don't know whether the code base allows this, maybe least intrusive would be a change just for the desktop that puts the secondary title behind instead of below.

**Comment by CDrummond** [comment]
But you can't just increase the font zoom. Some of Material's icons are from a font file, others are SVG icons. This leads to a mix of icon sizes that just looks awful.

**Comment by doompadee** [comment]
I don't follow, both icon formats are perfectly scalable. You just have to make their size dependent on the used font. But the problem here has nothing to with icons. The subtoolbar uses a fixed height (`--sub-toolbar-height`) that does not provide enough space if the titles use bigger fonts because of 'zoom text only' mode. If I use a relative size for the height, the problem goes away. That would be the proper way to do it, IMHO.

But my proposed fix would not involve any sizing at all. Everything can stay the same, just the layout of the two titles could be changed to be in a single line on desktop (where there is enough horizontal space). To make it look nicer, all elements should be aligned vertically, then.
