### ISSUE TITLE
Grouping for compilations

### ISSUE THREAD

**Issue by darrell-k** [CDrummond/lms-material#1005]
The new grouping code is not working well for compilations. Might be because of the sequence of results from LMS, or ...?

Thoughts?

**Comment by CDrummond** [comment]
Broken how, and where? Seems fine to me, both browse and queue

**Comment by darrell-k** [comment]
Was just about to attach the JSON response, but noticed an obvious problem: no track numbers in the album, so LMS isn't going to do a very good job with the sort!

I'll, close this issue, sorry for the false alarm. But perhaps the LMS scanner should do a slightly better job with data like this, maybe assign track numbers on the basis that the file names are probably in sequence.
