### ISSUE TITLE
Latest release breaks LMS on Windows Home Server

### ISSUE THREAD

**Issue by jllong22** [CDrummond/lms-material#1013]
After updating to Material Skin 5.7.1 on Microsoft Windows Home Server 2011 LMS becomes unresponsive.
Multiple WHS restarts and LMS service restarts did not resolve the issue.
To get LMS responsive I removed Material Skin related files then reset the interface to default.

**Comment by CDrummond** [comment]
Sorry, but I really cannot see this being a Material issue. There is no Windows specific code, and if Material was preventing startup, etc, it'd affect all OS's.

**Comment by CDrummond** [comment]
I suggest you create a new topic on https://forums.slimdevices.com for this, as its highly unlikely Material is the cause of this.
