### ISSUE TITLE
Simplify Add to Favorite for single track

### ISSUE THREAD

**Issue by tanathos** [CDrummond/lms-material#1014]
First of all: amazing job, I love this UI and how fast and responsive it is.
I decided to switch from Volumio and mOode to piCorePlayer with LMS just for how much better the UI/UX is.

I've only one issue with it: I can simply add to Favorite an entire album, but to do it for a single track is very tedious.
You need to:

Right-click:
![image](https://github.com/user-attachments/assets/2534894c-11b6-4973-b31b-06843e9b868c)

Click "More":
![image](https://github.com/user-attachments/assets/f1c3c811-c954-435e-9586-970a9146f95c)

Click "Save to Favorites":
![image](https://github.com/user-attachments/assets/7a67f79c-8f9c-4ffc-91d9-da8b115b1018)

And click "Add...".

It would be really nice to have a single-click shortcut somewhere on the Now Playing bar or at least on the expanded Now Playing screen... The default LMS theme allows you to it, so I guess the API already supports such action.

This request was already expressed here: https://github.com/CDrummond/lms-material/issues/491
And there's this comment on the thread:
https://github.com/CDrummond/lms-material/issues/491#issuecomment-852791258

But it looks like it was later removed?

Again, it's a minor thing, but I think it would be a nice addition.
Thanks!

**Comment by CDrummond** [comment]
What is the use case for favouring a single track? As opposed to adding these to a playlist?

**Comment by tanathos** [comment]
It's more an habit: using Spotify for a long time now I got used to just click an icon and that's it.
Now with LMS I'm creating my randomized playlists that run for hours while I'm working, when I ear something I REALLY like I would like to bookmark it quickly somewhere... Favorites would be the logical choice.

Plus, even if I decide to use a playlist, instead, there are many clicks to perform, and a final dialog to choose the playlist. Not optimal IMHO :)

**Comment by tanathos** [comment]
Awesome!
