### ISSUE TITLE
directly jump to menu

### ISSUE THREAD

**Issue by marcelveldt** [CDrummond/lms-material#102]
Hi, great work on this, it looks amazing!

Small question. I'm actually only using LMS for streaming media (Spotify and Qobuz subscriptions) and I don not use the default library menus at all.
Playlists are automatically selected and played by my home automation software.

Every now and than me or my wife just needs to perform a search to add a track to the playlist or something and she gets confused of the menu items.

Would it be possible to jump directly to a defined menu ?
For example I'd like to open the material web interface directly on the Spotty plugin.

Something like http://lmsserver/material/desktop.html?menu=Spotty

Thanks in advance!

**Comment by CDrummond** [comment]
No, sorry - not without messing the code. You can always just pin Spotty to the first page, and then its only 1 extra click.

**Comment by marcelveldt** [comment]
OK, fair enough thanks. Would be great if you could have your own menus defined but I understand your choice that would make it very hard to maintain.
I might take a look at the code myself one day, for now the pinned spotify icon will do.

Compromise: Any chance for a toggle to just hide some menus ?
