### ISSUE TITLE
Desktop view flipping between multiple Squeeze devices 

### ISSUE THREAD

**Issue by stevel6868** [CDrummond/lms-material#104]
When there are multiple players present, on recent updates running in desktop mode the lower progress bar (id="np-bar") has started flipping between the active player and the first player on the list. The change is brief and it reverts to the active player.  

Other times I press the play icon at the top, the playing starts but the rest of the display remains on the previous album.  After about 10 to 15 seconds it updates.

Could this be related to the change to cometd ?

If so I'll attempt to bisect and determine exactly which commit introduced the problem.

Thanks again for lms-material, your efforts are greatly appreciated.

Steve

**Comment by CDrummond** [comment]
Never seen this, the whole page should be flipping if that was the case - as the queue and the bottom toolbar should be linked to the current player. But, yeah, cometd would be my guess as to the cause. I've noticed an issue if I have the queue filled with short tracks (posted on the forum about this). Starting to think polling wasn't that bad...

**Comment by stevel6868** [comment]
Agree re polling :)

I'll run some tests over the weekend and try to confirm whether cometd is the problem.

**Comment by CDrummond** [comment]
OK. Spotted a **really** stupid bug that _might_ be the cause of this. Can you edit server.js and add `iscurrent: playerId == this.$store.state.player.id,` at about line 214. Then change lines 230 and 253 to use `iscurrent` and not `current`

**Comment by CDrummond** [comment]
...or, just add `var isCurrent = this.$store.state.player && playerId==this.$store.state.player.id;` then change lines 230 and 253 to use `isCurrent` and not `player.current`

**Comment by stevel6868** [comment]
Done, and looking good so far.  Will monitor and confirm.

**Comment by CDrummond** [comment]
I had a weird issue last night where the queue was not cleared - thinking that might've been caused by this too.

**Comment by stevel6868** [comment]
So far I've not had the inconsistency between the top and the bottom of display but I did see it flip back to the first player and stay there.  I suspect that's a separate problem.

**Comment by CDrummond** [comment]
So, whole UI went back to 1st player? This would imply the player was missing from sererstatus, and Material picked the 1st of the remainder to be active. Try adding some debug.

server.js add to line 179:
```
console.log("[" + new Date().toLocaleTimeString()+"] SS "+i.playerid+" "+(this.$store.state.player ? this.$store.state.player.id : "<>"));
```

and to line 214:
```
console.log("[" + new Date().toLocaleTimeString()+"] PS "+playerId+" "+(this.$store.state.player && playerId==this.$store.state.player.id));
```

Then in store.js line 188 add:
```
console.log("[" + new Date().toLocaleTimeString()+"] current player not found");
```

The 'SS' messages are serverstatus - here LMS lists each player. 'PS' is player status events. If Material receives a server statu sevent, it cehcks that the current player is listed - if not, then Material changes player.

Pleaer add this debug, and see if it shows your player being missing from the server status message.

**Comment by CDrummond** [comment]
Forgot to mention - SS will log `<plyer ID in list> <curent player id>`. PS wil log `<player bing update> <true if its current, false otherwise>`

**Comment by stevel6868** [comment]
Ok, thanks.  I'll get to this over the weekend.

**Comment by stevel6868** [comment]
Installed commit b83ad3b, enabled debug with ?debug=true, can see the COMETED and JSON messages in the log but no errors and the "flip" problem hasn't occured. I'm inclined to say you've fixed it. Many thanks.

**Comment by CDrummond** [comment]
Thanks for the confirmation. I'll close this now.

Could you do one more test for me? Can you update your checkout, and check things are still OK? The commit you mention was to work-around an issue I was seeing where cometd did not always send player status update messages in a timely manner when I sent a player message vis JSONRPC (e.g. toggling power). The work-around was quite heave though - in that I asked for an update after every player message (even if it failed). I've now reverted to the pre-cometd way of asking for updates where I thought it was necessary. Still using cometd to listen for external changes. Hopefully this works as good as before.

The only cometd issue I seem to have left is that if I have a queue filled with short (2 seconds or less tracks), I don't seem to get updates on all track changes. Most odd. Posted a query on the forums - but no response...

**Comment by stevel6868** [comment]
I've updated to 6307123e and the flipping problem isn't present, but I do notice the browser window being refreshed occasionally (maybe every few minutes).  It looks like a double refresh (two in quick succession).  It seems to coincide with a COMETED SERVER message in the log, but doesn't coincide with every such message.

**Comment by CDrummond** [comment]
Thanks for getting back. However, I was meannig more on the lines of how the skin functions in general. (Although reading my comment above, that was not clear!). I'm not convinced the cometd change is a change for the better. I'm consdering adding back some limited polling - e.g. near the end of a track (to work-around the 2 second issue above).

**Comment by stevel6868** [comment]
The skin is working well (as it was before the cometd change too).   Do you suspect the problem is in cometd or in LMS?  FWIW my system is smoother with cometd (i.e. changing playback via a remote or from another device is reflected almost instantly across devices).  So I'd encourage you to stick with cometd if you can, there are benefits beyond those provided by polling.

**Comment by CDrummond** [comment]
Yeah, I will stick with cometd. The issue I have with it is that some changes take seconds to be reported in a status update. This affects the display when playing short tracks. However, I have a work-around for this where I poll every 0.5 seconds for the last 2 seconds of a track. I'd prefer no polling, but this seems impossible. Likewise, I was hoping that when the user changes volume, toggles shuffle options, etc. (with material) that cometd would issue a status update reasonably quickly (i.e.. less than a second). But again, this seems not to be the case - so after issuing one of these commands, I manually request a status update.

But glad to hear things have not regressed for you, and are in fact better. Gives more more confidence to make a release. Thanks for the testing, and feedback.

**Comment by stevel6868** [comment]
Glad to help.
