### ISSUE TITLE
Pause button on chrome media notification 

### ISSUE THREAD

**Issue by COlklei** [CDrummond/lms-material#105]
For some strange reason the pause button on the Chrome media notification bar in Android does nothing. Previous / next song is working though. Any help is appreciated. o7

**Comment by CDrummond** [comment]
Same here, on Android 9. Will fix.

**Comment by CDrummond** [comment]
Hmmm... For me, play works, pause does not. It could be the way I'm faking an audio playback that is now broken. I might just have to remove this feature :-(

**Comment by CDrummond** [comment]
**Very** hacky work-around added. Play button will always be shown (and when pressed Material will issue a pause if currently playing). Title is prefixed "[PAUSED]" when paused.

Not really happy with this, but not sure what else to do.

**Comment by COlklei** [comment]
Thanks a lot for the ultrafast fix! It works flawlessly now. The whole media notification bar API is made for web apps which are really playing something so this 'abuse' of the api for the remote control will always have to be a hacky thing, I guess. 😎

**Comment by COlklei** [comment]
Sorry, accidentally closed it. But that's up to you of course.

**Comment by CDrummond** [comment]
Yeah, I sort-of agree. This hack is probably the best it's gonna be. You even see a slight flicker in the play icon, where Material fakes a play every 15 seconds to keep the notification alive.

So, I'll close for now.
