### ISSUE TITLE
About page for attribution

### ISSUE THREAD

**Issue by stevel6868** [CDrummond/lms-material#113]
Have you considered adding an About page, ideally below Information in the v-btn menu on the top right?

This could be used to show the Material Skin version (which would be helpful when debugging caching issues on mobile devices) but also could be used to acknowledge components or plugins, indeed LMS itself. Ideally the contents would be fetched from a JSON or XML file, allowing customisation.

**Comment by CDrummond** [comment]
Not too keen on an about dialog filled with info most people could not care about.

However, I have added the material version to the info dialog.

**Comment by stevel6868** [comment]
Excellent, thanks
