### ISSUE TITLE
"i" button becomes play control - activated accidentally on touch screen

### ISSUE THREAD

**Issue by michaelherger** [CDrummond/lms-material#114]
When I tap the "i" button at the top on an iOS device, the playback would automatically be paused, as that button becomes the playback control and is being activated immediately. Unfortunately I can't reproduce it in a desktop browser. Most likely the finger tap behaves differently from a single click, leaving the finger "logically" still on the button while the button itself changes.

**Comment by CDrummond** [comment]
Is this on git/master? Or the releaseed version? As it _should_ be fixed in git via https://github.com/CDrummond/lms-material/commit/60c5822ea51469d30c308f3e0436bc5b9ed893c4

**Comment by michaelherger** [comment]
Well, the server is on that revision. How to check in the UI?... I'll see whether it's a caching issue.

**Comment by CDrummond** [comment]
On Safari, if you use a private tab - then it should be a clean instance each time.

**Comment by michaelherger** [comment]
Ok, I can confirm that in private mode on the phone I tried about a dozen times and it worked fine all the time. But as soon as I save it to the home screen and start from there it fails. I have no idea whether iOS is keeping a cache there. But even after removing it first from the Home screen it wouldn't recover.

I'll watch it a bit. Maybe it'll correct itself in a few... I'll let you know. Thanks!

**Comment by CDrummond** [comment]
I would imagine its a cache issue. To clear Safari's cache you need to use the settings app, and clear history. Hence why easier to try in a private tab.

**Comment by michaelherger** [comment]
Yeah, that sounds like an iOS/Safari/Cache issue: picked up an old iPhone I never used for this purpose. And it worked right from the first try.
