### ISSUE TITLE
Make favorites sort optional

### ISSUE THREAD

**Issue by cgoldberg** [CDrummond/lms-material#121]
ability to leave Favorites in existing order was really nice.  Did that feature get removed?

**Comment by CDrummond** [comment]
Yes, that was removed. However, I'm considering re-adding this (and drag'n'drop re-ordering) when I add drag'n'drop ordering of playlists.

**Comment by cgoldberg** [comment]
+1 for adding it back

**Comment by CDrummond** [comment]
Option is back in 0.7.3 :-)
