### ISSUE TITLE
Skin hangs on loading some icons?

### ISSUE THREAD

**Issue by hpmueller1971** [CDrummond/lms-material#134]
Hi,

since a few days, the page wont load fully, it does not render the icon for Artists, Random Mix, Scroll to current track and clear playlist (all the others are fine).

[19-07-29 18:24:46.9028] Slim::Networking::IO::Select::__ANON__ (131) Error: Select task failed calling Slim::Web::HTTP::processHTTP: Can't locate object method "query_param" via package "URI::http" at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/MaterialSkin/Plugin.pm line 215.

I'd assume [this](https://github.com/CDrummond/lms-material/commit/2b3502da2d1c071d40e87c23ad98a4bdfe7f612e) is the cause, it works if i comment line 215 out (but then, obviously, on the dark skin, the four icons are black instead of white)...

Can someone confirm this?

Regards

/hp

**Comment by CDrummond** [comment]
Which version of LMS are you running? As its working fine with 7.9.2

**Comment by hpmueller1971** [comment]
I'm on 7.9.2 too... I'll purge the full dpkg and see if it changes anything...

Regards

/hp

**Comment by CDrummond** [comment]
Hmmm... Which verison of Perl? I'm on 5.28.1 Looking for `query_param` in my LMS install located:

```
find . -name \*.pm | xargs grep query_param
./Slim/Plugin/UPnP/SOAPServer.pm:	my $id = $request->uri->query_param('player');
./Slim/Plugin/UPnP/Events.pm:		my $id = $request->uri->query_param('player');
./Slim/Plugin/UPnP/Events.pm:		my $id = $request->uri->query_param('player');
./Slim/Plugin/DnDPlay/Plugin.pm:	if ( my $id = $request->uri->query_param('player') ) {
./CPAN/URI/QueryParam.pm:sub URI::_query::query_param {
./CPAN/URI/QueryParam.pm:sub URI::_query::query_param_append {
./CPAN/URI/QueryParam.pm:sub URI::_query::query_param_delete {
./CPAN/URI/QueryParam.pm:  $u->query_param(foo => 1, 2, 3);
./CPAN/URI/QueryParam.pm:  for my $key ($u->query_param) {
./CPAN/URI/QueryParam.pm:      print "$key: ", join(", ", $u->query_param($key)), "\n";
./CPAN/URI/QueryParam.pm:The query_param_* methods have deliberately been made identical to the
./CPAN/URI/QueryParam.pm:=item @keys = $u->query_param
./CPAN/URI/QueryParam.pm:=item @values = $u->query_param( $key )
./CPAN/URI/QueryParam.pm:=item $first_value = $u->query_param( $key )
./CPAN/URI/QueryParam.pm:=item $u->query_param( $key, $value,... )
./CPAN/URI/QueryParam.pm:If $u->query_param is called with no arguments, it returns all the
./CPAN/URI/QueryParam.pm:=item $u->query_param_append($key, $value,...)
./CPAN/URI/QueryParam.pm:   $u->query_param($key,
./CPAN/URI/QueryParam.pm:                   $u->query_param($key),
./CPAN/URI/QueryParam.pm:of $key, whereas the query_param_append() method does not.
./CPAN/URI/QueryParam.pm:=item @values = $u->query_param_delete($key)
./CPAN/URI/QueryParam.pm:=item $first_value = $u->query_param_delete($key)
./CPAN/URI/QueryParam.pm:Using the query_param_delete() method is slightly more efficient than
./CPAN/URI/QueryParam.pm:   $u->query_param($key, []);
./CPAN/URI/QueryParam.pm:The values returned by the query_param() method should stay the same
```

So, Material is not the only module using this.

**Comment by CDrummond** [comment]
I've updated the code to check if "query_param" exists, if not it calls "as_string" on the URI and manually attemtps to extract the "c" query parameter. I'm hoping "as_string" exists! If not, no idea waht to do.

As stated, "query_param" works for me - and is used elsewhere in the LMS codebase.
