### ISSUE TITLE
Mobile view redirecting to desktop

### ISSUE THREAD

**Issue by justinj0305** [CDrummond/lms-material#139]
When I try forcing the mobile version with /material/mobile (as per documentation) it constantly redirects itself to /material/desktop.  This occurs in Firefox and Chrome.  Skin is v0.9.5.
Ordinarily this wouldn't be an issue on a desktop however I am trying to embed the player into a frame so I specifically want the mobile version as the desktop version gets collapsed too much and does not render properly.

> Material should automatically choose mobile or desktop layouts, but you may also force one or the other.
> 
>     http://<yourserver>:9000/material/mobile will force mobile layout
>     http://<yourserver>:9000/material/desktop will force desktop layout
> 
> Material also has two other views; a mini-player and now-playing screen. The mini-player can be launched via the desktop view (and this is how it is intended to be used), or via the URL below. Now-playing can only be accessed via the URL below (it is in fact a trimmed down desktop view, that only shows now-playing).
> 
>     http://<yourserver>:9000/material/mini
>     http://<yourserver>:9000/material/now-playing

**Comment by CDrummond** [comment]
Use material's settings and set to desktop layout. If this setting is left at auto, then any resize will cause material to check whether to use desktop or mobile.

I'll update the documentation to mention this. Will leave this report open until I do.

Sorry for the confusion.

**Comment by justinj0305** [comment]
I did look at material's setting but when saving it says "NOTE: 'Application layout' is not saved, as this is a per-device setting." which doesn't help me when I want it to appear automatically as a mobile view in the frame for any browser or device that uses it.
It's also not just the UI rearranging itself due to the size, it physically redirects the URL:
-I type http://192.168.100.21:9000/material/mobile and hit enter
-Page loads momentarily and then redirects and reloads to http://192.168.100.21:9000/material/desktop

As the application layout setting is a cookie based setting, this causes it to appear deformed in an iframe.  I think the option of /desktop /mobile needs to override any CSS or script checking that it does.

**Comment by CDrummond** [comment]
It is the size checking, but it happens at start-up too. There is no option of /desktop /mobile - these are the URLs that are used. The code would not know if the user entered these, or if the code changed the URL.

Anyhow, I'll add a "?auto=false" (or something like this) to disable the size checking and auto switching.

**Comment by justinj0305** [comment]
Based on the documentation I would have expected that /material would have used an auto selection but /material/desktop or /material/mobile would have used the path explicit.
Obviously that's not the case but anything to force it one way or the other would be appreciated :)

**Comment by CDrummond** [comment]
Fixed for next release - note README.md will also be updated then.
