### ISSUE TITLE
Long time to delete playlist

### ISSUE THREAD

**Issue by CDrummond** [CDrummond/lms-material#142]
https://forums.slimdevices.com/showthread.php?109624-Announce-Material-Skin&p=948777&viewfull=1#post948777

**Comment by ronfischler** [comment]
I am not getting consistent behavior, but when it fails to delete a recently created playlist, I get a popup that says: Failed to delete playlist! (Error: Network Error)

**Comment by ronfischler** [comment]
Craig, I might owe you a huge apology. This issue might have been entirely of my own making. My server is using Ubuntu 18.04 OS, which might be involved but regardless, I had the plugin AutoRescan running, with a delay of 5 seconds.

Running AutoRescan appears to conflict with adding and deleting playlists, and may have nothing to do with Material at all.

Additionally, I have my Playlist folder inside my FLAC music folder, which might be a blunder on my part as well.

**Comment by CDrummond** [comment]
He he :) no problem. Would explain why I've not seen the issue...

**Comment by ronfischler** [comment]
I think this can be closed, as it appears to work as long as a scan is not going on while trying to save or delete a playlist. However, is it possible to give a more descriptive error message that explains that the operation should be tried again later, that a scan of the user's library is in progress?

**Comment by CDrummond** [comment]
Done :-)
