### ISSUE TITLE
Setting a new Preset

### ISSUE THREAD

**Issue by ronfischler** [CDrummond/lms-material#144]
"Set Preset" is missing as an option in the overflow menus for favorites and playlists.

The option is also missing from the overflow menus in extensions such as Spotty and Radio Paradise.

**Comment by CDrummond** [comment]
Have you configured Material to show presets? It's off by default. The 'Save as preset' menu item is only applicable if Material is configured to show the presets. It is also only shown where the 'Add to favorites' is displayed - but not for local music items (eg. artists, albums, playlists). Perhaps I should add it for playlists?

Just tried, and it seems to be working for me.

**Comment by ronfischler** [comment]
Ah, yes - I understand. Yes, I would suggest adding "Set Preset" to playlists too.

I am not sure how I got confused. I thought it was missing from favorites in addition to playlists, but I see it now!
