### ISSUE TITLE
Double tap events on persistent top and bottom navigation bars

### ISSUE THREAD

**Issue by ronluna** [CDrummond/lms-material#145]
I'm running a little test to load lms-material inside a UIWebView container for an iPhone app. I have tried everything that I can think of but I can't prevent the lms-material theme to repeat tap events on the top and bottom persist tab (The center is works fine though). So I'm know wondering what .js could be causing this behavior?

**Comment by CDrummond** [comment]
Sorry, I'm not sure what you mean. By top 'tab' you mean the toolbar at the top containg the player menu and volume button? And by bottom 'tab' you mean the browse/now-playing/queue navigation bar?

Why do you want to stop double-taps? AFAIK, there is no support for double-click/tap. In the 2 areas I use double-click (start a track in queue, show cover in now-playing) I use a timer. If second tap received within specific time, its treated as double-click/tap.

**Comment by CDrummond** [comment]
CLosing, its been a week and no response.

**Comment by ronluna** [comment]
Please don't close it yet. I was trying to record the screen of the iPhone to show a little better the behavior and see if you can point at what file I could edit to prevent the double tap event.

Here is the video.

https://drive.google.com/file/d/15Y6RlwHxItDD-zYvbuxBhf0iaGT68yHx/view?usp=sharing

Let me know when you get a chance please

**Comment by CDrummond** [comment]
What double tab event? I'm not sure what the problem is. How are you seeing repeated events? Are you saying that a _single_ tap on (e.g.) the volume control is producing _two_ taps? If so, that's got to be an issue with your system.

**Comment by CDrummond** [comment]
Sorry - I didn't mean to offend. So, are you saying you **want** to be able to double-click on the top/bottom bars? Why?

**Comment by ronluna** [comment]
your comment was not offensive at all! :)
On the contrary, you've been amazing and We love what you have done... :)

now, back to subject. 

nope, The behavior experienced in lms-material is that single tap events are automatically being repeated and being translated to a double click event instead of what they really "a single tap event" 

apparently if the page being loaded inside the mobile browser is defined as a non-scalable page the tap events will be handled correctly.  It seems as mobile browser have not found a way to distinguish a real single tap to a double tap for zooming purposes.

if is not too much trouble and have xcode installed please try the following:

https://github.com/dimitardanailov/xcode-uiwebview-objectivec

and load from the iOS simulator your local lms-material into the UIWebView

you will see exactly what I mean.

**Comment by CDrummond** [comment]
Sorry - I'm on Ubuntu. So, why is it working in Safari, Chrome, etc, but not UIWebView? It works in androids WebView, within an app, as another user created a standalone app to embed material.

I'll re-open the issue.

Could it be that some meta-data needs to be set on the mobile.html page?

**Comment by ronluna** [comment]
It could have something to do with the on-click effect on this class:

class="lms-bottom-nav-button v-btn v-btn--active v-btn--flat theme--dark active-nav"

maybe vuetify has something to do with it. as it only affects buttons with the splash effect. the drop down works fine as well as the link icon.  but anything that has the splash effect on the top or bottom bar receive a double tap event.

**Comment by CDrummond** [comment]
Closng due to inactivity.
