### ISSUE TITLE
Mobile view redirecting to desktop (still)

### ISSUE THREAD

**Issue by justinj0305** [CDrummond/lms-material#149]
Related to issue #139 that I previously raised.  I've got version 0.9.7 of the skin but it is still redirecting to desktop view even with ?auto=false in the URL.

**Comment by CDrummond** [comment]
Do you see layout options in Material's settings - as they should not be there if that options is active. Have you cleared your browser cache?

**Comment by justinj0305** [comment]
New browser window, tried Chrome and Firefox in incognito/private mode to rule out any issues with cache or cookies.
After putting in the full URL (http://server:9000/material/mobile?auto=false) it does the same as before; briefly loads page (flashes on screen for a fraction of a second) and then redirects the URL to http://server:9000/material/desktop.  All options for manually choosing the layout (saved in a cookie so not obviously not reflected in private mode) exist.

**Comment by CDrummond** [comment]
D'oh!!! That's because this is not in 0.9.7 - will be in the next release!!!

**Comment by justinj0305** [comment]
Git's showing me it was pushed into a commit for 0.9.7 and README.md has been updated in the same commit which is reflected?

**Comment by CDrummond** [comment]
It was done in the devel branch - which has now been merged into master. But 0.9.7 was released (from master) before it was merged.

**Comment by justinj0305** [comment]
Ahh gotcha.  Any idea when you'll be releasing 1.0?

**Comment by CDrummond** [comment]
When its ready. Might be tomorrow.
