### ISSUE TITLE
Lang

### ISSUE THREAD

**Issue by sky418** [CDrummond/lms-material#151]
I make ru.json
HowTo upload?

**Comment by CDrummond** [comment]
3 options; create a pull request (easier for updates, etc), email me the ru.json file, or attach to this issue.

**Comment by sky418** [comment]
[ru.zip](https://github.com/CDrummond/lms-material/files/3621103/ru.zip)

**Comment by sky418** [comment]
The 2
Cant navigate inside Radio folder 
I see all folders but can't login

**Comment by CDrummond** [comment]
Please dont mix issues, it makes things hard to keep track of.

Anyhow, Material gets its listings from LMS - LMS hadles login, etc. Just checked, and Radio is woriking for me.

**Comment by sky418** [comment]
Я нахожу небольшую ошибку в переводе
вместо мини а написать мульти
исправить сейчас
[ru.zip](https://github.com/CDrummond/lms-material/files/3621146/ru.zip)
