### ISSUE TITLE
np-bar

### ISSUE THREAD

**Issue by sky418** [CDrummond/lms-material#152]
I need to move np-bar to the top of gui
yes, i can do it by myself, but it will take some time
Can you help me where to find which file the np-bar rool's

**Comment by CDrummond** [comment]
You mean the botom toolbar in desktop layout? Its not as easy as just moving it, you need to edit the CSS files to adjust the list sizes (top/bottom), etc. A lot of work.

I wish web GUI layout was as simple as it is in Qt :-( Perhaps it is, but I'm no web developer.

**Comment by sky418** [comment]
Ok. THX
