### ISSUE TITLE
Missing "More" main menu item and "Random Albums" option?

### ISSUE THREAD

**Issue by therealcodlord** [CDrummond/lms-material#158]
In material skin in the "My Music" menu there used to be a "More" option where you could choose random albums etc. I loved that feature and used it a lot. Since a recent update to material skin (possibly 1.0.0?) there is no "More" option at all. Under "My Music" I just see:
Album Artists
All Artists
Albums
Genres
Years

I can't see anything in the changelog or settings that would explain this. I have not changed anything else with my LMS config or setup.

Running on Ubuntu Linux 19.04
LMS v7.9.2 - 1568726655 
Material Skin v1.0.1
I see that there is skin v1.0.2 on github but it's not yet showing in LMS as an official plugin version hence why I am not running that version.

Thanks

**Comment by CDrummond** [comment]
This has been discussed on the slimdevices forum. Use default webui to enable random albums category using "extended browse modes". You will be able to configure the list of player modes in material 1.0.0
