### ISSUE TITLE
Qobuz Search no longer working

### ISSUE THREAD

**Issue by ronfischler** [CDrummond/lms-material#160]
Material desktop display, Qobuz Search no longer works; nothing happens when I click on Search. In fact, it appears to be grayed out! I don't know when it first failed. It still works in the mobile display however.

**Comment by CDrummond** [comment]
Sorry, but I do not use any streaming services. Can't see how it would differ between desktop and mobile - they share the same code. Is this with latest master, or 1.0.2? If its with 1.0.2, try master. Also, perhaps try each of the releases until you find the one where it broke.

**Comment by ronfischler** [comment]
Darn it - I think I understand what was happening, after watching how it works in the default LMS display. I must have forgotten, as I was travelling for the past several weeks, and not using the desktop, only the mobile display on my phone.

When one clicks Qobuz Search, the user should just start typing his search string, even though he might not be able to see a cursor, like me, ... it works. Clearly I was confused - pilot error.

I am sorry Craig; I think I wasted your time. A quick check using developer tools would have cleared this up for me right at the start. Sheesh. 

By the way I was travelling through the EU, visiting a variety of places and using the mobile display and Squeeze Player via a VPN to my server at home here in Silicon Valley ... it worked beautifully the entire trip; fantastic.

I will close this issue, on account of terminal pilot error.

**Comment by CDrummond** [comment]
You cannot see the search field? It _should_ scroll into view.
