### ISSUE TITLE
Ru LNG new fixes

### ISSUE THREAD

**Issue by sky418** [CDrummond/lms-material#162]
[ru.zip](https://github.com/CDrummond/lms-material/files/3684500/ru.zip)

**Comment by CDrummond** [comment]
Thanks. Could you please use pull requests for future updates? Makes it much easier.

**Comment by sky418** [comment]
Ok
One more suggestion
Can You add
"Add to the end of the queue"

**Comment by CDrummond** [comment]
What? Where? if you mean as a generic action then there is alrey "Append to queue"

**Comment by sky418** [comment]
Can't see
5 min

**Comment by sky418** [comment]
My Bug
Wrong translation 5 min fix it

**Comment by sky418** [comment]
[ru.zip](https://github.com/CDrummond/lms-material/files/3686295/ru.zip)
Fix
I translate as "random queue"

**Comment by CDrummond** [comment]
Applied. But please, no more zip files - use pull requests. Thanks.

**Comment by sky418** [comment]
I haven't do it any time before and can't understand how it works
I try but nothing happens. Can't publish
