### ISSUE TITLE
Some fixed German Translations

### ISSUE THREAD

**Issue by Bitpainter75** [CDrummond/lms-material#163]
Hi,

please Update the following german translations:

"Full rescan":"Alles neu durchsuchen",
"Last scan: %1":"Letztes Durchsuchen: %1",
"Power on all group members when playing to group.":"Alle Gruppen-Mitglieder einschalten, wenn Wiedergabe auf Gruppe gestartet wird.",
"Remove the selected items?":"Sollen die ausgewählten Einträge entfernt werden?",
"Rename failed":"Umbenennen ist fehlgeschlagen",
"Update rescan":"Aktualisieren",
"Swipe up and down to change current volume.":"Wische nach oben und unten, um die aktuelle Lautstärke zu ändern",
"Each player can have its own unique set of browse modes (Artists, Albums, Genres, etc). This is the set of options that will appear within the 'My Music' section. Use the button below to configure which modes will be available for this player.":"Jedes Gerät kann seine eigenen Browse-Modi haben (Interpreten, Alben, Stilrichtungen etc.). Das ist die Liste möglicher Einstellungen, die in 'Meine Musik' erscheinen werden. Benutze den Knopf unten um festzulegen, welche Modi auf diesem Gerät verfügbar sein sollen.",

Thx and best regards

**Comment by CDrummond** [comment]
Please submit a pull request against master for these.

**Comment by CDrummond** [comment]
Thanks!
