### ISSUE TITLE
Artwork For Tracks From 'No Album'

### ISSUE THREAD

**Issue by pkcrawford** [CDrummond/lms-material#167]
Hey Craig, would it be possible to show the artist image for tracks that do not have any album artwork?  Right now, 'No Album' tracks just show the generic grey CD image in the queue and now playing windows.  It would be great if it would show the Artists images as they appear in the 'Artists' menu.

**Comment by CDrummond** [comment]
Implemented in git/master for 1.1.0 Not sure about this though, as if there is no artist image you get that awful trumpeter...
