### ISSUE TITLE
"More" menu and deleting previously searched Spotty results

### ISSUE THREAD

**Issue by mikecappella** [CDrummond/lms-material#175]
I'm moving this issue from the Slimdevices forums to here, as per suggestion by Craig.

Requested info (this is before navigating to the previous searches area and then clicking the ellipsis:

`[8:05:19 AM] JSON RESP: {"method":"slim.request","result":{"base":{"actions":{"add":{"cmd":["spotty","playlist","add"],"itemsParams":"params","params":{"menu":"spotty"},"player":0},"more":{"window":{"isContextMenu":1},"cmd":["spotty","items"],"params":{"menu":"spotty"},"player":0,"itemsParams":"params"},"go":{"itemsParams":"params","params":{"menu":"spotty"},"cmd":["spotty","items"]},"playControl":{"window":{"isContextMenu":1},"cmd":["spotty","items"],"player":0,"params":{"_quantity":"25000","item_id":"0","_index":"0","menu":"spotty"},"itemsParams":"playControlParams"},"add-hold":{"cmd":["spotty","playlist","insert"],"player":0,"params":{"menu":"spotty"},"itemsParams":"params"},"play":{"itemsParams":"params","params":{"menu":"spotty"},"player":0,"cmd":["spotty","playlist","play"],"nextWindow":"nowPlaying"}}},"count":49,"item_loop":[{"type":"search","text":"New Search","actions":{"go":{"params":{"search":"__TAGGEDINPUT__","item_id":"0.0","cachesearch":1,"menu":"spotty"},"cmd":["spotty","items"]}},"input":{"softbutton1":"Insert","title":"New Search","processingPopup":{"text":"Searching..."},"help":{"text":"Use the scroll wheel to change letters, then press the center button to select that letter. Press the center button again to start your search."},"softbutton2":"Delete","len":1}},{"text":"marconi union","actions":{"more":{"player":0,"params":{"menu":1,"deleteMenu":47},"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"]},"go":{"params":{"item_id":"0.1","menu":"spotty"},"cmd":["spotty","items"]}},"type":"link","addAction":"go"},{"addAction":"go","text":"hammock","actions":{"more":{"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1},"params":{"deleteMenu":46,"menu":1},"player":0},"go":{"params":{"menu":"spotty","item_id":"0.2"},"cmd":["spotty","items"]}},"type":"link"},{"type":"link","actions":{"go":{"params":{"item_id":"0.3","menu":"spotty"},"cmd":["spotty","items"]},"more":{"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"],"params":{"deleteMenu":45,"menu":1},"player":0}},"text":"lana del rey","addAction":"go"},{"type":"link","actions":{"more":{"params":{"menu":1,"deleteMenu":44},"player":0,"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"]},"go":{"cmd":["spotty","items"],"params":{"item_id":"0.4","menu":"spotty"}}},"text":"Birds Requiem","addAction":"go"},{"actions":{"more":{"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"],"player":0,"params":{"menu":1,"deleteMenu":43}},"go":{"cmd":["spotty","items"],"params":{"item_id":"0.5","menu":"spotty"}}},"text":"Dhafer Yousef","type":"link","addAction":"go"},{"addAction":"go","actions":{"go":{"params":{"item_id":"0.6","menu":"spotty"},"cmd":["spotty","items"]},"more":{"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1},"player":0,"params":{"menu":1,"deleteMenu":42}}},"text":"Music for Installations","type":"link"},{"type":"link","actions":{"more":{"player":0,"params":{"menu":1,"deleteMenu":41},"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1}},"go":{"params":{"menu":"spotty","item_id":"0.7"},"cmd":["spotty","items"]}},"text":"michael kiwanuka","addAction":"go"},{"text":"efterklang","actions":{"more":{"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1},"player":0,"params":{"deleteMenu":40,"menu":1}},"go":{"params":{"menu":"spotty","item_id":"0.8"},"cmd":["spotty","items"]}},"type":"link","addAction":"go"},{"type":"link","actions":{"go":{"params":{"menu":"spotty","item_id":"0.9"},"cmd":["spotty","items"]},"more":{"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1},"player":0,"params":{"menu":1,"deleteMenu":39}}},"text":"ram dass","addAction":"go"},{"type":"link","text":"philip glass","actions":{"go":{"params":{"menu":"spotty","item_id":"0.10"},"cmd":["spotty","items"]},"more":{"player":0,"params":{"deleteMenu":38,"menu":1},"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1}}},"addAction":"go"},{"addAction":"go","text":"Wakers of the Wind","actions":{"more":{"params":{"menu":1,"deleteMenu":37},"player":0,"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"]},"go":{"params":{"menu":"spotty","item_id":"0.11"},"cmd":["spotty","items"]}},"type":"link"},{"addAction":"go","text":"The Late Show EP","actions":{"more":{"params":{"deleteMenu":36,"menu":1},"player":0,"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1}},"go":{"params":{"menu":"spotty","item_id":"0.12"},"cmd":["spotty","items"]}},"type":"link"},{"addAction":"go","type":"link","text":"Anatomy of Angels: Live at the Village Vanguard","actions":{"more":{"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"],"player":0,"params":{"menu":1,"deleteMenu":35}},"go":{"params":{"menu":"spotty","item_id":"0.13"},"cmd":["spotty","items"]}}},{"type":"link","actions":{"more":{"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1},"params":{"deleteMenu":34,"menu":1},"player":0},"go":{"cmd":["spotty","items"],"params":{"item_id":"0.14","menu":"spotty"}}},"text":"Thievery Corporation","addAction":"go"},{"actions":{"go":{"cmd":["spotty","items"],"params":{"item_id":"0.15","menu":"spotty"}},"more":{"params":{"menu":1,"deleteMenu":33},"player":0,"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"]}},"text":"cold specks","type":"link","addAction":"go"},{"addAction":"go","text":"miguel bose","actions":{"go":{"cmd":["spotty","items"],"params":{"menu":"spotty","item_id":"0.16"}},"more":{"player":0,"params":{"menu":1,"deleteMenu":32},"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"]}},"type":"link"},{"addAction":"go","type":"link","text":"Rick Braun","actions":{"more":{"player":0,"params":{"menu":1,"deleteMenu":31},"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1}},"go":{"params":{"menu":"spotty","item_id":"0.17"},"cmd":["spotty","items"]}}},{"actions":{"go":{"params":{"menu":"spotty","item_id":"0.18"},"cmd":["spotty","items"]},"more":{"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1},"params":{"menu":1,"deleteMenu":30},"player":0}},"text":"the best of solomon grey","type":"link","addAction":"go"},{"addAction":"go","actions":{"go":{"params":{"item_id":"0.19","menu":"spotty"},"cmd":["spotty","items"]},"more":{"player":0,"params":{"deleteMenu":29,"menu":1},"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"]}},"text":"solomon grey","type":"link"},{"text":"holly herndon","actions":{"more":{"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"],"player":0,"params":{"menu":1,"deleteMenu":28}},"go":{"params":{"item_id":"0.20","menu":"spotty"},"cmd":["spotty","items"]}},"type":"link","addAction":"go"},{"addAction":"go","actions":{"go":{"params":{"menu":"spotty","item_id":"0.21"},"cmd":["spotty","items"]},"more":{"player":0,"params":{"deleteMenu":27,"menu":1},"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"]}},"text":"We Out Here","type":"link"},{"actions":{"more":{"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1},"player":0,"params":{"menu":1,"deleteMenu":26}},"go":{"params":{"menu":"spotty","item_id":"0.22"},"cmd":["spotty","items"]}},"text":"american gods","type":"link","addAction":"go"},{"addAction":"go","type":"link","actions":{"go":{"params":{"menu":"spotty","item_id":"0.23"},"cmd":["spotty","items"]},"more":{"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"],"player":0,"params":{"deleteMenu":25,"menu":1}}},"text":"Chasing the Moon"},{"addAction":"go","type":"link","text":"natalie taylor","actions":{"more":{"player":0,"params":{"menu":1,"deleteMenu":24},"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1}},"go":{"cmd":["spotty","items"],"params":{"item_id":"0.24","menu":"spotty"}}}},{"addAction":"go","type":"link","actions":{"more":{"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1},"params":{"menu":1,"deleteMenu":23},"player":0},"go":{"cmd":["spotty","items"],"params":{"item_id":"0.25","menu":"spotty"}}},"text":"The Man With The Red Face"},{"type":"link","text":"cafe del mar","actions":{"more":{"params":{"deleteMenu":22,"menu":1},"player":0,"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"]},"go":{"params":{"menu":"spotty","item_id":"0.26"},"cmd":["spotty","items"]}},"addAction":"go"},{"addAction":"go","type":"link","actions":{"go":{"params":{"menu":"spotty","item_id":"0.27"},"cmd":["spotty","items"]},"more":{"player":0,"params":{"menu":1,"deleteMenu":21},"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1}}},"text":"Anna Maria Jopek"},{"addAction":"go","actions":{"go":{"cmd":["spotty","items"],"params":{"menu":"spotty","item_id":"0.28"}},"more":{"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"],"player":0,"params":{"menu":1,"deleteMenu":20}}},"text":"finding gabriel","type":"link"},{"text":"brad mehldau","actions":{"go":{"params":{"item_id":"0.29","menu":"spotty"},"cmd":["spotty","items"]},"more":{"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"],"params":{"deleteMenu":19,"menu":1},"player":0}},"type":"link","addAction":"go"},{"addAction":"go","type":"link","actions":{"more":{"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1},"params":{"menu":1,"deleteMenu":18},"player":0},"go":{"cmd":["spotty","items"],"params":{"menu":"spotty","item_id":"0.30"}}},"text":"camila meza"},{"addAction":"go","text":"madonna","actions":{"more":{"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"],"params":{"deleteMenu":17,"menu":1},"player":0},"go":{"params":{"menu":"spotty","item_id":"0.31"},"cmd":["spotty","items"]}},"type":"link"},{"addAction":"go","text":"Jack Nitzsche","actions":{"go":{"cmd":["spotty","items"],"params":{"item_id":"0.32","menu":"spotty"}},"more":{"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1},"player":0,"params":{"deleteMenu":16,"menu":1}}},"type":"link"},{"addAction":"go","text":"Starman soundtrack","actions":{"go":{"cmd":["spotty","items"],"params":{"item_id":"0.33","menu":"spotty"}},"more":{"params":{"deleteMenu":15,"menu":1},"player":0,"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"]}},"type":"link"},{"actions":{"more":{"params":{"menu":1,"deleteMenu":14},"player":0,"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"]},"go":{"params":{"menu":"spotty","item_id":"0.34"},"cmd":["spotty","items"]}},"text":"Starman","type":"link","addAction":"go"},{"text":"kyle preston","actions":{"go":{"cmd":["spotty","items"],"params":{"item_id":"0.35","menu":"spotty"}},"more":{"player":0,"params":{"deleteMenu":13,"menu":1},"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"]}},"type":"link","addAction":"go"},{"type":"link","actions":{"go":{"params":{"menu":"spotty","item_id":"0.36"},"cmd":["spotty","items"]},"more":{"params":{"deleteMenu":12,"menu":1},"player":0,"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1}}},"text":"pat metheny","addAction":"go"},{"actions":{"more":{"params":{"deleteMenu":11,"menu":1},"player":0,"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"]},"go":{"cmd":["spotty","items"],"params":{"item_id":"0.37","menu":"spotty"}}},"text":"bullitt","type":"link","addAction":"go"},{"type":"link","text":"jackie brown","actions":{"go":{"params":{"menu":"spotty","item_id":"0.38"},"cmd":["spotty","items"]},"more":{"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"],"player":0,"params":{"deleteMenu":10,"menu":1}}},"addAction":"go"},{"addAction":"go","type":"link","actions":{"go":{"cmd":["spotty","items"],"params":{"menu":"spotty","item_id":"0.39"}},"more":{"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"],"player":0,"params":{"menu":1,"deleteMenu":9}}},"text":"An Enduring Voice"},{"addAction":"go","type":"link","text":"the cranberries","actions":{"more":{"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"],"player":0,"params":{"deleteMenu":8,"menu":1}},"go":{"cmd":["spotty","items"],"params":{"menu":"spotty","item_id":"0.40"}}}},{"actions":{"more":{"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1},"params":{"menu":1,"deleteMenu":7},"player":0},"go":{"params":{"menu":"spotty","item_id":"0.41"},"cmd":["spotty","items"]}},"text":"fela kuti","type":"link","addAction":"go"},{"addAction":"go","text":"Music of Many Colours","actions":{"more":{"params":{"menu":1,"deleteMenu":6},"player":0,"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"]},"go":{"params":{"menu":"spotty","item_id":"0.42"},"cmd":["spotty","items"]}},"type":"link"},{"addAction":"go","type":"link","text":"mr fingers","actions":{"more":{"player":0,"params":{"menu":1,"deleteMenu":5},"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1}},"go":{"cmd":["spotty","items"],"params":{"item_id":"0.43","menu":"spotty"}}}},{"type":"link","text":"Exitmusic","actions":{"more":{"params":{"menu":1,"deleteMenu":4},"player":0,"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1}},"go":{"cmd":["spotty","items"],"params":{"menu":"spotty","item_id":"0.44"}}},"addAction":"go"},{"actions":{"go":{"params":{"menu":"spotty","item_id":"0.45"},"cmd":["spotty","items"]},"more":{"params":{"menu":1,"deleteMenu":3},"player":0,"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1}}},"text":"The Sight Below","type":"link","addAction":"go"},{"addAction":"go","text":"war on drugs","actions":{"go":{"cmd":["spotty","items"],"params":{"item_id":"0.46","menu":"spotty"}},"more":{"player":0,"params":{"deleteMenu":2,"menu":1},"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1}}},"type":"link"},{"actions":{"go":{"cmd":["spotty","items"],"params":{"item_id":"0.47","menu":"spotty"}},"more":{"params":{"deleteMenu":1,"menu":1},"player":0,"window":{"isContextMenu":1},"cmd":["spotty","recentsearches"]}},"text":"She Who Dwells in the Secret Place ","type":"link","addAction":"go"},{"text":"sinead oconnor","actions":{"go":{"cmd":["spotty","items"],"params":{"item_id":"0.48","menu":"spotty"}},"more":{"cmd":["spotty","recentsearches"],"window":{"isContextMenu":1},"params":{"menu":1,"deleteMenu":0},"player":0}},"type":"link","addAction":"go"}],"title":"Search","window":{"windowStyle":"text_list"},"offset":0},"id":1,"params":["00:04:20:23:cd:16",["spotty","items","0",25000,"item_id:0","menu:spotty"]]}`

This is after clicking More:

```
utils.js?r=DEV-2019-10-18-08-01-33:16 [8:11:12 AM] JSON REQ: ["00:04:20:23:cd:16",["spotty","recentsearches",0,25000,"menu:1","deleteMenu:39"]]
utils.js?r=DEV-2019-10-18-08-01-33:16 [8:11:12 AM] JSON RESP: {"params":["00:04:20:23:cd:16",["spotty","recentsearches","0","25000","menu:1","deleteMenu:39"]],"id":1,"result":{"item_loop":[{"actions":{"go":{"player":0,"params":{"delete":"39"},"cmd":["spotty","recentsearches"]}},"text":"Delete: \"ram dass\"","nextWindow":"parent"},{"actions":{"go":{"player":0,"params":{"deleteAll":1},"cmd":["spotty","recentsearches"]}},"text":"Clear complete search history","nextWindow":"grandParent"}],"count":2,"offset":0},"method":"slim.request"}
```

**Comment by CDrummond** [comment]
Thanks for this. Am I correct in assuming that all these items can be clicked on? What would you expect to happen when you click on them? What happens in other UIs - default web UI, iPeng, SqueezeCtrl, etc?

I added this into my checkout, and each entry is clickable. Because of this my change will have no affect, as it explicitly checks the item s not clickable so as to not override that.

**Comment by mikecappella** [comment]
Correct, all items in the list can be clicked on.

Ideally, the More menu would be replaced with the two choices: 

- Delete "_some search name_"
- Clear complete search history

since these are the only to choices that appear in a new page, after you click More.  I would have sworn that in a past MS release, there was no More sub-menu that appears, and clicking the ellipsis immediately took you to the page with the two items above (hence my claiming there was now one more level of indirection).

Default LMS skin doesn't offer a way to clear.  iPeng - there is no More button, but long hold of a previous search result brings up a menu with the two choices above.

**Comment by CDrummond** [comment]
Thought so. Yes, if a list item's menu only had one entry, previous material releases would just show that - and not the three dotted menu button I could revert to that. Guess that's the only way to resolve this.

Surely default web UI has the 'M' button - then leading to the choice to delete?

SqueezeCtrl acts like iPeng - a long press on an items button brings up a menu with the play choices, etc. But I was never keen on that, as it resizes as shown.

**Comment by mikecappella** [comment]
Not that I can see.

![2019-10-18_08-39-15](https://user-images.githubusercontent.com/8551810/67108159-c8e4ef80-f182-11e9-88bf-3e598f9e55d1.png)

iPend handles this, in a way I consider, correct:

![UNADJUSTEDNONRAW_thumb_4fc](https://user-images.githubusercontent.com/8551810/67108199-dbf7bf80-f182-11e9-9c5b-42c0dfda3297.jpg)

**Comment by CDrummond** [comment]
I've changed back to showing the 'More' action and not the menu-action if there is only 1 entry. This should the be the same behaviour as before.

I'm not keen on showing the 'More' actions as a menu - as some have quite a few entries. This is one behaviour I do no like about SqueezeCtrl.

**Comment by mikecappella** [comment]
The change works.  I can live with this.  Thanks.

**Comment by CDrummond** [comment]
OK, well I close then.
