### ISSUE TITLE
Dynamic Search

### ISSUE THREAD

**Issue by pkcrawford** [CDrummond/lms-material#179]
Any chance you would be able to add the dynamic search capability that is built in to the default UI?
As shown in the attached image, in the default UI, search results start appearing as I type instead of having to submit:
![lms_search](https://user-images.githubusercontent.com/55283925/67484534-4a7ec680-f636-11e9-83a9-e688ba86e9ee.png)
It is such a handy feature, especially for someone like me that has problems spelling.  Gives me a chance to correct my errors on the fly.

**Comment by CDrummond** [comment]
No. This would be incosistent with seach on other places. It would also not fit into the current UI.
