### ISSUE TITLE
"hang" the mobile display - 100% CPU

### ISSUE THREAD

**Issue by ronfischler** [CDrummond/lms-material#184]
This appears to happen in material/mobile, but not the desktop display.

Using the "My Music" Search tool in the Browse panel, I search for an artist and then drill down to their album listing, then jump back to the "Now Playing" display, and do a long click on the now playing button, or select "More" information, the info about the currently playing track is rendered back in the Browse panel, replacing the album listing, (I use the grid view.)

OK, now if I hit Material's back-navigation button, the left arrow, the material display hangs, and I have to reload material and start over. Strangely, this does not occur when using the desktop.

**Comment by CDrummond** [comment]
Not just 1.2, master too! This caused my whole OS to hang! Will try to fix. Thanks for reporting.

**Comment by CDrummond** [comment]
Should be fixed now in 1.2 and mater. Can you update and confirm? Thanks.

**Comment by ronfischler** [comment]
Updated my checkout of branch 1.2 and yes, I confirm the issue is fixed. I have not tested the master branch version however, so I will let you close the issue if you feel it is fully resolved.

**Comment by CDrummond** [comment]
Change is the same for master and 1.2
