### ISSUE TITLE
Option to display bit-depth and sample rate

### ISSUE THREAD

**Issue by rmccu** [CDrummond/lms-material#188]
There is an option to "Display technical info" that will display the bitrate of the file, but it would be nice to see the bit-depth (e.g. 16/24/32-bit) and sample rate (e.g. 44.1/48/88.2/96khz etc.)

**Comment by CDrummond** [comment]
I can add sample rate, but (AFAIK) there is no way to get the bit depth. However, (as with most of the technical info) I fail to see the point in showing this.

**Comment by CDrummond** [comment]
Implemented (samplerate) in 1.2 branch for 1.2.0

**Comment by rmccu** [comment]
Thanks. I will read around about bit depth. The reason I would like to know this is I have some albums that are 16/44.1 or 48khz and then others that are 24-but with varying sample rates. So it helps to know which albums/songs are which. 

Would it be possible to put this in the format of the album name?

**Comment by CDrummond** [comment]
No. I'm not going to add this to the album listing.

Why does it help to know this? Surely _listening_ to the music is important. Not its file format, bit rate, sample rate, etc.

**Comment by cavemandaveman** [comment]
> I can add sample rate, but (AFAIK) there is no way to get the bit depth. However, (as with most of the technical info) I fail to see the point in showing this.

@CDrummond When navigating to the 3 dot menu on a track > More > More Info, there is a field called Sample Size, which is synonymous with bit-depth. Is there a way to grab this field and show it as part of the technical info, next to the sample rate?

**Comment by CDrummond** [comment]
No, this info needs to be in the status messages - and its not.
