### ISSUE TITLE
Mobile on PC - links in Queue

### ISSUE THREAD

**Issue by d6jg** [CDrummond/lms-material#189]
Links shown in Queue do not work when you run Material in Mobile mode on a PC.
Links shown in Queue DO work when you run Material in Desktop mode on a PC.
Screenshot is Chrome (app mode) running /Material/mobile

![image](https://user-images.githubusercontent.com/47001366/68484471-3a213b00-0235-11ea-828a-aa934fb943c7.png)

On a proper mobile device the Queue does not display links (correctly)

**Comment by CDrummond** [comment]
Actually the links work, just the view is not changed - which is a bug in itself. You can confirm by switching to browse afer clicking a link.

**Comment by d6jg** [comment]
Please feel free to rename the Issue accordingly then 😊

Kind regards


Jim Gooch
Director
Double 6 Ltd
Direct Line +44 (0) 845 508 1950
Mobile  +44 (0) 7802 550302
Support +44 (0) 1270 898 044
VOIP 8120540@draytel.org<mailto:8120540@draytel.org>
Skype double6jg
www.double6.net<https://www.double6.net/>
