### ISSUE TITLE
[feature request] lyrics font size

### ISSUE THREAD

**Issue by s-timm** [CDrummond/lms-material#191]
Hey! 
First, thanks A LOT for your awesome theme. I really love it and it has replaced two apps I was using before! 

There is only one thing that bothers me at the moment: I am using a tablet in landscape mode in the kitchen to control my LMS. I use the desktop mode to use most of the space available (1920x1080 pixels).
However, when I switch to see the lyrics the font-size is far too small (I am reading the lyrics while cooking from a meter or so away). So I'm always modifying the CSS to get a bigger font-size for "np-info-lyrics" to xx-large or xxx-large. But I have to do this every time there is an update :-(

So this is my request: 
Could you maybe include a plus/bigger and minus/smaller button on the lyrics page to change the font-size? And remember the setting? That would be so cool!

Best regards

**Comment by CDrummond** [comment]
Implemented in 1.2 branch for 1.2.0

**Comment by s-timm** [comment]
Wow, that was fast! Thank you! :-)
