### ISSUE TITLE
Qobuz integration works but very minor issue

### ISSUE THREAD

**Issue by d6jg** [CDrummond/lms-material#196]
Craig
I know you don't use streaming services but you will be pleased to know that Material works very well with Qobuz plugin bar one tiny issue which is that when you add an artist, album or track to Qobuz favouites via "More" it returns "empty" in the pop up but it does actually work!

From More
![image](https://user-images.githubusercontent.com/47001366/70254852-ae3ff780-177d-11ea-9642-4cd1dcba00c4.png)

Choose Manage Favourites

![image](https://user-images.githubusercontent.com/47001366/70254897-bf890400-177d-11ea-9d6f-ce2715c296eb.png)

Choose one of the Add options

![image](https://user-images.githubusercontent.com/47001366/70254933-cca5f300-177d-11ea-9478-965bd9da3fbc.png)

Returns

![image](https://user-images.githubusercontent.com/47001366/70254963-dcbdd280-177d-11ea-8399-157b1b4799e6.png)

Obviously very very low priority

**Comment by CDrummond** [comment]
Can you attach the JSON debug logging for this? I have code to exclude 'Empty' - if its Material that's setting this.

**Comment by d6jg** [comment]
[6:24:00 PM] JSON REQ: ["00:04:20:1f:53:70",["trackinfo","items",0,25000,"menu:trackinfo","track_id:-178146920","item_id:19.0.0","url:qobuz://45929060.flac"]]
utils.min.js?r=1.2.0:24 [6:24:00 PM] JSON RESP: {"method":"slim.request","id":1,"result":{"title":"Add 'Kenny Dorham' to favorites","window":{"windowStyle":"text_list"},"base":{"actions":{"go":{"itemsParams":"params","params":{"track_id":"-178146920","menu":"trackinfo","url":"qobuz://45929060.flac"},"cmd":["trackinfo","items"]},"playControl":{"player":0,"itemsParams":"playControlParams","params":{"_index":"0","item_id":"19.0.0","_quantity":"25000","url":"qobuz://45929060.flac","track_id":"-178146920","menu":"trackinfo"},"window":{"isContextMenu":1},"cmd":["trackinfo","items"]},"add-hold":{"itemsParams":"params","player":0,"cmd":["trackinfo","playlist","insert"],"params":{"track_id":"-178146920","menu":"trackinfo","url":"qobuz://45929060.flac"}},"play":{"itemsParams":"params","player":0,"cmd":["trackinfo","playlist","play"],"nextWindow":"nowPlaying","params":{"track_id":"-178146920","menu":"trackinfo","url":"qobuz://45929060.flac"}},"more":{"cmd":["trackinfo","items"],"params":{"track_id":"-178146920","menu":"trackinfo","url":"qobuz://45929060.flac"},"window":{"isContextMenu":1},"itemsParams":"params","player":0},"add":{"player":0,"itemsParams":"params","params":{"track_id":"-178146920","menu":"trackinfo","url":"qobuz://45929060.flac"},"cmd":["trackinfo","playlist","add"]}}},"item_loop":[{"text":"Empty","type":"text","style":"itemNoAction","action":"none"}],"count":1,"offset":0},"params":["00:04:20:1f:53:70",["trackinfo","items","0",25000,"menu:trackinfo","track_id:-178146920","item_id:19.0.0","url:qobuz://45929060.flac"]]}
utils.min.js?r=1.2.0:24 [6:24:00 PM] JSON REQ: ["00:04:20:1f:53:70",["trackinfo","items",0,25000,"playlist_index:11","menu:1","html:1"]]
utils.min.js?r=1.2.0:24 [6:24:00 PM] JSON RESP: {"method":"slim.request","result":{"window":{"windowStyle":"text_list"},"base":{"actions":{"more":{"player":0,"itemsParams":"params","params":{"url":"qobuz://45929060.flac","track_id":"-178146920","menu":"trackinfo"},"window":{"isContextMenu":1},"cmd":["trackinfo","items"]},"add":{"params":{"url":"qobuz://45929060.flac","track_id":"-178146920","menu":"trackinfo"},"cmd":["trackinfo","playlist","add"],"player":0,"itemsParams":"params"},"playControl":{"itemsParams":"playControlParams","player":0,"cmd":["trackinfo","items"],"window":{"isContextMenu":1},"params":{"_index":"0","url":"qobuz://45929060.flac","_quantity":"25000","track_id":"-178146920","playlist_index":"11","html":"1","menu":"1"}},"add-hold":{"cmd":["trackinfo","playlist","insert"],"params":{"url":"qobuz://45929060.flac","track_id":"-178146920","menu":"trackinfo"},"itemsParams":"params","player":0},"play":{"nextWindow":"nowPlaying","params":{"url":"qobuz://45929060.flac","track_id":"-178146920","menu":"trackinfo"},"cmd":["trackinfo","playlist","play"],"player":0,"itemsParams":"params"},"go":{"itemsParams":"params","params":{"url":"qobuz://45929060.flac","track_id":"-178146920","menu":"trackinfo"},"cmd":["trackinfo","items"]}}},"item_loop":[{"actions":{"go":{"cmd":["playlistman","add","track"],"params":{"id":"-178146920","menu":1}}},"addAction":"go","text":"Add to ...","type":"redirect"},{"addAction":"go","text":"Music, Walk With Me","actions":{"go":{"cmd":["trackinfo","items"],"params":{"menu":"trackinfo","track_id":"-178146920","isContextMenu":1,"item_id":"1","url":"qobuz://45929060.flac"}}}},{"actions":{"go":{"cmd":["playlistcontrol"],"params":{"cmd":"add","track_id":"-178146920"},"nextWindow":"parent","player":0},"play":{"cmd":["playlistcontrol"],"params":{"cmd":"add","track_id":"-178146920"},"nextWindow":"parent","player":0},"add":{"cmd":["playlistcontrol"],"params":{"cmd":"add","track_id":"-178146920"},"nextWindow":"parent","player":0}},"style":"item_add","addAction":"go","type":"text","text":"Add to End"},{"actions":{"add":{"player":0,"nextWindow":"parent","params":{"cmd":"insert","track_id":"-178146920"},"cmd":["playlistcontrol"]},"play":{"player":0,"nextWindow":"parent","params":{"cmd":"insert","track_id":"-178146920"},"cmd":["playlistcontrol"]},"go":{"player":0,"nextWindow":"parent","params":{"cmd":"insert","track_id":"-178146920"},"cmd":["playlistcontrol"]}},"style":"item_insert","text":"Play Next","type":"text","addAction":"go"},{"addAction":"go","type":"text","text":"Play","actions":{"go":{"nextWindow":"nowPlaying","params":{"cmd":"load","track_id":"-178146920"},"cmd":["playlistcontrol"],"player":0},"play":{"nextWindow":"nowPlaying","params":{"cmd":"load","track_id":"-178146920"},"cmd":["playlistcontrol"],"player":0}},"style":"itemplay"},{"actions":{"go":{"player":0,"params":{"url":"qobuz://45929060.flac","title":null,"isContextMenu":1},"cmd":["jivefavorites","add"]}},"style":"item_fav","addAction":"go","type":"text","text":"Save to Favorites"},{"text":"Artist: Kenny Dorham","type":"text","style":"itemNoAction","action":"none"},{"style":"itemNoAction","action":"none","text":"Album: Afro-Cuban","type":"text"},{"text":"Year: 2012","type":"text","style":"itemNoAction","action":"none"},{"actions":{"go":{"params":{"item_id":"9","url":"qobuz://45929060.flac","track_id":"-178146920","isContextMenu":1,"menu":"trackinfo"},"cmd":["trackinfo","items"]}},"text":"More Info","addAction":"go"},{"type":"text","text":"Title: Lotus Flower","action":"none","style":"itemNoAction"},{"addAction":"go","type":"link","text":"What Was That Tune?","actions":{"go":{"params":{"track_id":"-178146920","isContextMenu":1,"menu":"trackinfo","item_id":"11","url":"qobuz://45929060.flac"},"cmd":["trackinfo","items"]}}},{"actions":{"go":{"params":{"url":"qobuz://45929060.flac","item_id":"12","menu":"trackinfo","track_id":"-178146920"},"cmd":["trackinfo","items"]}},"addAction":"go","text":"On Spotify: Kenny Dorham"},{"actions":{"go":{"cmd":["trackinfo","items"],"params":{"track_id":"-178146920","menu":"trackinfo","url":"qobuz://45929060.flac","item_id":"13"}}},"addAction":"go","text":"On Spotify: Afro-Cuban"},{"addAction":"go","text":"On Spotify: Lotus Flower","actions":{"go":{"cmd":["trackinfo","items"],"params":{"track_id":"-178146920","menu":"trackinfo","url":"qobuz://45929060.flac","item_id":"14"}}}},{"actions":{"go":{"cmd":["trackinfo","items"],"params":{"menu":"trackinfo","track_id":"-178146920","item_id":"15","url":"qobuz://45929060.flac"}}},"addAction":"go","type":"outline","text":"Artist information"},{"actions":{"go":{"params":{"menu":"trackinfo","track_id":"-178146920","item_id":"16","url":"qobuz://45929060.flac"},"cmd":["trackinfo","items"]}},"text":"Album information","type":"outline","addAction":"go"},{"actions":{"go":{"params":{"menu":"trackinfo","track_id":"-178146920","item_id":"17","url":"qobuz://45929060.flac"},"cmd":["trackinfo","items"]}},"type":"link","text":"Lyrics","addAction":"go"},{"actions":{"go":{"cmd":["trackinfo","items"],"params":{"url":"qobuz://45929060.flac","item_id":"18","menu":"trackinfo","track_id":"-178146920"}}},"addAction":"go","text":"Personnel"},{"text":"On Qobuz","addAction":"go","actions":{"go":{"params":{"track_id":"-178146920","menu":"trackinfo","url":"qobuz://45929060.flac","item_id":"19"},"cmd":["trackinfo","items"]}}}],"count":20,"offset":0},"id":1,"params":["00:04:20:1f:53:70",["trackinfo","items","0",25000,"playlist_index:11","menu:1","html:1"]]}

**Comment by CDrummond** [comment]
The debug does not line up with your screenshots. However, I _think_ the area of code does not have enough debug.

I've added some debug that _might_ help, please:

1. Download `browse-page.min.js` from https://filebin.net/ru5tk8r0wh89bjnr/browse-page.min.js?t=u6reytxo
2. Copy this to `MaterialSkin/HTML/material/html/js/`
3. Restart LMS
4. Reload Material in your browser (but with no `?debug=json`, etc.), and do a full cache re-load (Ctrl-shift-R in firefox)
5. Recreate the issue
6. Paste the text from the console tab of your browser's developer tools, here

Thanks.

**Comment by CDrummond** [comment]
...actually, use the version in this ZIP file (its the same, but saves using 3rd party site):

[browse-page.zip](https://github.com/CDrummond/lms-material/files/3929375/browse-page.zip)
