### ISSUE TITLE
Auto focus on Search input

### ISSUE THREAD

**Issue by sifus** [CDrummond/lms-material#198]
When i click on search option on spotty, i do have click agin in the input.

It will be more efficiant to be auto focus on search input...

**Comment by CDrummond** [comment]
Sorry, I don't use any streaming services - so don't have access to spotify. However, I'm not sure what you are referring to. Spotty's search field should be an entry field within the list - in the browse view, or the left had side of desktop layout. To enter text you need to click on the field. I'm unsure as to why you think you need to click again.

I've tried with the YouTube plugin, which has multiple entry fields. A single click causes the field to get focus.

How does Spotty's search item appear?

**Comment by mikecappella** [comment]
He's correct.  When you click Search, you're taken to the Search page, but the search entry field is not selected, so you have to select it first before you can type.  What do you need?

**Comment by CDrummond** [comment]
Ah, so in this search page is the entry field the only item in the list? Of so, I guess I could auto focus an entry field if it is the only item.

(Wonder why spotty does not just have the entry where you click search. Still, that's an issue for spotty.)

**Comment by mikecappella** [comment]
Correct.
<img width="699" alt="image" src="https://user-images.githubusercontent.com/8551810/70855222-5f304b80-1e7c-11ea-938b-52fe247204c3.png">

**Comment by michaelherger** [comment]
I think this is not a bug but unfulfilled user expectations. The Search item would indeed open a sub menu with previous searches, and the first item would be the text input. I've never seen a text input automatically get the focus. Eg. go to Radio, and you'd have to click it, too.  Therefore I believe there's nothing wrong here, and this is more a feature request.

**Comment by CDrummond** [comment]
But the search item is not the only item. So, nothing I can do here. On mobile if I auto focus the keyboard will come up. I could auto focus on desktop, but then the "new search" text will be hidden.

**Comment by sifus** [comment]
Yes sorry this is not a bug but an improvement. (I don't know where to write it)

@michaelherger is an ergonomic rule:
"if I click on" Search ", the next step should focus on the search action"

I understand "the historical element" but it is another use.

on mobile, you can open the keyboard, this is the normal route of the user when a user clicks on "search".
Moreover, even with the keyboard up, the user can scroll on historic list

**Comment by CDrummond** [comment]
Implemented for desktop browsers. However, the keyboard auto-appearing on mobile just feels odd, so not implemented there.

**Comment by sifus** [comment]
ok no problem, thank you for your reactivity :)
