### ISSUE TITLE
Customize now playing with metadata/tags

### ISSUE THREAD

**Issue by rmccu** [CDrummond/lms-material#199]
It would be nice if I could configure the now playing screen to add in some metadata/tags. Probably around the area where the bitrate & codec is (e.g. "804kbps VBR • flc").

It would be awesome if I could modify the album list to show tags as well.

**Comment by CDrummond** [comment]
No, sorry - not interested in adding more data to nowplaying screen. What else would be required?

As to albums, Material shows the relevant info that is obtainable from the JSON API as is. So again, no.
