### ISSUE TITLE
Tab per player?

### ISSUE THREAD

**Issue by bushchannelstepper** [CDrummond/lms-material#200]
First, thanks for this excellent piece of work.  I especially appreciate the sleep timer showing up in the web GUI.

I have a feature request - I've long wondered why each player needs to be picked through the drop-down instead of having a tab per player.  Is this something you think would be straightforward to implement in the MUI skin?

Thank you

**Comment by CDrummond** [comment]
No, sorry. This would definitely not work for mobile - too cramped. For desktop, the volume, now-playing bar, and eve browse view (as different players can have different modes) would be different per-player.

So, just use different browser tabs.
