### ISSUE TITLE
Random Mix - not all settings visible

### ISSUE THREAD

**Issue by d6jg** [CDrummond/lms-material#203]
In default GUI there are some settings that aren't visible in Material

![image](https://user-images.githubusercontent.com/47001366/71893051-7512f280-3142-11ea-87f6-c147ed5e89ae.png)

**Comment by CDrummond** [comment]
...and those options are needed becasue? To me they look like a server setting. Why would I want this configurable per mix?

**Comment by d6jg** [comment]
You wouldn’t need them per mix but equally they are not exposed in Server Settings at all

I noticed it because I use Random Seed favourites in conjunction with LastMix/DSTM viz:

randomplay://track?genres=Blues%20Rock&dontContinue=1

Michael added this functionality sometime last year. It uses the 10 : 10 setting.

When I set up the Favourites I altered the settings to be 5 : 5 rather than 10 : 10.

There is no way to do this in material at all.

Very Minor.

Kind regards


Jim Gooch
Director
Double 6 Ltd
Direct Line +44 (0) 845 508 1950
Mobile  +44 (0) 7802 550302
Support +44 (0) 1270 898 044
VOIP 8120540@draytel.org<mailto:8120540@draytel.org>
Skype double6jg
www.double6.net<https://www.double6.net/>

**Comment by CDrummond** [comment]
But why is it needed? Just becasue LMS can support an option does not mean it should be shown. Why would I care if it was 10 tracks, or 50?

**Comment by d6jg** [comment]
You wouldn’t care a toss but my Random Seed doesn’t want 50 tracks before LastMix/DSTM kicks in it just wants (in my case) 5.

Don’t worry about it – it was more an observation than an issue.

Kind regards


Jim Gooch
Director
Double 6 Ltd
Direct Line +44 (0) 845 508 1950
Mobile  +44 (0) 7802 550302
Support +44 (0) 1270 898 044
VOIP 8120540@draytel.org<mailto:8120540@draytel.org>
Skype double6jg
www.double6.net<https://www.double6.net/>

**Comment by CDrummond** [comment]
I have no issue adding it, just want a clear use case. What's wrong with the default of 10 tracks before it kicks in. Why 5?

**Comment by d6jg** [comment]
Good question.
The answer is that the more random tracks you have the more there is likely to be a rogue in the mix.
The seed is random but as soon as LastMix/DSTM kicks in it becomes focused.

That said there is no problem with the default so leave it.

Kind regards


Jim Gooch
Director
Double 6 Ltd
Direct Line +44 (0) 845 508 1950
Mobile  +44 (0) 7802 550302
Support +44 (0) 1270 898 044
VOIP 8120540@draytel.org<mailto:8120540@draytel.org>
Skype double6jg
www.double6.net<https://www.double6.net/>

**Comment by CDrummond** [comment]
Done for 1.3 The reason these settings weren't there before, is that they are not in the JSONRPC API for RandomMix. They're actually config items, so I've added code to read and set these.
