### ISSUE TITLE
Browse Menu Navigation - Mobile display on phone

### ISSUE THREAD

**Issue by ronfischler** [CDrummond/lms-material#209]
I am using the Browse pane on my Android phone: I touch Apps and of course I get the Apps list. Now, I tap the back-arrow at the top to return to the Home menu. What happens however is after returning, we immediately descend into the first app listed. Something interesting is that if I keep my finger pressing on the back-arrow for a couple of seconds, then I return properly to the Home display. This seems to only happen when I am trying to return from Apps.

I duplicated this behavior in multiple browsers, to make sure it wasn't specific to Kiwi.

I don't know when this behavior began, but I think it is fairly recent.

**Comment by CDrummond** [comment]
Confirmed! Very odd. **Only** happens when navigating out of Apps, and only if an app is the 1st pinned item.

**Comment by ronfischler** [comment]
I pulled the last commit to material to remove the long-press on the back-button, but the behavior navigating out of Apps remains on my Android 10 phone, tested in Kiwi, Opera, and Chrome. Strange but this behavior is NOT occurring using the Firefox mobile browser. Very weird.

**Comment by ronfischler** [comment]
OK, maybe I am suffering some kind of pilot error, as the long-press action still works on the back button.

**Comment by CDrummond** [comment]
Clear your browser's cache. The code has been removed, so can't act on long-press.

**Comment by ronfischler** [comment]
You were right of course. I cleared out my mobile browser's cache, and the issue is solved. I thought I had done that to begin with, but somehow I had failed to do it correctly. Thank you.
