### ISSUE TITLE
v1.4 Screensaver Feature

### ISSUE THREAD

**Issue by ronfischler** [CDrummond/lms-material#217]
In testing, I have found an issue when this feature is enabled:

When the player being monitored by material is currently playing, and I do any action such as changing the volume or browsing my music and then leave material alone, then 60sec later the screensaver will activate, but only momentarily. This only happens once after the last action.

Assuming the timer is running, then it seems that just before displaying the screensaver, that the enabling function needs to check if the player is playing or not.

**Comment by ronfischler** [comment]
In addition, I found another issue with screensaver which is difficult to describe.

Scenario:
Using my Android phone, I start playing something, and I turn the phone display off: when the song ends, I wait a while - more than 60s, I assume the screensaver came on. However, I turn back on the display, and material displays normally. If I don't touch it, the display stays normal without the screensaver ever appearing. I suspect material assumes the screensaver is on the screen, when it is not.

If I leave that alone and switch to another app, and then switch back, the screensaver is now on, and I cannot get out of it ... I have to kill the browser. It seems that when the screen is off, the screensaver code is either not running, or it is not aware of the state of the display.

This feature might be difficult to make bullet proof!

**Comment by CDrummond** [comment]
Please update and try again. Made some changes, not 100% sure if they help.

**Comment by ronfischler** [comment]
I updated my v1.4 checkout, cleared the cache and restarted the browser & material on both my phone and laptop. I have not finished testing, but I wanted to give my status so far, and I think the changes do appear to be helping. I have not gotten stuck in the screensaver again after the update.

**Comment by ronfischler** [comment]
OK, this is strange, and this behavior is new with the update ... the screensaver appeared to be working correctly at first, but then I switched the current player being monitored by material to another, (I currently have four devices connected to my LMS server,) and I began playing on that one, and despite playing, after 60s of no mouse/keyboard activity - the screensaver faded in anyway. I do an action to restore the display, but then the behavior repeats again. 

I suspect somehow, the screensaver feature is still looking at the original player, and seeing that it is not playing  any longer, is basing it's decision to activate based on that original player, not the current one. Just a guess.

**Comment by ronfischler** [comment]
Testing last commit: the behavior of the screensaver coming on when it should not appears to be fixed.

In testing, I notice something now: when the screensaver comes on when it should, I found that clicking the mouse in the material display does not drop the screensaver; I have to move the mouse. Hitting a key on my laptop keyboard works, but a mouse click does not. Strange.

On my phone, touching the screen works to drop the screensaver, and I would have thought that is identical to a mouse click on a laptop, but maybe not? I note that tapping the laptop touchpad does not drop the active screensaver either; I have to slide my finger on the touchpad. I think this is new behavior.

**Comment by ronfischler** [comment]
Updated to last commit, testing using Kiwi, Firefox, and Vivaldi browsers, and the inclusion of mousedown has fixed the problem of mouse clicks failing to deactivate the screensaver function.

I will continue with testing...

**Comment by ronfischler** [comment]
I think this is working well now. It looks good on my TV, connected to my LMS server via an HDMI cable. This is the  intended usage, this or a dedicated Android tablet in webapp / kiosk mode.

I believe this issue can be closed, but I have a question regarding use on my phone running Android 10: if I pause the player, (SB Player,) in material and lock the phone, the Android lock screen is displayed. I then come back >60s later and unlock the phone, re-enabling the screen: it comes up showing the Now Playing display for an instant but then a moment later the screensaver starts to come on, and then immediately fades out. Is it possible to keep the screensaver from flashing on/off like this when the phone is unlocked? Can Javascript detect if the screen is not running or unavailable, and not start the screensaver to begin with? This is a minor point now, and I think the feature is pretty solid.

**Comment by CDrummond** [comment]
Can you try removing line 60, `bus.$emit('hasFocus');`, from `server.js`? Does this help? Or make things worse?

**Comment by ronfischler** [comment]
I commented out line 60, server.js. 

The behavior is different: if the material screensaver comes on while the screen is off or the browser is minimized for >60s while not playing, then when made visible again, the screen saver comes on after a moment, but now it stays on waiting for a user action, rather than flashing on then off.

I think maybe this is better. I imagine an expert in GUI presentation would say that anything flashing fast enough that the user cannot be certain what was on the screen is never a good idea.
