### ISSUE TITLE
Tool tip for the "next" button is missing

### ISSUE THREAD

**Issue by sonor3000** [CDrummond/lms-material#219]
In version 1.3 in the mobile view the tool tip for the "next" button is missing. Because all other buttons are labeled perfectly I was able to find the button with my screen reading software, butt adding the tool tip for the button would be nice anyway :-).
working fine

**Comment by CDrummond** [comment]
Hmm... I'm seeing a tooltipf for "Next track". Jsut noticed "Stop" (if enabled) does not have a tooltip. Will look further.

**Comment by CDrummond** [comment]
Do you have the stop button set to show? Is it possible you're confusing the stop and next buttons?

**Comment by CDrummond** [comment]
As stated, 'next' button has tooltip, but 'stop' did not. Fixed now.

**Comment by sonor3000** [comment]
Sorry for not responding earlier..., but still no tool tip or alternative text for the next button is shown in the mobile view :-(.

How to reproduce:

- Open LMS in the Safari browser with the material skin activated on an iOS device. I used my iPhone 7 with the latest iOS.
- Activate the VoiceOver screen reader in the settings on the iOS device.
- Now flig from left to right with one finger to go from one element to the other in the opened LMS page till you reach the next button. There no text is read, VoiceOver only sais "Button".

On Windows with Google Crome and on the Mac with Safari the tool tip / alternative text for the button is read, so maybe it is a problem related to VoiceOver on my iOS device...

**Comment by CDrummond** [comment]
Ah! For some, stupid reason, I'd placed the tooltip for the next button on the icon not the button! Fixed for 1.3.2. Sorry.
