### ISSUE TITLE
Artist and album name in search results for titles

### ISSUE THREAD

**Issue by alexkleinwaechter** [CDrummond/lms-material#221]
Hi Craig,

first of all thanks for the great work. You really know how to handle vue/vuetify :-) Is it possible to show the artist and album title in the search results for titles like in the original lms frontend? If you have a lot of different versions of a song it can be hard to find the right one.

Material skin:
![image](https://user-images.githubusercontent.com/24670532/73298640-f9bad300-420d-11ea-9a0e-0272ed8af62a.png)

LMS:
![image](https://user-images.githubusercontent.com/24670532/73298740-2a9b0800-420e-11ea-915f-d1fa548d6261.png)

That would be great!
Best
Alex

**Comment by alexkleinwaechter** [comment]
Yay! Thanks!

**Comment by CDrummond** [comment]
Also, for the next feature release (1.4.0) I've changed the 'All' search to perform artist, album, track, and playlist searches separately, and then combine the results. What this means is that all the metadata, that appears when you search on just one type, will be there on results for 'All' Previously I used LMS's search API for this 'All' search, and it only returned limited metadata.
