### ISSUE TITLE
## FEATURE REQUEST ## Make the interface more "Material" like

### ISSUE THREAD

**Issue by gsi095** [CDrummond/lms-material#226]
Hi,

Is it possible to make the interface even more "material" like? Just some small tweaks. I love the theme and I can see a few small changes that would make it even better. 

Im not sure where to start with custom css. 

Some examples are:

- flattening the top and bottom bars to remove the shadow lines. A flat line is what most modern players use. 
- dark theme be totally black, not black and grey (like the dark sonos interface)
 https://apps.apple.com/au/app/sonos-controller/id293523031
- allow the top or bottom bar (or both) to be be coloured. e.g. everything white except the bottom navigation bar black with white text.
- unify text around a single font. E.g. the track number (e.g. 1/12) and time stamps are a different font 

Thanks for all your work on this

Dave

**Comment by CDrummond** [comment]
Material uses the vuetifyjs framework for its Material look. Answering your points:

1. Shadows are, and always have been, part of Material - see https://material.io/components/ But I'll consider removing them.
2. Not keen on yet another theme. And definetly not an all black theme - this would move the differantiation between fixed content (the top/bottom bars) and the scrollable area.
3. Again, not keen on this, too much work for no real gain. Finding colour combinations that work (e.g. with the blue of th etime progress, volume slider, etc.) is non trivial.
4. No. Roboto, the Material font is used in 99% of places. Numbers use a monospace font to prevent jitter.  "01:01:01" has a different width to "08:08:08" with non-monospace fonts.

**Comment by CDrummond** [comment]
I've removed the shadows, and adjusted the dark/light CSS files to make further customisation easier. I'm thinking of 3 variants; light, dark, and black. The I might add different variants for the highlight colour (currently blue). So you could have e.g. Black variant with Yellow highlight.

**Comment by CDrummond** [comment]
Closing, most points implemented now. You can use a custom CSS file to colour the top/bottom bars.

**Comment by CDrummond** [comment]
p.s. For 1.4.0, you can now choose; light, light (with coloured top/bottom bars), dark, dark (with coloured top/bottom bars), and black. For each of these you can choose the colour to be used; red, purple, blue, green, orange, brown.

**Comment by gsi095** [comment]
wow thanks. I look forward to 1.4.0 being released

I absolutely love this theme. Its the only reason I stay with LMS

**Comment by gsi095** [comment]
Quick question, do I need to wait for you to release 1.4 as the latest
version or is there a way to run the 1.4 branch now?

Thanks
Dave

**Comment by CDrummond** [comment]
If you want to run 1.4 now, then you need to:

1. Use the 'Clone or download' button on the main github page
2. Checkout the 1.4 branch
3. Copy the 'MaterialSkin' folder to a plugin folder on your LMS installation

Note, that 1.4 is still under heavy development.
