### ISSUE TITLE
Additional browse mode is missing from My Music

### ISSUE THREAD

**Issue by terba** [CDrummond/lms-material#236]
One of my Additional Browse Modes doesn't show up in the Material Skin. I have two additional browse modes configured:

```
| Name:             | Apply to:       | Browse by: | Contributor Roles: | Genres: |
|Classical Composers|All music library|Artists     |COMPOSER            |Classical|
|Classical Albums   |All music library|Albums      |                    |Classical|
```
The `Classical Albums` is visible in My Music, but the other, the `Classical Composers` not. In the default skin it works.

**Comment by CDrummond** [comment]
Have you enabled this for Material? In Material, go to 'Settings', in the 'Browse' section you will see this list of 'Home screen' items. Click the cog icon next o 'My Music' This will produce another dialog allowing you to configure the modes shown in 'My Music'

Does that resolve it?

**Comment by CDrummond** [comment]
BTW, With Material you can browse via 'Genres > Classical > Composers', 'Genres > Classical > Albums'

**Comment by terba** [comment]
The cog icon did the trick! Thank you for the skin also.
