### ISSUE TITLE
Older Browser compatibility ?

### ISSUE THREAD

**Issue by afond** [CDrummond/lms-material#238]
Hi,

Great job with lms-material

I was experiencing issues with a gray empty screen on IOS 9.3.6 on iPad3 (last IOS and no update to be expected for this device)

I tried several browser (chrome, opera, firefox) but it’s look like they all use integrated safari 9 engine or framework (IOS limitation ?).

As far as i understood Safari 9 is not compatible with material skin and embeded components (react ? html5 ? other ?).

This old device is dedicated into controlling music and i’m upset it’s not being capable of rendering modern ui like material.

Do you think of a possible workaround ?

Best regards

**Comment by CDrummond** [comment]
Sorry - but I have no such device, so there is not much I can do about this.

iOS has only **one** rendering engine - Chrome, etc, are just wrappers around this. This is one of the reasons I would never by into iOS.
