### ISSUE TITLE
getVolume function in utils.js

### ISSUE THREAD

**Issue by DevFlorian** [CDrummond/lms-material#243]
Hi,
i'm writing an android app, that uses lms-material.
Is it possible to add a function to get the current Volume?
Thanks

Florian

**Comment by CDrummond** [comment]
Would a notification mechanism not be better? i.e. I could forward changes to volume, player, playback, etc? If I added a`getVolume` you'd have to poll this for changes. I did think about creating a simple wrapper around web/chrome-view, and I was going to use notifications from the javascript to java side so that I could show lock screen controls, etc.

**Comment by DevFlorian** [comment]
Yeah, good idea, but I just started and for now i need the initial volume when the App get started.

**Comment by CDrummond** [comment]
No, I will not add a `getVolume` for the reason stated. There's no way for you to know what the initial volume is, because you will not know when the player status has been updated. Therefore an initial value could be correct, or random. So, makes no sense to add this.

**Comment by DevFlorian** [comment]
Ok, so i would also need a notification, when the Player is changed and when volume is changed like you described before.

**Comment by CDrummond** [comment]
OK, I have no idea if this works - but I followed the notes @ https://medium.com/@elye.project/making-android-interacting-with-web-app-921be14f99d8 - also see https://github.com/elye/demo_web_native_app_interaction/blob/master/app/src/main/java/com/elyeproj/webappinteraction/MainActivity.kt

I used 'nativeObj' not 'androidObj' and used 'updateStatus' as function name. I guess you need to code like:

```
my_web_view.loadUrl("javascript: " +
                "window.nativeObj.textToAndroid = function(updateStatus) { " +
                JAVASCRIPT_OBJ + ".updateStatus(status) }")
```

Material will call `updateStatus` every time the player's status is updated.

**Comment by CDrummond** [comment]
Did the above change help? It's in 1.5.1 If its of no use, then I'll remove the code.

**Comment by DevFlorian** [comment]
Sorry, havn‘t tried it yet.

**Comment by DevFlorian** [comment]
It doesn´t work when i change players or call updateNative from console, but when i call window.nativeObj.updateStatus('test') from Console it works. So i guess there is an error in updateNative

**Comment by CDrummond** [comment]
As stated, I never tried any of this. When called on player updates, an object is passed to `window.nativeObj.updateStatus()` - does yu JAva code handle this being an object? Perhaps objects cannot be passed? If so, perhaps try `window.nativeObj.updateStatus(JSON.stringify(status));` - this will covert the status object into a JSON string, you then need to parse this in the Java code.

**Comment by DevFlorian** [comment]
it works, when i overrive your updateNative function like this:
`view.loadUrl("javascript: " + "updateNative = function(status) { window.nativeObj.updateStatus(status)}");`
I guess one of your checks cause that return is always called.
In witch cases do you expect them to pass and call window.nativeObj.updateStatus?

**Comment by CDrummond** [comment]
D'oh!!!! I'm 99.99% sure the error is the `!=` in

```
    if (undefined==window.nativeObj || undefined!=window.nativeObj.updateStatus) {
        return;
    }
```

i.e. the code should be:

```
window.nativeObj = function NativeClass(){};
function updateNative(status) {
    if (undefined==window.nativeObj || undefined==window.nativeObj.updateStatus) {
        return;
    }

    try {
        window.nativeObj.updateStatus(status);
    } catch (e) {
    }
}
```
...so I check both `window.nativeObj` and `window.nativeObj.updateStatus` are defined. Sorry about that.

Are you stating that it works if passing an object? I've re-added the code (with the above fix). Does it now work?

**Comment by CDrummond** [comment]
Any updates? Is your app open source, or will it be? Would be nice to see the code.

**Comment by DevFlorian** [comment]
Not yet. Unfortunately i have less time than i want for the app and yes it should be Open Source in the Future.

**Comment by CDrummond** [comment]
I've changed the code a little, details in README.md But I've tested and this is working under Android.

**Comment by CDrummond** [comment]
I've started to work on an Android WebView app to embed material - if you are interested its at https://github.com/CDrummond/lms-material

NOTE: Its at a VERY early stage!
