### ISSUE TITLE
Folder-specific scan-buttons not working

### ISSUE THREAD

**Issue by microrache** [CDrummond/lms-material#246]
In server-settings under "basic settings" there is a rescan-buttons next to each configured media folder. Unfortunately these buttons don't work for me (LMS v7.9.2 - 1578996832 w/ Material skin from github's master-branch). I always have to use the "Rescan Media Library"-option below the media folder section to initiate a complete rescan. Is this a general problem or does this issue correspont with my folder-names (see screenshot below)?

![image](https://user-images.githubusercontent.com/23389242/77247149-94dc9180-6c2e-11ea-80b6-9bdd41c094e1.png)

**Comment by CDrummond** [comment]
These pages are from LMS's Classic Skin. All material does is apply some CSS to make them more Material-like. So, if something is not working its an LMS or Classic Skin issue.
