### ISSUE TITLE
Feature Request: Play next buttons

### ISSUE THREAD

**Issue by grasshide** [CDrummond/lms-material#247]
Is it possible to have a "play next" button next to the play and add buttons (added in #237 I think) in the left plane? That is actually my most used function when adding music to a (usually long) playlist.
Thank you!!!

**Comment by CDrummond** [comment]
These are in the context menu (use the three dotted button). I'm not going to add to the hover/sub-tioolbar.

**Comment by bajax** [comment]
Would you accept a patch that adds this as an option?

**Comment by CDrummond** [comment]
No, if I wanted the buttons they'd be easy enough to add - I see no real need for these on hover.

**Comment by bajax** [comment]
Even as a configurable option?  There are obviously at least a few people who would like it.
