### ISSUE TITLE
Deezer not availlable in the applications

### ISSUE THREAD

**Issue by bricolodu13** [CDrummond/lms-material#251]
Hello,

Thank you for your plugin that is very well done !

I have tried a few applications (bandcamp, Qobuz, Soundcloud, Deezer)
Bandcamp is working fine
Qobuz is working fine
Soundcloud is working fine
I have checked that Spottify is showing, but I have no more active acount, so didn't tested
However, Deezer (needs a Logitech MySqueezebox account) is not showing.
I can activate Deezer with the default skin but it doesn't show in Material Skin.

Best Regards,
Jean

**Comment by CDrummond** [comment]
Shows for me.
