### ISSUE TITLE
Drag 'n Drop file doesn't work (Windows - Google Chrome)

### ISSUE THREAD

**Issue by bricolodu13** [CDrummond/lms-material#252]
Hello,

I have find a second issue.
The Drag 'n Drop plugin is not enabled under the Material Skin.
It is working perfectly under the default Skin, but not in Material Skin, may be it's because of web browser limitation ?

Best regards,
Jean

**Comment by bricolodu13** [comment]
> enabled

king

**Comment by bricolodu13** [comment]
Hello,

I have find a second issue.
The Drag 'n Drop plugin is not enabled under the Material Skin.
It is working perfectly under the default Skin, but not in Material Skin, may be it's because of web browser limitation ?

Best regards,
Jean

**Comment by CDrummond** [comment]
Not supported.

**Comment by CDrummond** [comment]
...but its a reasonable request, I'll see what I can do.
