### ISSUE TITLE
Rescan dropdown is empty

### ISSUE THREAD

**Issue by hctom** [CDrummond/lms-material#254]
Currently the rescan dropdown is empty under "Information". It opens the dropdown box, but there is nothing in it:

![image](https://user-images.githubusercontent.com/8543951/77849208-397c4780-71ca-11ea-8335-ba99778b83ce.png)

I hope this is only a minor issue. My current workaround for triggering a rescan is to server settings and use the buttons there.

Thanx in advance!

**Comment by CDrummond** [comment]
Ah!!!! This is due to my dev machine being on LMS8 and the required functionality is not in 7.x :( Will fix. Sorry.

**Comment by hctom** [comment]
Wow you are so fast! Thanks a lot for all your good work!
