### ISSUE TITLE
PWA Support

### ISSUE THREAD

**Issue by Vesyrak** [CDrummond/lms-material#255]
Hey,

First of all, thanks for the great work!

I'm looking into adding Progressive Web App support for the webpage, as it would make it easier for me to use. However, I cannot seem to get the files I add registered by the squeezebox webserver.

How do you exactly test your plugin?
I tried copying the files to the cache/nstalledPlugins/Plugins folder and to the squeezeboxserver/Plugins folder, but neither worked, so not sure how I should approach this.
I am working in a docker container, but I dont think that should be any different.

Thanks in advance!

**Comment by CDrummond** [comment]
Sorry, what files are you adding? If you are going to manually install the plugin, as in not via the plugin manager, then you should install to the top-level plugins folder. e.g. instead of `/usr/local/lms/Cache/InstalledPlugins/Plugins/` use `/usr/local/lms/Plugins/`

**Comment by Vesyrak** [comment]
In order to add PWA support, a service worker needs to be added that ensures offline functionality, together with an offline.html page. Additionally, headers need to be added and the manifest slighty adapted, adding support for e.g. 512x512 icons.

I can't seem to get it to work however. 
The way I understand it now is that I add the folder `MaterialSkin` to the `/usr/share/squeezeboxserver/Plugins` folder, and it gets installed.
The version on the plugin page shows that its detected (vtest) I guess. However, if I try to load offline.html I get 404s.

**Comment by CDrummond** [comment]
(I think) you will need to edit Plugin.pm to serve offline.html - as is done for mini.html, etc.

However, AFAIK, PWAs (and service workers) need to work over HTTPS, and LMS is HTTP.

**Comment by Vesyrak** [comment]
Ah, thank you, I'll check that out! And that's true, but it seems that I can bypass that using a proxy

**Comment by Vesyrak** [comment]
Adding WPA support seems to be more complex than I anticipated.
Do you perchance have any suggestions of docs on the plugin system?

**Comment by CDrummond** [comment]
Why do you want PWA support? Material needs constant access to LMS, so cannot work offline. I'm not sure what benefit PWA brings here.

Sorry, no docs on the plugin system.

**Comment by Vesyrak** [comment]
Purely for having an app icon instead of having to browse to a webpage. Speeds up my connection to the server. 
I also considered wrapping the page in an app, but then I thought this was considerably more easy and useful.

**Comment by CDrummond** [comment]
You can add the page to the android homescreen - works well with kiwi.

Currently I'm using 'Fully Kiosk Browser' with Nova launcher. Nova allows me to change the text and icon of apps - so I have changed the Fully name to LMS and set it to use Material's icon.

**Comment by Vesyrak** [comment]
That's actually a really neat solution and solves all my issues with PWA/LMS. Thanks!

**Comment by CDrummond** [comment]
I've started to work on an Android WebView app to embed material - if you are interested its at https://github.com/CDrummond/lms-material

NOTE: Its at a VERY early stage!

**Comment by Vesyrak** [comment]
I guess you meant https://github.com/CDrummond/lms-material-app ?

I will gladly check it out though, thanks for notifying!
