### ISSUE TITLE
Request: Use SETSUBTITLE Tag for multi-disc albums

### ISSUE THREAD

**Issue by chrober** [CDrummond/lms-material#257]
I highly appreciate the feature "When LMS is set to list a multi-CD album as 1 album, then visually split up the CDs' track listings, and allow to play individual CDs" introduced with v1.5.0.

I'd like to propose the following enhancement for it: "MusicBrainz Picard" is setting a tag called `SETSUBTITLE` if a disc has a dedicated name, e.g. https://musicbrainz.org/release/15cf95c2-bbe6-37cc-8a61-c5d5116b267a
So this new feature would be even greater if lms-material would display the disc names (if provided via `SETSUBTITLE`) instead of just "Disc x".

**Comment by chrober** [comment]
...or maybe display the `SETSUBTITLE` in addition to "Disc x"?
...and maybe even display it (optionally) for eaach song in the play queue in addition to the album title?

**Comment by CDrummond** [comment]
Sorry, JSONRPC API has no mention of this tag.

**Comment by chrober** [comment]
I can see this tag in lms-material, tough.
It is listed as `TSST` there:
![image](https://user-images.githubusercontent.com/26856218/78450354-3ed00b00-767e-11ea-9c3a-14cd0ae91f3c.png)

**Comment by CDrummond** [comment]
And??? I said the **API** does not support this field. Feel fee to prove me wrong.

**Comment by CDrummond** [comment]
Sorry, my last reply reads a bit aggressive - I apologise for that. I agree using the subtitle would be great, but unfortunately can't be done with current API. This API only returns a sub-set of all available tags.
