### ISSUE TITLE
Switch player between server

### ISSUE THREAD

**Issue by dede53** [CDrummond/lms-material#259]
Hey!

I found a small bug:
![Bildschirmfoto vom 2020-04-07 13-40-14](https://user-images.githubusercontent.com/13135177/78664965-5b19b500-78d5-11ea-8c51-ad84549ce6ee.png)

Looking to the files there should be the name of the server instead of %2.
The toolbar.js contains:
`i18n("Move '%1' from '%2' to this server?", player.name, player.server),`
And on the browserconsole is a value for player.server.
Thats why I expect the error in i18n.js:
```
function i18n(str, val, val2) {
    if (undefined==translation || !(str in translation) || translation[str]==="") {
        return undefined==val ? str : undefined==val2 ? str.replace("%1", val) : str.replace("%1", val).replace("%2", val2);
    }
    return undefined==val ? translation[str] : translation[str].replace("%1", val);
}
```

I'm not sure, but the second return-statement is missing the replacement of the second value and like this it should work well:

```
function i18n(str, val, val2) {
    if (undefined==translation || !(str in translation) || translation[str]==="") {
        return undefined==val ? str : undefined==val2 ? str.replace("%1", val) : str.replace("%1", val).replace("%2", val2);
    }
    return undefined==val ? translation[str] : undefined==val2 ? str.replace("%1", val) : str.replace("%1", val).replace("%2", val2);
}
```

I don't know how I can test this, so maybe my idea is wrong.
And for the future, how can I test it? Just start a webserver serving the whole repo?

Thank you very much for your incredible work!!

**Comment by CDrummond** [comment]
Thanks for the analysis, spot on. Fixed now.

To test, I just install the dev version of Material. I have it sym-linked into the top-level Plugins folder.

**Comment by dede53** [comment]
Amazing! 

Okay, that works! Thank you!
