### ISSUE TITLE
Please add updateNative again from #243

### ISSUE THREAD

**Issue by DevFlorian** [CDrummond/lms-material#261]
I just wanted to try handling updateNative with my Android App, but i noticed that i’ve already Updated it to 1.5.2.
Would you please add it again?
I‘m going to try it right after it‘s there again. 
Thanks

**Comment by CDrummond** [comment]
No. The code is in 1.5.2 If you need to use a version from git then checkout the 1.5.2 tag.

Please don't open new issues, but add to the existing one.
