### ISSUE TITLE
Advanced album search result buttons do not function correctly

### ISSUE THREAD

**Issue by doctorjames** [CDrummond/lms-material#262]
### With lower SEARCH option set to **Songs**:

- When searching for individual tracks using advanced search, clicking **play** or **add** works correctly. 

```html
<span class="browsedbLeftControls">	
<a href="/material/status_header.html?command=playlist&amp;subcommand=loadtracks&amp;track.id=12281666&amp;player=40%3A6c%3A8f%3Ab8%3A0a%3A4f" target="status"><img src="/material/html/images/b_play.gif" alt="Play" title="Play" width="13" height="13"></a>
<a href="/material/status_header.html?command=playlist&amp;subcommand=addtracks&amp;track.id=12281666&amp;player=40%3A6c%3A8f%3Ab8%3A0a%3A4f" target="status"><img src="/material/html/images/b_add.gif" alt="Add to Current Playlist" title="Add to Current Playlist" width="13" height="13"></a>
<a href="javascript:void(0);" onclick="toggleFavorite(this, 'file%3A%2F%2F%2Fmisc%2Fmedia%2Faudio%2Flibrary%2FMusic%2FAlbums%2FBryan%2520Ferry%2520Orchestra%2C%2520The%2F2012%2520-%2520The%2520Jazz%2520Age%2520(CD%25EF%25B8%25B0FLAC%25EF%25B8%25B016bit%25EF%25B8%25B044.1kHz%25EF%25B8%25B0Stereo)%2F05%2520Avalon.flac', '5.%20Avalon%20from%20The%20Jazz%20Age%20by%20The%20Bryan%20Ferry%20Orchestra')"><img src="/material/html/images/b_favorite.gif" alt="Save" title="Save" width="13" height="13"></a>
</span>
```

### Change lower SEARCH option to to **Albums**:

- Clicking over **play** in the results does nothing. 

- Clicking over **add** in the results opens another small player window and actually starts to play the album. (And if using Squeezelite-X the windows opens in the browser.)

```html
<span class="browsedbLeftControls">			
<a href="javascript:void(0);" onclick="toggleFavorite(this, 'db%3Aalbum.title%3DAvalon', 'Avalon')"><img src="/material/html/images/b_favorite.gif" alt="Save" title="Save" width="13" height="13"></a>
<a href="/material/status_header.html?command=playlist&amp;subcommand=loadtracks&amp;album.id=753127&amp;player=40%3A6c%3A8f%3Ab8%3A0a%3A4f" target="status"><img src="/material/html/images/b_play.gif" alt="Play" title="Play" width="13" height="13"></a>
<a href="/material/status_header.html?command=playlist&amp;subcommand=addtracks&amp;album.id=753127&amp;player=40%3A6c%3A8f%3Ab8%3A0a%3A4f" target="status"><img src="/material/html/images/b_add.gif" alt="Add to Current Playlist" title="Add to Current Playlist" width="13" height="13"></a>
<a href="/material/clixmlbrowser/clicmd=albuminfo+items&amp;album_id=753127&amp;linktitle=Information%20(Avalon)/?player=40%3A6c%3A8f%3Ab8%3A0a%3A4f" target="browser"><img src="/material/html/images/b_mmmix.gif" alt="More" title="More" width="13" height="13"></a>			
</span>
```

I think the the **play** button  ends up being the `toggleFavourite ` javascript link and the **add** button ends up being the loadtracks link. It's not clear to me why it opens another window but the **More** link has a `target="browser"` so maybe it gets involved somehow. 

Presumably the css modification needs tweaking to hide both these unwanted elements?

### Scroll to results

At present only the change in scrollbar visually indicates the results arriving.

I realise most of the functionality comes from the Classic theme advanced search page, but I see that the `<div id="browsedbList">` element only appears in the page when there are results. Is it possible to inject the `#browsedbList` fragment into the form element so that the window jumps to the results after submission?

```html
<form method="GET" name="searchForm" id="advSearchForm" class="resultsPage" action="advanced_search.html#browsedbList">
```

**Comment by doctorjames** [comment]
Hi Craig,

I'm using **Material Skin 1.5.4** with **Logitech Media Server Version: 8.0.0 - 1587185153** and I'm still seeing some of the erroneous behaviour I described above regarding the **play** and **add**  buttons in the advanced album results:

* Clicking over **play** in the album results does nothing.
* Clicking **add** starts to play the album.

(This is both on Firefox and Squeezelite-X)

The jump to the results works well.

Cheers.

**Comment by CDrummond** [comment]
Hmmm... you are correct. Order of buttons is different for album and song results.
