### ISSUE TITLE
Artists from online sources shown in Authors library

### ISSUE THREAD

**Issue by pascalberger** [CDrummond/lms-material#266]
There was a bug in LMS that the `Authors` library did show artists from online sources: https://github.com/Logitech/slimserver/issues/323. This was fixed in LMS and works now in default skin, but it still shows me the artists without albums from online sources in material skin.

**Comment by CDrummond** [comment]
Have you tried clearing Material's cache? Start Material:

```
http://<yourserver>:9000/material/?clearcache=true
```

This cache should be automatically invalidated (so subsequently recreated) when your library is rescanned, as Material uses the rescan time as part of the key. However, if a change is made to LMS's behaviour and you have not rescanned, then the cache could have old data.

**Comment by pascalberger** [comment]
`clearcache=true` didn't help. I also tried with a rescan (updated files)

**Comment by CDrummond** [comment]
Can you try Material from git? Because looking at the slimserver changes I see nothing that Material can influence. Have you tried other clients? iPeng, SqueezeCtrl, Squeezer???

**Comment by CDrummond** [comment]
Perhaps this is related to the API used? Looking at the slimserver change, a modification is made to BrowseLibrary.pm - which I think is called via "browselibrary". But Material does not use that, it use the "artists" JSONRPC call. Perhaps a change to this is also required?

@mherger https://github.com/Logitech/slimserver/issues/323 contains a change that modifies "BrowseLibrary.pm" for the "browselibrary" API call. Should a correspoding change not be made for the non-slimbrowse case? Material coverts "browselibrary" SlimBrowse calls into plain "artists" and "albums" calls. `["browselibrary","items", 0, 100, "library_id:5c4a4c4a","mode:myMusicArtistsAudiobooks"]` gets converted to `["artists", 0, 100, ,"library_id:5c4a4c4a","tags:sEQ"]`  Should I also pass `"mode:myMusicArtistsAudiobooks"` in the converted command?

**Comment by michaelherger** [comment]
The crucial change isn't that, but the check for `library_id`: if the menu is created for a particular `library_id` which is not the same as the default `library_id` for the client, then don't get the additional online artists. In that case only use `tags:s` instead of `tags:sEQ`.

**Comment by CDrummond** [comment]
@mherger OK, I can do that - easy enough. But isn't this altering what's `tags:` does? Every other `tag:` value changes the metadata that is returned, not the list of items. Now `EQ` is also acting as a filter. Seems a bit odd to me.

**Comment by CDrummond** [comment]
@pascalberger Can you use the git version of Material and confirm this is now fixed? I don't use any online streaming services, so cannot check myself.

**Comment by pascalberger** [comment]
@CDrummond I tested with current repo and this issue has been fixed. Thank you very much 👍
