### ISSUE TITLE
Change Color of Icon in Browser Tap

### ISSUE THREAD

**Issue by hme0354** [CDrummond/lms-material#267]
Is it possible to change the color of the Icon in the Browser Tap?

**Comment by CDrummond** [comment]
What? What icon? "Browser Tap"??? Do you mean "Browser Tab"? As in change Material's icon???

**Comment by hme0354** [comment]
yes, I mean the browser tap. The blue muscial note. Is it possible to change the color?

**Comment by CDrummond** [comment]
This icon is Material's icon - so I have not intention of changing. You have not eve said why you would want it changed.
