### ISSUE TITLE
Mute Button

### ISSUE THREAD

**Issue by Cessquill** [CDrummond/lms-material#270]
Hi - I currently have my LMS playing internet radio pretty much all day while working from home.

Would it be possible to add an optional mute button somewhere?  Would be very handy when taking a call to cut the sound rather than kill the stream.

I get I could just drag to zero, press stop, turn off the amp, etc., but when the phone/PC rings a quick mute would be perfect.

**Comment by CDrummond** [comment]
Long press the volume button.

**Comment by Cessquill** [comment]
Thanks!  Tried double-clicking it, but not long clicking.

(would prefer the option of a dedicated button though, since when I need to mute it's relatively urgent)
