### ISSUE TITLE
Add Spanish lang 

### ISSUE THREAD

**Issue by sauriodino** [CDrummond/lms-material#271]
Hi, is possible to add Spanish language to the lang folder? I know it’s a blank file to edit it in there, but my question is related to how to edit the language file, parts are in Spanish and parts in English, like “My Music” instead of “Mi Música”, thanks

**Comment by CDrummond** [comment]
copy `blank.json` to `es.json` and update any strings that you want translated. e.g.
```
{
"%1 Menu":"%1 Menú",
"%1 minutes":"",
....
```

Now when Material sees `%1 Menu` it will convert to `%1 Menú`, but `%1 Minutes` will be last as is - as there is no translation.

(%1 is a pclceholder that gets replaced with a value when running)

**Comment by sauriodino** [comment]
Thanks @CDrummond
