### ISSUE TITLE
Player's power state icon: colors ambiguous

### ISSUE THREAD

**Issue by schnillerman** [CDrummond/lms-material#274]
The power state of a player seems to be indicated by a grey (off) and dark blue (on) icon. The two cannot (at least by me) be easily distinguished. It would help to indicate power state on by an e.g. green icon.

**Comment by CDrummond** [comment]
Same colour is used for other 'toggle' elements. If blue is not sufficient for you, choose another colour.

**Comment by schnillerman** [comment]
I just screened the manual but didn't get across how to customize colors if that's what you mean. Would you mind telling me how?

**Comment by CDrummond** [comment]
Manual is out of date - its for 1.2, Material is now at 1.5

Go to 'Settings' in main menu (top right three dotted button).

**Comment by schnillerman** [comment]
How cool - I thought this was the color setting for the main color, not the highlights. Well okay then, I'm very happy now. Would you also add white as a color?

Von: CraigD <notifications@github.com>
An: CDrummond/lms-material <lms-material@noreply.github.com>
Kopie: schnillerman <mi6@mailueberfall.de>, Author <author@noreply.github.com>
Empfangen: 03.05.2020 10:31:45
Betreff: Re: [CDrummond/lms-material] Player's power state icon: colors ambiguous (#274)

**Comment by CDrummond** [comment]
No, sorry - too much hassle.
