### ISSUE TITLE
Transfer queue etc not working in landscape view

### ISSUE THREAD

**Issue by lh14576** [CDrummond/lms-material#275]
Hi,

it seems that transfer queue to other player etc. is no longer visible when the viewport is in landscape format.
v 1.5.8

**Comment by CDrummond** [comment]
Working fine for me. Option is moved to the main menu (three dots top right) when there is insufficient space.

**Comment by lh14576** [comment]
Sorry, I was very unprecise. I actually mean that the when switching from portrait to landscape view the result is inconsistent depending on wether "browse" or "queue" was the last selection in portrait mode.

Below are a couple of pictures to better illustrate my point:
1. switching from "browse" to landscape:
![_Screenshot_20200504-140302](https://user-images.githubusercontent.com/30257285/80964739-af02b580-8e11-11ea-81f3-a3d878638e01.png)
![_Screenshot_20200504-140316](https://user-images.githubusercontent.com/30257285/80964737-add18880-8e11-11ea-93e0-2aaed57850ef.png)
![_Screenshot_20200504-140325](https://user-images.githubusercontent.com/30257285/80964738-af02b580-8e11-11ea-86c0-ef9e58733a33.png)

2. switching from "queue" to landscape:
![_Screenshot_20200504-140350](https://user-images.githubusercontent.com/30257285/80964753-b2963c80-8e11-11ea-9da8-76131ea43911.png)
![_Screenshot_20200504-140359](https://user-images.githubusercontent.com/30257285/80964748-b1fda600-8e11-11ea-9e93-1bffa5b33a66.png)
![_Screenshot_20200504-140408](https://user-images.githubusercontent.com/30257285/80964750-b1fda600-8e11-11ea-980f-b5481f843982.png)

IMO it would be preferable if the landscape view would always be identical no matter if "browse" or "queue" was selected in portrait mode.
Thx!
