### ISSUE TITLE
Ramdisk

### ISSUE THREAD

**Issue by XavierP56** [CDrummond/lms-material#276]
The RamDisk option in Daphile is missing.
Could you please add it ?
If you could also automatically enable it when adding things in the playlist, it would be great !

Many thanks !

**Comment by CDrummond** [comment]
What is this? Where does that appear? What has it go to do with a skin????

**Comment by XavierP56** [comment]
Hi,

Daphile is a dedicated Linux server / player using LMS.
Daphile has changed the LMS interface to provide a new functionality : Play
from RamDisk

In Daphile, you have a little icon at the bottom right that look like a
little ram component.
If you click on it, Daphile Server will load the playlist in a ram disk.
Believe me : The sound quality is GREATLY improved. Of course, you need a
good Hifi System to hear it but it really improves a lot sound quality.

So I'd like the Material interface you wrote can also provide such
functionality !

Look at the attached screenshot of the Daphile interface:
[image: image.png]
The Ramdisk is the little "ram component" on the left of "Combo 384
Amanero" (first icon)

Let me know if something is unclear.

Best Regards,
Xavier.

**Comment by CDrummond** [comment]
Sorry - but this sounds like Daphile themselves should implement this as an LMS plugin, so all UIs/Controllers can use this.

**Comment by XavierP56** [comment]
I'm sure you can send the right command to the Daphile Server to enable
this RamDisk caching.

Best Regards,

**Comment by CDrummond** [comment]
I'm sure I could. Still, it should be a LMS plugin - probably a per-player setting. Then it will be available, and usable to all.

**Comment by XavierP56** [comment]
I understand your point of view.
However, if you do it, I'll be really grateful !
Because Daphile is great for it's musicality when RamDisk option is enabled
!

You'll make Material Plugin a great addition to Daphile if you're willing
to implement such functionality.

Best Regards,
Xavier.

**Comment by CDrummond** [comment]
I cannot do this, as I do not use daphile! Still, the skin is open source - so I'm sure someone else could look into this. Sorry, but for me a plugin is 100% the way to go.

**Comment by XavierP56** [comment]
If that can help when I click on the Ramdisk button, it seems to send this:

http://192.168.1.150/cgi-bin/ramplay.json?cmd=start&player=5a%3A9e%3A42%3Ab0%3A66%3A8b&_=1589280975721

GET
/cgi-bin/ramplay.json?cmd=start&player=5a%3A9e%3A42%3Ab0%3A66%3A8b&_=1589280975721
HTTP/1.1
Host: 192.168.1.150
Connection: keep-alive
Accept: application/json, text/javascript, */*; q=0.01
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
X-Requested-With: XMLHttpRequest
Referer: http://192.168.1.150/cgi-bin/AudioPlayer
Accept-Encoding: gzip, deflate
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: DaphileWebSessionID=RtNFMP; DaphileWallPaper=true;
Squeezebox-expanded-PLUGIN_MY_APPS_MODULE_NAME=0;
Squeezebox-expanded-FAVORITES=0; Squeezebox-expanded-MY_MUSIC=1;
Squeezebox-expandPlayerControl=true; Squeezebox-enableHiDPI=1;
Squeezebox-expanded-PLUGINS=0; Squeezebox-expanded-RADIO=1;
Squeezebox-player=5a%3A9e%3A42%3Ab0%3A66%3A8b

Best Regards,
Xavier.

**Comment by XavierP56** [comment]
Hi,

When Ramdisk is processing, I see:

http://192.168.1.150/cgi-bin/ramplay.json?cmd=status&player=5a%3A9e%3A42%3Ab0%3A66%3A8b&_=1589280975737

And status:
{"status":"0"}
..
{"status":"99"}
and then:
{"status":"stop"}
