### ISSUE TITLE
Add option for current date / time on Now Playing screen

### ISSUE THREAD

**Issue by spedinfargo** [CDrummond/lms-material#278]
I love the simplicity and elegance of the Now Playing screen (which is the main reason that I stumbled on and am using Material) so I'm hesitant to ask for a feature like this.

It would be cool to be able to show the current time or date/time somewhere on the Now Playing screen.  I love having my Windows table sitting on my desk off to the side and getting a quick glance of what's playing when I look over - would be awesome to also have a clock embedded in that glance.

If not a feature that could be added, any tips on how I could customize the Now Playing screen to add this myself?

Thanks!

**Comment by CDrummond** [comment]
Sorry, but I have no intention of adding this - there is no obvious place for this, and the code for the now-playing page is complicated enough. Just use the clock of the device itself.

**Comment by spedinfargo** [comment]
I thought that might be a bit of a long shot.  In case anyone else wants something like this, a hack would be to use an "always on top" floating clock similar to this one:  DL Clock from DualitySoft.  Using the Roboto font and setting the background of the clock to transparent and eyeball centering it, it looks pretty good.  Obviously gets in the way if you're using the Material skin in an interactive mode (instead of just a non-interactive display), but works for what I need.

Thanks for the great work on the skin.

**Comment by CDrummond** [comment]
I'm going to re-open this. What I'm thinking is that I could display the clock in the main top-toolbar when on now-playing page (mobile), or now-playing is expanded (desktop), and there is sufficient space.

**Comment by CDrummond** [comment]
Implemented for 1.6.0

**Comment by spedinfargo** [comment]
:-)
