### ISSUE TITLE
Now-Playing View

### ISSUE THREAD

**Issue by ruaid0r** [CDrummond/lms-material#286]
Hi there,

I'm new to GitHub so sorry if I'm doing it the wrong way but I didn't know how to adress my question.

First of all: Thank You for this Wonderful Skin. I like it a lot!

My Question is about the "now-playing view".

I have an iPad Air 2 which I use as a display for the Material Skin. If I save the URL to my Home-Screen to use it in Fullscreen-Mode the Now-Playing View wastes a lot of space (imho) - picture One.

I Like the Now-Playing View from Picture Two WAY better but I can't seem to set is as default (maybe I'm too dumb). It only works when using Safari as i would normally browse the web. But not starting it from Home-Screen. Using it at a Desktop (App-Mode or directly in Chrome in works fine)

btw. On an iPad Pro 12,9" it's the same issue. Running it in Fullscreen-Mode toggles picture One

Is there a way to change it?

Thank You in advance!

Regards,

![Waste](https://user-images.githubusercontent.com/55585478/82938202-b5f49200-9f91-11ea-96db-24a8fb1f0460.jpg)
![wish](https://user-images.githubusercontent.com/55585478/82938203-b68d2880-9f91-11ea-947c-fe5f2a60632d.jpg)

**Comment by CDrummond** [comment]
This is due to the aspect ratio of the view, when in full screen its more square than when it has more chrome. Material will use landscape mode **only** if `width >= height*1.5` Not sure I really want to change that, as it was set to this value at the request of another user.

**Comment by CDrummond** [comment]
For 1.7.1, I've changed this to be landscape if width>=height*1.3 for mobile devices.

**Comment by ruaid0r** [comment]
Thank you for the quick reply!

I tried to test it myself but I‘m not a coder so I‘ll wait patiently for the update :)

1.3 seems to be good.

Again: Thank you!

**Comment by CDrummond** [comment]
IPad, etc, are all 4:3 which equates to a ratio of 1.3333 - so 1.3 should kick in for fullscreen. I've also made some slight tweaks, so that portrait will look nicer.
