### ISSUE TITLE
Installing plugin updates Material Skin not working properly

### ISSUE THREAD

**Issue by tophee** [CDrummond/lms-material#288]
Not sure what exactly is going on, but I want to quickly mention that I have repeatedly had to install plugin updates and restart LMS via `http://xxx.xxx.x.xx0:9000/Default/settings/` because when I did it via the Material Skin, it looked like the install went through but then it didn't and the updates kept showing up again... 

I am using Logitech Media Server Version 7.9.2 - 1578727069

**Comment by CDrummond** [comment]
Updates are handled by LMS.

**Comment by tophee** [comment]
Well, obviously LMS installs the actual updates, but the Material skin provides an interface to trigger that process and when I use that interface it doesn't work while it _does_ work if I use the default LMS skin.

**Comment by CDrummond** [comment]
Well, I have just tried the Material interface - and it **does** work. In fact, I always use the Material interface to update my plugins - never had it fail. This is with LMS 7.9.2 and 8.0
