### ISSUE TITLE
No entries in playlist on random mix

### ISSUE THREAD

**Issue by zortnac** [CDrummond/lms-material#292]
Hello,

When I upgraded from 1.7.1 to 1.8.0 I noticed that when create a "Random Mix" under My Music that nothing gets shows in the queue. The mix still plays and I can still move to previous and next tracks.

This is in Chrome verison 83 on OSX; I did not check other browsers. I confirmed that it works normally when I downgraded back to 1.7.1.

**Comment by CDrummond** [comment]
This will be the issue with disc/track numbers discussed on forms.slimdevices.com. Already fixed in 1.8.1 - released 4 days ago.

**Comment by zortnac** [comment]
Thanks! Apologies for the duplicate.
