### ISSUE TITLE
No All Songs entry in Bandcamp URL search results

### ISSUE THREAD

**Issue by mavit** [CDrummond/lms-material#295]
Steps to reproduce:

1. Install the Band’s Campout plugin.
2. Enter the URL of a Bandcamp album into the Bandcamp URL field.

In the LMS default skin, at the top of the list is an “All Songs” entry that can be used to play or enqueue all items in the list.  There’s no equivalent in the Material skin.

**Comment by CDrummond** [comment]
Can you give me an example URL? As seems to work for me.

**Comment by CDrummond** [comment]
OK. I misread - as usual! I can see the issue - but its also the same in SqueezeCtrl. There is no "All Songs" entry in the response. Not sure how the default web is determining that one should be added...
