### ISSUE TITLE
Only basic settings in Server Settings

### ISSUE THREAD

**Issue by Falcon-1** [CDrummond/lms-material#302]
Hi There,

Thanks for the incredible skin! I've set it to default only to find that I couldn't change it because I'm only seeing the basic screen.

lms-server:9000/default helped me tough.

Any idea what it could be?

Kr, Mike

**Comment by CDrummond** [comment]
Sorry, but this must be an issue with whatever browser you are using - I see all screens. Just confirmed with Firefox and Chromium. Top -left click 'Basic Settings' produces a menu.
