### ISSUE TITLE
'Show current track information * Ctrl+D' Overloads LMS

### ISSUE THREAD

**Issue by pkcrawford** [CDrummond/lms-material#307]
Whenever I use the 'Show current track information * Ctrl+D' button at the top right of the interface, I get a "Server connection lost!" alert while things are "Fetching".  If I wait long enough things eventually get back to normal.
Funny things is I can manually retrieve this information through the normal 'More' menus.
Is their a way to disable the 'Show current track information * Ctrl+D' feature from the main interface?

**Comment by CDrummond** [comment]
Sorry, never seen this. All I can think of is that you are holding down 'Ctrl-D' and it is firing repeatedly - if so I have changed the code (for the next release) to ignore the same keyboard short cut if less than 100ms between events.

You can only disable all shortcuts (in the settings dialog) not all.

**Comment by pkcrawford** [comment]
Thanks CD.  I figured out that it only happens on tracks that have no album metadata.  I guess the 'Music and Artist Information' plugin doesn't like tracks labelled as "No Album" in the interface.  In my collection, I tag tracks with the album information only if I actually have all of the tracks from the album.  I will stop using this feature for my "singles" collection.
