### ISSUE TITLE
Qobuz plgiN Search does not work.

### ISSUE THREAD

**Issue by marcoc1712** [CDrummond/lms-material#308]
Using Qobuz Plugin everything is working properly but search.

What is expected after a seach is that the list of found  artists, album and tracks is displayed, but it is not.

![image](https://user-images.githubusercontent.com/1246886/88537991-e21ea480-d00e-11ea-8ed1-5a24a0b574c5.png)

**Comment by CDrummond** [comment]
Sorry, but I do not use any streaming services. To progress this you will need to get some debug out of material.

1. Launch via http: //SERVER:9000/material/?debug=json
2. Open browser's developer tools
3. Open console tab in developer tools
4. Navigate in Qobuz app to where you enter search, but dont enter yet
5. Clear messages from browser's console tab
6. Perform your search
7. Post the REQ/RESP messages sent to/from LMS to this bug report.

This way I can see what is going on and try to debug.

**Comment by michaelherger** [comment]
That screenshot doesn't even show Material. I bet that's in the wrong place.

@marcoc1712 - please report this on the forum.

**Comment by CDrummond** [comment]
Closing. Requested more info, none give. Screenshot is not Material. I've asked on the LMS forums, and no one else has this issue.
