### ISSUE TITLE
Feature request: Let repeat button toggle "Don't stop the music"

### ISSUE THREAD

**Issue by magicus** [CDrummond/lms-material#310]
I really like how the repeat button turns into the eternity symbol when Don't stop the music is enabled. I'd love to see this idea expanded, so that Don't stop the music could be turned on and off by this button. More specifically, instead of a tri-state button, it should become quad-state: repeat all, repeat song, don't stop the music, just stop. 

I realize this is more difficult, since Don't stop the music is a setting that needs to be turned or off, instead of just reskinning the "no repeat" state look of the button. But I think it would be really neat: Don't stop the music is a great invention, but you don't want it all the time, and it is currently way too hard to turn on and off. This would make the "repeat" button more answer the question "What should I do when the current playlist is finished?"

**Comment by CDrummond** [comment]
I was originally going to do this. Turnig DSTM off is easy enough - but how to turn on? There's no way I can reliably know what the previous setting was. If DSTM had a 'mixer' setting, and a 'enabled' setting then this is what I would do. So, sorry unless DSTM changes, nothing I can do.

**Comment by magicus** [comment]
@CDrummond You don't think it is possible to set a default value for DSTM in Material? That was how I envisioned it, anyway.

**Comment by magicus** [comment]
(Or reading and caching the original value for DSTM, when turning it off)
