### ISSUE TITLE
Icons for actions not showing in multi-disc albums for tracks

### ISSUE THREAD

**Issue by Audio-Demon** [CDrummond/lms-material#322]

**Comment by CDrummond** [comment]
Not sure what is wroong on your system, but I have just checked and icons are shown. Sorry, but the code for showing these icons does nto care about mult-disc.

**Comment by Audio-Demon** [comment]
Hey,
I was about to share some more invformation. Sorry.
Thanks for Looking into the Code.

I was referring to "mouse over":
When LMS treats Multi Disc Albums as Single Album I don't get the Play and + Icons per track / Disc:
![image](https://user-images.githubusercontent.com/70367112/91540247-cd3d7580-e91a-11ea-95d2-93bd4ece0629.png)
Single Disc Looks like this:
![image](https://user-images.githubusercontent.com/70367112/91540318-e9411700-e91a-11ea-8e25-d0b82f2d161e.png)

Best,
Jan

**Comment by CDrummond** [comment]
Ah, those! Yup I can confirm. Sorry I closed this too soon (really bad habit of mine)

**Comment by Audio-Demon** [comment]
That's okay - I did't share much to begin with.
Thanks for Looking into this.

**Comment by CDrummond** [comment]
Code change, browse-page.js ~716
```
                                   (this.items.length>1 && this.items[0].header && undefined!=this.items[1].stdItem && this.items[1].stdItem!=STD_ITEM_GENRE && this.items[1].stdItem!=STD_ITEM_YEAR) ||
```
