### ISSUE TITLE
Back button (Mouse & Keyboard)

### ISSUE THREAD

**Issue by Audio-Demon** [CDrummond/lms-material#323]
Hello CDrummond,

First of all a big Thnak You for Squeezelite-X and the Material Skin,
I would love to have the functionality of the backspace and mouse-back (e.g. Tilt-Wheel-left),
I'm used to using it in Jive.
I think it would make Music-Browsing-Experience on a "normal" (mouse & Keyboard) Desktop PC a lot smoother.

Thanks & Best,
Jan

**Comment by CDrummond** [comment]
Material already navigates back in browse via the browser's back button. If you mouse/keyboard does not wotk that way - sorry nothing I can do. I do not use Windows - so don't use Squeezelite-X. 

As to use backspace - seems like a reasoanble request.

**Comment by CDrummond** [comment]
All that should be required is adding the following to main.js
```
        bindKey('backspace');
        bus.$on('keyboard', function(key, modifier) {
            bus.$emit('esc');
        }.bind(this));
```

This will then treat backspace the same as esc.

**Comment by Audio-Demon** [comment]
Hi,
it really is my Hardware! Thanks! I'm Looking into it now.
I always thought back button was ignored in Material Skin and just reversed to last page opened before (but it is a Windows issue I guess)
Best,
Jan
