### ISSUE TITLE
Dragging playback slider shouldn't switch tab (mobile)

### ISSUE THREAD

**Issue by kayue** [CDrummond/lms-material#33]
On iPad, when I attempt to use(drag) the playback(timeline) slider, it would switch to the queue/browse tab. I suspect there is gesture hijacking issue happening.

**Comment by CDrummond** [comment]
Playback slider does not support drag. But I agree that it should also not cause the view to change.

**Comment by kayue** [comment]
@CDrummond Thanks. Nice project btw.
