### ISSUE TITLE
Including a material icon in a custom plugin

### ISSUE THREAD

**Issue by andrew-codechimp** [CDrummond/lms-material#331]
Love the material skin and would like to include a material style icon in my plugin.
Looked through docs and could not see how to specify a "material alt" icon.
Is there a way for me to add this to my plugin and get material to use it whilst using the original for non-material converts?

My plugin is here https://github.com/codechimp-org/lms-tvh

**Comment by CDrummond** [comment]
There is no way, material itself maps from LMS icons to material-style icons. This is done via the `MaterialSkin/HTML/material/html/misc/icon-map.json` file

**Comment by andrew-codechimp** [comment]
OK - will you accept a pull request if I provide the icon/updated map file?

**Comment by CDrummond** [comment]
Of course! Saves me doing it :)

**Comment by CDrummond** [comment]
Perhaps the tv icon here - https://material.io/resources/icons/?style=baseline ??

**Comment by andrew-codechimp** [comment]
I was going to provide the official TVH icon into /lms-material/tree/master/MaterialSkin/HTML/material/html/images

It will go material/mono quite easily with my Sketch skills - https://worldvectorlogo.com/logo/tvheadend

**Comment by CDrummond** [comment]
I can download, and fix that for Material if you like. Not sure what then entry in `icon-map.json` should be.

**Comment by andrew-codechimp** [comment]
Just working that out myself and half way through the material icon fix, I'll PR you both shortly.

**Comment by CDrummond** [comment]
Icon added now.

**Comment by CDrummond** [comment]
I suggest, if its OK, that you rename your icon to `tvheadend.png` then the mapping becomes: `"/tvheadend.png":{"svg":"tvheadend"},`

**Comment by CDrummond** [comment]
Or `"/TVH/html/images/radio.png":{"svg":"tvheadend"},` if you don't want to rename, and `TVH` is the plugin's folder name.

**Comment by CDrummond** [comment]
Got impatient, so implemented :)

**Comment by CDrummond** [comment]
p.s. App shows as "TVH" in app list - not a very friendly name. Perhaps "TVHeadend" might be better?

**Comment by andrew-codechimp** [comment]
I was halfway through changing my repo lol. I'll undo that.
Everyone knows it as TVH and technically it's a bit like Spotty, not Spotify but something that talks to Spotify.
Thanks for the very quick update.
