### ISSUE TITLE
lock individual rooms

### ISSUE THREAD

**Issue by Obelix411** [CDrummond/lms-material#339]
Hi
Is it possible to block individual rooms for users? I would like, for example, that the living room cannot be controlled from the children's room.
Best regards
Stefan

**Comment by CDrummond** [comment]
Interesting idea. I could add a 'Hide players' option to the settings dialog, then those players would not show in the UI. This would be on a per-instance setting, i.e. per-phone, etc. And the user could easily go into settings and un-tick a player to allow access.

Would that suffice?

**Comment by Obelix411** [comment]
Yes, that would be a good way, maybe you can protect the button for the setting and password, then not everyone can change something

**Comment by CDrummond** [comment]
Been thinking about the implementation for this, and to do it correctly will need to cover a lot of corner cases - e.g. what to show in the 'Manage players' dialog for a group that contains a member that is hidden? What to show when there are no unhidden players. And, as this is not a feature I'd ever use, I just don't feel like implementing. Therefore I'm closing as 'wontfix', feel free to submit a pull request. Sorry.
