### ISSUE TITLE
Search not working correctly

### ISSUE THREAD

**Issue by s-timm** [CDrummond/lms-material#342]
Hiya!
Great skin! Just updated to 1.9.0 and found a little bug. 
I am using an Android tablet (Android 5.1, 10.8 inches, screen 1920x1280 pixels) and Chrome 85.0.4183.81

1. When I open Material skin in the browser (desktop layout), the search option is there (screenshot 1)
2. When I touch the search symbol (magnifying glass) the keyboard pops up but no search field is visible (screenshot 2).
3. When I hide the keyboard immediately (touching the rectangle at the bottom of the screen) the search option has disappeared completely (screenshot 3). Reloading the tab is not bringing it back - only closing the tab and opening a new Material skin tab helps.

I hope you can fix this - maybe even giving us the option to keep the old search or use the new search-as-you-type

Thanks for your help and hard work!!!
sasha

![Screenshot_2020-09-20-15-40-48](https://user-images.githubusercontent.com/12531230/93746958-40729880-fbf6-11ea-9694-05ff772d3dbc.jpg)
![Screenshot_2020-09-20-15-41-53](https://user-images.githubusercontent.com/12531230/93746972-45cfe300-fbf6-11ea-9612-5d9a354da896.jpg)
![Screenshot_2020-09-20-15-42-24](https://user-images.githubusercontent.com/12531230/93746978-4a949700-fbf6-11ea-8548-8503340ecc20.jpg)

**Comment by CDrummond** [comment]
Ah! Looks like the code to scroll an editable field into view has scrolled the search-edit out of view, and it remains there! Will try to fix.

**Comment by CDrummond** [comment]
Fixed in master for 1.9.1
