### ISSUE TITLE
Issue playing Top Tracks

### ISSUE THREAD

**Issue by cellhunt** [CDrummond/lms-material#344]

**Comment by cellhunt** [comment]
Running version 1.9
Go to Top Tracks
Play a song
I get a “ Something went wrong”
Does not happen with the default skin or ipeng

**Comment by cellhunt** [comment]
Not fixed in the latest update

**Comment by CDrummond** [comment]
Then you need to provide debug, as it is for me. i have just now confirmed, and I **can** play a track from 'Top Tracks'

**Comment by cellhunt** [comment]
Wierd tried again and it worked :)
Thanks heaps

**Comment by cellhunt** [comment]
The search in Qobuz is not working after upgrading to Material Skin 2.0

**Comment by CDrummond** [comment]
@cellhunt search in Qobuz is not releated to "top tracks" Please dont update closed bugs with irrelevant information - as I amy miss it. Anyhow, search should now be fixed in master - and will be in a future 2.0.1 release.
