### ISSUE TITLE
Extras

### ISSUE THREAD

**Issue by CDrummond** [CDrummond/lms-material#345]
Add support for listing 'Extras' items
1. Hidden by default
2. Filter list (exclude Alarm Clock, DSTM)
3. Show items as iframe

Iframe code will need updating:

1. Intercept clicks to create history
2. Long-press to close

**Comment by CDrummond** [comment]
Implemented in `devel` branch.

**Comment by lief-erickson** [comment]
I was not the original requester, but I'm happy to see this implemented!
