### ISSUE TITLE
Can't create Sync-Groups

### ISSUE THREAD

**Issue by DrSky2007** [CDrummond/lms-material#35]
If I want to sync all available players, everything is working fine, but if I try to remove one player, the whole sync group is going down. Also if I want to start a sync with only one player, nothing happens.

I only can set all players to sync or no sync, but I'm not able to select specific players to sync. I can select the specific players in the material theme, but nothing happens after that.

If I set this in the calssic theme, everything works as  expected, the grouped players are also shown correctly in the material theme, but it is not possible to make those settings in the material theme itself.

**Comment by CDrummond** [comment]
Fixed by https://github.com/CDrummond/lms-material/commit/f265ed7427e04ec211de73c1e550f54f8fb79f3b
