### ISSUE TITLE
App from Apps-Directory in Root 

### ISSUE THREAD

**Issue by hismastersvoice** [CDrummond/lms-material#354]
I love to you your Skin and use it every day, only one thing is not convenient  to use (for me).
In my Apps-Dir I only have the Spotty-App, and it would be nice if there is a possibility to move this App (or other Apps) to the Root-Dir of the Player. So it is directly reachable without going into the Apps-Dir.

Not sure if there is not possible because of the LMS-Structure, but maybe you can think about.

Thanks.

**Comment by CDrummond** [comment]
Use the "Pin to homescreen" option.
