### ISSUE TITLE
Time format in the alarm time picker

### ISSUE THREAD

**Issue by rgriebl** [CDrummond/lms-material#362]
The Vue v-time-picker component does support both a format="ampm" (default) and a format="24hr" option. It would be nice to be able to configure this. Maybe as a first step it would be enough to tie it to the language being used, so e.g. german users would always get a 24hr time picker?
Thanks for considering.

**Comment by CDrummond** [comment]
Removed config item. Browser's locale will be used - to be consistent with time in screen saver, etc.
