### ISSUE TITLE
version 2.0.0 does not want to load interface

### ISSUE THREAD

**Issue by OneB1t** [CDrummond/lms-material#364]
Hello
i just upgraded from 1.9.1 to 2.0.0 and now UI does not want to load itself. I can still access /default and it works fine. I also allready reinstalled plugin and still same issue.
This is my plugin tab i disabled all other plugins in order to find cause:
![image](https://user-images.githubusercontent.com/320479/97105045-a603ea00-16b8-11eb-837b-940f34c52306.png)
This is how load request looks like
![image](https://user-images.githubusercontent.com/320479/97105080-d055a780-16b8-11eb-90b0-9ef97f46bdeb.png)

Server version:
![image](https://user-images.githubusercontent.com/320479/97105110-eebba300-16b8-11eb-8a30-1484ee3451e1.png)

Is there something i need to do when going up to version 2.0.0?

**Comment by svalgaard** [comment]
I've upgraded to v 2.0 and it worked out of the box.

What happens if you specifically ask for this theme, i.e., something along the line of this:
http://player.lan/Material/

Also just to rule a client error out, have you tried another browser (maybe your phone)?

**Comment by CDrummond** [comment]
Material 2.0.0 **does** work. It is the **only** interface I use on my Android tablet and Linux desktop. Also tested on an older iPad, works there too.

Sorry, but this is an issue on our system. Try clearing your browser's cache and re-loading.

**Comment by OneB1t** [comment]
> I've upgraded to v 2.0 and it worked out of the box.
> 
> What happens if you specifically ask for this theme, i.e., something along the line of this:
> http://player.lan/Material/
> 
> Also just to rule a client error out, have you tried another browser (maybe your phone)?

Same thing happen when i try to access directly /material endpoint.
I tested also anonymous mode and phone which both are returning empty response for me :-/

Is there some log on server side where i can check if everything is fine?
