### ISSUE TITLE
Settings store not working in Dash

### ISSUE THREAD

**Issue by michaelherger** [CDrummond/lms-material#37]
This probably is not really a bug, but some issue in Vue: I wanted to use the Material skin with [Dash](https://kapeli.com/dash). It's working great, once loaded. But settings, the selected player etc. don't stick. They always reset when re-launched. Could it be that the store code is checking the browser's capabilities based on the user-agent string or the like? According to Dash's author it should support local storage. But he's using a custom UA string.

**Comment by CDrummond** [comment]
Can't see this being a Material issue. Settings are stored using standard Javascript localStorage.setItem/getItem - not Vue specific functions. See https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

The **only** user-agent checking Material does is to check if the browser is a mobile browser, and if so default to the mobile layout. But none of this affects localStorage.

**Comment by michaelherger** [comment]
Just figured out the debugger was available from within Dash. And I can confirm that `localStorage` is being used and populated with the settings, localization etc. But it doesn't persist - which must be a Dash problem.
