### ISSUE TITLE
Keyboard shortcuts for rating

### ISSUE THREAD

**Issue by CDrummond** [CDrummond/lms-material#371]

**Comment by lief-erickson** [comment]
Original request: 
> is there any possibility to add shortcuts (e.g. Ctrl+Shift+[1..5] 

Note: Some users have TrackStat configured to use 1-10 for ratings, not 1-5. Just mentioning so this detail doesn't slip through the cracks when designing a scheme.

This setting is configured in *Server Settings > TrackStat > Ratings Settings* > Rating scale 1-10.
```
Rating scale from 1-10, remote buttons are 1-9 and 0 to put a 10 rating. If not enabled holding 1-5 on remote will set ratings and 0 means unset ratings.

**Comment by CDrummond** [comment]
Only 5 stars are shown, so I only intend to add 5 keyboard short cuts. For 1/2 stars you will need to use the mouse.

**Comment by lief-erickson** [comment]
Understood. Please make that clear in the release notes.
