### ISSUE TITLE
Link to Update instructions missing?

### ISSUE THREAD

**Issue by RURon** [CDrummond/lms-material#372]
I might miss something basic, but on my Raspberry system when a new LMS update is available, I get an information in the "3 dot" menu top right (green circle with black arrow up) stating so. When I click it and click the entry in the expanded menu about the update, I get to the Information page that lists all the info about the LMS installation where it also states that a new version is available (in bold!) - but from there I miss the link to the update instructions, which are on /updateinfo.html - so I guess I wonder if that link is somewhere else on Material? So far I switch back to normal skin, then grab the update instructions from there (the command line to update) and then switch back to Material...

Greetings and great skin!
Rodja

**Comment by CDrummond** [comment]
Must admit that I never see this, as I manually update. However, you _might_ be able to get to this from server settings.

I'll see about adding a link from the info dialog.

**Comment by CDrummond** [comment]
Implemented in 2.1 branch, not for 2.0.x as it introduces a new string.
