### ISSUE TITLE
New LMS version 8

### ISSUE THREAD

**Issue by janusloo** [CDrummond/lms-material#373]
Hi there,

in LMS version 8 there is a new functionality to integrate online music services in My Music. So for example: I have Tidal and all my favourited albums/artists/tracks will also be shown in music libray in My Music. There I can browse to my favourite artists and drill down to see more from Tidal. When I clicked one of the links: albums/playlists the link doesn't open to list Tidal info though. It just did nothing. Please see screenshot. If I reverted back to the Default LMS skin these links work as expected!

Is this something that you can fix, please? Thanks in advance!
![Screenshot - 12_11_2020 , 11_56_55](https://user-images.githubusercontent.com/36502136/98931594-83f2d000-24de-11eb-841d-1dfa56505b4e.png)

**Comment by CDrummond** [comment]
Sorry, I dont use any streaming servicess. You will need to proviude the JSON debug messages. See my sig in the LMS forums.

**Comment by janusloo** [comment]
Hi okay, I have turned on debug for JSON in LMS and attached the log here. If there is anything else you need please let me know. thanks!
[server.log.zip](https://github.com/CDrummond/lms-material/files/5531592/server.log.zip)

**Comment by janusloo** [comment]
Hi I am so sorry to inform you that your skin works in the new version. It somehow can browse Tidal from My Music. Strange that it didn't work before. My excuses for raising this unnecessary issue. I will close it. Thank you so much for this skin!
