### ISSUE TITLE
android navigation bar is hidden when launched from start screen

### ISSUE THREAD

**Issue by steinarb** [CDrummond/lms-material#374]
If LMS with material is launched from the start screen on android, the navigation bar (three buttons: Back, Home, switch app) is hidden, and any attempts at making it appear interferes with the currently playing app.

So there is no way to get out of the app/page.

The workaround is to go to the Settings page and touch the bottom of the display.  Then the navigation bar appears and home or switch app can be used to get out of the LMS page.

It would be nice if the navigation bar appears, or could be made to appear, under currently playing, at the bottom of the page.

**Comment by steinarb** [comment]
Let me amend that: it is actually possible to get the android navigation bar by touching the display just below the currently playing.

But it can be hard to hit such as not to interfere with currently playing, so a little extra space below currently playing should to the trick (just enough to place a finger).

**Comment by CDrummond** [comment]
That is controlled by your browser, not the skin. If you mean the material webview wrapper - you can configure this in its settings.
