### ISSUE TITLE
Apps are gone randomly (only using Material Skin, default works fine)

### ISSUE THREAD

**Issue by ASNNetworks** [CDrummond/lms-material#375]
Hi,

I have a weird issue and I don't know if it's Material Skin, or maybe something else is bugged which causes this. So I notice multiple times a day my 'apps' suddenly don't list apps from mysqueezebox.com I use Tidal a lot and have it as a shortcut on the main menu as well. When it's gone from 'apps' the icon on the homescreen is still there, but opening it results in an empty list (since the app is gone).  P.S. I'm running latest LMS 8.0 (17-nov) with Squeezelite-X (both on Windows) and a separate Squeezelite player add-on on a Raspberry Pi through Home Assistant. I'm using LMS for a week now, so I have no prior experiences with this issue.

However, when I refresh the browser and don't open the Material Skin but the default one, it's all there fully working. One thing I also notice, is that the plugin Online Music Integration keeps turning Tidal off. However, with the default skin, Tidal still works even when this is turned off . 

Here are two screenshots, 2 seconds apart of the exact same instance and player.
![msedge_pymvTXd6Wc](https://user-images.githubusercontent.com/54230480/99568977-5e7b3000-29d0-11eb-9118-76953ce5e385.png)

![msedge_jCUJrrPav4](https://user-images.githubusercontent.com/54230480/99568982-6044f380-29d0-11eb-8554-d28c0fc5e71d.png)

I have no idea how this is related to the Material Skin and if mysqueezebox.com and/or Online Music Integration plugin have anything to do or not. One thing I do know, is that it has no issues running the default skin and only when using Material Skin.

I'm still not sure what I do to get them back, I tried different stuff every time and the apps returned, but it's unclear what helped. Maybe it was just a coincidence and it comes back automatically. or maybe restarting the server triggers it to work again (untill they're gone again). Also the apps themselves work fine. As I said, using the default theme shows them and they work fine. Also when using Material Skin while the apps are disappeared, playlists I have favorited also just work (in this case Tidal).

Any thoughts what the issue can be?

**Comment by CDrummond** [comment]
Sorry, but list of apps comes from LMS. Your missing ones are, or appear to be, ones that come from mysqueezebox. For these, they need to be enabled for each player. As of 2.0.2 Material will refresh the apps list if a player changes.

**Comment by ASNNetworks** [comment]
> Sorry, but list of apps comes from LMS. Your missing ones are, or appear to be, ones that come from mysqueezebox. For these, they need to be enabled for each player. As of 2.0.2 Material will refresh the apps list if a player changes.

Hi thanks for the explanation! Can you explain to me how I can enable it for each player? I still don't understand how Material Skin shows all apps and then after a while they disappear. I'm confused by your explanation how they appeared in the first place and then suddenly disappear.

**Comment by CDrummond** [comment]
I don't use your system, so I have no idea what is happening. But, the list of apps comes from LMS - the same message is used each time. If apps show with playerA active, and you switch to playerB - then Material will refresh the apps list. If Tidal is not registerd (on mysqueezebox.com) for playerB it will be removed (or rather LMS will not return it when Material asks for the app list).

**Comment by ASNNetworks** [comment]
> I don't use your system, so I have no idea what is happening. But, the list of apps comes from LMS - the same message is used each time. If apps show with playerA active, and you switch to playerB - then Material will refresh the apps list. If Tidal is not registerd (on mysqueezebox.com) for playerB it will be removed (or rather LMS will not return it when Material asks for the app list).

Thank you for the explanation. I did notice that the Squeezelite player running on Home Assistant as an add-on does not show on mysqueezebox.com while the squeelite-x app on Windows does show there. So if I understand you correct, this is why sometimes the apps dissapear while using Material Skin? If one of the players doesn’t show, Material Skin mignt reload the app list which will remove the apps on all player views. 

Then I’ll contact the dev of the add-on to see how this can be fixed to appear on mysqueezebox.com
