### ISSUE TITLE
Mobile interface not selected except when embedded

### ISSUE THREAD

**Issue by magicus** [CDrummond/lms-material#379]
Something happened a number of versions before, were my iPhone suddenly does not use the mobile friendly version with the three tab buttons below, but instead gets a crammed version of the tablet layout, which is more or less unusable. :-(

This only happens when I connect directly to the web UI from Mobile Safari. When it is embedded, for instance as a separate tab in Home Assistant, I get a usable mobile UI.

**Comment by magicus** [comment]
![DC0FDDBD-B534-4B65-B90F-D8553490131A](https://user-images.githubusercontent.com/6209108/100515240-db4d9d00-317a-11eb-8c98-9590b7b00568.png)
 Example form iPhone SE.

**Comment by magicus** [comment]
![A7215BF3-B51F-4D9B-AF44-A28EC1BBDB03](https://user-images.githubusercontent.com/6209108/100515313-721a5980-317b-11eb-85b6-3ae9425528b8.png)
Example from embedded within Home Assisstant.

**Comment by magicus** [comment]
Let me know if you need more information! I’ll be happy to assist with adding information about the difference in environments. It was just a bit too out of reach for me to figure out and submit a patch all by myself.

**Comment by CDrummond** [comment]
If you use "http://SERVER:9000/material" Material will select desktop if width>=750px Looking at apple's site that appears to be the case. However, that is the screen pixels which should not be the HTML pixels (if that makes sense). What Safari is (I assume) reporting the device pixels and the embedded home assistant not, I'm unsure. Which iOS version is this?

-----------------
As a work-around, you can force mobile layout - use "http://SERVER:9000/material/mobile"

**Comment by magicus** [comment]
Thanks for the workaround! I did not know about it. 

Actually, this seems to be some kind of user error. Possibly some bad cookie that had been set. When I tried with the workaround, and then tried again with just SERVER:9000/material, I got the correct mobile interface. I had to delete and re-create the home screen web app as well, and then it worked there as well. 

Is there a way in Material Skin to toggle between desktop and mobile layout? I did not find it, at any rate.

**Comment by CDrummond** [comment]
Top right of Material is a 3 dotted buton which shows a menu. Select 'Settings' from there, and within this settings dialog is an option to choose the layout. However, this option is hidden if you have forced desktop or mobile - via http://SERVER:9000/material/desktop, etc.
