### ISSUE TITLE
Lyrics from UNSYNCEDLYRICS tag

### ISSUE THREAD

**Issue by bb010g** [CDrummond/lms-material#382]
Bandcamp songs normally have lyrics here, but they're unreadable, even under More Info > View Tags. All you get is a value like `(828 Bytes)`. It'd be nice if the normal lyrics view allowed viewing these locally tagged lyrics.

**Comment by CDrummond** [comment]
Lyrics come from 'Music and Artist Information' plugin, not Material.

**Comment by bb010g** [comment]
Thanks! For future reference: https://forums.slimdevices.com/showthread.php?99537-Announce-Music-amp-Artist-Information-plugin&p=997488&viewfull=1#post997488
