### ISSUE TITLE
Disable auto-switching players?

### ISSUE THREAD

**Issue by sandeen** [CDrummond/lms-material#387]
I have Material (as the android app) running on a tablet in the living room with piCorePlayer on a rpi generating the music, and it's working great.
However, if the piCorePlayer ever reboots or otherwise disappears from what the LMS knows, the instance on the tablet switches to another available player and doesn't switch back when the piCorePlayer returns.  I'd prefer to disable this auto-switching (although manual switching to control other players would still be nice)

Is this possible?

Thanks - this is a really great way to add a display to an rPi client.

**Comment by CDrummond** [comment]
No, I will not disable this. The player comes from LMS, Material cannot control a non-connected player.

However, what I can do is if a player is marked as 'default' then auto-switch to this when it re-appears in the list. So:

1. Player A is default
2. Player A truned off
3. Material switches to player B
4. Player A re-appears in LMS's list
5. Material switches to A
6. User changes to B
7. Player B is switched off
8. Material switches to A
9. Player B re-appears
10. Material stays on A

**Comment by hismastersvoice** [comment]
I have more or less the same problem.
My player in the garage will be switched off when nobody is at home. So I have to click and select again, not nice, but ok.
This solution sounds great for me and solve it perfectly.
Thanks!

**Comment by sandeen** [comment]
That makes sense - I hadn't thought about the implications of staying "on" a player that doesn't exist at the time.

The ability to set a preferred or default player seems like it'd work really well for an instance that is more or less dedicated to a physically adjacent player.

Thanks for considering the request,
-Eric

**Comment by CDrummond** [comment]
Implemented in 2.2 branch, I jsut need to test before closing.

**Comment by CDrummond** [comment]
Confirmed working in 2.2 branch for 2.2.0 release.

**Comment by sandeen** [comment]
Thank you!
