### ISSUE TITLE
Ratings aren't shown in left pane

### ISSUE THREAD

**Issue by grasshide** [CDrummond/lms-material#388]
When browsing albums, they usually had the rating shown in the overview. Somehow it disappeared. Mostly I forget which are the best songs on an album. So this is really helpful to find them again :).

Show ratings is activated in settings. They are shown in the playlist section and in the bottom bar.

Version: 8.0.0 - 1605892076 @ Fri Nov 20 21:34:11 CET 2020

**Comment by CDrummond** [comment]
Please ensure you are on the latest MaterialSkin release before reporting bugs, and mention its version in any reports.

This has already been fixed in 2.1.2 - which I released 3 hours ago (so 2 before this report).
