### ISSUE TITLE
/html/docs doesn't scroll in Firefox 84.0

### ISSUE THREAD

**Issue by PhilRW** [CDrummond/lms-material#391]
Viewing the documentation at `/html/docs` won't scroll using Firefox 84.0 on Mac OS. It does work on Chrome and Safari. 😕

**Comment by CDrummond** [comment]
What documentation at `html/docs` ??? Material does not shop with any documentation. If you are referring to `https://cdn.statically.io/gh/d6jg/material-documentation/master/html/Material%20Skin.html` Then you need to raise an issue on its github page - [https://github.com/d6jg/material-documentation/issues](https://github.com/d6jg/material-documentation/issues)

**Comment by PhilRW** [comment]
Say I were running LMS at http://localhost:9000/. If I wanted to access the built-in documentation at http://localhost:9000/html/docs/, the material skin would affect those as well.
