### ISSUE TITLE
Music folder view

### ISSUE THREAD

**Issue by atcapollo** [CDrummond/lms-material#394]
Is there any way to still access the music folder view?

My albums are stored as:

             Root
        /        |        \
FLAC     ALAC      Non FLAC

So often I like browsing the in FLAC folder to ensure I am playing the highest quality, when I have some albums which are also in MP3 / OGG other formats.

**Comment by CDrummond** [comment]
Yes. Browse modes come from LMS. To configure which are shown in Material, use its settings dialog - in this dialog next to 'My Music' is a cog icon, click that.

**Comment by atcapollo** [comment]
Thanks super helpful.
