### ISSUE TITLE
Material Skin casues "Configure LMS" browser screen to go blank after install

### ISSUE THREAD

**Issue by Astronautra** [CDrummond/lms-material#396]
I finally determined that it's right after i install and apply the Material Skin that I can no longer get to Configure LMS tab to load.  "LMS Web Page" loads fine with the new skin look, and it plays, but I can't get to the Configure LMS unless I re-install the whole picore player from scratch.  Please help and please, **Happy New Year!**

Rpi3+ picoreplayer, Chrome PC, Chrome OSX, Safari, Firefox... same result with any browser.

**Comment by CDrummond** [comment]
If you set 'Material Skin' as the active 'Web interface' then that is what will be used, and LMS's settings would then be accessible via 'Server settings' in Material's main menu. You can still access the 'Default' (i.e. previous) skin via http://SERVER:9000/Default/

If you don't want Material to function this way don't set it as the 'Web interface', leave that set to 'Default' and you can use Material via http://SERVER:9000/material/

**Comment by Astronautra** [comment]
I get it now.  Too much beer maybe.  Thanks.
