### ISSUE TITLE
Feature request: spectrogram

### ISSUE THREAD

**Issue by hlugt** [CDrummond/lms-material#402]
Hi, love your skin, works excellent. Wondering if it could be possible to add a spectrogram for a track, and maybe replace the progress bar with it? Noticed the Plexamp app (music addon for plex, unfortunately  plexpass needed and I prefer my LMS setup) has it, and I really like the insight it gives in the dynamics. I hardly use the scroll feature but it gives a nice edge I think... 
Can it maybe be considered?

![2795B17A-3401-422F-8C5B-754B34414D44](https://user-images.githubusercontent.com/7116919/104463730-6e6b5680-55b2-11eb-8ede-3d4fae7ae252.png)

**Comment by hlugt** [comment]
Just noticed your remark at #188 so maybe you consider this technical info and thus useless. But as defense: it now seems more accepted that loudness is a consideration in the appreciation of the listening experience, and this might help with added insight...?

**Comment by CDrummond** [comment]
Material skin does not decode any music, so would not have the required information.
