### ISSUE TITLE
Can't access zip file

### ISSUE THREAD

**Issue by jf7642** [CDrummond/lms-material#403]
Dear CDrummond:

I failito install material skin on LMS and find following message

unable to download MaterialSkin from https://github.com/CDrummond/lms-material/releases/download/2.1.3/lms-material-2.1.3.zip - Connect timed out: Resource temporarily unavailable

while i cannot access this link in browser too

Thanks
jf7642

**Comment by CDrummond** [comment]
Works for me. However, an errors such as this would be a github issue, nothing I can do about it.
