### ISSUE TITLE
[Feature Request] More robust support for Podcasts

### ISSUE THREAD

**Issue by cavemandaveman** [CDrummond/lms-material#408]
Using the podcast plugin, I've noticed a couple of things about shows and episodes that could be tweaked for a better user experience. If any of these are out of the skin's control, please let me know.

**Shows**:

Can a show's thumbnail be shown next to it's title?

Can the show description be accessible, possibly from the overflow menu?

**Episodes**:

Currently, when you are browsing through podcast episodes in the left pane and click its overflow menu > More, it goes straight to the episode notes/description. Two things here: First, the description is not formatted properly. It is all one big block of text - no line breaks, bullet-point formatting, http links, etc. Second, for the button title, instead of "More" something more in line with "Show Notes" or "Description" might be better. It's kind of unexpected when it goes straight to the description.

When a podcast episode is in the right pane, in the queue, and you click its overflow menu > More, you do not have the choice to see a description at all. It would help to have it accessible here.

When a podcast episode is playing, it doesn not show the episode thumbnail but rather a generic antenna as the picture. It does show the episode thumbnail when browsing, however.

**Comment by CDrummond** [comment]
These are issues with the podcast plugin, not the skin.
