### ISSUE TITLE
possibility to hide controls and top-nav-bar

### ISSUE THREAD

**Issue by Goeste** [CDrummond/lms-material#410]
Hi @CDrummond,

Just a quick question: Is there a way (or a parameter) to hide the top navigation bar and player controls (except for the timeline)  in fullscreen mode? Or could that be an enhancement feature?

I'd like to use the FS mode to show what is plaing in a room via a screen (no touch).

Best regards and stay safe in these times, goeste

**Comment by CDrummond** [comment]
No, but you can do this with Material's custom.css  - see https://github.com/CDrummond/lms-material/wiki/Detailed-Information

Try this:

Create `material-skin/css/np.css` **within** your LMS's `prefs` folder, with the follownig contents:
```
.lms-toolbar{display:none!important;}
:root{--main-toolbar-height:0px!important;}
.no-control-adjust,.np-controls-wide{display:none!important;}
```

Launch material with `http://SERVER:9000/material/now-playing?css=np&player=01:02:03:04:05:06` (replace `01:02:03:04:05:06` with actual player's ID, or its name (need to URL encode name (space -> %20, etc)).
