### ISSUE TITLE
set active player from within custom.js

### ISSUE THREAD

**Issue by lh14576** [CDrummond/lms-material#419]
Hi,
I would like to set the active player from within custom.js. I can call `bus.$emit` events but I struggle with finding the correct command for setting the active player. A little hint would be cool
Thank you!

**Comment by CDrummond** [comment]
You cannot set player that way, active player is set in the Vuex store. Try:

```
store.commit('setPlayer', '01:02:03:04:05:06');
```

...replace `01:02:03:04:05:06` with the desired player ID. This works using Firefox's console in its developer tools.
