### ISSUE TITLE
Adding the bitrate/format/quality level into the song progress bar

### ISSUE THREAD

**Issue by roinou** [CDrummond/lms-material#420]
**feature request**

Would it be possible to include the current bitrate/format of the file playing, or better a small icon representing the quality level? In the progress bar near the track numbers or track time seems like an OK place.

If I can spare some time I'll fork the project and give it a go.

Thanks for the great work!

**Comment by CDrummond** [comment]
Already done, enable "Display technical info"

**Comment by roinou** [comment]
Right, thank you, I missed that settings menu somehow.
