### ISSUE TITLE
Enable copying of selected text

### ISSUE THREAD

**Issue by ryanfeeley** [CDrummond/lms-material#422]
### 🧱 STEPS TO REPRODUCE
<img width="354" alt="image" src="https://user-images.githubusercontent.com/68213/107119489-e812ff00-6855-11eb-819a-7912d37874f1.png">

1. Select some text
1. Select ⌘C to copy
1. Select a destination to paste text
1. Select ⌘V to paste

### ∴ EXPECTED RESULT
* Copied text is pasted

### 🤷‍♂️ ACTUAL RESULT
* Previous clipboard contents are pasted

### 📝 NOTES
* 🤨 Copying works via context menu oddly
* 💻 Tested only on Chrome and Firefox on a Mac
* ❤️ Thank you for extending the life of my SBT with this lovingly crafted software – it’s damned near perfect.

**Comment by CDrummond** [comment]
Ah, sorry, was incorrectly intercepting 'Ctrl+C' instead of 'Ctrl+Shift+C' :(

**Comment by ryanfeeley** [comment]
@CDrummond I can’t believe I'm the first to report this. I find myself looking up artists all the time. Related, I would love to interview you about the genesis of this project, and how you produced such a really well designed interface. It can't just be the framework you are using. Are you game? My email is interviews@ryanfeeley.com.

**Comment by CDrummond** [comment]
I'm happy to answer any non-personal questions, you can find my email all over the Material Skin source code...
