### ISSUE TITLE
Cannot Add Repository

### ISSUE THREAD

**Issue by jgizel** [CDrummond/lms-material#423]
On Apple Mac, LMS server ver 8.1.1, cannot add repository.  Get "Connect timed out: Bad file descriptor".

Solution is to add <?xml version="1.0"?> to top of public.xml file.

**Comment by CDrummond** [comment]
"Solution is to add to top of public.xml file." ??? Add what???

**Comment by CDrummond** [comment]
Material is part of official 3rd part repo - so no need to add this one anyway.

**Comment by jgizel** [comment]
Thought I placed it in the text.  Add <?xml version="1.0"?>

 

Regards,
