### ISSUE TITLE
Lyrics not changing when new song starts playing

### ISSUE THREAD

**Issue by s-timm** [CDrummond/lms-material#425]
Hi!
Thanks again for your great skin! 

I think I found a little bug: when I am playing a song and then look at the lyrics (first going to the little round i-symbol in the top right corner, then to "lyrics"), the lyrics are not being updated when a new song starts playing - the lyrics just don't change.
My impression is that in the past the lyrics were changing when the song was changing.

I don't know if this an issue with your skin or the "Music and Artist Information" plugin I also have installed. One little additional question: do you have any influence on where the lyrics come from? Or is the other plugin doing all that work?

 I am using an Android tablet (Android 5.1, 10.8 inches, screen 1920x1280 pixels), all plugins and browser (Chrome) up-to-date.
 
best regards

**Comment by CDrummond** [comment]
Lyrics update when song is changed for me. Is this local or streaming tracks? Are any errors logged in console tab of your browser's developer tools? I note you are using a tablet, can you recreate on a desktop/latop? (As its easier to get to developer tools there)

**Comment by s-timm** [comment]
OK, this is going to be very embarrassing :-)
I checked on my PC: I get some errors in the console (see attached) but everything works fine, lyrics changing, etc. 
![console](https://user-images.githubusercontent.com/12531230/107626482-26e1f400-6c5e-11eb-8fe2-7443e99a0cb1.jpg)

Back to the tablet and after several minutes trying on the PC, my phone and the tablet I see that there is a symbol that is blue on the PC and my phone but that is grey and struck-through on the tablet. And on the PC I see a tooltip popping up: "Update information when song changes" (*shame* :-)  
![symbol](https://user-images.githubusercontent.com/12531230/107626509-319c8900-6c5e-11eb-92e2-6f82fed6cf76.jpg)

Sorry to bother you!!!! :-D
