### ISSUE TITLE
Sorting buttons/options/dropdown

### ISSUE THREAD

**Issue by mousemat86** [CDrummond/lms-material#426]
Great theme – thanks for all the work on it. 

Are there any plans to add some sorting options/dropdown/buttons to the main browsing views? Simlar to say Plex which allows sorting by date added, title, year etc. 

I know this is possible deeper in the server settings but it would a handy addition for on the fly sorting in say Album view.

<img width="462" alt="Screenshot 2021-02-12 at 10 39 28" src="https://user-images.githubusercontent.com/57290277/107758608-09289380-6d1f-11eb-88a5-60e994d38dc5.png">

**Comment by CDrummond** [comment]
Already implemented, and for some time.
