### ISSUE TITLE
Generic svg icon breaks LMS image resizer

### ISSUE THREAD

**Issue by expectingtofly** [CDrummond/lms-material#433]
Unfortunately the generic icon provider convention causes havoc with LMS image resiser and breaks images : it does things like this :

http://172.16.0.8:9000/plugins/VirginRadio/html/images/VirginRadioLogo.svg_50x50.png

placing the rename after the .svg instead of at the end,  breaking the link.

Is it worth switching to your other idea of using underscore?

**Comment by CDrummond** [comment]
Yup, I'll change `xxxx.svg.png` to `xxxx_svg.png`
