### ISSUE TITLE
Config issue?

### ISSUE THREAD

**Issue by Pi-Pilou** [CDrummond/lms-material#438]
Hi 
Since the  new update, i have noticed an issue in the config menu.
The server and « platine » (see joined file )menu has disappeared from the main menu : ...
We have to go to the sub menu information to Access server and platine modification 
I don’t know if it is a bug or a volontary modification of the interface.
From my (and only my ;-) )point of view it is not a smart modification 

Best regards
Olivier
![BC2CA2AD-3743-4F11-AD96-01F8C7FEDD6E](https://user-images.githubusercontent.com/79844278/109492950-08685f00-7a8c-11eb-95cd-abf088e28859.jpeg)

**Comment by CDrummond** [comment]
This is deliberate, to reduce the number of 'Settings' menu actions.
