### ISSUE TITLE
Back arrow on playlist screen opens search

### ISSUE THREAD

**Issue by Phileep** [CDrummond/lms-material#444]
Hi

Appreciate this layout for LMS.

I am running V2.3.2 using chrome as browser

When I select a playlist from the  playlists and then want to go back, the back arrow (next to the search box) is selecting the search box and I cannot navigate out of the playlists section. Have to refresh the page to get out of playlists section.

![image](https://user-images.githubusercontent.com/8461946/110225574-db033180-7f21-11eb-8e08-9368299f8fb0.png)

**Comment by CDrummond** [comment]
Fixed in 2.3.3
