### ISSUE TITLE
Advanced search missing

### ISSUE THREAD

**Issue by th2j** [CDrummond/lms-material#448]
In the desktop view, the button "avanced search" doesn't work anymore. The advanced search page doesn't open when you click on it.

**Comment by CDrummond** [comment]
Works for me.

**Comment by th2j** [comment]
Why did you closed it ? The button doesn't work anymore, don't you want to look at this problem ?
I use 2.3.3, maybe the new version is ok (it is not proposed yes for me)

**Comment by CDrummond** [comment]
Because, as I stated, it **does** work. I have just installed 2.3.3 - and again, works just fine.
