### ISSUE TITLE
Pagehandler regexes are too generic, catching unwanted requests

### ISSUE THREAD

**Issue by michaelherger** [CDrummond/lms-material#449]
I was investigating an issue with the artist "Dominic Miller" in MAI. My plugin would fail to find his portrait using `http://localhost:9000/imageproxy/mai/artist/dominic%20miller/image_100x100_o`. After some investigation I figured out it was the Material skin plugin which has a page handler for `mini`. Well, that would match. 

https://github.com/CDrummond/lms-material/blob/54f2d3575d7a6e72ccd96b3d093cdafce311e914/MaterialSkin/Plugin.pm#L43

Please make these handlers more specific. Eg. by adding a path separater to the regex, or word boundaries to catch (eg. `^mini/`, `\bmini$`, `material/mini$` or whatever). Be as specific as possible to prevent accidentally hijacking other requests.

**Comment by CDrummond** [comment]
Can you checkout master and see if its OK now? I used (e.g.) `^mini$` - could not get `material/mini$` or `material\/mini$` to work.

**Comment by michaelherger** [comment]
I believe that should do the trick. At first I thought it might break your functionality for users who don't use Material as their default skin. But that seems to be taken care of by the web page handler. Thanks!
