### ISSUE TITLE
Cant find the Menu entry for BROWSE_MUSIC_FOLDER

### ISSUE THREAD

**Issue by oweitman** [CDrummond/lms-material#452]
Thank you for your effort.
the plugin is very nice.

i cant find the Menu entry for BROWSE_MUSIC_FOLDER
is this hidden?
can i add it?

**Comment by CDrummond** [comment]
Material's browse modes are configured via its settings menu - accessible by three dotted button top-right.

--------

Git hub issues are for issues, not support.

**Comment by oweitman** [comment]
if the menu entry is missing then it is an error or a feature request.
if several people do not find the setting in the sub sub menu, it would be an indication that the documentation should be improved.
Believe me, professionally and also in private projects, I know what issues and incidents are.
also the plugin link led me to github, without a notice, where I can ask a question (maybe also an issue?)
no offense

**Comment by CDrummond** [comment]
The menu is not missing, so no issue or feature request. And your original text was asking how to find something => support question. The plugin also gave you a link to the LMS forums - which I would have thought would be a fairly obvious place to ask questions, as that is where othe users are likely to be. The Material documentation is not written by me, and is very out of date.

I will appologuse for my initial respone, as it came off slighly rude - I should not respond whilst tired.
