### ISSUE TITLE
What happened to Player Settings..?

### ISSUE THREAD

**Issue by magicus** [CDrummond/lms-material#454]
I noticed that some of the last updates of lms-material has removed the Server and Player Settings from the "..." menu. Is that just a mistake, or was this intentional?

I used both of these quite a lot, and now I'm clicking around wildly in the UI to find them.

Most used of all was the sleep timer. I noticed that once you have *activated* the sleep mode, it now showed a new GUI element, which was pretty nifty! But I'm finding no easy way to *enter* sleep mode. I only know how to start it using the Player Settings menu, and it is deeply hidden in Settings now. If there is an easier way to enter sleep mode, then it is not obvious enough from the UI how ot find it.

**Comment by CDrummond** [comment]
All settings moved to settings dialog - as that's where it makes sense for them to be.

Long-press on play-button, or player's power button will bring up sleep options.

**Comment by magicus** [comment]
Is there some way to make this discoverable? I honestly don't know how I should have figured that out, unless you have told me. (This is bit in contrast to the rest of the lms-material, which is incredibly intuitive and smooth.)

Maybe some way to present changes in new versions? Maybe even just a link to an ever incrementing changelog with relevant changes? (The process of discovering new features for long-time users are different from how new users learns the entire thing.)
