### ISSUE TITLE
Failing to browse artist's albums due to invalid artistAlbumSort value?

### ISSUE THREAD

**Issue by michaelherger** [CDrummond/lms-material#47]
After the upgrade to 0.2.3 I failed to browse albums from an artists list. Whether main Artists list, or inside a Genre, it failed with a generic "network error" message. When I then went to the settings I saw that there was no value set for the artistAlbumSort. Checking storage I'm seeing that it's set to the boolean `false`, rather than `album` (as I usually have it).

Setting the sort value once again fixed the browsing.

**Comment by michaelherger** [comment]
Heh... after some navigating around that parameter is re-set to `false`, and browsing is failing again... Something seems to be overriding that value.

**Comment by michaelherger** [comment]
One more datapoint: while I first saw the issue in my desktop browser (Safari 12.0.2, FWIW), I'm experiencing the same on my phone. I've saved the app to the start screen. Whenever I launch it from their the parameter is reset.

**Comment by CDrummond** [comment]
Should be fixed now, and you update and confirm?

**Comment by michaelherger** [comment]
Thanks! Value is not reset if broken. But fixing is easy enough. I'm surprised nobody else is complaining about this...
