### ISSUE TITLE
FR: Alternate year display for albums

### ISSUE THREAD

**Issue by jdheyburn** [CDrummond/lms-material#473]
The year appearing next to the album title in parenthesis is quite bulky. Is it possible to have an option or two for:

- Option to change to `TITLE • YEAR`
- If user specified track metadata to appear on new line, this should be respected too
- Disable the year appearing entirely

![image](https://user-images.githubusercontent.com/34041368/115544707-d65cc780-a29a-11eb-9478-b5c909ef4e42.png)

Hope that makes sense!

**Comment by CDrummond** [comment]
Sorry, I have no plans to make this configurable and I'm happy with the current format.

**Comment by jdheyburn** [comment]
No worries - thanks! :)
