### ISSUE TITLE
Add some more Material love to settings pages

### ISSUE THREAD

**Issue by michaelherger** [CDrummond/lms-material#477]
The topic came up in a slider related thread. Could some of the settings pages be improved further? I noticed you already implemented the file/folder picker - excellent! What about sliders? Here's the relevant code from the Default skin:

```javascript
		initSliders : function() {
			var items = Ext.query('input[class*=sliderInput_]');
			var inputEl;
			
			for(var i = 0; i < items.length; i++) {
	
				if (inputEl = Ext.get(items[i])) {
					var min, max, increment;
					min = 0;
					max = 100;
					increment = 1;

					var params = inputEl.dom.className.match(/sliderInput_([-]?\d+)_(\d+)_(\d+)/);

					if (params == null) {
						params = inputEl.dom.className.match(/sliderInput_([-]?\d+)_(\d+)/);
						min = RegExp.$1;
						max = RegExp.$2;
					}

					else {
						min = RegExp.$1;
						max = RegExp.$2;
						increment = RegExp.$3;
					}
					
					// here's where you'd initialise a slider using above range, which would
					// update the actual input field with its data
//  					initMagicSliderHandler(inputEl, min, max, increment);
				}
			}			
		},
```

**Comment by CDrummond** [comment]
Thanks for this, I'll see about implementing later. The file/folder picker I'm not really satisfied with, as if you shrink the page width the button moves below.

**Comment by CDrummond** [comment]
Added material-esque sliders. Unfortunately, I cant seem to find out how to make the lower part of the groove/trough coloured under WebKit/Chrome with just CSS. Managed to do this for Firefox and IE - but not Chrome :(
