### ISSUE TITLE
Browse Folders Missing?

### ISSUE THREAD

**Issue by laberlaib** [CDrummond/lms-material#480]
Version material: updated today: 2.3.7
Logitech Media Server Version: 7.9.3

Hi,
first of all, I love the skin. I use it on several tablets to control my squeezeserver.
But I have to integrate the music of my wife, which is not well tagged. So usually she browses my folder, but I cannot find this option on material skin:
material in German: As you can see, scrolling is not possible - all options are shown
![grafik](https://user-images.githubusercontent.com/81492190/116808704-a2a35c80-ab3a-11eb-8977-e1f949a6affb.png)
default:
![grafik](https://user-images.githubusercontent.com/81492190/116808742-d1213780-ab3a-11eb-9321-515ede932e5a.png)
("Musikordner" => Browse folders)

Thx laberlaib

**Comment by CDrummond** [comment]
Material's browse modes are configured via its settings menu - accessible by three dotted button top-right.

Please look for duplicates **before** creating issues. Duplicates: #452 #465

**Comment by laberlaib** [comment]
Thank you for the fast reply and sorry for the hassle.
I am new to github and overlooked the "closed" button.
Same holds for the settings menu: been there but blind.
