### ISSUE TITLE
Feature suggestion - easy add to favourites

### ISSUE THREAD

**Issue by rosscullen** [CDrummond/lms-material#491]
Hi @CDrummond thank you for your endeavors in developing this outstanding web UI for LMS. Your efforts are greatly appreciated :-D

Just a suggestion for consideration... Squeezebox has never been good for a '1 click/touch' to add a song to favorites/playlist. Similar to liking an Instagram post (and Spotify), it would be great to see a heart icon on the "playing" view so the user can quickly add the current song to favorites. Instagram app also has a feature that allows you to double click on an image to 'like'... this might also be considered.

Once you have your favorites compiled over time, you could spend time then organising them into playlists, etc.

Would appreciate your views on this. Thanks and keep up the good work! R

**Comment by CDrummond** [comment]
Not sure I see the point of adding a song to favourites, as you'd quickly have too many. I personally only use favourites for radio stations. This seems like a feature that would be better served by using one of the ratings plugins (TrackStat or RatingsLight).

**Comment by rosscullen** [comment]
Thanks for response. I guess my thinking around it was if you were passively listening, and a song you enjoyed came on, you could quickly grab the phone and favorite it. Then when you've got free time to organise things, you would go through the favorites and potentially split them out into playlists.

For example, if I was listening to Spotify on random and favoring songs as I heard them, I might come back to the favorites at the end of the year and create a "sounds of 2021" playlist. Hope this makes sense! 

Maybe its just my way of thinking! Either way, thanks for considering. I haven't come across RatingsLight so will be sure to check it out. Thanks @CDrummond  👍

**Comment by CDrummond** [comment]
2.4.5 Will have "Add to favourites" / "Remove from favourites" in the now-playing context menu - accessible via right (or long) click on the now-playing cover-art.

**Comment by rosscullen** [comment]
Greatly appreciated @CDrummond look forward to trying it out 😊
