### ISSUE TITLE
Plugin settings (summary page)

### ISSUE THREAD

**Issue by rosscullen** [CDrummond/lms-material#494]
Hi @CDrummond,

Just a suggestion but... when going into "Settings", "Server Settings" and plugins, (especially when I haven't accessed in it in a while), I always find it confusing to find where the Plugins Summary page but I eventually realise its listed as "plugins" among all the other plugins (listed on the menu item as "**Plugins**" -> "Plugins". 

It may be something you have considered before but would you consider having it more visible. Maybe on the drop-down menu, you could move it to the top if possible (directly under "Plugins") and maybe call it something like "Plugins Summary", "Plugins Overview" or "Plugins Settings". Thanks for considering. R.

**Comment by CDrummond** [comment]
Order of these comes from LMS. For server, and (extra) player settings **all** Material does is use the 'Classic' (not 'Default') skin pages with some CSS tweaks (to make it _look_ more material-like).
