### ISSUE TITLE
Will not add [material] folder to [HTML]

### ISSUE THREAD

**Issue by networxnet** [CDrummond/lms-material#50]
Tried to install automatically by adding a repository and manually by copying to plugin folder. Both ways don't add a "material" folder to HTML folder after restart.

Is this a known issue?

LMS is 7.9.2 - 1545144292 @ Tue Dec 18 16:23:28 CET 2018

**Comment by CDrummond** [comment]
I don't know what is wrong on your particular system - but the plugin does install and work.

**Comment by michaelherger** [comment]
@networxnet please check the forum. You seem to be running LMS in failsafe mode - which effectively disables all plugins!
