### ISSUE TITLE
Persisting Interface settings or define Global settings

### ISSUE THREAD

**Issue by hagak** [CDrummond/lms-material#505]
Would it be possible to create a base global interface setting so that you do not need to configure every client that connects.  This would also benefit some clients that I have found do not seem to persist the settings through restarts.

**Comment by CDrummond** [comment]
Already implemented, and for some time. See menu top right of settings dialog.

**Comment by hagak** [comment]
Could you be a little more detailed?  I know about the menu settings and have configured a good bit of items.  My issue is I have to do it for ever client and it does not always stick on some clients so it becomes a bit cumbersome.

Am I missing something obvious?

**Comment by hagak** [comment]
ugh I just found it.  Sorry.
