### ISSUE TITLE
Missing URL add for radio stream link

### ISSUE THREAD

**Issue by erdoukki** [CDrummond/lms-material#506]
How can I add link to url stream radio with material skin ?
I have to enable Default skin to uss the Add Radio Link and then switch back to Material Skin...

Can this feature be add directly in Material Skin please ?

**Comment by erdoukki** [comment]
> Ctrl+U • Add URL to queue
https://cdn.statically.io/gh/d6jg/material-documentation/master/html/MaterialSettings.html

But is it possible to have it like the Default skin feature ?

**Comment by CDrummond** [comment]
It _is_ the same, jsut in a (IMHO) more logical place.

**Comment by erdoukki** [comment]
How do we do from an iOS iPhone ?

**Comment by CDrummond** [comment]
When there is insufficient space for actions in the toolbars Material moves them to the menu. Switch to queue page, and open menu via three dotted button top-right.
