### ISSUE TITLE
Support for LMS 8.2.0 dynamic (opml) Favourites

### ISSUE THREAD

**Issue by expectingtofly** [CDrummond/lms-material#515]
Hi 

LMS 8.2.0 now supports more sophisticated favourites.  Previously, a favourite could only a single audio url or a playlist
A plugin can provide an 'favorites_url' and 'favorites_type' along with a menu item.  That allows LMS to put that menu item as a 'favorite'.  As long as the plugin supports the url format to correctly supply the opml for a menu if selected, then it all works.

The [youtube plugin](https://github.com/philippe44/LMS-YouTube/blob/0f1fa93954a511272d8c9de46439deeeef47f21a/plugin/Plugin.pm#L623) and the [BBC Sounds plugin](https://github.com/expectingtofly/LMS_BBC_Sounds_Plugin/blob/3c3cee0e5bcaadec72f42c52da25eddf139c5a32/BBCSounds/BBCSoundsFeeder.pm#L114) in ver 2.20 have taken advantage of that to allow users to set specific menu items as 'favorites'.  In BBC Sounds they can set the entire "My Sounds" menu as a favourite or individidual series/podcasts as favorites.

As far as I can see, the controllers haven't caught up with this facility yet and aren't recognising that a menu item (e.g. a 'link' type) has a 'favorite_url' and allowing the user set it as a favourite.
This is how it appears in the default skin :

![image](https://user-images.githubusercontent.com/73394021/130205356-08efa4d3-3f77-4833-a2f2-42cd1bbb3f92.png)

Of course once a dynamic favourite has been added, Material Skin supports it just fine.
Is this something that could be considered for support in Material Skin?

Stu

**Comment by CDrummond** [comment]
I dont see a favroutites_url with BBC Sounds. I only see (e.g.):

```
      {
        "type": "link",
        "icon": "plugins/BBCSounds/html/images/MySounds_MTL_icon_recent_actors.png",
        "actions": {
          "go": {
            "cmd": [
              "bbcsounds",
              "items"
            ],
            "params": {
              "item_id": "1",
              "menu": "bbcsounds"
            }
          }
        },
        "text": "My Sounds",
        "addAction": "go"
      },
```

**Comment by expectingtofly** [comment]
Oh yes,  I see the problem!   I wonder how default skin does it?

**Comment by CDrummond** [comment]
No idea! Perhaps there needs to be another param sent by material to ask for these links???

**Comment by expectingtofly** [comment]
> No idea! Perhaps there needs to be another param sent by material to ask for these links???

I think this is actually a small bug in LMS, and will just work if LMS provided the favorites_url,  I've raised in the forum to find out if it's a design choice or not.   I'll close this issue with the expectation that there would be no change in Material to support it.
