### ISSUE TITLE
Announcement: Simple Web View Android App

### ISSUE THREAD

**Issue by andreasbehnke** [CDrummond/lms-material#52]
Hi,

my wife was missing a home screen icon for lms-material and the fav icon from chrome did not work. So I wrote a very simple android app:
https://github.com/andreasbehnke/lms-material-app
- Feel free to test it.

Implemented so far:
- fullscreen view
- show preference dialog if an error occured (i.e. wrong URL to LMS)
- coloring compatible with dark theme of lms-material

Missing:
- Use android volume buttons for lms volume control. Either by communicating directly with LMS (complex and leaving the lite style of being a web view) or by calling JavaScript function - here I need your help implementing this, I need some global functions for volume up/down. At the moment I have no luck executing any JavaScript in the webview though.
- configuration setting: Switch to desktop view in landscape view.
- configuration setting: Switch between dark/light theme (or detect theme from WebView?)

**Comment by CDrummond** [comment]
I can't build this - as I purged my system of Android Studio, etc. a few days ago! But cool idea. As for the missing parts:

I've just added `incrementVolume()` and `decrementVolume()` - which you should be able to call.

Switching desktop/mobile requires re-loading the page. Perhaps you could just do this manually? Or set the `lms-material::layout` setting to `auto|mobile|desktop`

The dark/light UI is controlled via `lms-material::darkUi` local-storage setting.

Can you access these settings? And make changes?

**Comment by CDrummond** [comment]
Odd that the homescreen icon is not working - it'd be good to get that fixed. Still, allowing volume control via hardware buttons would be great! Perhaps also implement lock screen controls? I could allow access to the cover URL via a javascript function.

**Comment by andreasbehnke** [comment]
> I can't build this - as I purged my system of Android Studio, etc. a few days ago! But cool idea. 


> 
> I've just added `incrementVolume()` and `decrementVolume()` - which you should be able to call.
> 
> Switching desktop/mobile requires re-loading the page. Perhaps you could just do this manually? Or set the `lms-material::layout` setting to `auto|mobile|desktop`
> 
> The dark/light UI is controlled via `lms-material::darkUi` local-storage setting.
> 
> Can you access these settings? And make changes?



> Odd that the homescreen icon is not working - it'd be good to get that fixed. Still, allowing volume control via hardware buttons would be great! Perhaps also implement lock screen controls? I could allow access to the cover URL via a javascript function.

I have the feeling that the homescreen icon gets a wrong URL. But I have a special setup, a nginx proxy for calls to http://my.server.com:80 to http://my.server.com:9000/material - maybe this is causing the issue?

**Comment by CDrummond** [comment]
I'm going to close this, as its not an issue with the skin. However, I **love** the idea, so please feel free to contact me via email (my email address is in the source files) if you need to discuss this further (e.g. additions required to make features accessible, etc).
