### ISSUE TITLE
There is no "Music Folder" and "Disks and folders" items in "My music"menu

### ISSUE THREAD

**Issue by korandcom** [CDrummond/lms-material#520]
<img width="258" alt="lms-native" src="https://user-images.githubusercontent.com/37064530/131509349-70386c5d-a70a-4d66-8c55-13eafe378f6a.png">

Can't see "Random Mix" and "Top Tracks" and some others items too.

**Comment by CDrummond** [comment]
Material's browse modes are configured via its settings menu - accessible by three dotted button top-right.

Please look for duplicates before creating issues. Duplicates: #452 #465 #480

**Comment by korandcom** [comment]
Sorry - my mistake. Will look better for the next time.
