### ISSUE TITLE
Play/Pause button not centered perfectly

### ISSUE THREAD

**Issue by michaelherger** [CDrummond/lms-material#53]
The highlight when hovering over the Play/Pause button isn't centered with the button's circle perfectly fine:

![bildschirmfoto 2019-01-02 um 17 45 44](https://user-images.githubusercontent.com/2789989/50602051-7ddd4280-0eb6-11e9-9d86-1091d0665540.png)

I'm seeing this on Safari 12/macOS 10.14, as well as Chrome (here the circle seem to be too low, rather than too far to the left). 

No biggie at all.

**Comment by CDrummond** [comment]
Can't say I'd eve noticed it that bad before. Can you update and see if the changes I've just made have helped?

**Comment by michaelherger** [comment]
Yeah, I believe it's indeed better. Thanks!
