### ISSUE TITLE
Feature request: Make 'search' available for all music sources

### ISSUE THREAD

**Issue by krid** [CDrummond/lms-material#532]
The search UI is only available from the Home Screen.  It would be really handy if it were available from all the various music source pages.  i.e. I'd like to be able to start a search when I'm viewing the "New Music" list (since that's the page I leave open all the time).

**Comment by CDrummond** [comment]
Sorry, no. From a user perspective I'd expect a search started from 'New Music' to search only those albums,etc. And LMS search is not designed for this (AFAIK).

**Comment by krid** [comment]
Well OK....

Is there a keyboard shortcut to go back to the Home Screen?  That would at least make it possible to get to Search with two keystrokes.
