### ISSUE TITLE
Home Screen Items settings are regularly forgotten

### ISSUE THREAD

**Issue by StewLG** [CDrummond/lms-material#539]
I have tried to use the Material skin on and off for a while now, but keep getting stopped by an aggravating issue. I navigate my music by on-disk folder, so I use the "Music Folder" browse mode. This is not enabled by default in the Material skin, so I enable it (Interface Settings -> Home Screen Items -> Gear Icon next to "My Music" -> check "Music Folder").

Music Folder is then available under My Music for a bit, but eventually it disappears, and is unchecked under Home Screen Items. I wish I could say there was some associated event that seems to cause this, but I have yet to connect it to anything. It's happened at least a half dozen times though over the past year.

Let me know how I can help research this, if you need further help.

**Comment by CDrummond** [comment]
Material stores settings in your browser's local storage. So, if settings are being "forgotten" its likely that your browser is clearing cookies/data on exit.

To help with this, you can save some settings as the default settings. The defaults will be used if there are no settings in local storage. Saving of defaults can be accomplished via the top-right menu in Material's interface settings dialog.
