### ISSUE TITLE
Can't find where to enable

### ISSUE THREAD

**Issue by sky418** [CDrummond/lms-material#540]
Somehow disabled the "Delete album" in the play drop-down menu, now I can't find where to enable it 
Help if you can

**Comment by CDrummond** [comment]
Github issues is for bugs/features - not support. Please use the [LMS forums](https://forums.slimdevices.com/showthread.php?109624-Announce-Material-Skin/) for questions such as this.

However, I assume you mean the "Remove album" option in the queue. This is only shown for tracks that have an "album_id" parameter - i.e. local LMS tracks.
