### ISSUE TITLE
Wrong background color on non square album cover in dark mode

### ISSUE THREAD

**Issue by werdeil** [CDrummond/lms-material#548]
In dark mode the non square album covers are still filled in white, leading to a strange display

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/6229844/146954146-af51b609-81d6-4995-9240-dd6b78b0353e.png">

Isn't it possible to to fill the empty space in transparent to avoid this kind of issue?

**Comment by werdeil** [comment]
From what I understand of the code you use the cover from LMS that has already the white margins, so I guess there is not much you can do on las-material side...

**Comment by CDrummond** [comment]
If you double-click (or right-click and select 'Show image') on the cover in the bottom toolbar - does the image shown also have the white bars?

**Comment by werdeil** [comment]
Yes it has the white bars.

**Comment by CDrummond** [comment]
Then it is LMS that is supplying the white bars. Nothing I can do here.

**Comment by mherger** [comment]
What resizing parameters are you using? LMS can render with transparent padding, but it requires the correct parameters. @werdeil can you check the same album in the Default skin to see whether you get the bars there, too?

**Comment by michaelherger** [comment]
That's odd: I checked some of my non-square album covers. But none of them would show a white border: in Default the cover would be served in its original ratio, in Material slightly cropped, to make it square:

Default:
<img width="165" alt="Screenshot 2021-12-23 at 16 47 58" src="https://user-images.githubusercontent.com/2789989/147263269-0685a986-e834-4618-a6a4-45e3979fc2ff.png">

Material:
<img width="195" alt="Screenshot 2021-12-23 at 16 48 32" src="https://user-images.githubusercontent.com/2789989/147263327-1de91293-a6d7-4453-ba2c-211265a2b107.png">

As you can see in the second image the cover got cropped on the side. But no white border.

**Comment by werdeil** [comment]
My full apologies to you @mherger and @CDrummond, this issue was indeed in the cover embedded on the file and not on LMS side. 
I'm really sorry for that, thanks a lot for the quick replies and keep up the good work on LMS !
