### ISSUE TITLE
Volume slider and buttons

### ISSUE THREAD

**Issue by audiofool** [CDrummond/lms-material#55]
Hi
Excellent work!  Looks great.  I use the desktop view on and ipad in order to see the volume value at all times.  Is it possible to have an option to remove the volume slider, I use the buttons but am worried about accidentally sliding to full volume.  Without the slider the buttons would be closer together which would be helpful.  Also, I use my own custom volume solution which requires me to set the volume steps to 2 instead of 5.  I modified the constants.js file, but it might be useful to others to have a settings option.
Thanks again,
Mike

**Comment by CDrummond** [comment]
Sorry, but I have no intention of hiding the slider. As for the volume step, I'm not sure I want to make configurable - there are already way to many config options. But, it is something I have thought about, and implementing should be easy enough.
