### ISSUE TITLE
Add to Favorites

### ISSUE THREAD

**Issue by larod241** [CDrummond/lms-material#551]
Hi,

Is it possible to simplify the management of favorites with, for example, the addition of an icon to like and add the album to our favorites.
Ex: I am listening to a Qobuz album, and by clicking on a heart icon, I go directly to the favorites management screen.
Even better, add it to the different contectual menus.

Thank you for your work.

**Comment by CDrummond** [comment]
Material already adds an action to add, or remove, a favourite to the context menu (three dots next to each item) where applicable. For this to work the apps needs to provide a favorite_url - which, for example, the YouTube app does.

Sorry, but I do not use Qobuz, or any other streaming service, so cannot comment on how these work. However, if favorite_url is returned by these services then an entry will be in the context menu.

**Comment by CDrummond** [comment]
Re-reading this, sorry, I assume you mean to manage your Qobuz favourites - not LMS's favourites. e.g. so that you can favourite an album in Qobuz and have LMS integrate that with its local library. While I can see the use case, its not something I can do - as LMS does not provide the controller with access to enough info to do this. And, as stated, I do not use Qobuz so could not even experiment to see if I could implement a work-around to enable this.

**Comment by larod241** [comment]
Hello,

I understand that my request is not easy.
In fact, the favorites must be established in the service used (qobuz, spotify, ...) and not in the LMS favorites.
For example, by clicking on a heart on the home screen, the favorites are added to the service used if possible (spotify, qobuz, ...)

In general, perhaps this "heart" could appear if the function is available as for Youtube, like what is done on official applications.

Thank you and happy new year

Sorry for my poor English, I'm French and google translator is my friend ;-)

**Comment by CDrummond** [comment]
The heart icon appears in Material if an item defines a 'favorite_url' - but this is only for LMS favourites. If this is not specified, Material has no way of knowing how to favourite.

As to adding to a service's favourites, sorry but (as stated) LMS does not provide the required info.

Also, please do not apologise for your English - its 100000000000% better than my French! Bonne année!

**Comment by larod241** [comment]
Hello,

I have just tested and it is possible to add an album / song favorites in Qobuz or Spotify via the info then the service and then via the management of favorites.

It would be great if we could, depending on the service used, directly land on this menu from the playback interface.

With for example a heart and by clicking on it, we come across the favorites menu of the service and we can thus, very quickly, add in favorites (on the streaming service), an album, an artist or a song.

I made a little GIF to show the process.
In the end, the album ended up in favorites, directly on Qobuz.

I don't know if I am very clear! :-D
![fav](https://user-images.githubusercontent.com/20423481/148111120-f87a22a8-2ae2-4360-984d-a50c9f420742.gif)

**Comment by CDrummond** [comment]
Sorry, but no - there is no standard API for this. You would need to create an issue on the LMS github site to create an API to add favourites to a service, detect if item is favourited, remove favourite, etc. Only then could it be used in Material, and other UIs.

**Comment by larod241** [comment]
Issue open : https://github.com/Logitech/slimserver/issues/744 

Let's see !
