### ISSUE TITLE
Time Line too low on iPad

### ISSUE THREAD

**Issue by larod241** [CDrummond/lms-material#554]
Hello,

The progress bar of the chason is superimposed with the visual navigation indicator on an iPad running ios15.

Would it be possible to neutralize the lowest zone of the interface (it is limited under iphone, but it works) so that the system navigation indicators do not overlap?

Have a good day

![IMG_0054](https://user-images.githubusercontent.com/20423481/147873132-7c34ca25-64af-456c-b255-c0f05c29e964.jpeg)

**Comment by CDrummond** [comment]
I have no such iPad, so cannot check - but for 2.8.3 (and in git/master if you want yo confirm), I have slightly adjusted this bootom bar. Looking on desktop Firefox before and after - the after's progress bar's bottom is slighlty higher than the bottom of the  before's progressbar. So, hopefully worked-around.

I'll leave this report open until 2.8.3 is released and you can confirm the fix.

**Comment by larod241** [comment]
> I have no such iPad, so cannot check - but for 2.8.3 (and in git/master if you want yo confirm), I have slightly adjusted this bootom bar. Looking on desktop Firefox before and after - the after's progress bar's bottom is slighlty higher than the bottom of the before's progressbar. So, hopefully worked-around.
> 
> I'll leave this report open until 2.8.3 is released and you can confirm the fix.

Thanks.

I don't know how to test this adjustment and confirm it's ok. I have to copy file directly to my LMS server ?

**Comment by CDrummond** [comment]
You would need to manually install Material from github, etc. Simple steps:

1. git clone https://github.com/CDrummond/lms-material.git
2. Copy the contents of 'MaterialSkin' from this git clone over the Cache/InstalledPlugins/Plugins/MaterialSkin folder of your LMS install
3. Restart LMS
4. Clear browser's cache
5. Re-load page

...or just wait for 2.8.3...

**Comment by larod241** [comment]
It's perfect now.
Thank you for this rapid handling of my request.

![IMG_0055](https://user-images.githubusercontent.com/20423481/147875313-158380c3-54be-4a97-809a-5859ea3a65c7.jpeg)

**Comment by CDrummond** [comment]
Great, thanks for the confirmation!
