### ISSUE TITLE
Pin on left corner of cover.

### ISSUE THREAD

**Issue by BeActivated** [CDrummond/lms-material#557]
How can i turn off showing the pins that are showed on some covers, they are on multi cd's, but also on single cd's.
Visual I think it is disturbing, but that is a ofcource subjective.
![Pins](https://user-images.githubusercontent.com/88147509/148133796-c3fc2270-2515-492a-b3be-331f01b0369c.jpg)

**Comment by CDrummond** [comment]
This emblem should only appear (as of 2.8.2) if LMS is set to tret multi-disc albums as 1 album (i.e. 1 entry in the albums list) and an album has a disccount greater than 1.

**Comment by CDrummond** [comment]
Which version of Material are you using? Where the emblem is on a single-cd do any of the tags have a disc number > 1 ?

**Comment by BeActivated** [comment]
Thank you for your reply. Yes, I am using version 2.8.2. I treat albums with multiple discs as one item. Except multi-disc collections containing original albums. With the latter I don't give a disc number, so this gives me the wrong indication. Some work todo then.
The playback menu on the cover of a multi-disc is very nice. But I don't think it' is usefull when using 'Album Artists'. If the choosen artist contains a subset of a  'Various Artists album'
![sample](https://user-images.githubusercontent.com/88147509/148438229-0db56c66-de2b-464b-9af1-81d7f0834243.jpg)
.

**Comment by CDrummond** [comment]
The emblem will **only** appear if LMS returns disccount>1 the is controlled via the following line of code:

```
multi: lmsOptions.groupdiscs && undefined!=i.disccount && parseInt(i.disccount)>1
```

`lmsOptions.groupdiscs` ls material's variable set to store the LMS group discs option. So, only if this is set and an album has a disccount of more than 1 is the `multi` flag set - and this is what is checked to control whether the emblem is shown.

Therefore, if you are seeing this on single disc albums then LMS is stating these have a disccount>1 - looks like an issue with your tags or LMS to me.

Please:

1. Start material with debug - `http://SERVER:9000/material/?debug=json`
2. Navigate to your artist list
3. Open your browser's developer tools
4. Go to the console tab
5. Clear contents of console - click X or trash icon
6. Click on 'The Supremes'
7. Copy the **full** JSON RESP message produced after clicking 'The Supremes' This will contain the response sent by LMS. If there is a lot of data your browser might not be showing the full text in the console tab - the text might end with "...", in which case you need to click that so that the whole message is shown.
8. Add the contents of the RESP message here so that I can see its contents.

**Comment by CDrummond** [comment]
Actually, I guess it 'Hooverphonic' that you want to click, and not 'The Supremes'

**Comment by BeActivated** [comment]
material.min.js?r=2.8.2:234 [19:16:28] JSON REQ: ["00:04:20:23:0a:16",["albums",0,25000,"tags:jlqsyKSE","sort:album","artist_id:740997","role_id:ALBUMARTIST","library_id:0"]]
material.min.js?r=2.8.2:234 [19:16:28] JSON RESP: {"params":["00:04:20:23:0a:16",["albums","0",25000,"tags:jlqsyKSE","sort:album","artist_id:740997","role_id:ALBUMARTIST","library_id:0"]],"method":"slim.request","id":5,"result":{"count":20,"albums_loop":[{"album":"A New Stereophonic Sound Spectacular (Collected 2012)","textkey":"A","artist_id":"740997","disccount":10,"id":481150,"artwork_track_id":"cc91869d","year":1996},{"album":"The Best Of","textkey":"B","artist_id":"740997","disccount":2,"id":481164,"artwork_track_id":"5a458113","year":2016},{"album":"Blue Wonder Power Milk (Collected 2012)","textkey":"B","artist_id":"740997","disccount":10,"id":481151,"artwork_track_id":"0b48a1b1","year":1998},{"album":"Hidden Stories","textkey":"H","artist_id":"740997","disccount":1,"id":481167,"artwork_track_id":"c8da7a52","year":2021},{"album":"Hooverphonic Presents Jackie Cane (Collected 2012)","textkey":"H","artist_id":"740997","disccount":10,"id":481153,"artwork_track_id":"0145f749","year":2002},{"album":"In Wonderland","textkey":"I","artist_id":"740997","id":481163,"artwork_track_id":"a292e084","year":2016},{"album":"Looking For Stars","textkey":"L","artist_id":"740997","disccount":1,"id":481165,"artwork_track_id":"04197855","year":2018},{"album":"The Magnificent Tree","textkey":"M","artist_id":"740997","disccount":1,"id":481148,"artwork_track_id":"6522e1f5","year":2000},{"album":"The Magnificent Tree (Collected 2012)","textkey":"M","artist_id":"740997","disccount":10,"id":481152,"artwork_track_id":"648b4180","year":2000},{"album":"More Sweet Music (Collected 2012)","textkey":"M","artist_id":"740997","disccount":10,"id":481155,"artwork_track_id":"20198c74","year":2005},{"album":"The Night Before","textkey":"N","artist_id":"740997","id":481149,"artwork_track_id":"4f89089d","year":2010},{"album":"The Night Before (Collected 2012)","textkey":"N","artist_id":"740997","disccount":10,"id":481158,"artwork_track_id":"85a651aa","year":2010},{"album":"No More Sweet Music (Collected 2012)","textkey":"N","artist_id":"740997","disccount":10,"id":481156,"artwork_track_id":"f49fcf19","year":2007},{"album":"The President Of The Lsd Golf Club (Collected 2012)","textkey":"P","artist_id":"740997","disccount":10,"id":481157,"artwork_track_id":"bde336e3","year":2007},{"album":"Reflection","textkey":"R","artist_id":"740997","id":481162,"artwork_track_id":"9f7c5f78","year":2013},{"album":"Sit Down And Listen To (Collected 2012)","textkey":"S","artist_id":"740997","disccount":10,"id":481154,"artwork_track_id":"d0edd0e5","year":2003},{"album":"Top 40 Hooverphonic (Their Ultimate Top 40 Collection)","textkey":"T","artist_id":"740997","disccount":2,"id":481166,"artwork_track_id":"969784a0","year":2018},{"album":"With Orchestra","textkey":"W","artist_id":"740997","id":481161,"artwork_track_id":"71749547","year":2012},{"album":"With Orchestra (Collected 2012)","textkey":"W","artist_id":"740997","disccount":10,"id":481159,"artwork_track_id":"b07f7edf","year":2012},{"album":"With Orchestra Live (Koningin Elisabethzaal 2012)","textkey":"W","artist_id":"740997","disccount":1,"id":481160,"artwork_track_id":"4a3ef7a1","year":2012}]}}

**Comment by CDrummond** [comment]
Thanks for this, so which album has the emblem when you think it should not? The following all have disccount>1

- A New Stereophonic Sound Spectacular (Collected 2012)
- The Best Of
- Blue Wonder Power Milk (Collected 2012)
- Hooverphonic Presents Jackie Cane (Collected 2012)
- The Magnificent Tree (Collected 2012)
- More Sweet Music (Collected 2012)
- The Night Before (Collected 2012)
- No More Sweet Music (Collected 2012)
- The President Of The Lsd Golf Club (Collected 2012)
- Sit Down And Listen To (Collected 2012)
- Top 40 Hooverphonic (Their Ultimate Top 40 Collection)
- With Orchestra (Collected 2012)

**Comment by BeActivated** [comment]
The 10 cd's of the Collected Box. They are not treated as a multi-disc album, because they all have a different Album name.
![Collected](https://user-images.githubusercontent.com/88147509/148594001-3005519c-28ff-4c60-8bf0-1262f7e44a12.jpg)
x

**Comment by CDrummond** [comment]
But, as stated before, they have disccount>1. This is why the emblem is shown. So, sorry, either there is an issue with LMS or with your tags.

**Comment by BeActivated** [comment]
According the link down, a multi-disc set needs the following conditions:
Album name has to be exactly the same for all discs in the set, Discnumber has to be be the same for all tracks on the disc and per disc in the set the number increasing. The option to treat multi-discs as one album has to be enabled.
https://wiki.slimdevices.com/index.php/Organising_multi-disc_sets.html
I did a test on the server.
The jason output also gives a disccount value for non multi-disc sets, it uses the Totaldisc tag for it.
So then everything goes wrong.
Can i install a version before the 2.8.2? or do you have some other ideas what to do.

**Comment by CDrummond** [comment]
>  do you have some other ideas what to do.

Fix your tags.
