### ISSUE TITLE
[Feature Request] - authorise swipe on the cover to change prev/next song

### ISSUE THREAD

**Issue by schmurtzm** [CDrummond/lms-material#560]
Hi, 

when you are in the "Playing" view it could be useful and intuitive to change song by swiping left or right on the cover.
It is often quicker for the user to swipe than making a precise click on the "next" button.
The actual behavior is changing the view so it could be an option in settings to let the user choose the behavior ?

Thanks for this awesome skin (this is one of the biggest reason that I still use my squeezebox nowadays 😉 )

**Comment by CDrummond** [comment]
Implemented for future 2.9.0 release.
