### ISSUE TITLE
[Feature Request] - New option : switch automatically to "Now Playing" view

### ISSUE THREAD

**Issue by schmurtzm** [CDrummond/lms-material#561]
Hi, what a pleasure to use your skin on my desktop everyday !
Now I would like to convert an old tablet into a dedicated audio player and it changes some details in the use.

Do you think possible to add an option to be able to switch automatically to "Now Playing" view just after having selected a song ?

Description of the feature : 
-
When the option called "Switch to "Now Playing" view automatically" is activated, it could have 2 rocker buttons : 
- when playing start     =>  it switch to the Now playing view immediately if you select a song in the browser or even if you launch a song remotely
- after [ ] seconds of playing without interaction => switch to now playing view if the user don't touch the UI during a time he have selected

This feature could be awesome for dedicated players ;)
Thank you.

**Comment by CDrummond** [comment]
I considered this, but have decided against it. The current mobile layout does auto-switch to now-playing when an item is selected for play from browse - ie via the (>) toolbar button, or the 'Play now' menu entry. Thought about doing this for desktop too, but not sure I really see the use case there.

As for doing this whenever play is initiated from another controller, again not something I'd personally want - or have any usecase for.

However, you can add custom javascript to Material - see https://github.com/CDrummond/lms-material/wiki/07-Customisation

Something like, untested, _should_ work:

```
bus.$on('playerStatus', function(playerStatus) {
    if (playerStatus.isplaying) {
        bus.$emit('expandNowPlaying', true); // Desktop layout
        bus.$store.commit('setPage', 'now-playing'); // Mobile layout
    }
});
```

**Comment by schmurtzm** [comment]
Thanks for your answer 😉 
The objective is that when I start to play something remotely I'm sure to see the cover on the player screen.
It could be interesting for Squeezelite-X but also for other autonomous linux player too.
 I have always been annoyed by this lack of this functionality on Squeezebox touch and Squeezebox radio : I don't like to see the main menu when I send a playlist remotely to my Squeezebox.

I've just tested but withtout success :  
I've created /var/lib/squeezeboxserver/prefs/material-skin/custom.js , put your code inside , put the right rights on the file, rebooted server and reloaded skin but it doesn't switch to now playing.
I'm not an expert into javascript debugging but I think that my custom.js is never called...

**Comment by CDrummond** [comment]
Just tried, and it works for me. If you add `window.alert('Hello');` near the top then you should get an alert message stating 'Hello' each time you start material.

You can also try adding "?js=my-script-name" (no extension) as a URL query parameter, and then use `prefs/material-skin/js/my-script-name.js` as filename.

However, my suggestion was not a 100% complete solution. You only want to trigger the views if the state changes from not-playing to playing.
