### ISSUE TITLE
can not play tracks with soundcloud

### ISSUE THREAD

**Issue by cereyanli** [CDrummond/lms-material#571]
I can play soundcloud tracks from standart LMS gui but when I try to do this with material skin  track loads but not play. 

This is same for all combinations eg different PC, different browser , different mobile device.

where shall start to troubleshoot?

**Comment by CDrummond** [comment]
Have you tried other controllers? e.g. Squeezer, SqueezeCtrl, or iPeng? Default skin uses a different API to Material and other conntrollers. If these other controllers also do not work, then then issues lies with SqueezeCloud - and has been reported efore , see #208

**Comment by CDrummond** [comment]
So, have you tried other controllers?

**Comment by cereyanli** [comment]
Hi

Yes I tried. I got the same result so I assume this issue same as #208 so we can close this issue
