### ISSUE TITLE
Missing current reading indicator in the playlist

### ISSUE THREAD

**Issue by Atmis** [CDrummond/lms-material#573]
Hello,

I wanted to share with you a strange behavior with the current reading indicator in the playlist.
Most of the time the "pq-current" indicator is missing, on any device/browser connected to my LMS server (Edge, Safari iOS, Firefox)
![image](https://user-images.githubusercontent.com/5329747/156038735-99a015b6-c308-464b-9c3f-a94a6a994287.png)

I made 2 basics tests without success:
	- Uninstalled the plugin, removed prefs and cache, reinstalled: same issue
	- Purged the cache of the browser or using private mode: same issue

Using the dev tools in the browser, I checked the URL of the SVG picture, and the color (?c=xxxxxx) is not properly sent as an argument:
![ScreenShot 2022-02-28 19_29_47 PMA](https://user-images.githubusercontent.com/5329747/156038868-2f184b3c-107a-4783-b9b3-e01e270bb500.png)

Calling this URL directly gives me an error:
![ScreenShot 2022-02-28 19_08_00 PMA](https://user-images.githubusercontent.com/5329747/156038977-0eb29abf-28fa-40de-84e4-3be9b75be9ff.png)

If I add the color as an argument, it is fine:
![ScreenShot 2022-02-28 19_21_59 PMA](https://user-images.githubusercontent.com/5329747/156039042-1bfd3a45-e67f-443a-8470-12f7ac24407f.png)

In fact, changing the color from the skin settings is temporarily fixing the issue by sending back the color argument to the SVG picture. But I could not determine why the color is not systematically sent.

Strange thing, I also made a test on a different LMS Server, the color is also not sent but I get no error and a white icon instead (no color) (the screenshot show 2.8.4, but behavior is the same with 2.9.1):
![image](https://user-images.githubusercontent.com/5329747/156039362-43d7465e-ce6c-4e9f-a215-7bb03f1013dd.png)

I hope I was clear enough, and thanks a lot for your huge work on developing this Material Skin !

**Comment by CDrummond** [comment]
The colour is read from a CSS variable. I have no idea how or why it is undefined for your use case. Perhaps daphile is interfering? Have you tried LMS on a standard PC?

I've updated the code so that if this colour cannot be found it will use black - which is better then nothing.

**Comment by Atmis** [comment]
Thank you for your feedback.
I did a quick test by installing LMS on my PC (Windows), installed Material Skin, and behaviour is the same: the color is not sent to the icon URL after a refresh. But there is at least a black indicator without error (Just like my second Daphile unit):
![image](https://user-images.githubusercontent.com/5329747/156071600-613b3cd5-607a-4488-b791-21fa3999828e.png)
So I guess this is not related to Daphile.


I digged a bit more to try to understand why the SVG file is failing on my Daphile, and here is he difference between the file rendered on Daphile:
```
<svg id="svg4" width="16" height="16" version="1.1" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
 <ellipse id="path1287" cx="7.9999" cy="7.9999" rx="7.1466" ry="7.1466" fill="#fff" stroke="#&r=2.9.1" stroke-width="1.75"/>
 <path id="path1579" d="m6 12 6-4-6-4z" stroke-width=".73854" fill="#&r=2.9.1"/>
</svg>
```

And the file rendered on the Windows installation I just setup:
```
<svg id="svg4" width="16" height="16" version="1.1" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
 <ellipse id="path1287" cx="7.9999" cy="7.9999" rx="7.1466" ry="7.1466" fill="#fff" stroke="#" stroke-width="1.75"/>
 <path id="path1579" d="m6 12 6-4-6-4z" stroke-width=".73854" fill="#"/>
</svg>
```
I can't understand why the behavior is different, but we clearly see that stroke and fill value are not valid on my Daphile due to the missing color.

**Comment by CDrummond** [comment]
The problewm is no colour is sent in the SVG request. In the daphile example, Material thinks the colour is "&r=2.9.1".

The colour is read from a CSS property. For some reason this is failing on your setup, so no colour is sent.

Can yo try other colour variants?

**Comment by CDrummond** [comment]
Can you checkout the git version, and see if this helps?

**Comment by Atmis** [comment]
Just tried the git version on my Daphile instance, and it works perfectly. I changed, the color, refreshed, used private navigation, tested on Edge, Firefox, Safari iOS, and I could not make it failed once. It is perfect!
![image](https://user-images.githubusercontent.com/5329747/156129197-09716ed4-6c36-4923-9c0a-52ad4a0829f8.png)

Thanks a lot for your support!

**Comment by CDrummond** [comment]
Great! Thanks for the confirmation.
