### ISSUE TITLE
Currently have DEVELOPMENT installed?

### ISSUE THREAD

**Issue by a13xmay** [CDrummond/lms-material#575]
Didn't do anything but now I have a version called DEVELOPMENT installed, perhaps something to do with auto update?

How can I get v 2.9.2 back?

**Comment by CDrummond** [comment]
I have just installed Material via LMS, and it installs 2.9.2. Sorry, but i have no idea why you have a dev version.

All i can suggest is that you remove MaterialSkin and re-install. If this does not work, then there is something odd on your system.
