### ISSUE TITLE
Possible to see bit rate?

### ISSUE THREAD

**Issue by a13xmay** [CDrummond/lms-material#578]
Hi, when I ask Material to 'Display Technical Info', is it possible to see the file bit rate rather than the VBR data rate? Would be more suitable if showing kHz and file format?

**Comment by CDrummond** [comment]
Material gets this info from LMS. All Material does is combine the bitrate, samplerate, etc, strings into one. So, if its not showing a value then that's due to LMS.

**Comment by a13xmay** [comment]
Thank you for your time
