### ISSUE TITLE
High CPU use for streaming service Qobuz

### ISSUE THREAD

**Issue by th2j** [CDrummond/lms-material#579]
Hello,

When i play music from Qobuz (my qobuz music is integrated in my database via the plugin online music library integration), the cpu use is very high. I found that it is due to material skin because when i don't use it, the problem is gone.

You can find some infos in this post :
https://github.com/Logitech/slimserver/issues/776

Thanks
Thomas

**Comment by CDrummond** [comment]
Please use Material's debug in a console window. e.g.

1. Start Material - `http://SERVER:9000/material/?debug=json`
2. Open your browser's developer tools
3. Switch to the console tab
4. Play a track in Qobuz

You should now see the messages being sent by Material. Are the very frequent?

**Comment by th2j** [comment]
no i don't see frequent messages, just some image at the beginning

**Comment by CDrummond** [comment]
Then it cannot be Material's fault. There is no other way it can load LMS. You will have lots at the start, and near the end, to try to get time in sync.

**Comment by th2j** [comment]
when i close material tab, it is ok
when it is open, i see high load from lms, constantly

**Comment by CDrummond** [comment]
And if you try: `http://SERVER:9000/material/?debug=json,cometd,libcometed` - does that show high message count?

**Comment by th2j** [comment]
here is the results : 

when i play from the plugin qobuz (the load is ok) :
https://www.dropbox.com/s/letrqsmk3igak1h/qobuz%20plugin%20ok?dl=0

when i play qobuz from the database (the load is much higher) : 
https://www.dropbox.com/s/44a4zeq5zemgy64/qobuz%20database%20ko?dl=0

i think is is because the request are longer, for exemple you can see [HTTP/1.1 200 OK 985ms]
vs 0ms for the plugin

**Comment by CDrummond** [comment]
Well, both those show the same messages/sec sent to the server.

OK has: 19 cometd messages and 19 JSONRPC requests in 19 seconds
Database has: 44 cometd messages and  42 JSONRCP requests in 42 seconds

So, about 1 cometd and 1 JSORPC per second.

Looking at the status messages, that all have a player time of 0 => track is not yet playing? This is also confirmed by the status message having `"waitingToPlay":1`

Sorry, but from Material's perspective everything looks OK. Both logs show the same load on the server - as in the same number of message sent/received per second.

**Comment by th2j** [comment]
so it sends both one message per second, but maybe in one case the execution is more demanding for the server ?
this is not normal for exemple that the sound cuts a little bit when i add some tracks to the playlist. It shows that LMS can't handle.

**Comment by CDrummond** [comment]
**But** the **same** message count is sent in both examples. Now, the 1/second should decrease when playing - but your logs show that the track has not started to play (`"waitingToPlay:1` and `"time":0`). Material polls more frequently at the start of playback. Something appears to be amiss on your system, as I do not see this behaviour.

If Material sends the **same** messages in both scenarios, but LMS reacts differently, then I fail to see how this can be a Material issue. Granted it _appears_ Material is triggering this issue, but it is not Material's fault.

**Comment by th2j** [comment]
> but your logs show that the track has not started to play

I have modified the output for playing via aplay. But i tests the normal conf and there is still the same problem. I can send you new logs if you want.

**Comment by CDrummond** [comment]
What's the point? Material sends the **same** messages - and **LMS** reacts differently. What else do you expect Material to do?

**Comment by th2j** [comment]
what is the point of these messages each second ? The standard LMS page is working differently ?

**Comment by CDrummond** [comment]
Material uses a different API - it is **not** the same as the default skin. The point of the message is to know when playback has started, etc.

**Comment by michaelherger** [comment]
What kind of players are you using? How many of them?

**Comment by th2j** [comment]
just one -> squeezelite

**Comment by CDrummond** [comment]
I've reduced the frequency of this polling. However, seeing as you only have 1305 (1300 qobuz, 5 local) albums in your library I have no idea why a status message would cause high CPU.

**Comment by th2j** [comment]
ok thanks,

i don't know either, that is a mystery !

**Comment by th2j** [comment]
it is specific for playing via qobuz with music integrated in database
so it is linked to the data witch are stored in db

**Comment by th2j** [comment]
when i open the db with sqlite3, it is long except for library.db,
it is the first time i use this, so i don't know if this is normal or not

artwork.db
cache.db
imgproxy.db
library.db
persist.db
qobuz.db

what do you think about that ?

**Comment by michaelherger** [comment]
I don't understand. Does it take a long time to open library.db in SQLite?

**Comment by th2j** [comment]
sorry if i tell something silly, i am not a programmer :)
i opened the db to see what is inside and i see that opening the library is fast but the others are longer too open

**Comment by michaelherger** [comment]
@CDrummond would you send the next poll no matter whether the first response came in? Could it be the request takes longer than a second, thus requests queuing up?

**Comment by CDrummond** [comment]
@michaelherger Yes, REQ/RESPs are not synchronised - as in there is no internal queue in Material waiting for a RESP before sending a REQ.

Should there be? Will LMS **always** send a RESP? Perhaps at least for status messages? I could make it that I don't send a status request if one has been sent but no response. However, I'd probably then need to add some sort of timeout mechanism in case the response was just "lost" - or never sent by LMS.

**Comment by CDrummond** [comment]
@michaelherger However... looking at the log files @th2j sent, the response is received in under a second. So, I don't think its a queuing of messages issue. If you `egrep "JSON REQ|JSON PLAYER" <log>` you can see the requests and responses.

**Comment by michaelherger** [comment]
You should always get some kind of result: either a 200 with a valid response, or at the very least a 500 or something if the request failed (which I would never expect to happen). What http client library are you using? They usually provide a timeout parameter which should handle this easily.

**Comment by CDrummond** [comment]
I'm using axios, and yes I can set a timeout - I even started to modify the code for this. However, as stated above all the responses are under a second - so timeouts would not help. Material, in the logs above, is not sending out a status request whilst another is active.

Really, the reason is LMS is using high CPU to lookup qobouz metadata. Perhaps if LMS cached this somehow, e.g. keep info for last requested track and if same is requested again return cached copy.

**Comment by michaelherger** [comment]
The fun/interesting thing is: it's not even about looking up Qobuz data, but about just local DB queries! It only happens when track metadata is integrated with the local music library, where there's no online lookup after the scan. According to the profiling files th2j sent LMS spends a lot of time in the database code ("outside" LMS' own code). 

I was wondering whether something about his data file was wrong (corrupted indexes or something), but I can't reproduce the lag on my system, using his file. The only reason why I'm still trying to understand is because I can't believe that an Intel based system considered more powerful than my NAS should behave that badly, when my Raspberry Pi 3B easily handles these queries with an even larger library, when other users are easily handling hundreds of thousands of tracks etc... 

I'll second your thought: this is not a Material issue, but an oddity in that particular installation emphasised by Material.

**Comment by michaelherger** [comment]
@th2j - I recommend you join forums.slimdevices.com and ask about why your system might not get out of the ´waitingToPlay´ state. There are guys who understand the streaming code much better than I do. Fixing that issue at least would lower the polling rate, and thus lower the overall load.

One other suggestion I'd have is to shut down LMS, delete library.db*, and start over.

**Comment by CDrummond** [comment]
I've commited the code to timout status messages and to only allow 1 active per player. Not sure this will help here though, as they were taking less than a second anyway. Still, having more then 1 active makes no sense, so no reason not to have the code...

**Comment by michaelherger** [comment]
I just saw that @th2j also posted on the Squeezelite repository, about increasing buffer sizes etc. I wonder whether he's set the buffers so high LMS basically stays in `waitingToPlay` state until it has buffered all of the track. Which, with hires, lossless etc. can take a while?

But we should stop discussing this here, as it really isn't a Material issue. Sorry for the noise 😂.

**Comment by CDrummond** [comment]
@michaelherger I agree, so will close.
