### ISSUE TITLE
[Support] Default player in non-mobile view?

### ISSUE THREAD

**Issue by edgar-vincent** [CDrummond/lms-material#582]
Hello,

First, I'd like to thank you for this absolutely stunning work. I am amazed by the amount of work you have been putting into this.

I noticed that when lms-material is open on a mobile phone, one can change the default player. Is it also possible to do that in a non-mobile view? I keep playing music in my living room instead of my headphones by mistake because I tend to forget to change the current player. This is on my laptop, on which I'd like a specific player to be always selected by default.

Thanks again,

EV

**Comment by CDrummond** [comment]
Setting a default player is the same whichever view you use.

I assume you are referring to the 'Default player' setting in the Material APK? What this does is set the 'player' URL query parameter. e.g. `http://localhost:9000/material/?player=PlayerName` (NOTE: PlayerName needs to be a percent encoded name, or the player's ID (its MAC address - e.g. 01:02:03:04:05:06)) - see https://github.com/CDrummond/lms-material/wiki/01-Introduction

You can also use the 'Manage players' dialog to set a default player.

**Comment by edgar-vincent** [comment]
Thanks a lot for the quick reply. I'd missed that. Thanks a lot!
