### ISSUE TITLE
i save light theme  as default,but it won't work

### ISSUE THREAD

**Issue by xeyesen** [CDrummond/lms-material#585]
everytime i use a new browser or new device to open lms, it alway use the dark theme,but i already set light theme as default.
it's that the way it work or some setting i missed
Please help me with this problem.
Thanks

**Comment by CDrummond** [comment]
Duplicate of #539

**Comment by xeyesen** [comment]
i did click the top-right menu and save as default, but light theme is not set to default

**Comment by CDrummond** [comment]
Ah, oops! I'm so sorry - I really should have read this more closely before closing. Never a good idea to read issue reports late at night.

Should be fixed in next release.

**Comment by xeyesen** [comment]
> Ah, oops! I'm so sorry - I really should have read this more closely before closing. Never a good idea to read issue reports late at night.
> 
> Should be fixed in next release.

Thanks.
