### ISSUE TITLE
Unable to navigate after chosing genre without name

### ISSUE THREAD

**Issue by viertelb** [CDrummond/lms-material#592]
I just recently started using material skin and library views. When I pick a certain library view and then move into genres and pick an empty genre (I have to fix this), I get to one specific artist and his albums. 

Once in that view I am unable to move back out of that artist again because the **back button** left of "Musikquellen" (music sources) is gone. 

Above "Acid" there is the empty genre ("Stilrichtungen" in German): 
![1](https://user-images.githubusercontent.com/7363661/168747153-9da084a0-a744-444f-ae08-6d906fe8fcc0.PNG)

Once in the empty genre the back button is missing:
![2](https://user-images.githubusercontent.com/7363661/168747159-a477722a-8236-4c71-9c95-0ece6459370b.PNG)

I use library views:
![3](https://user-images.githubusercontent.com/7363661/168747164-e4b3daa6-ea2e-4f05-8b10-4c3fc8d203c2.PNG)

The back button is visible when I am in the artist inside the empty genre. But moving back out of the artist will show the first picture (back button missing)
![4](https://user-images.githubusercontent.com/7363661/168747656-9ec2331d-e37f-44f8-9c50-a4486d65cce4.PNG)

I have to reload the website to get out of it.

This does not happen with other genres. 

(Of course I have to fix the genre, don't know what is wrong with it yet.)

**Comment by viertelb** [comment]
I upgraded from 8.2 to 8.3 (beta: https://downloads.slimdevices.com/nightly/index.php?ver=8.3) and the issue re-appeared. Can I fix it?

**Comment by viertelb** [comment]
Of course, sorry. I somehow was under the impression it was resolved. Thanks for your efforts!

**Comment by CDrummond** [comment]
It is resolved, just not released. I don't make a new release for each bug fix.
