### ISSUE TITLE
[Feature] Add synchronize player icon next to transfer queue icon

### ISSUE THREAD

**Issue by chippmann** [CDrummond/lms-material#595]
Currently the process of synchronizing players is quite nested.
One has to click the player dropdown, select "Manage Players", find the "main" player in the list (which can be difficult if there are many), click the three dots, select synchronize.

As we already seem to have the information for the "main" player on the home screen it should be possible to show the synchronize dialog directly from the home screen without the need of moving through nested menu's.

I suggest placing a additional icon next to the "Transfer queue to another player" icon which directly opens the synchronize dialog for the currently selected player in the dropdown.
Or if the space is too small, allow replacing the casting icon next to the player name with a synchronize button, like the option we have for the power button.

**Comment by CDrummond** [comment]
You can drag'n'drop to synchronise, or better still use the group players plugin. Long-press on 'Manage players' menu entry will also open sync dialog. (Yes, I know this is kinda hidden and I need someway to document/announce these long-press items...)

Not sure about adding yet another button to the queue, there's too many already.

**Comment by chippmann** [comment]
Oh very nice! Thx for the explanation.

True the space is very limited on mobile there.
How about the cast icon replacement? Or a long press on the dropdown?

I'd still prefer a "one" click option if possible as the sync option is something i use very frequently, but I'm of course also more than happy with the available options if you think otherwise.

**Comment by CDrummond** [comment]
> How about the cast icon replacement?

What 'cast' icon? Material has no cast icon. To the left of the player's name is its icon (which can look like a cast icon for chromecast players). Having said that, I _could_ perhaps add long-press on this icon to bring up dialog. Or maybe even standard press...

> Or a long press on the dropdown?

What drop down? If you mean on the players list menu, no - not sure the toolkit supports this. Plus it only saves one click.

**Comment by chippmann** [comment]
Very nice thx a lot!
