### ISSUE TITLE
not consider as web app

### ISSUE THREAD

**Issue by jsmdy** [CDrummond/lms-material#598]
I add on android menu through opera or firefow on Android but both don't consider as web app, so it's just a link which launch the full browser, not a lonely web app page. I don't know if there is a way to force the browser to consider the page as a web app. I know how it's working with web app because I have vue.js remote torrent app which is working as "an app".

**Comment by CDrummond** [comment]
Firefox does not support web-apps, no idea about Opera - but I cannot, and will not, test on every browser. For Android just use chrome, its installed by default and works perfectly with Material.

I personally use Firefox on Android from my general browsing, and use the Material APK for accessing LMS.
