### ISSUE TITLE
Track and album genre

### ISSUE THREAD

**Issue by larod241** [CDrummond/lms-material#599]
Hello,

Would it be possible (with an option) to display, when using Qobuz, the genre of albums or songs? (Jazz, Blues, ...)
For example, below the name of the album, or a title and the artist.

This info is present when you select to see the information of an album, for example.

Thank you for this work and this theme which is superb.

**Comment by CDrummond** [comment]
Sorry, no. LMS does not expose this info, and I do not use Qobuz so would not know how to work-around this.

**Comment by larod241** [comment]
Ok, thanks for that answer.

As the information is present when you enter an album, I thought it was then possible to display it in the lists.

Cordially


<img width="398" alt="Capture d’écran 2022-06-20 à 12 58 05" src="https://user-images.githubusercontent.com/20423481/174587502-cf7dcc94-daa8-4b7c-aff5-7031e2b13257.png">

**Comment by CDrummond** [comment]
When creating the list before this LMS does not give the client (e.g. Material Skin) this information. Only when you enter this list is this info available. And even here its just 'text' that is given to the client. Material has no (reliable) way of knowing that this line is the Genre. (Yes it could parse "Genre: XXXX", but that syntax vould change, or a have a different translation in user's language, etc).

**Comment by larod241** [comment]
OK I understand.
I will have tried ! :D
