### ISSUE TITLE
dynamic/sql playlist are not showing up since last release

### ISSUE THREAD

**Issue by the-other-martin** [CDrummond/lms-material#605]
I’m using both Logitech Devices (Squeezebox Touch) and lms-material to control LMS.
Since the last update my SQL playlists are no more showing up using lms-material (on iPhone and iPad). If I start one of the dynamic playlists via Squeezebox, suddenly I can see them under lms-material also. 
I can reproduce the bug with:
Starting built in “playlist” like my music/new music and then trying to use my music/dynamic playlist it’s showing my group (used “SQL Playlists”), but if I select/tip on it, my playlists are not showing up.
Could you please help to resolve? 
I didn’t have this problem before last update.
Kind regards, Martin

**Comment by CDrummond** [comment]
How do I create an SQL playlist? I've installed "Dynamic Playlists 3" - but no idea how to create any. Do I need any other plugins installed? Can you give me an example SQL/Dynamic playlist that I can add to my LMS?

**Comment by the-other-martin** [comment]
According to "Dynamic Playlists 3" docu it is not necessary to have "SQL Playlist" plugin installed. Instead simply save the *.sql.xml file into the "DPL-custom-lists" folder. It will show up as soon you have enabled the group of this playlist in the settings.

I'm using plugin from Erland Isaksson "SQL Playlist (v2.6.272)"
https://github.com/erland/lms-sqlplaylist
https://github.com/erland/lms-sqlplaylist/wiki
since very long time.

Not sure if you can find the plugin in the standard plugin list of LMS - if not please try to add repo ["https://github.com/LMS-Community/lms-plugin-repository/blob/master/unsupported.xml"](https://github.com/LMS-Community/lms-plugin-repository/blob/master/unsupported.xml)
If that doesn't work you can get plugin from his homepage: http://downloads.isaksson.info/download/

It is supported through "Dynamic Playlist 3" - you need to enable under DPL settings/Enabled dynamic playlists the respective group - in my example below I've used the group name "SQL PLaylists".
You can create own playlist directly from LMS web frontend home menu "SQL Playlist"/"Create new playlist".

One example from my SQL PLaylists (attaching it as xml file also) - this is selecting songs with all available genres but the ones listed, random it, up to 30 songs at the same time.

-- PlaylistName:03 Lieblingstitel
-- PlaylistGroups: SQL Playlists
-- PlaylistLimitOption:unlimited
select tracks.url from tracks
    join genre_track on
        tracks.id=genre_track.track
    join genres on
        genre_track.genre=genres.id
    left join dynamicplaylist_history on
        tracks.id=dynamicplaylist_history.id and dynamicplaylist_history.client='PlaylistPlayer'
    where
        audio=1
        and dynamicplaylist_history.id is null
        and    genres.name not like '%(%)%'
        and    genres.name not like 'Alternative%'
        and    genres.name not like 'Blues%'
        and    genres.name not like 'Boogie%'
        and    genres.name not like 'Books & Spoken%'
        and    genres.name not like 'Cabaret%'
        and    genres.name not like 'Children''s Music%'
        and    genres.name not like 'Christmas%'
        and    genres.name not like 'Classical%'
        and    genres.name not like 'Country%'
        and    genres.name not like 'Deutsch%'
        and    genres.name not like 'Dixie%'
        and    genres.name not like 'Dub%'
        and    genres.name not like 'Ethno%'
        and    genres.name not like 'Industrial%'
        and    genres.name not like 'Jazz%'
        and    genres.name not like 'Kabarett%'
        and    genres.name not like 'Metal%'
        and    genres.name not like 'Operette%'
        and    genres.name not like 'Schlager%'
        and    genres.name not like 'Soundtrack%'
        and    genres.name not like 'Tanzmusik%'
        and    genres.name not like 'Techno%'
        and    genres.name not like 'Volksmusik%'
    group by tracks.id
    order by random()
    limit 30;

**Comment by CDrummond** [comment]
Seems to work for me:

1. Saved the above as `/tmp/03 Lieblingstitel.sql.xml` - DPL seems to default to `/tmp` for custom playlists
2. Had to install `SQL Playlists` - else no `SQL Playlists` entry (neither in Material nor Default skin)
3. Navigate `MyMusic / Dynamic Playlists / SQL Playlists` and `03 Lieblingstitel` is shown
4. Selecting `03 Lieblingstitel` gives me options to Play, Append, and Add

Tried with Material from git/master and 2.10.1 release.

**Comment by the-other-martin** [comment]
This works for me only if I've started/selected one of the Dynamic Playlists from standard LMS web frontend first.
If there is something else running (no DPL) or nothing running currently I can navigate to DPL/SQL Playlists but it doesn't show up with the "03 Liebelingstitel" (same example used as above) - the "SQL Playlists" "button has no function - using 2.10.1 Material-Skin and DPL 3.2.7

**Comment by CDrummond** [comment]
Sorry, but if it works for me then not sure what I can do. AFAIK, nothing has been changed in 2.10.1 that should affect this. Certainly adding a DPL to the queue should in no way affect the browse. Perhaps its a DPL issue?

What you could do is look at the JSON REQ messages that Material sends when it does not work and when it does - and see if there is any difference.

**Comment by CDrummond** [comment]
When you say they are not showing up - do you mean they are not in the list, or they are there but you can't activate them?

**Comment by CDrummond** [comment]
Just releases 2.10.2 - might help, might not.

**Comment by the-other-martin** [comment]
Thanks for your message and new release.
Unfortunately still same on my iPad:
Test scenario:
1) select one of the standard LMS features, I’m using “my music/new music’ and play one of the albums
2) navigate to “dynamic playlists”, my group can be seen there (“Custom Dynamic Playlists”)
3) press “Custom Dynamic Playlists”, nothing happens (should show all my own custom lists in this group, but doesn’t)

Same scenario with LMS standard Web Interface:
…
3) after pressing “Custom Dynamic Playlists” all my own custom lists in this group are shown and can be played

PS: I’m using the following LMS server: piCorePlayer on RaspberryPI
Logitech Media Server Version: 8.2.0 - 1627922070 @ Tue Aug 3 11:43:18 CEST 2021
Hostname: pi-LMS
IP-Adresse des Servers: 192.168.1.130
Server-HTTP-Portnummer: 9000
Betriebssystem: piCore - DE - utf8
Plattformarchitektur: armv7l-linux
Perl-Version: 5.32.0 - arm-linux-gnueabihf-thread-multi-64int
Audio::Scan: 1.02
IO::Socket::SSL: 2.068
Datenbankversion: DBD::SQLite 1.58 (sqlite 3.22.0)
Anzahl erkannter Player: 4

**Comment by CDrummond** [comment]
How do I get this "Custom Dynamic Playlists" group? Or is it the same as the "PlaylistGroups: SQL Playlists" from the example above?

Have you tried with other clients? Squeezer or iPeng? As these use the same API as Material, whereas the Default skin does not.

As you are using Safari its possible that even though you have updated to 2.10.2 Safari is still using the cached javascript from 2.10.1. Please clear Safari's cache and try again. Perhaps even use "private" mode, after clearnig cache, as this should use fresh data each time.

Also, if this also affects desktop browsers, please:

1. Start material with debug - http://SERVER:9000/material/?debug=json
2. Navigate to 'My Music'
3. Open your browser's developer tools
4. Go to the console tab
5. Clear contents of console - click X or trash icon
6. Click on 'Dynamic Playlists'
7. Copy the full JSON RESP message produced after clicking 'Dynamic Playlists' This will contain the response sent by LMS. If there is a lot of data your browser might not be showing the full text in the console tab - the text might end with "...", in which case you need to click that so that the whole message is shown.
8. Add the contents of the RESP message here so that I can see its contents.

**Comment by the-other-martin** [comment]
you're a hero! It's always the simple things: On different devices (iPad, iPhones) I simply closed the browser and opened again.
Since I did that, I haven't faced the described problem! It works as expected now! Many thanks!

Anyway I followed your above instructions (Firefox):

My Music/Dynamic Playlists:

`[5:20:18 PM] JSON REQ: ["00:87:33:35:80:bb",["dynamicplaylist","browsejive",0,25000]] [material.min.js:237:69](http://192.168.1.130:9000/material/html/js/material.min.js?r=2.10.2)
[5:20:18 PM] JSON RESP: {"result":{"offset":0,"item_loop":[{"actions":{"add":null,"play":null,"go":{"itemsParams":"params","params":{"group1":"Custom%20Dynamic%20Playlists"},"cmd":["dynamicplaylist","browsejive"]}},"params":{"group1":"Custom%20Dynamic%20Playlists"},"text":"Custom Dynamic Playlists/"}],"count":1,"base":{"actions":{"add":{"cmd":["dynamicplaylist","playlist","add"],"itemsParams":"params"},"play":{"cmd":["dynamicplaylist","playlist","play"],"itemsParams":"params"}}}},"method":"slim.request","params":["00:87:33:35:80:bb",["dynamicplaylist","browsejive","0","25000"]],"id":3} [material.min.js:237:69](http://192.168.1.130:9000/material/html/js/material.min.js?r=2.10.2)

​`

My Music/Dynamic Playlists/Custom Dynamic Playlists:
`[5:21:59 PM] JSON REQ: ["00:87:33:35:80:bb",["dynamicplaylist","browsejive",0,25000,"group1:Custom%20Dynamic%20Playlists"]] [material.min.js:237:69](http://192.168.1.130:9000/material/html/js/material.min.js?r=2.10.2)
[5:21:59 PM] JSON RESP: {"result":{"base":{"actions":{"play":{"cmd":["dynamicplaylist","playlist","play"],"itemsParams":"params"},"add":{"itemsParams":"params","cmd":["dynamicplaylist","playlist","add"]}}},"count":7,"item_loop":[{"actions":{"do":{"params":{"playlistid":"dplusercustom_01 Daniel320"},"cmd":["dynamicplaylist","playlist","play"],"itemsParams":"params"}},"style":"itemplay","text":"01 Daniels Rave Heisl","params":{"playlistid":"dplusercustom_01 Daniel320"}},{"text":"02 Julias iTunes Songs","style":"itemplay","params":{"playlistid":"dplusercustom_02 Julia256"},"actions":{"do":{"cmd":["dynamicplaylist","playlist","play"],"params":{"playlistid":"dplusercustom_02 Julia256"},"itemsParams":"params"}}},{"params":{"playlistid":"dplusercustom_03 lieblingstitel_new"},"style":"itemplay","text":"03 Lieblingstitel","actions":{"do":{"cmd":["dynamicplaylist","playlist","play"],"params":{"playlistid":"dplusercustom_03 lieblingstitel_new"},"itemsParams":"params"}}},{"params":{"playlistid":"dplusercustom_04 lieblingstitel_enhanced"},"text":"04 Lieblingstitel erweitert","style":"itemplay","actions":{"do":{"itemsParams":"params","cmd":["dynamicplaylist","playlist","play"],"params":{"playlistid":"dplusercustom_04 lieblingstitel_enhanced"}}}},{"text":"Ab Jahr ...","params":{"playlistid":"dplusercustom_ab_jahr_new"},"actions":{"add":null,"go":{"itemsParams":"params","cmd":["dynamicplaylist","jiveplaylistparameters"],"params":{"playlistid":"dplusercustom_ab_jahr_new"}},"play":null}},{"params":{"playlistid":"dplusercustom_genre_new"},"text":"Stilrichtung...","actions":{"add":null,"go":{"params":{"playlistid":"dplusercustom_genre_new"},"cmd":["dynamicplaylist","jiveplaylistparameters"],"itemsParams":"params"},"play":null}},{"actions":{"go":{"itemsParams":"params","params":{"playlistid":"dplusercustom_interpret_new"},"cmd":["dynamicplaylist","jiveplaylistparameters"]},"play":null,"add":null},"params":{"playlistid":"dplusercustom_interpret_new"},"text":"Interpret..."}],"offset":0},"method":"slim.request","params":["00:87:33:35:80:bb",["dynamicplaylist","browsejive","0",25000,"group1:Custom%20Dynamic%20Playlists"]],"id":4} [material.min.js:237:69](http://192.168.1.130:9000/material/html/js/material.min.js?r=2.10.2)

​`

last but not least - to answer your question: yes - it is the same as the same as "Playlist Groups:" - I've now renamed it to "Custom Dynamic Playlists" (from previous used example SQL PLaylists") - sorry haven't mentioned that before

**Comment by CDrummond** [comment]
So, just a cache issue :)

**Comment by the-other-martin** [comment]
Many thanks!
