### ISSUE TITLE
Issue with: Add some CSS to prevent scrolling of 'body' in Safari.

### ISSUE THREAD

**Issue by samwatling** [CDrummond/lms-material#608]
Hi there. As always, thank you for the effort you put into developing this.

It looks like the CSS you added to deliver this functionality: ‘Add some CSS to prevent scrolling of 'body' in Safari.’ may have a slight bug. On my iPhone in Safari, if there’s nothing to ‘scroll’ in the lower part of the screen (a playlist, list of menu items etc.), the top part of the screen (player name etc) tries to scroll instead. When you stop swiping the lower section of the screen, the top bar then returns to what it was displaying before (player name and so on). Apologies, hard to describe but hope that makes sense. Not sure how to screen grab that particular bug…

**Comment by CDrummond** [comment]
So, _Safari_ attempts to scroll a non-scrollable section? And display reverts to normal? This is when used in brower? Or When pinned to home screen (in app mode).

Still, seems like a Safari bug to me.

**Comment by CDrummond** [comment]
Can you try the following version? Unzip the contents of this file over the top of your existing MaterialSkin folder in your LMS's plugins folder. Restart LMS, clear Safari cache, full reload, etc.

[lms-material-test.zip](https://github.com/CDrummond/lms-material/files/9392224/lms-material-test.zip)

Some changes were made for #589 - I think this might conflict with these CSS changes. If you try the attached can you also see if #589 is still fixed, or if it now re-occurs (if you ever experienced it anyway!)

**Comment by samwatling** [comment]
This may be a false positive - I've tried this today and the bug doesn't exhibit itself either in mobile safari or in app mode. I can only think the issue yesterday was related to cached CSS / other files from an earlier version of the Material skin following my update to the latest version yesterday.

**Comment by CDrummond** [comment]
So, should this now be closed - if it is a non-issue?

**Comment by samwatling** [comment]
Yes, thanks!
