### ISSUE TITLE
Feature: setting to change the context menu

### ISSUE THREAD

**Issue by daemmi** [CDrummond/lms-material#610]
Hey there,
I really like the material skin, it's awesome. I also like to use it on partys because everyone can add music to the queue. But what happen from time to time if friends are not used to lms they klick on play now. What isn't that bad but then the complete queue is gone. So it would be awesome to change the context menu so that you can't just click play, so that only the option play next or add are visible or enabled. So the queue would never be deleted.

Would it possible to add this feature?

Best wishes
Jonas

**Comment by CDrummond** [comment]
I guess what you want is something similar to [iPeng Party](http://penguinlovesmusic.de/ipeng-party/)? e.g.

- Only allow to add to playlist
- Prevent volume changes
- Prevent sync changes
- Hide 'Manage players'
- Hide 'Player settings'
- Hide 'Server settings'
- Disable queue re-order
- Disable saving of queue

Any others?

To implement this I _think_ I'd need someway of installing 2 skins - e.g. MaterialSkinParty and MaterialSkin. Then you'd set 'MaterialSkinParty' as the default skin - so users would just need to browse to "http://server:9000" and they would see the locked down version. You would then use "http://server:9000/material/" to access full control. Make sense?

**Comment by CDrummond** [comment]
Work started in the `dev` branch, for 2.11.0, to implement this.

**Comment by daemmi** [comment]
Hey, sounds good. Makes absolutely sense for me. Looking forward to check it out. Thanks.

**Comment by CDrummond** [comment]
Closing, as implemeted for 2.11.0 in dev branch.

**Comment by daemmi** [comment]
@CDrummond can I somehow install the dev branch to test the new mode, the coming weekend is a good opportunity to test it.

**Comment by daemmi** [comment]
Feedback: it worked like a charm! Only thing I would suggest is also to disable the next and previous song buttons, some started to fight when someone added a song someone didn't want to hear, haha.

**Comment by CDrummond** [comment]
Thanks for the feedback, and glad it worked. I'll re-open this so that I don't forget to disable those buttons.

**Comment by CDrummond** [comment]
Buttons disabled.
