### ISSUE TITLE
Ad to homescreen Iphone iOS 16 no Icon

### ISSUE THREAD

**Issue by MichaelFrech** [CDrummond/lms-material#611]
Hallo. 
Recently switched from android to iphone and tried to ad LMS Material url to the homescreen but the well known icon i have got on android dont show up.
Instead there is a icon crated like a screenshot from the LMS page.

Also got my Lms Gui secured with the Login feature (user/password) and have to tipe it in, every time i load the shortcut after swiping it "away" in the iphone multitask view.
Do you have any suggestions for this behaviors?
Please excuse my poor Englisch.

By the way, thank you very much for your excellent work on the Material UI. REALLY appreciate it a lot !!!!
One of the best donations i ever made. Have to give you another one soon😁.

Best regards
Michael

**Comment by CDrummond** [comment]
Sorry, but I'm not sure there is much Material can do - these sounds like iOS issues/limitations. The "Add to homescreen" icon should work, as I know others use this. If this nolonger works on iOS 16, then that's an iOS issue - as this has not been changed in Material for a long time.

As to the username/password prompt. again (AFAIK) nothing Material can do - as its not activated until after the credentials have been entered.

I would not be surprised if these issues are down to the fact that LMS is accessed via "http" but most web-apps should be "https".
