### ISSUE TITLE
Manage Players exclusive URL?

### ISSUE THREAD

**Issue by kylepyke** [CDrummond/lms-material#612]
Hi!

I'm wondering if there is a way to access the "Manage Players" page via URL, similar to how there is a dedicated "Now Playing" page, if you load xxx.xxx.x.xx:9000/material/now-playing?

It would be VERY useful for applications like Home Assistant.

Thanks!

**Comment by CDrummond** [comment]
Try:
```
http://SERVER:9000/material/?action=dlg.open/manage
```

**Comment by kylepyke** [comment]
Brilliant! Thanks so much!

**Comment by CDrummond** [comment]
I've also just updated the Wiki page with more diaog names, as this URL above was not very obvious. Seee [03-Actions](https://github.com/CDrummond/lms-material/wiki/03-Actions)

**Comment by kylepyke** [comment]
So great. Thank you again for all of your work on this!

The way the /material/now-playing page hides the browse and queue tabs is very slick. I wonder if you'd consider doing something similar with some of the other pages. It's be great to hide the back arrow on the manage players page!

**Comment by CDrummond** [comment]
No, the manage players dialog is a full page dialog. If you **only** want the dialog and nothing else you could add some [CSS](https://github.com/CDrummond/lms-material/wiki/07-Customisation) to hide the dialog's back button.

NOTE: Currently this dialog will auto-close if there are no players. So, I'm not sure this is really the experience you are looking for. I could, for the next release, just add some text "No players found" instead of closing.

**Comment by kylepyke** [comment]
Hmmm... Yeah, it doesn't _quite_ work the way I was hoping. It seems to only load the Manage Players page about 40% of the time. Most often, it just loads the Now Playing page.

Thanks for your help anyways!

**Comment by CDrummond** [comment]
The 'Manage players' dialog will only open if there are players attached. Please note Material is a single page web app, as in there is only 1 HTML file (now-playing.html redirects to index.html and adds some query parameters) - all other 'pages' are crated via javascript.

**Comment by kylepyke** [comment]
Of course, excuse my inaccuracy calling the 'Manage Players' dialog a page.

What seems to happen, I'm guessing, is that the list of players isn't populated before the javascript module loads that dialog, so for a brief moment, it appears that there are no players attached, causing the dialog to close. In any case it was worth a shot, and thanks again for your help!
