### ISSUE TITLE
Party mode: Too many redirects

### ISSUE THREAD

**Issue by stephanvdplas** [CDrummond/lms-material#621]
When trying to start party mode by using URL parameter ?party, the browser tells me: ERR_TOO_MANY_REDIRECTS.
In the address barI observe a lot of slashes: https://server.vdplas.net:8999/material?party/////////////////////////////////////////////////////////

**Comment by CDrummond** [comment]
Wrong URL, you need a "/" after "materail" - e.g. https://server.vdplas.net:8999/material/?party - or just https://server.vdplas.net:8999/materialparty/

**Comment by stephanvdplas** [comment]
Clear! It is working!
