### ISSUE TITLE
Rename Alt to Option on macOS clients

### ISSUE THREAD

**Issue by ryanfeeley** [CDrummond/lms-material#622]
As there is no Alt key on Macintosh keyboard, consider adding a shortcut string for Option.

MAC CURRENT
- Alt+▲ • Increase volume
- Alt+▼ • Decrease volume
- Alt+◀ • Previous track
- Alt+▶ • Next track
- Alt+(N) • Switch to Nth player

MAC PROPOSED 
- Option+▲ • Increase volume
- Option+▼ • Decrease volume
- Option+◀ • Previous track
- Option+▶ • Next track
- Option+(N) • Switch to Nth player

**Comment by CDrummond** [comment]
Does the actual shortcut still work, just the displayed string is wrong?

**Comment by ryanfeeley** [comment]
Yes, Option works. I think you just need another variable like you did for ⌘.

**Comment by ryanfeeley** [comment]
You may even want to consider adding the keyboard shortcut to the tooltip 
<img width="169" alt="image" src="https://user-images.githubusercontent.com/68213/205331081-fbe2886b-e96e-4d32-8f6c-079eda5a028d.png">
