### ISSUE TITLE
Make search globally accessible?

### ISSUE THREAD

**Issue by pbrekelmans** [CDrummond/lms-material#623]
Would it be possible to have the search button, or a shortcut key to search, always accessible in the interface?
It is not very obvious for perusing casual users to first have to go to Home, and then find the looking glass button in the music sources header bar on the right - i'd say Search deserves an entry of its own in the top level menu maybe? Just some thoughts on enhancing an already brilliant interface to LMS, thank you!

**Comment by CDrummond** [comment]
This has been requested before, but I will not be adding. If I the albums list open I would expect to **only** search in albums, if I was listing an album of many tracks then search should be limited to them, etc. LMS does not, AFAIK, support that - hence its placement in the home screen.
