### ISSUE TITLE
Player power button on home frame works only once

### ISSUE THREAD

**Issue by waltonbruce** [CDrummond/lms-material#624]
Enable the interface option to display the power button on the home frame for the current player.

Press the button once, it toggles player state on/off.

Subsequent press does nothing.    (The drop down power buttons do still work however.)

Refreshing the browser page (chrome) gets the button to work again, but only once.

This issue began with a recent update, not sure which one exactly.    

Latest LMS 8.3.1 running here perhaps that's it?

Not urgent, just a little annoying

Thanks for the great work on this skin.

**Comment by CDrummond** [comment]
This is a material issue, but is already fixed ready for next release.

**Comment by CDrummond** [comment]
@waltonbruce 3.0.2 has just been released with this fix.
