### ISSUE TITLE
Allow desktop users to Mute/Unmute

### ISSUE THREAD

**Issue by ryanfeeley** [CDrummond/lms-material#625]
On the touch interface users can tap the Mute button.

This does not exist on desktop, nor does a keyboard shortcut.

Considering adding something like an Option-click Reduce Volume to offer mute.

(mute is a useful feature to detect system noise in ways that pause does not afford)

**Comment by CDrummond** [comment]
Long-press on volume labels - as detailed in the 'Help text'

**Comment by ryanfeeley** [comment]
Oops! I missed it! You are incredible and I can't believe how hard it is to find a single flaw with this interface.

**Comment by CDrummond** [comment]
Thanks, but its certainly not without its flaws. Things like long-press are hard to find, hence the help text, and I was not quite sure where to put the long-press to mute. Originally this was on the buttons, but I was getting weird responses uses long-press on these so moved to the labels.
