### ISSUE TITLE
Display composer next to song title

### ISSUE THREAD

**Issue by audiomuze** [CDrummond/lms-material#626]
Would it be possible to list the track composer ( when present ) next to the performer in the album browse and make them clickable links?

![pic](https://i.imgur.com/zP0aloV.png)

![pic](https://i.imgur.com/rLJ3q5O.png)

**Comment by CDrummond** [comment]
I've started work on this for a future 3.1.0 release. Note, next release is likely to be 3.0.3 (which will not have this).

**Comment by CDrummond** [comment]
Closing as implemented for 3.1.0
