### ISSUE TITLE
Incorporate additional metadata that's imported from tags via LMS scanner

### ISSUE THREAD

**Issue by audiomuze** [CDrummond/lms-material#632]
At present LMS presents all albums an artist appears in as one consolidated list without distinguishing between albums, EP's, Singles, Bootlegs, Compilations, Appearances and Various Artist albums.  

Given that LMS' scanner pulls tags that would help with being able to present recordings distinguishing between these types (and thus making it far easier to explore a large body of work) it'd be hugely beneficial for if Material skin could leverage this metadata where the tags exist.

The attached image shows three data points that lend themselves to an enriched exploration of a music collection:
LABEL: Record label, which would enable exploration of a library by record label
RELEASTYPE: Release Type (https://musicbrainz.org/doc/Release_Group/Type addressing albums, EP's, Singles, Bootlegs, Compilations, Appearances and Various Artist releases
)
VERSION: musicbrainz' _releasecomment to distinguish different releases of an album from one another

![image](https://user-images.githubusercontent.com/6852511/207718506-830b1c18-0a28-45b8-979d-b426b50ac567.png)

Would you consider leveraging these tags where they're present in the LMS database?

**Comment by CDrummond** [comment]
The items are not available via LMS' JSONRPC API.
