### ISSUE TITLE
Multiple server entries 

### ISSUE THREAD

**Issue by artatgray** [CDrummond/lms-material#633]
I'd like to request the ability to add and store multiple IP addresses/host names on the Server Settings page of the application. I have those as I've a VPN that I connect to often, as well a LAN, and Auto-discovery doesn't work with the former.

What I do in that situation now is, open the VPN client and copy/paste the relevant IP from it into LMS Material Android. This is workable, but slightly inconvenient - some might find it not to be particularly user friendly as well.

Thanks in advance... 😎

**Comment by CDrummond** [comment]
Material skin is served from LMS - therefore is server instance specific. This repo is for the skin only, not the Android APK.

I realised the APK repo did not have issues enabled, which I now have - and have transferred this over: https://github.com/CDrummond/lms-material-app/issues/3
