### ISSUE TITLE
play/add all button is not shown on tidal tracks page but shown on palylists page

### ISSUE THREAD

**Issue by cyron** [CDrummond/lms-material#635]
I'm starting tidal recently and found the play/add all buttons are not shown on tracks page,
but these buttons are shwon on palylists page.
and when I switch back to lms origin theme, the "All Sons" is shown on tracks page.

I took the screenshots and response json in case needed.
[https://drive.google.com/file/d/1117_591rHq2lR84tX4SMKWuAMvbhjFmH/view?usp=share_link](url)

**Comment by CDrummond** [comment]
Is the option to play/add shown on the menu of "Tracks" entry before showing the list of tracks (i.e. does parent item's menu have this?)

Do other controllers (e.g Squeezer, iPeng) show the "All songs" entry?

**Comment by cyron** [comment]
thanks for the replay.

this is the parent menu of playlists and tracks, no play/add bottun shown.

![Novedades](https://user-images.githubusercontent.com/764831/209496831-5a69faf7-26b1-447d-85f3-9ffcf41c331d.png)

and I trid Squeezer, it behaved exactly same as meterial skin, buttons shown on playlists but not on tracks.

**Comment by CDrummond** [comment]
Squeezer uses the same API as Material, whereas Default skin uses another. Sorry, but this implies its LMS not indicating that this is possible. If no "All songs" entry is added then Material does not know a way to add all songs in one go.

As a work-around you can select one track, invert selection (so all bar 1st selected track are selected), re select 1st track, then add/play all.
