### ISSUE TITLE
Enhance Technical information related to tracks

### ISSUE THREAD

**Issue by audiomuze** [CDrummond/lms-material#637]
![image](https://user-images.githubusercontent.com/6852511/209947259-abbac7a9-efbb-430f-ade5-4233d91caebc.png)

Is it possible to enhance the display above by removing the (meaningless) VBR data and replacing it with something more useful e.g. showing bit depth and sample rate of the file alongside file type?

Seems the data is readily available to Material Skin:
![image](https://user-images.githubusercontent.com/6852511/209948064-044e113b-637a-4877-8514-7ab6a9817dcb.png)

**Comment by CDrummond** [comment]
Only samplesize seems to be missing. I've added this for 3.1.0
