### ISSUE TITLE
Enhance expanded Now Playing

### ISSUE THREAD

**Issue by audiomuze** [CDrummond/lms-material#638]
Consider adding some additional info to Now playing  expanded screen (taking into account other enhancements already implemented but not reflected herein):

![ksnip_20221229-125053](https://user-images.githubusercontent.com/6852511/209955741-a900b1b5-9cc9-43cc-a143-1b4baec37227.jpg)

**Comment by CDrummond** [comment]
You can already show composer, conductor, etc. meta-data here - needs configuring server-side. The other info is available when showing artist/album/song info.
