### ISSUE TITLE
Could you add a Filter in the browse showing all albums an artist appears in?

### ISSUE THREAD

**Issue by audiomuze** [CDrummond/lms-material#639]
For large collections it'd be useful to be able to view an artist and then filter in order to find an album quickly.  Ideally a Filter would match whatever text is typed, whether it's an album name, year, song etc. - whatever's possible based on the data Material Skin has at its disposal in that view.

**Comment by CDrummond** [comment]
Whilst I can see the advantage of a filter, I'm not 100% convinced its worth the effort. Material would **only** be able to filter on the displayed text, as it does not have the list of tracks at that level and does not store any further data.

If an artist has may albums, then Material will show a quick-jump bar on the left - allowing you to quickly scroll. You can also choose to sort by year, in which case this quick jump will contain years.

Sorry, but this is just not a feature I would use, and have no time/enthusiasm to implement. However, Material Skjin is open soruce and I gladly accept pull requests.
