### ISSUE TITLE
Uncaught TypeError in server settings

### ISSUE THREAD

**Issue by DrewNeon** [CDrummond/lms-material#641]
My system enviroment is as follow:

OS: Windows 10
Logitech Media Sever: v8.3.0
Material Skin: v3.0.3
Browser: Google Chrome or Firefox

Some pages, such as formatting under server settings show the following error in the browser console.

`prototype.js?r=git353c504:6913 Uncaught TypeError: Cannot read properties of null (reading '_prototypeUID')
    at getUniqueElementID (prototype.js?r=git353c504:6913:24)
    at getOrCreateRegistryFor (prototype.js?r=git353c504:6936:13)
    at register (prototype.js?r=git353c504:6949:20)
    at new observe (prototype.js?r=git353c504:6997:17)
    at interface.html?player=aa%3Aaa%3Aec%3A19%3A8a%3Ac8&playerid=aa%3Aaa%3Aec%3A19%3A8a%3Ac8:860:2
getUniqueElementID @ prototype.js?r=git353c504:6913
getOrCreateRegistryFor @ prototype.js?r=git353c504:6936
register @ prototype.js?r=git353c504:6949
observe @ prototype.js?r=git353c504:6997
(anonymous) @ interface.html?player=aa%3Aaa%3Aec%3A19%3A8a%3Ac8&playerid=aa%3Aaa%3Aec%3A19%3A8a%3Ac8:860
`

**Comment by CDrummond** [comment]
The 'Server settings', extra 'Player settings', and 'Extras' pages are all actually frmo the 'Classic' (ont 'Default') skin - and Material jsut adds some CSS tweaks, and a little JS.

All the above errors are from the 'Classic' skin - you can see the same if you navigae to "http://server:9000/classic"

You should report this issue on the slimserver github repo.

**Comment by DrewNeon** [comment]
> The 'Server settings', extra 'Player settings', and 'Extras' pages are all actually frmo the 'Classic' (ont 'Default') skin - and Material jsut adds some CSS tweaks, and a little JS.
> 
> All the above errors are from the 'Classic' skin - you can see the same if you navigae to "http://server:9000/classic"
> 
> You should report this issue on the slimserver github repo.

Thanks for the prompt reply! 

I did checked the location of the file mentioned in the error. Indeed, prototype.js is under the Default skin. However, even I set the Web interface to Material Skin from the Interface setting, this error persists.

It seems that this error won't go away for a while until LMS fixes this bug, my following question is that whether this error message actually produces any problems when using Material Skin with LMS?
