### ISSUE TITLE
Can't Reset Default Skin

### ISSUE THREAD

**Issue by hipresto** [CDrummond/lms-material#644]
LMS 8.2.0 running on PiCore. Sizing issues on Android tablet running Firefox - too large for screen. I could finally resize if I went into Material Skin Interface settings and pinched. Tried to revert to default skin. I only get a bit of the layout now, and the rest is blank. Same is true if I go to the LMS setup page, but not if I go through the link in PiCore.

I deinstalled the Material Skin plugin. No change. Now in the interface list, there is Default, Light, Classic, and FR.

Please advise.

Thanks!

**Comment by CDrummond** [comment]
This has nothing todo with Material. Sorry, but these sort of questions belong on the LMS forums.

BTW, there is a APK for Material that will alloy you to set a zoom level - [Material APK](https://search.f-droid.org/?q=LMS&lang=en)
