### ISSUE TITLE
Enhancement suggestion: Disable keyboard autocorrect in search fields.

### ISSUE THREAD

**Issue by Atmis** [CDrummond/lms-material#646]
Hi,

I am using Material Skin mostly on iOS (iPhone and iPad) as a remote control, time to time from my PC. I think it would be interesting to disable the autocorrect included with the soft keyboard on search fields (at the root of Material Skin, or in plugins like Qobuz for example).
Most of the search are made with words that either are not present in the OS dictionary, or the language is not appropriate (switching between French and English search for example), and if you are not careful you are good torenew your search because the autocorrect has changed your search terms.

Example : searching "Bebel Gilberto" changes to "Bevel Gilberto", "Carlos Kleiber" changes to "Carlos Klein et", "Erik Truffaz" to "Erik truffade", "Bozilo" to "bao I'll", etc.

The Qobuz iOS native app disables the autocorrect in the search field and it is much more comfortable to use.

I guess <input type='text' autocomplete='off' spellcheck='false' autocorrect='off' autocapitalize='off'> would work, but I am not a proper html developer.

Thank you for your splendid work.

**Comment by CDrummond** [comment]
Sorry, but from a quick search I don't think you can. Also, I see no harm in these suggestions - they appear as options which you are free to ignore.

**Comment by CDrummond** [comment]
Material uses v1.5x of the Vuetify Javascript framework. This `autocomplete` is supported via `browser-autocomplete` on the `v-text-field` element. I've tried `browser-autocomplete="off"` and `browser-autocomplete="new-password"` - and neither work. I have confirmed that `<v-text-field browser-autocomplete="off"....` is transformed into `<input autocomplete="off"...`

And after writing the above I tried with `<v-text-field autocorrect="off"` - and seems to stop the auto-correct for me. I still get suggestions above the keyboard, but to me that makes sense and is OK.

iOS seems to aggressively cache things, so if you are making changes you probably need to clear Safari's cache before changes will be seen.

**Comment by CDrummond** [comment]
I've added `autocorrect="off"` for v3.1.0 of Material.

**Comment by Atmis** [comment]
Thank you ! I will test it when I am back home this evening.

**Comment by Atmis** [comment]
Hi Craig,
I made some testing, I confirm that the autocorrect="off" is working (and it is so much better this way!), but it is not applying on all fields.

On the root screen, the simple search field has autocorrect="off" and is working, but not the advanced search dialog (Title, Artist, etc.), I confirm that the autocorrect="off" is not present. It should be added in the advancedsearch-dialog.js file.

Same in Qobuz, it works with the search field on the header when the display is set to list view, but if I switch to grid view, the search comes into a popup dialog, and the autocorrect="off" is not there.

I think the autocorrect="off" should be present in mostly all v-text-field.

**Comment by Atmis** [comment]
Hi Craig,
I made some testing, I confirm that the autocorrect="off" is working (and it is so much better this way!), but it is not applying on all fields.

On the root screen, the simple search fields have autocorrect="off" and is working, but not the advanced search dialog (Title, Artist, etc.), I confirm that the autocorrect="off" is not present. It should be added in the advancedsearch-dialog.js file.

Same in Qobuz, it works with the search field on the header when the display is set to list view, but if I switch to grid view, the search comes into a popup dialog, and the autocorrect="off" is not there.

I think the autocorrect="off" should be present in mostly all v-text-field.

**Comment by CDrummond** [comment]
...ah, forgot about those. Updated now.

**Comment by CDrummond** [comment]
...and thanks for testing, and providing feedback - much appreciated.

**Comment by Atmis** [comment]
Just tested your correction and I confirm that is now working in the other fields I mentioned earlier.

Thank YOU ! I use Material Skin daily at home, it is a great piece of software with Daphile and LMS. This enhancement will make it nearly perfect for me.

It is now time for a small donation
