### ISSUE TITLE
Enhancement Suggestions - Hide Years in Albums, Show full A-Zs

### ISSUE THREAD

**Issue by rfgdrake** [CDrummond/lms-material#647]
Sorry if this has already been covered elsewhere but is there a way of hiding the Year when looking at Albums?  It's interesting periodically to look at the age of albums (or check that multipart albums all have the same tag) but it does clutter up the screen.

And looking at Albums and at Artists, the A-Z in the left sidebar misses some letters.  I can see that this is to allow an abbreviated 'full' list to appear on one page but it means that if I want to search for an Album in B, I have first to go to A or to C, and scroll either up or down to get to B.  Would it be possible to have the option of this as a full scrolling section, showing all letters?

Thank You for your work on the Materials skin.  One of [Darko's](https://darko.audio/?s=squeezebox) videos recommended it so I thought I'd give it a try.  I've had my Squeezeboxes for years but this new skin has made LMS appear all new and shiny!

**Comment by CDrummond** [comment]
Sorry, no the listing format is not conifigurable.

Letters are removed from the A-Z jumpbar if there is insufficient space to show them all.
