### ISSUE TITLE
Album information contains programming code after update to version 3.1.0

### ISSUE THREAD

**Issue by BeActivated** [CDrummond/lms-material#648]
Hello,
Album information contains programming code. See pictures.
![Before update](https://user-images.githubusercontent.com/88147509/214074529-5fddcc35-0f5e-4b1b-9d6a-cd3ad0e4afe5.jpg)
![After update](https://user-images.githubusercontent.com/88147509/214074549-d8d490a4-3940-4f06-8ff8-f4c1604c5a91.jpg)

**Comment by CDrummond** [comment]
Thank you for taking the time to report this. However, it has already been mentioned on the slimdevices forums and is fixed for 3.1.1
