### ISSUE TITLE
PopUp showing backside <obj class ...> rather than content

### ISSUE THREAD

**Issue by gstalnaker** [CDrummond/lms-material#651]
Craig - see screen shots. I've the lastest version (well, LMS doesn't say that there is a new version so I'm assuming I have the latest). 

How to get to this, or the way I get to it:

My Music > Genres > Select genre > Albums > Select album > See track listing > Hold cursor over menu icon on far right of track item > Popup appears with unexpected values

Usually I see the list of artists, but now I'm seeing what appeas to be backside scripting code.

![LMSMaterial_Issue_Screenshot_20230128_121026](https://user-images.githubusercontent.com/11047967/215284209-3da8d44b-4792-4d10-8a03-d332b861b3fb.jpg)
![LMSMaterial_Issue_Screenshot_No2_20230128_121026](https://user-images.githubusercontent.com/11047967/215284210-cccd331d-8851-4c1e-9203-a56022233202.jpg)

**Comment by CDrummond** [comment]
Thanks for reporting, should be fixed in 3.1.3
