### ISSUE TITLE
Play-All Button Disappeared - Qobuz My Favorites Songs List

### ISSUE THREAD

**Issue by WouterNordsiek** [CDrummond/lms-material#654]
The play-all-songs button does not appear in the material skin. (I thought this button was there about a year ago, but it seems to be disappeared now)
<img width="427" alt="Scherm­afbeelding 2023-02-11 om 22 26 28" src="https://user-images.githubusercontent.com/106081189/218281897-eebc0412-9b5f-41a1-aa51-d9560063f7fd.png">

This is how it looks in material skin:
<img width="546" alt="Scherm­afbeelding 2023-02-11 om 22 28 16" src="https://user-images.githubusercontent.com/106081189/218281902-4d680a8f-15a8-49fe-af96-6fba9d7d27c7.png">

**Comment by CDrummond** [comment]
The reason for no add all / play is is that there is more than 200 tracks in this list. For these lists Material adds the tracks one by one, and this is very slow. For this reason Material limits this functionality to lists of 200 tracks or less. However, I have no access to Qobuz, so cannot confirm how slow it is.

If you select the first track, use Material's invert selection (which will select all bar the first), then re-select the first, add/play all should now appear. If you use one of those, how slow is the action?

**Comment by CDrummond** [comment]
Are you OK with installing a version of Material from git? If so I could suggest some changes to try and work-around this.

**Comment by WouterNordsiek** [comment]
> Are you OK with installing a version of Material from git? If so I could suggest some changes to try and work-around this.

Sure, let's give this a try! I'm kinda new, so have to figure out how to easy update from the git version. Running picoreplayer and LMS from the pi4.

**Comment by CDrummond** [comment]
If you do use the version from git, try the 3.2 branch

**Comment by WouterNordsiek** [comment]
> 
<img width="627" alt="Scherm­afbeelding 2023-02-13 om 21 25 46" src="https://user-images.githubusercontent.com/106081189/218576899-39cfd2f5-0022-4468-97e3-1cd0b1948aa2.png">

It works! And the PLAY ALL and ADD buttons do appear. But as you predicted.. its very slow. At least on the Pi4 (picoreplayer and lms) and stops at 20 songs or so. 
On the other hand the performance with LMS 8.1.1 on my Synology DS918+ is working much better and taking like 2 minutes to add every 100 songs, which is fine! 

The workaround with the 'select' function is working nice too, so if you don't want to implement this in the master version, i can live with that! Keep up the good work, for this super nice skin!!!

**Comment by CDrummond** [comment]
3.2 branch is slow? Odd I've just tried a YouTube search that returns 200 items, added all, and it takes ~3seconds on a Pi4. (I had to hack the code to force it to use this method, as by default it uses a quicker one - but this is the only service I have access to).

The changes in 3.2 will be merged into master, when its ready for release.

**Comment by WouterNordsiek** [comment]
> 3.2 branch is slow? Odd I've just tried a YouTube search that returns 200 items, added all, and it takes ~3seconds on a Pi4. (I had to hack the code to force it to use this method, as by default it uses a quicker one - but this is the only service I have access to).
> 
> The changes in 3.2 will be merged into master, when its ready for release.

I don't think it is the branch, i think it maybe is my setup/combination on my pi4 with cpugovenor powersave (for better picoreplayer sound quality). I did not install 3.2 on my synology yet, but tried adding all the 600+ songs with your 'select' workaround. (as i assume this is the same process as pressing the play all/add button)

**Comment by CDrummond** [comment]
> 2 minutes to add every 100 songs

That's **very** slow!

---

Do these add/play all options appear for other control points?

---

If you edit `browse-page.js` and change line 11 from:
```
const ALLOW_FAKE_ALL_SONGS_ITEM = new Set(['youtube']); // Allow using 'fake' add all item
```
to:
```
const ALLOW_FAKE_ALL_SONGS_ITEM = new Set(['youtube', 'qobuz']); // Allow using 'fake' add all item
```

Then **fully** reload browser page (e.g. clear cache, etc). Does this then work? And is it faster (should be, and is **much** faster with YouTube).

---

In the 3.2 branch the list of commands to add track is sent as 1 command to LMS, and the server (e.g. Pi4) adds tracks one by one. In Master the web-page sends add command for each track.

**Comment by WouterNordsiek** [comment]
`const ALLOW_FAKE_ALL_SONGS_ITEM = new Set(['youtube', 'qobuz']); // Allow using 'fake' add all item`

WOW That fixes it!!! Its now lightning fast :)
