### ISSUE TITLE
Nice to Have Feature Request: Display of non-square, rectangular artwork

### ISSUE THREAD

**Issue by Supertramp1969** [CDrummond/lms-material#656]
Hi Craig,
First of all, many thanks for providing us your great user-interface to access our music.
A nice to have feature would be to display non-square, rectangular artwork like the example below in full without cutting the bottom part in the browse window. Sort of like a vertical letterbox.
Thanks for your feedback and keep up your great work!
Toine

![cover](https://user-images.githubusercontent.com/121453970/219583921-3b8e32f5-77c9-4ebd-9f33-74f65bfb14d0.jpg)

**Comment by CDrummond** [comment]
No, sorry. Material is for showing album covers, and these are squre.

**Comment by Supertramp1969** [comment]
Fair enough Craig. Thanks!
