### ISSUE TITLE
Alt+(N) keyboard shortcut not working on French (AZERTY) keyboard

### ISSUE THREAD

**Issue by edgar-vincent** [CDrummond/lms-material#660]
Hi!

Thanks (again) for this wonderful theme. 
I've been trying to use the keyboard shortcuts to change players by pressing `Alt + digit`, but they don't seem to work with a French keyboard layout. They do work when I switch to a British layout. I'm using Firefox 110 and Gnome 43 on Arch Linux.

On a French (AZERTY) keyboard, digits are entered by pressing `Shift` and one of the top row keys. For example, `1` is entered by pressing `Shift+&`, where the `&` key is where the `1` key is on an English-language layout.
 Maybe the necessity of an extra modifier key prevents it from being picked up. Pressing `Alt+&` does not work either.

Moreover, I think it would be nice to have shortcuts to switch to the next/previous player, in order for the user not to have to remember which number is associated with which player. In my case, for example, I only have two players, and I keep forgetting which one is which. I'd like to be able to simply switch to the other player without thinking about its number. What do you think?

Thanks again for consistently writing the best Linux audio players! I used Cantata exclusively for years, and now only use lms-material.

EV

**Comment by CDrummond** [comment]
Confirmed. I switched my KDE/Plasma keyboard to French - Alt+Shift+1 works for "Alt+1" shortcut in konsole. Perhaps its the JS library that I use for keyboard shortcuts that does not support this. I'll see what I can do.

Must admit I never actually use these shortcuts.

**Comment by edgar-vincent** [comment]
Thanks a lot! I tried to install the master branch version, but I couldn't get the keybindings to work, but maybe the old version was conflicting with the new one. I'll wait for the next release and let you know.

**Comment by edgar-vincent** [comment]
It works fine with the stable release! Thanks again.
