### ISSUE TITLE
Queue +toolbar + info key disappear on LG webOS browser tv 

### ISSUE THREAD

**Issue by Jerry87878787** [CDrummond/lms-material#661]
As in object on LG webOS tv browser the bottom toolbar , queue list and info key are not available 

as a picture ( now and before ) 

![F2D3E68C-F6C2-4893-BB39-4113E8E38B6C](https://user-images.githubusercontent.com/127791502/224846780-f929c6e3-7909-4f19-a3ae-a9e3596b49ce.jpeg)

![06AD4640-3051-46E5-85D0-C32EFE25C919](https://user-images.githubusercontent.com/127791502/224846918-6398a792-4415-4a6b-a969-8b670a438c18.jpeg)

**Comment by CDrummond** [comment]
I've seen your postings on LMS forums, never replied as there is not much I can do. Sorry, bu t I do not have access to such a device - and to be honest, large screen usage is not exactly a use-case I envisaged.

I leave this report open, as its valid, but as I said not much that I think I can do about this - I'm not a Javascript/web developer.

**Comment by Jerry87878787** [comment]
thanks for all you do, maybe in my opinion, one solution would be to go back to previous release, but i don't know if it can be done

**Comment by CDrummond** [comment]
Are you saying it worked in older releases? If so, if you can track down the last working release I can do a diff and try and determine what might have broken things. All releases are available on this github site. You just need to download the relevant `lms-material-VERSION.zip` file.

**Comment by Jerry87878787** [comment]
Yes it works properly and very saissfying  until a few days ago …

**Comment by CDrummond** [comment]
OK, so you need to determine which was the last useable build.

**Comment by Jerry87878787** [comment]
For sure 3.1.4

**Comment by CDrummond** [comment]
And 3.2.0?

**Comment by Jerry87878787** [comment]
Maybe , cos I rmb that 2 weeks ago everything was ok .

**Comment by CDrummond** [comment]
As stated, you need to determine the last one that was OK. I cannot do this for you. I need to know for definite which was the **last** version that worked.

**Comment by CDrummond** [comment]
Hmm... Looking at the diff between 3.2.0 and 3.2.1 the _only_ change I can see which _might_ affect this is that I use a `replaceAll` function. This was added in 2021 - but if your TV's browser is  really old, perhaps it does not support this.

I've added a work-around for 3.2.2, so will be wait to see if this is fixed then. Alternatively you could checkout the code from git and try.

**Comment by kjwop** [comment]
I have the same issue with my iPad running iOS 12.5.7. 
Version 3.2.0 (with "Application" visible in the Settings menu) worked fine, but after installing 3.2.1 the queue and the "playing" bar disappeared. They are visible only in the Expanded Now Playing view.

**Comment by Jerry87878787** [comment]
> wait

Thx craig u are very kindly and available , I have not so big skill ti fix issue by code etc. 
anyway , my tv is LG Oled C9 ( 2019 ) until 20 day ago it have zero problem with material skin , I give u this info only for help your great job. 

it will mean that I will resign myself to using classic daphile on tv :) 

looking for a new future release 
:)

**Comment by Jerry87878787** [comment]
> I have the same issue with my iPad running iOS 12.5.7.
> Version 3.2.0 (with "Application" visible in the Settings menu) worked fine, but after installing 3.2.1 the queue and the "now playing" bar disappeared. "Now playing" is visible only in the Expanded Now Playing view.

I read on slimdevices forum that u can fix this issue on iPads simply deleting cache and deleting icon LMS on home board .

**Comment by kjwop** [comment]
Unfortunately, deleting cache, etc., did not work for me. I can wait for 3.2.2 but also would like to downgrade to 3.2.0.

**Comment by CDrummond** [comment]
I will release 3.2.2 soon which should resolve this issue. When that is released, if you confirm the fix I will then close this.

**Comment by kjwop** [comment]
Great, thanks!

**Comment by Jerry87878787** [comment]
Great Craig  …fixed  

u are the best … i give u a gift soon pp:) 

thx thx thx

**Comment by Jerry87878787** [comment]
![C18C1159-C00C-4A8D-8ED7-3576A9ED0001](https://user-images.githubusercontent.com/127791502/226120820-f37a74fc-bec1-4be3-8658-e0862b38e1ad.jpeg)

**Comment by dartemisia** [comment]
Brilliant! Completely fixed. Thanks for all your fine work!

**Comment by kjwop** [comment]
Works for me too! Who needs Roon when we have Material on top of LMS ;-))
Thanks!
