### ISSUE TITLE
Issue with mobile layout on desktop PC

### ISSUE THREAD

**Issue by wjwaldron** [CDrummond/lms-material#662]
I reported this on the forum, but thought it might be better to report here. For the past few months, I've been using the desktop layout on my PC . For various reasons, I find I prefer to use the mobile layout. After switching back to that layout, I find that in the "show track information" Album tab track listing, where the artist & composer should be shown , I get code starting with <obj class="link item"

![Screenshot 2023-03-15 094230](https://user-images.githubusercontent.com/4700100/225326882-af223e7e-6e90-4319-95af-9e692358c370.png)

This doesn't happen when I use the desktop layout. It also doesn't happen on my phone using the mobile layout with Material APK -- so it appears to be an issue with using the mobile layout on a non-touch device.

**Comment by CDrummond** [comment]
Thanks for reporting this here, makes it much less ikely to be overlooked! Is this the only place you see these errors? No errors in queue? No errors when browsing?

**Comment by wjwaldron** [comment]
No errors elsewhere. Tracks display properly when browsing and when in the queue.
