### ISSUE TITLE
> I have the same issue with my iPad running iOS 12.5.7.

### ISSUE THREAD

**Issue by kjwop** [CDrummond/lms-material#663]
> I have the same issue with my iPad running iOS 12.5.7.
> Version 3.2.0 (with "Application" visible in the Settings menu) worked fine, but after installing 3.2.1 the queue and the "now playing" bar disappeared. "Now playing" is visible only in the Expanded Now Playing view.

I read on slimdevices forum that u can fix this issue on iPads simply deleting cache and deleting icon LMS on home board .

_Originally posted by @Jerry87878787 in https://github.com/CDrummond/lms-material/issues/661#issuecomment-1472710402_

**Comment by CDrummond** [comment]
Please do not open new issues for an existing issue!
