### ISSUE TITLE
Server Settings Password

### ISSUE THREAD

**Issue by moritz-hoelting** [CDrummond/lms-material#665]
I've set a server settings password and now the button to view server settings is gone. Where can I enter my password to show the button again?

**Comment by CDrummond** [comment]
In Material's Interface settings you should find a field to enter the password - this field is only shown if the server-side has a password.

Also, please note this site is for bugs/features, and is not a support site. Please use the Material thread on the slimdevices forum for support queries (as others mat also be able to help). https://forums.slimdevices.com/forum/user-forums/3rd-party-software/106269-announce-material-skin
