### ISSUE TITLE
Clear upcoming - feature request

### ISSUE THREAD

**Issue by COlklei** [CDrummond/lms-material#675]
Is it possible to include a 'clear upcoming' onto the queue page? At the moment there is only the clear queue button and this also stops the currently played title.

**Comment by CDrummond** [comment]
Re-opening as whilst feature is done I'm not 100% sure on when/how to show these options.

**Comment by CDrummond** [comment]
Decided to always show all actions, but dim unusable ones (e.g. 'Remove upcoming tracks' when current track is last)
