### ISSUE TITLE
Unable to toggle Alarm Enable

### ISSUE THREAD

**Issue by patman62** [CDrummond/lms-material#681]
Sometime recently the alarm enable toggle stopped working in the Material Skin - it looks like it toggles but it doesn't stick, leave the player setting and come back and it's still on its previous setting. It works on the default skin. I think it stopped working at the same time the toggle UI element changed appearance.

**Comment by hctom** [comment]
I think this is still broken in 3.3.3. When using the toggle for all alarms, its state does not seem to be saved correctly and opening the player settings again, has the toggle back in its old position. Default skin still allows to toggle all alarms without problems.

**Comment by CDrummond** [comment]
This has already been noted in the LMS forums, and is fixed fore next release.

**Comment by hctom** [comment]
Sorry for the late reply - that sounds perfect and thank you for all your hard work!
