### ISSUE TITLE
Unable to show artists pictures or other covers online 

### ISSUE THREAD

**Issue by Jerry87878787** [CDrummond/lms-material#685]
Hi Craig , on web os LG smart tv , when we try to find or show additional pictures or albums cover from step routing : more – artist information –pictures ….

 system find pictures online from discogs; all music; or more but we can’t seeing .

Same things happens with small artwork on Youtube ( I’m leaving pictures for better explanation)

 

On IOS devices or Pc there is no issue .
I post only a screen 

![IMG_6751](https://github.com/CDrummond/lms-material/assets/127791502/2b27d12d-b8d8-48db-a79f-422129b5a75e)
![IMG_6752](https://github.com/CDrummond/lms-material/assets/127791502/85612f21-152c-460b-b893-8c4034597c6e)
![IMG_6753](https://github.com/CDrummond/lms-material/assets/127791502/f7a29930-26d0-4822-a62c-9e39c7cd640f)
![IMG_6750](https://github.com/CDrummond/lms-material/assets/127791502/1beca7bf-68c2-4c54-b981-2c00efaecd9e)
![IMG_6754](https://github.com/CDrummond/lms-material/assets/127791502/56599259-12eb-4fee-881d-f8d2e9f55b1e)

On release 3.2.3 everythings was  good on alls devices

**Comment by Jerry87878787** [comment]
YouTube had reversed issue 
![IMG_6755](https://github.com/CDrummond/lms-material/assets/127791502/0c047918-7ffc-41d3-86bc-eccec0a175d5)


Thx for your kindly support

**Comment by CDrummond** [comment]
No updates, looks like a browser issue, so closing.
