### ISSUE TITLE
Party Modus play next

### ISSUE THREAD

**Issue by daemmi** [CDrummond/lms-material#689]
Hey,

Is it possible to deactivate in party modus to deactivate that someone can add a song to play next? I think that was so in a version before. It would be nice to have it back.

All the best
Jonas

**Comment by CDrummond** [comment]
Sorry, I'm unsure what you are asking for. Is it to _remove_ "Play next" ? i.e. so that songs can _only_ be appended to the queue?

**Comment by daemmi** [comment]
Exactly. I thought that was so already when you implemented the party modus.
