### ISSUE TITLE
Add a service worker

### ISSUE THREAD

**Issue by cbonnissent** [CDrummond/lms-material#69]
Add a [service worker](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker) for the assets so the page can be considered like a PWA and installed on android.

**Comment by CDrummond** [comment]
Sorry, but I'm not sure I see the benefit. The code cannot work offline, as it needs to connect to the server. And you can already 'Add to homescreen' So, what benefit does this provide?

Also, I have no idea how to add one of these, what it should do, etc.

**Comment by CDrummond** [comment]
According to https://developers.google.com/web/fundamentals/primers/service-workers/ serviceworkers need to be served over HTTPS, LMS is HTTP.

**Comment by CDrummond** [comment]
I would be more than happy to have a serviceworker - I just have no idea how to create or use one. I'm not a web-developer, and most of this is new to me. I'm very much learning as I go along (never used the Vue.js framework before this).

**Comment by mavit** [comment]
> And you can already 'Add to homescreen' So, what benefit does this provide?

With Chrome for Android, if a site qualifies as an installable app, you'll get an icon in the launcher rather than simply on the home screen.  With Chrome for desktop, if a site qualifies, a "⊕" icon appears in the URL bar which you can click on to get the same.

**Comment by CDrummond** [comment]
And site needs to be served over HTTPS. LMS is not HTTPS, so this would fail anyway,
