### ISSUE TITLE
If selected player is part of a synced group can the main volume slider control the volume of all member in the group relatively?

### ISSUE THREAD

**Issue by ronluna** [CDrummond/lms-material#690]
if the selected player is member of a synced group iPeng (iOS app) by default uses the volume slider to control the volume of all the players in that group (relatively). this comes very handy and I was wondering if a similar option could be implemented?

**Comment by CDrummond** [comment]
I think what you want is to use the group player plugin.

**Comment by ronluna** [comment]
The group player plugin requires to create predefined "group players" causing a longer player list and possibly adding confusing to unfamiliar users. I suggested iPeng as the group volume control in this app is done dynamically and based on members that have joined a synced group. This help keeping the interface cleaner and reducing possible confusion.  

Some LMS could have 7 , 10 or even more players and being able to control the volume with a single slider for all the player in a synced group is very helpful.

**Comment by ronluna** [comment]
Similar to this:


https://github.com/CDrummond/lms-material/assets/9822111/f4c238d3-415d-430c-861e-f72914d65d04

**Comment by CDrummond** [comment]
Whave I've currently implemented is:

1. A toggle button bottom-left of the sync-group player volume dialog. When enabled all volume changes are applied to all members.
2. Likewise added a 'Synchronise volumes' option to the menu (top right) of the manage players dialog

Didn't really want to add a furhter volume slider, so this seemed like a reasonable compromise.

**Comment by CDrummond** [comment]
Remove synchronised volume changes. Added a 'Group Average' slider at the top of the group-volume dialog:

![image](https://github.com/CDrummond/lms-material/assets/1141694/b633da00-a2fd-477c-8ddb-8fcd90ec1825)

When adjusting volumes by this the group members are adjusted relatively.

Not sure about the header 'Group Average' - suggestions welcome!

**Comment by ronluna** [comment]
This is indeed very clever... just tested it! 
Brilliant!!!

Thank you!!!

**Comment by CDrummond** [comment]
Closing, as done for 3.4.0
