### ISSUE TITLE
Feature Request / Idea: Album contains additional artwork 

### ISSUE THREAD

**Issue by benjamindaines** [CDrummond/lms-material#692]
Currently there is not any kind of obvious indication that a local album has additional artwork (such as booklet scans, etc), one has to go to the "More Info" page and then select "Local Artwork."  It would be great if there was a little overlay icon (or the option to have an overlay icon) on the album cover while browsing to indicate that there are additional images within a subfolder (such as "scans," "artwork," "pdf," etc).  Perhaps a little booklet icon or something along those lines.  

I know that would greatly improve my user experience, and I'm sure plenty of other would appreciate it as well :) 

Thank you for your consideration & thanks for creating such a great UI that really brings LMS into the 21st century.

**Comment by CDrummond** [comment]
Sorry, but the LMS API provides no way of knowing this when requsting a list of albums. I could make a request for each album, but that would be slow if there are many albums. So, for now, this is a no-go. LMS itself would need to be updated to allow for this.

When listing an albums tracks material shows a "..." icon in the toolbar, if there are local files for an album then a "Show local files" (or some such entry) should be disaplyed. This is only for text, PDF, etc, and does not work for artwork - I asked on the slimdevices forms for this, and supplied Michael with a patch for MAI that did this, but don't think he ever merged it.

**Comment by benjamindaines** [comment]
Bummer. Thanks for the reply
