### ISSUE TITLE
Play Album Starting At Track

### ISSUE THREAD

**Issue by d4n3ll** [CDrummond/lms-material#693]
This function does not seem to work correctly for multi-disc albums. Instead, my system queues the first 2500 tracks in my database, (sorted alphabetically by title and plays that list from the position of the track originally selected). FWIW the Play Album Starting At Track function works perfectly for single disc albums. The Play Disc Starting At Track function works perfectly for multi-disc albums.

Material Skin 3.3.5
Bowser Chrome on Win 10.
LMS 8.3.1 running on RPi v 4.

**Comment by CDrummond** [comment]
Hmmm... Works for me, but I'm using a pre-release version. Please Use Material's JSON debug to see what message is sent when you "Play album starting at track". To do this:

1. Use URL: http :// SERVER:9000/material/?debug=json
2. Open your browsers developer tools
3. Navigate in Material to the album you want to play
4. Clear all messages from the Console tab of your developer tools
5. Use the "Play Album Starting At Track"
6. In the Console tab you should see some "REQ" entries - these are the messages sent to LMS. Please add these to this ticket.

**Comment by d4n3ll** [comment]
Hi

I wasn’t sure where I should save the log from, so FWIW this starts from selecting the album, then the second disc, then the third track, then it loads 2500 tracks from the top of the alphabetical list and starts playing the third track.

FWIW this is not isolated to one browser or one LMS server. I get the same behaviour using Safari on my iPhone. And I have two completely separate servers, both RPi4s running the same versions of LMS and Material and I get exactly the same behaviour off both.

Many thanks

D

PS am I allowed to make a sneaky feature request? Material is absolutely brilliant. The disc title facility is doubly brilliant. Might it be possible to have an option to display the disc title in the now playing window?

Sent from Mail for Windows

**Comment by d4n3ll** [comment]
Hello again

I thought I’d send a log starting just at the moment I press play album starting from track., in case that helps.

D



Sent from Mail for Windows

**Comment by CDrummond** [comment]
All I need is the REQ message sent when you add tracks - not the responses from LMS. I need to confirm if what is sent is OK or not.

**Comment by d4n3ll** [comment]
Hi CraigI’m not very techy I’m afraid. From your reply I’m not sure if you got what you needed. D
    	Dan ***@***.***+447880795699
    
  

 From: CraigD ***@***.***>Sent: Tuesday, August 15, 2023 10:18 amTo: CDrummond/lms-material ***@***.***>Cc: d4n3ll ***@***.***>; Author ***@***.***>Subject: Re: [CDrummond/lms-material] Play Album Starting At Track (Issue #693) 
All I need is the REQ message sent when you add tracks - not the responses from LMS. I need to confirm if what is sent is OK or not.

**Comment by CDrummond** [comment]
There was no log attached to the email.

**Comment by d4n3ll** [comment]
That’s bizarre. There really was. Will send again later. Sorry. D
    	Dan ***@***.***+447880795699
    
  

 From: CraigD ***@***.***>Sent: Tuesday, August 15, 2023 1:44 pmTo: CDrummond/lms-material ***@***.***>Cc: d4n3ll ***@***.***>; Author ***@***.***>Subject: Re: [CDrummond/lms-material] Play Album Starting At Track (Issue #693) 
There was no log attached to the email.

**Comment by d4n3ll** [comment]
Craig. The log was included as an attachment. It’s on my phone which I did not use to send originally. I’ve also posted the opening bit of the log below. Is this what you need? You can see it queuing up the wrong tracks Sorry for the trouble. Dmaterial.minjs?r=3.3.5:244 [10:12:04] JSON REQ: ["00:04:20:23:63:84",["playlistcontrol","cmd:load","filter:2","play_index:2"]]
material.min.js?r=3.3.5:244 [10:12:30] JSON RESP: {"id":0,"method":"slim.request","params":["00:04:20:23:63:84",["playlistcontrol","cmd:load","filter:2","play_index:2"]],"result":{"count":93504}}
material.min.js?r=3.3.5:244 [10:12:30] JSON UPDATING (00:04:20:23:63:84)
material.min.js?r=3.3.5:244 [10:12:30] JSON REQ: ["00:04:20:23:63:84",["status","-",1,"tags:cdegiloqrstuyAABGIKNSTk"]]
material.min.js?r=3.3.5:244 [10:12:30] JSON PLAYER (00:04:20:23:63:84): {"playlist mode":"off","player_name":"Office","signalstrength":0,"playlist repeat":0,"playlist_cur_index":"2","playlist_loop":[{"trackartist_ids":"939965","albumartist":"Brian Eno","artist_id":"939965","comment":"flac only","genres":"Popular","id":13597079,"album":"Ambient 1: Music For Airports","albumartist_ids":"939965","trackartist":"Brian Eno","type":"flc","url":"file:///mnt/music/Music%20Server/Lossless/Popular/Brian%20Eno/1978a%20-%20Ambient%201,%20Music%20for%20Airports/01%20-%2011.flac","album_id":"1065018","samplesize":"16","title":"1/1","year":"1978","coverid":"917d965f","bitrate":"508kbps VBR","duration
    	Dan ***@***.***+447880795699
    
  

 From: Dan Elliott ***@***.***>Sent: Tuesday, August 15, 2023 10:17 amTo: CDrummond/lms-material ***@***.***>; CDrummond/lms-material ***@***.***>Cc: Author ***@***.***>Subject: RE: [CDrummond/lms-material] Play Album Starting At Track (Issue#693) Hello again I thought I’d send a log starting just at the moment I press play album starting from track., in case that helps. D   Sent from Mail for Windows From: CraigDSent: 14 August 2023 13:00To: CDrummond/lms-materialCc: d4n3ll; AuthorSubject: Re: [CDrummond/lms-material] Play Album Starting At Track (Issue#693) Hmmm... Works for me, but I'm using a pre-release version. Please Use Material's JSON debug to see what message is sent when you "Play album starting at track". To do this:Use URL: http :// SERVER:9000/material/?debug=jsonOpen your browsers developer toolsNavigate in Material to the album you want to playClear all messages from the Console tab of your developer toolsUse the "Play Album Starting At Track"In the Console tab you should see some "REQ" entries - these are the messages sent to LMS. Please add these to this ticket.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by d4n3ll** [comment]
Yes that’s right. Fwiw as another feature suggestion it would be nice for the collapse if more than … option had a flexible rather than a fixed (200) threshold or even the choice of collapse based on number of discs rather than tracks. Just thoughts. Material is brilliant and I’m really grateful for it in any form. ThanksD
    	Dan ***@***.***+447880795699
    
  

 From: CraigD ***@***.***>Sent: Tuesday, August 15, 2023 4:11 pmTo: CDrummond/lms-material ***@***.***>Cc: d4n3ll ***@***.***>; Author ***@***.***>Subject: Re: [CDrummond/lms-material] Play Album Starting At Track (Issue #693) 
Thanks for this. The following line is the issue:
JSON REQ: ["00:04:20:23:63:84",["playlistcontrol","cmd:load","filter:2","play_index:2"]]

I've managed to recreate this by having Material "collapse" multi-disc albums. eg. Where each disc is first shown as a header which you need to click to then show the tracks of that disc. I take it this is how you have Material setup?
I'll fix this for the next release.

**Comment by CDrummond** [comment]
Well this disc collapsing is broken, so I'm going to remove it. It's not a feature I use, and there are too many work-arounds as is.

What I'm going to do is add a menu entry allowing you to jump to a particular disc.

**Comment by CDrummond** [comment]
As stated, disc collapsing removed - replaced with a menu entry allowing to scroll to a disc.
