### ISSUE TITLE
When clicking on "Help" under "Setting", the help page content is gray

### ISSUE THREAD

**Issue by worsco** [CDrummond/lms-material#694]
The Help page is difficult to read. Material version is 3.4.0.  Browsers tested and same experience on all three: Chrome, Firefox, Vivaldi.  Unknown when this bug was introduced.

![image](https://github.com/CDrummond/lms-material/assets/4623488/75af59a8-5bc6-4e59-bbbb-70f1b6647c09)

**Comment by worsco** [comment]
Theme setting is Adwaita Dark

**Comment by worsco** [comment]
I don't know if this is related.  I turned on Firefox developer tools (F12) and I see:

![image](https://github.com/CDrummond/lms-material/assets/4623488/627191af-55d9-450a-86a1-d668cc83ca97)

**Comment by CDrummond** [comment]
Thanks for reporting. I never spotted as I'm running un-minimized dev versions. Just tried with the released version and I could see the issue. Fixed the build script so this should no longer happen. Fix will be in 3.4.1

**Comment by worsco** [comment]
Thank you, your coding efforts are much appreciated!!!  I've donated previously and will donate again!
