### ISSUE TITLE
Help translations

### ISSUE THREAD

**Issue by jwchen119** [CDrummond/lms-material#698]
Hi,

I would like to impelement a new language "zh-TW" for Traditional Chinese, but it is not an option on Material Skin.
How to add the new language to the path "MaterialSkin/HTML/material/html/lang/zh-TW.json" ?
Please let me know the files I need to edit, thanks.

**Comment by CDrummond** [comment]
Thanks for the offer - much appreciated. I've just written a wiki page which hopefully makes the steps for adding a new translation clearer. Please see https://github.com/CDrummond/lms-material/wiki/15-Translations

As you are adding "zh-TW" I don't think LMS natively supports this, so you will probably also need to update LMS itself.

For Material's JSON files, these are all lowercase, so this would be "MaterialSkin/HTML/material/html/lang/zh-tw.json"

**Comment by jwchen119** [comment]
> I don't think LMS natively supports this, so you will probably also need to update LMS itself.

Yes, I've raised an issue on slimserver to impelement the new language.
And thanks for your help, I'll submit PR after the translation is done.

**Comment by CDrummond** [comment]
OK, will close. Pleas let me know if the instructions I posted are unclear, incorrect, missing steps, etc.
