### ISSUE TITLE
Enhancement - Overlay when scrolling 

### ISSUE THREAD

**Issue by sanc909** [CDrummond/lms-material#70]
Hi 

Firstly many thanks for creating this skin. It's great. I've been using and have created a simple overlay that displayed when scrolling multi-page lists.  On the desktop skin it overlays the first letter of the item at the top of the screen.  

It's not yet  perfect  (I'm new to vuejs so there are probably other ways to do this) - but if you're interested there's a short clip of it - click the image and it should play.

[<a href="http://www.youtube.com/watch?feature=player_embedded&v=D1OQskOw6XM
" target="_blank"><img src="http://img.youtube.com/vi/D1OQskOw6XM/0.jpg" 
alt="Click to Play" width="240" height="180" border="10" /></a>](url)

Have managed to get it to work with the light and dark skins. Could be amended to show, for example the  album cover, but I went with simple letter to start with.   

Thanks 
San

**Comment by CDrummond** [comment]
Wow! Looks great :-) I look forward to the pull request :-)

**Comment by CDrummond** [comment]
I'll close this, seeing as you closed the pull request.
