### ISSUE TITLE
[Feature Request] Dynamic Search

### ISSUE THREAD

**Issue by NSP-0123456** [CDrummond/lms-material#704]
Could it be possible to have a filtered view or a search function on each panel takimg more than a single character.
When i browse my music folder  I have thousands of entry, i would like to be able to filter/search with an input field.
Search is a goto to first matching entry, F3 key or a next button option in ui  go to next entrry.
Filtering only show matching entries.

**Comment by CDrummond** [comment]
I'll think about adding a filter action for 3.5.0

**Comment by NSP-0123456** [comment]
I will wait, it will be great with Squeezelite-X :)

**Comment by CDrummond** [comment]
Why did you close this? Nothing has been done yet.

**Comment by NSP-0123456** [comment]
Sorry Graig. As it was taken into account (put in back,log for 3.5.0 ) and it is not a bug i closed the feature request.

**Comment by CDrummond** [comment]
Sorry, but this probably won't be in 3.5.0. I can see the use-case of the feature, just not sure where to place it. Screen real-estate is cramped on a mobile device, and there's already a few buttons.

**Comment by NSP-0123456** [comment]
yYu do not need any new button, just change behavior when hitting key or clicking letters. Add an option to enable it and instead of searching only one letter at the time refine with additional letter. Reset search or filter when hitting escape or a clicking a reset letter.

**Comment by CDrummond** [comment]
Hitting what key? What letters?

So, you are referring to the existing search field? This is already dynamic - the input is 'debounced' so searches are not performed immediately.

**Comment by NSP-0123456** [comment]
I'm mainly using the interface with Squeezelite-X on laptop, and also in list mode from Music Folder. 
The Key are the keyboard letters reacting like clicking on the letters shown at left in Music Folders. (like in picture)
![Squeezelite-MusicFolder](https://github.com/CDrummond/lms-material/assets/2108244/e9a9bcbb-9041-407c-9115-d3b2f76c7f4a)

**Comment by CDrummond** [comment]
Right, so some sort of text field, and therefore button to open, would be required. 

What's more concerning is that your jump list (the numbers/letters down the side) has repeated entries.

**Comment by CDrummond** [comment]
Closing as not something I have a personal need for, so have no time/enthusiasm to implement.

**Comment by CDrummond** [comment]
FYI, 4.2.0 will add a search-in-list action to allow searching for items in current list.
