### ISSUE TITLE
playback progress meter bug

### ISSUE THREAD

**Issue by nmcbennett** [CDrummond/lms-material#712]
I'm not sure what the playback time meter bar thing is called but there is a bug. If you have a track playing and say near the end you decide you want to hear a bit of the track again so you place the cursor a bit further back the timing is all out. It thinks the track has ended but it's still playing. i.e. the progress bar no longer reflects where we are in the track. It does also seem that if you select a particular time, for instance 3 minutes 47 seconds into the track it doesn't actually go to that point but instead randomly starts from some point in the track. 
Sorry this is hard to explain but it's a bug however I'm not sure if the bug is with Material Skin or elsewhere

![Screenshot 2023-09-06 at 20 30 46](https://github.com/CDrummond/lms-material/assets/36637276/e878d0df-fe36-425f-b985-adb25e1cbd1f)

Thanks
Neil

**Comment by CDrummond** [comment]
Sorry, just tried and Material is working fine - I can click anywhere and the song is changed to that position. Tried multiple positions with multiple tracks.

**Comment by nmcbennett** [comment]
Hi
Thank for looking. It must be something else that is causing it. I
wonder is this browser dependant. I'll try a few browsers to see if it
makes a difference.

Regards

Neil

**Comment by nmcbennett** [comment]
I just tried another browser and the same issue is there.
Basically to reproduce it you start a track and then click the moue near to
the end of the track like 5 or 10 seconds from the end.

Do this a few times and vary the exact place and sometimes it will go to
the correct place and other times it seems to be playing from the beginning
or near the beginning. I guess most people don't do this type of thing but
I'm a musician and often I might want to hear a section again over and over
to work something out.

I did make a video of it on my phone but it was way too large to email. Not
to worry if you can't reproduce it at your end. I may have some other issue
on my computer which is causing it.

Other than that - a fantastic piece of software and thank you very much!

Neil
