### ISSUE TITLE
[Feature Request] Display Lyrics on the Now Playing panel

### ISSUE THREAD

**Issue by fnavarro78** [CDrummond/lms-material#714]
I'm currently using Material Skin on the PiCorePlayer interface v3.4.4 and have installed the Music and Artis Information plugin.
Would be nice to have the ability to display current song's lyrics on the Now Playing area as an alternate or additional view for the current song information panel.
![image](https://github.com/CDrummond/lms-material/assets/73562748/92f915f0-26ee-44ee-8b50-175cb6f0338e)

**Comment by CDrummond** [comment]
Sorry, there is insufficient space - and lyrics are context info that is shown with the other info.
