### ISSUE TITLE
Enable browser's Ctrl-f (find) feature

### ISSUE THREAD

**Issue by maidentaiwan** [CDrummond/lms-material#715]
When using the Material skin in Google Chrome on Linux, the browser's "Find" function (typically Ctrl-f) seems to be disabled. It would be helpful to use this standard browser feature to search for text on the page. For example, if 100 album titles are displayed on the page, Ctrl-f would let you jump directly to a title of interest. Thank you for considering this request.

**Comment by CDrummond** [comment]
Ctrl-F is used to invoke the main material search.

**Comment by maidentaiwan** [comment]
I see this issue is closed so I'll open a separate one.
