### ISSUE TITLE
Permit searching from any page

### ISSUE THREAD

**Issue by maidentaiwan** [CDrummond/lms-material#716]
Many pages in the Material skin do not display a search icon (in Google Chrome on Linux). Examples are:

- Viewing the Albums page (Home > My Music > Albums)
- Viewing the tracks of any album

When you're on one of these pages, you can't search. You have to navigate through the UI to reach a page that has a search icon. This feels unnatural in a modern application.

Would it be possible to have a search icon always available?

Thank you.

**Comment by CDrummond** [comment]
Duplicate of #623
