### ISSUE TITLE
Let the user choose the functionality of ctrl-F

### ISSUE THREAD

**Issue by maidentaiwan** [CDrummond/lms-material#717]
The material search keystroke ctrl-F does nothing on almost every material page, because almost every material page lacks a search box. That is an unexpected user experience. (See #715 for context.)

Would you consider creating a Material setting that lets the user choose the functionality for ctrl-F: browser search vs. material search? Or perhaps a setting to choose the keystroke for material search (say, ctrl-F vs. F3) to allow standard browser search to work?

Thank you very much.

**Comment by CDrummond** [comment]
No - that's madness. Just disable all shortcuts.

**Comment by maidentaiwan** [comment]
Thank you for the suggestion.
