### ISSUE TITLE
[Documentation] Doc string for "Show home button" on  Settings>Interface page should mention Home key

### ISSUE THREAD

**Issue by maidentaiwan** [CDrummond/lms-material#720]
On the Interface Settings page, the doc string for "Show home button" says:

> When navigating into lists, show a home button to quickly navigate to the main (home) screen. Otherwise navigating home can be achieved via a long-press on the back button.

Please update the last sentence to say:

> Otherwise navigating home can be achieved via a long-press on the back button, or on full keyboards, by pressing the Home key.

**Comment by CDrummond** [comment]
Keyboard shortcuts are documented via the "(?)" icon next to their setting text. Shortcuts are only for desktop browsers, so todo what you want would require 2 versions of (almost) the same string (one with shortcut, one without) - increasing the amount of text to be translated.
