### ISSUE TITLE
Now playing cover not showing for favorites with local images

### ISSUE THREAD

**Issue by SaschaRH** [CDrummond/lms-material#721]
Hi,

I have some favorites with PNG covers but since the last update today they're not showing up in the now playing tab.

"Convert all now-playing PNG covers to JPG (if rounding covers)." might has something to do with it?!

Any ideas?

Thank you!
Sascha

**Comment by CDrummond** [comment]
Hmmm.. This was no doubt due to my attempt to fix another issue. Anyhow, I have removed the PNG->JPG conversion for 3.5.0, so will be fixed then.

**Comment by CDrummond** [comment]
Closing as fixed for 3.5.0
