### ISSUE TITLE
Link to original LMS help material in UI

### ISSUE THREAD

**Issue by maidentaiwan** [CDrummond/lms-material#723]
Is there a way to navigate within Material Skin to the original LMS help docs, found at http://localhost:9000/home.html?page=help? This page leads to all kinds of interesting docs like these:

http://localhost:9000/html/docs/index.html

The default LMS UI had a "Help" link that leads to this content. If there is a link or menu item in Material Skin, I can't find it. (And if there isn't one, could it please be added?) Thank you very much.

**Comment by CDrummond** [comment]
Already there in Material's "Information" dialog - look for "LMS technical information" at the bottom.

**Comment by maidentaiwan** [comment]
Thank you! I missed it.
