### ISSUE TITLE
Clicking "3rd-Party-Software" link on Information page produces broken page

### ISSUE THREAD

**Issue by maidentaiwan** [CDrummond/lms-material#724]
The following steps cause Material to show an error page.

1. Assume Material is running at http://localhost:9000
2. Visit the Information page
3. Near the bottom, click "LMS technical information"
4. Click the first link, "Artwork Setup"
5. Under "Useful plugins," click the link "3rd-Party-Software" which links to http://forums.slimdevices.com/forumdisplay.php?4-3rd-Party-Software
6. A new tab opens and loads the preceding page from forums.slimdevices.com. This is correct behavior.
7. Return to the original browser tab for Material. The URL is still http://localhost:9000, but the browser is now displaying an error page.

Reproduced in both Chrome and Firefox on Linux (see screenshots).

![chrome](https://github.com/CDrummond/lms-material/assets/4689691/5d8b3e3e-a90d-4b81-a957-ccb25c953721)
![firefox](https://github.com/CDrummond/lms-material/assets/4689691/4029268c-094a-4481-87cd-ff54f5011e76)

**Comment by CDrummond** [comment]
Fixed for 3.5.0

**Comment by maidentaiwan** [comment]
Thanks for such a quick fix.
