### ISSUE TITLE
Automatic light/dark switch

### ISSUE THREAD

**Issue by eengnr** [CDrummond/lms-material#730]
Hi!

I really like the Material theme and use it with your LMS web app.
Would it be possible to support automatic dark/light theme based on the current system setting of Android 13?
I tried to achieve this with a custom css in the colors or theme folder with `@media (prefers-color-scheme: dark)`, but this only partly worked in Chrome - not in the LMS app. Perhaps the app needs to be adapted as well?

It would be nice if automatic light/dark could be activated and two themes (e.g. "light" and "darker" could be selected).

**Comment by CDrummond** [comment]
There is a pull request for this, but its not finished. I may add for a future release.

**Comment by Atmis** [comment]
I came this morning to request that enhancement, and just saw that issue open. Great minds think alike 😀
Looking forward for this implementation!
And of course, as a daily LMS and Material Skin user, I want to thanks Craig for his hard work.

**Comment by CDrummond** [comment]
Implemented in `dev` branch for next non-bugfix release.
