### ISSUE TITLE
Adding stream URLs

### ISSUE THREAD

**Issue by tsengf** [CDrummond/lms-material#737]
Hi, when I use the default skin for LMS, there is an option "Tune in URL" under Radio. This option does not exist when using the material skin. Can this be supported? Thanks.

**Comment by CDrummond** [comment]
Already implemented. Use "..." button in queue view, select "Add URL to queue"

**Comment by tsengf** [comment]
This works. I want to pin streams as favorites. It's a bit roundabout but I can accomplish this. Thanks.

**Comment by tsengf** [comment]
Thank you.
