### ISSUE TITLE
Play Now modal for multi-disc

### ISSUE THREAD

**Issue by kerneljake** [CDrummond/lms-material#741]
I have a 3-CD set which I have tagged so that the album titles are different since the concert dates are different.  When I click on the Play Now icon, I see CSS in the dialog, and it offers to play all discs.

![screenshot](https://github.com/CDrummond/lms-material/assets/6081489/eeb5e899-0c1c-4104-8431-8fd1196da215)

```
    comment[0]: ALBUM=Solo Concerts  Bremen CD 1
    comment[1]: ALBUMARTIST=Keith Jarrett
    comment[2]: Composer=Keith Jarrett
    comment[3]: Comment=redacted
    comment[4]: Rating=5
    comment[5]: ARTIST=Keith Jarrett
    comment[6]: TITLE=Bremen, July  12, 1973 Part I
    comment[7]: Date=1973
    comment[8]: TRACKNUMBER=01
    comment[9]: GENRE=Jazz
    comment[10]: DISCNUMBER=1
    comment[11]: DISCTOTAL=3
```
```
    comment[0]: ALBUM=Solo Concerts: Lausanne CD 2
    comment[1]: Composer=Keith Jarrett
    comment[2]: Comment=redacted
    comment[3]: Rating=5
    comment[4]: ARTIST=Keith Jarrett
    comment[5]: TITLE=Lausanne, March 20, 1973
    comment[6]: Date=1973
    comment[7]: TRACKNUMBER=01
    comment[8]: GENRE=Jazz
    comment[9]: ALBUMARTIST=Keith Jarrett
    comment[10]: DISCNUMBER=2
    comment[11]: DISCTOTAL=3
```

This may fall into the realm of "user error" since I'm responsible for tagging things in this manner.  I have other multi-disc sets that do not exhibit this behavior because they are studio albums and share the same ALBUM.

Seen on macOS 13.6 (22G120) and Firefox 118.0.1.

**Comment by CDrummond** [comment]
Whilst there is an error in Material's code (now fixed for next release), there is also an issue with your tags.

As all your disc have a different ALBUM tag, then Material thinks each is an album (so discs are not grouped). But LMS tells Material this 'disccount' for each is more than 1, so Material shows its multi-disc emblem and produces the dialog that you see. But this dialog will only allow choosing of 1 disc, as that is all there is per ALBUM-tag.
