### ISSUE TITLE
Artist name does not appear in MacOS High Sierra

### ISSUE THREAD

**Issue by kjwop** [CDrummond/lms-material#743]
Hi Craig,
After upgrading from Material Skin 3.5.0 to Material Skin 3.5.4, the artist name no longer appears when an album is selected in the browse area. This happens only on my MacBookPro using MacOS 10.13. Material Skin 3.5.4 works fine on my iPad using iOS 12.5.7.
Hope this could be resolved.
Thanks for all your work on Material Skin!!

MacOS 10.13
![MacOs 10 13 High Sierra Screen Shot 2023-10-10](https://github.com/CDrummond/lms-material/assets/128090033/87488bee-7ebf-4bb0-910f-9d689c96be35)

iOS 12.5.7
![iOS 12 5 7 Screen Shot 2023-10-10](https://github.com/CDrummond/lms-material/assets/128090033/c782a5b1-8baa-4709-8ecd-cbedf4c98785)

**Comment by CDrummond** [comment]
The name in fact should not appear unless its different, so in this case macOS is correct. Sorry, but as you can see the code does work. Why its different between your systems I do not know. Not a mac or iOS person, so can't check. But there is no issue on any of my systems, and no other users have reported issues. So, looks like some setup/cache issue on your system.
