### ISSUE TITLE
MediaSession / Media Control - If paused when laptop put to sleep, music starts playing

### ISSUE THREAD

**Issue by mgartin** [CDrummond/lms-material#749]
First off - thank you for this very nice skin!
I found it via the squeezebox forum when specifically searching for a skin with MediaSession support, in order to have the play/pause/prev/next buttons easily accessible from my desktop (I use Linux/KDE). 
And it works great for the most part!

However, when I close the lid of my laptop, it seems that "play-pause-toggle" is issued rather than "pause" or "stop" in this implementation.

Essentially: If I open a tab with http://<my-lms-server>/material/?layout=desktop and play music on one of my sqeezebox devices, eg. a radio, and then pause the music, it will start playing if I close the lid of my laptop (putting it to sleep).
Similarly, if I have the music playing, and close the lid, it will pause the music (this is probably what most people want).

But I don't want the music to start playing when I close the lid late at night.

So - I've read that the Media Control code is kind of hacky, and I don't expect anyone to spend much time on this, but could it be that we can replace "toggle" with "pause" or "stop" somewhere in the code? 

I don't think the problem is with KDE, but I cannot really verify, since all other applications that supports the Media Controls runs on the laptop itself, and naturally won't play if the laptop is put to sleep.

**Comment by CDrummond** [comment]
Closing, as there is nothing Material can do. The media-session support is very much a hack as it needs to play a silent ogg file in a loop, wasting CPU. But as stated the only "toggle" behaviour is on the "play" command. If KDE is sending "play" to "pause" then its obviously wrong - but as stated, Material will "pause" if "play" is sent whilst playing.
