### ISSUE TITLE
503 on Current Track info page

### ISSUE THREAD

**Issue by worsco** [CDrummond/lms-material#751]
Something changed in the Internet earlier today on the "Current Track" information page.  That page is consistently displaying "I'm sorry, didn't find any relevant information." in the Artist section and "Unknown error: 503 Service Unavailable" in the Album section.  

Where does Material pull the info for this page from?  Perhaps the upstream API provider is now blocking access?

**Comment by worsco** [comment]
Thinking that it might have been a logitechmediaserver version upgrade issue, I downgraded to:

Version: 8.4.0 - 1697090833 @ Thu 12 Oct 2023 08:43:49 AM CEST

But the issue is the same.

**Comment by CDrummond** [comment]
Material uses the "Music and artist information" plugin to provide these details. There's currently an issue with this and all music. Please see the lms forums for more details. So this is not an issue with this skin.

**Comment by worsco** [comment]
Link to the LMS forum conversation:

https://forums.slimdevices.com/forum/user-forums/3rd-party-software/96425-announce-music-artist-information-plugin/page138
