### ISSUE TITLE
MAI Album Review header

### ISSUE THREAD

**Issue by wjwaldron** [CDrummond/lms-material#752]
More of a request than an issue...

I just updated to the latest dev version. I see in the changelog:
43. Strip headers from MAI text, as duplicates own headers.

Could I ask that you consider *not* stripping the name of the reviewer? I find this to be useful information, as I have come to respect the opinions of some AllMusic reviewers much more than others. After Michael fixed MAI for the AllMusic changes, it was so nice to have this back again, if only for a few days :)

Thanks as always!

**Comment by CDrummond** [comment]
This has already been changed.

**Comment by wjwaldron** [comment]
You remain the man. Thanks as always.
