### ISSUE TITLE
Player setting not saved

### ISSUE THREAD

**Issue by StillNotWorking** [CDrummond/lms-material#759]
On first page for Player Setting it seems none of the settings are saved. Smart Gain, Don't Stop the Music etc. There are no dedicated save button either for this page.

Settings are confirmed to be saved from the Classic GUI.

Material Skin 3.5.6
LMS is running on latest RPi-OS Lite 64-bit
Brower is Firefox 119 on Win10

**Comment by CDrummond** [comment]
I'm sorry, but settings are saved - I have just checked to confirm. There is no "Save settings" as they are saved when the back ("<-") button is pressed.
