### ISSUE TITLE
Better ability to rate (local) Spotify songs

### ISSUE THREAD

**Issue by ma3d1um** [CDrummond/lms-material#762]
Would it be possible to flip a switch somewhere in the code, so that we can also rate Spotify songs easily in the Now Playing screen? (LMS supports the rating of "local" Spotify songs -- i.e. songs from Spotify albums that have been imported to the library with the Online Music Library Integration feature). 

When playing local songs 5 empty stars are displayed in the Now Playing area, with which one easily can apply a rating. But with Spotify songs these are omitted and there also isn't a rating option available in the three-dotted overflow menu. The only way is to search for the currently playing song...

**Comment by CDrummond** [comment]
Sorry, but Material does not directly support setting ratings - its all done via RatingsLight or TrackStat. If either of these support this then it should be possible. However, I do not use any streaming services so cannot check.
