### ISSUE TITLE
Hamburger menu and action buttons disappeared from Queue items in v4

### ISSUE THREAD

**Issue by uhhh-clem** [CDrummond/lms-material#768]
...can we have them back please, at least in the Desktop view?

The blank space is wasted, and the new UI takes an extra click to do anything.

**Comment by CDrummond** [comment]
Clicking on anywhere on the track is the **same** as the hamburger menu button. These buttons were removed as they were superfluous.

**Comment by uhhh-clem** [comment]
Superfluous is one way of putting it; "discoverable", "accessible" and "visually consistent" are other ways of looking at it.

Some would say the pushpin for hiding the Queue is superfluous since that function is also available on the header toolbar.

**Comment by CDrummond** [comment]
FYI, these buttons will be back in 4.0.2. This was after a user on the slimdevices forum posted a message about a usage scenario that this prevents. That's all you had to do, was explain what was missing, or what scenario was prevented.

**Comment by CDrummond** [comment]
@mherger  LMS is missing the following 2 translations:
```
       CS      Správa zásuvných modulů
       NL      Beheer Plug-ins
```
