### ISSUE TITLE
[Feature Request] - Render Ratings as a Liked/Disliked system

### ISSUE THREAD

**Issue by cirdanlunae** [CDrummond/lms-material#771]
It's hard to explain what I mean, so I made a mockup. Many streaming services have a simple "Like"/"Dislike" system for songs. For users who don't care about granular control of ratings but care about "liking" songs, this is a nice feature. I think there could be a way to implement this without touching LMS's code.

[Current 5-star rated songs look like this](https://i.imgur.com/ZF66RXx.png)
[Current unrated songs look like this](https://i.imgur.com/njQyCGS.png)

[Here's a mockup of what I"m thinking using a "HEART" as the "like"](https://i.imgur.com/HV0U1yZ.png)
["Unliked" songs would look like this](https://i.imgur.com/sHBMVAf.png)

How this could be implemented:
-A setting that users could toggle, something like "Use LIKE/DISLIKE Ratings instead of stars"
-A secondary setting with the threshold of what is considered to be "LIKED" (for backwards compatibility for previously rated songs)

What would need to be done under the hood:
-When this setting is toggled, change how ratings are rendered as follows:
-Unrated: display as empty star
-Rated: display as a heart based on the THRESHOLD setting

I'm not sure if this is something that can be done, but I know that for a lot of people who are leaving streaming services that let you rank songs this way, it would be a welcome feature that could all be done skin-side.

**Comment by CDrummond** [comment]
Whilst I have no issue with this, I think it needs to be implemented in RatingsLight. e.g. as a quick rating. Then once the API is in there, I can add support for it. Then its not material-specific.

**Comment by CDrummond** [comment]
Also, one issue with a single heart is; what's the difference between un-set and disliked? You need at least 3 settings; disloked, unset, liked.

To be honest, this is not a feature I've ever seen the need for (and same goes for ratings). On my local system why would I have tracks I dont like? And sseeing as the system is multi-user, this again makes even less sense - as  what I like/dislike is different to other family members, making ratgings make even less sense.

When it comes to likin/unliking on a streaming service, then yes it makes more sense here. Their catalogue will contain a vast amount of items you do not lile. Also, your account is personal.

For this, and ratings, to make sense LMS needs to have the concept of users - which this late in the game I doubt it will ever have.

**Comment by CDrummond** [comment]
Closing, as this needs to be implemented as a like/dislike rating plugin. I Personally have no use for such a system, but would support if a plugin was made.
