### ISSUE TITLE
Player settings limited to general only

### ISSUE THREAD

**Issue by mcblacky** [CDrummond/lms-material#777]
Hi Craig,
Thanks for bringing us this nice skin for my beloved LMS server with picoreplayer. Please be informed that in your skin it is not possible to select the additional **player** settings other than the general page, since the pulldown menu is missing. As workaround I changed to the normal skin to change the settings I needed. It would be nice if this could be done from your (almost) perfect skin.

**Comment by CDrummond** [comment]
In "Player settings" either scroll to the bottom, or use the menu (top -right) and select "Extra player settings" - this willl then show the LMS settings. This theh has a menu for "Basis Settings", "Audio", "Synchronise", etc.

**Comment by mcblacky** [comment]
Thanks for the verry fast reply! Sorry for missing this one, expected the same as the server settings. A perfect skin after all.
