### ISSUE TITLE
Volume not working

### ISSUE THREAD

**Issue by jayo2005** [CDrummond/lms-material#781]
I have 2 Pi's setup but I cannot control the volume. I have picoreplayer setup on the rpi's and have them synced for volume but I have to go to the picoreplayer interface to adjust the volume. Cannot adjust from the LMS Material Gui

![2023-11-24_19-17-12](https://github.com/CDrummond/lms-material/assets/7015925/d4fc2ace-ba57-4c3b-b1db-c2c7debd0886)
![2023-11-24_19-22-01](https://github.com/CDrummond/lms-material/assets/7015925/0bf25663-f8ac-40d5-83e1-f08b026a8176)
Player settings also does not work. 

The volume slider is greyed out. If I adjust the volume from the picoreplayer it will reflect in LMS but I cant control the volume from LMS

**Comment by jayo2005** [comment]
Works on my mobile. Not my desktop

**Comment by CDrummond** [comment]
I have piCore setup and volume control works from both mobile and desktop - as they should its the same code.

Your first screenshot shows the control disabled this implies either; a) no player, b) player is set for fixed volume, or c) you are using party mode.
