### ISSUE TITLE
Various Artists album display behaviour for an artist in Material Skin vs. LMS

### ISSUE THREAD

**Issue by Supertramp1969** [CDrummond/lms-material#797]
Dear Craig,

I noticed a difference in behaviour between LMS and Material Skin with regards to the displaying of Various Artists albums for an Artist. 
When I click such an album in LMS it only shows the tracks of that particular Artist, where as in Material Skin all tracks of the album are shown meaning also the ones not for that particular Artist. 

Not sure if this is as intended?

Thanks,
Toine

**Comment by CDrummond** [comment]
There is a setting in material's server side settings (Server settings / Material Skin) to control this.

**Comment by Supertramp1969** [comment]
Oh, wow. Didn’t know these rich features.
Many thanks for your quick reply.
