### ISSUE TITLE
Interface setting "Draw background" appears twice in settings

### ISSUE THREAD

**Issue by maidentaiwan** [CDrummond/lms-material#799]
On the Interface Settings page, the setting "Draw background" appears twice -- once after "Show current date and time" and once at the very end of the list. This is in MaterialSkin 4.0.4 on Chrome Version 120.0.6099.71 (Official Build) (64-bit) on Linux.

![bug](https://github.com/CDrummond/lms-material/assets/4689691/6a1741d4-078f-4f22-aa74-d063bd9febbe)

**Comment by CDrummond** [comment]
That's because there's multiple options. These control background drawing on separate areas.

**Comment by maidentaiwan** [comment]
Ah, now I see the section headers "Now Playing" and "Queue". I didn't notice them before -- they don't stand out. Maybe make section headers a larger size or a different color? Just a thought.
