### ISSUE TITLE
INFO windows on LMS Material Skin config page can not be read

### ISSUE THREAD

**Issue by klslz** [CDrummond/lms-material#800]
"Play shuffled" and below "I" Info Windows on the LMS advanced settings MS cannot be looked at. These windows do open but but get cut off.

There's simply not enough space to fully open these info windows on my Chrome browser. 

I guess simply by adding a couple of empty lines at the bottom of that sheet will allow for scrolling further down,
which will solve the issue.

I just hit the issue when trying to have a look at the new "Play shuffled" help screen.

If you need more info let me know.

**Comment by CDrummond** [comment]
Ah, you mean the "i" windows on the "Default" skin? That's an issue with that skin - please report there.
