### ISSUE TITLE
Loupe for searching Deezer library

### ISSUE THREAD

**Issue by baerengraben** [CDrummond/lms-material#801]
I use lms-material with a touch panel (actually a Chomium Kiosk Mode). When searching my Deezer library, it is not possible to search via "touch" on the panel. When I perform the same search with the "LMS" app (downloaded via F-DROID), a loupe appears, which can be used to call up the "touch search".

I wonder why the loupe appears in the LMS app and not in a browser (Firefox, Chromium, etc.):

LMS-App:
![Screenshot_20231217-163350](https://github.com/CDrummond/lms-material/assets/9572444/d965fde1-d76d-45e9-a79c-31555bfa84b4)

Browser:
![Screenshot 2023-12-17 163757](https://github.com/CDrummond/lms-material/assets/9572444/fa43a84e-189e-44ae-9eb2-6477003d7b1c)

Any idea how I can get the loupe with a simple browser?

LMS-App Version: 0.4.2
Material Skin:  4.1.0

**Comment by CDrummond** [comment]
This search icon only appears for mobile devices, as it is assumed for others you can just press return.

**Comment by CDrummond** [comment]
I've updated the code so that these will now appear for touch and non-touch devices. This will be in 4.1.1

**Comment by baerengraben** [comment]
Great, Thank you! :)
