### ISSUE TITLE
Info Button Greyed Out on iOS/Safari, does nothing on macOS/Firefox

### ISSUE THREAD

**Issue by rudewire** [CDrummond/lms-material#802]
LMS: Version: 8.4.0 - 1702803696 @ Sun 17 Dec 2023 10:27:13 AM CET
Material: Material Skin 4.1.0
Server OS: Ubuntu 22.04.3 LTS
macOS Browser:  Firefox 120.0.1 (on macbook pro 2019)
iOS 17.2 Browser: Safari (on iphone 13 mini)

Problems:
-- on macOS/Firefox, the info button (button with central 'i') does nothing when clicked
-- on iOS/Safari, the info button is greyed out (not clickable)
-- on iOS/Safari, after an up-swipe from Playing tab to get into the new Artist/Album/Track info tabbed views, you have to be in the Album view to use the down-swipe to get out of this info view (alternately, you can click Playing bottom button, to get out of this Artist/Album/Track view)

**Comment by CDrummond** [comment]
Install "Music and Artist Information"

**Comment by rudewire** [comment]
Installed Music and Artist Information plugin, all issued listed persist

**Comment by CDrummond** [comment]
Then there are other issues on your system. Sorry, but this works fine here.

**Comment by CDrummond** [comment]
Try fully clearing your cache.

**Comment by CDrummond** [comment]
Whilst I'm not an apple user, I have checked on an iPhone and the "i" button works. So, as stated this is some issue on your setup.

**Comment by rudewire** [comment]
Ok, installing that plugin, rebooting server, and left the plugin “fetching” for a couple of hours the info button seems to be working. Thanks for the tip.

However item three in my original list still remains, but only in the “Track” info view, swiping up doesn’t return to the normal Playing menu.

**Comment by CDrummond** [comment]
Sorry, that's just the ways its implemented. Feel free to submit a pull request.

Also 1 ticket = 1 issue

**Comment by CDrummond** [comment]
Can't use swipe on lyrics, or text, as it interferes with scrolling of this. Also, these swipes are jsut shortcuts - the "(i)" icon in the toolbar is the main way ot access this.
