### ISSUE TITLE
iOS - Bookmark to Homescreen - fetches wrong MS icon

### ISSUE THREAD

**Issue by klslz** [CDrummond/lms-material#803]
I saved MS as normal bookmark. Here I saw the MS iOS square with rounded corners icon popping up.  OK.
When trying to use "add to homescreen" a small circular - non iOS compliant -  icon gets fetched and stored on the homescreen. NOK - I think that's not quite right.

Am I doing anything wrong here?

I have the latest iOS installed and I am using Safari.

**Comment by CDrummond** [comment]
When asking for icon.png Material should determine its iOS and return another icon. Could be the manifest, used for webapps, prevents this. I've updated the manifest code to also change icon filename. Sorry, but this is the best I can do.

**Comment by klslz** [comment]
You're quick on closing. :)

Anyhow. The fix seems to work.
