### ISSUE TITLE
Avoid plugin revision mismatch on custom git MS installations ?

### ISSUE THREAD

**Issue by klslz** [CDrummond/lms-material#805]
When installing a custom git version of Material Skin (for various reason), 
LMS notifies me on "New version available" after a restart even though the MS version number hasn't 
been changed in the repo.

Why is that? 
(1) I don't want a custom version get overwritten by the officially released version. 
(2) How can I avoid the notification (badge) for a custom build version - that basically comes 
     with the same version number and is basically newer than the official package ?

**Comment by CDrummond** [comment]
This is not an issue with the skin! Please this issue tracker is for material-skin _specific_ issues - no general LMS issues, or questions. Please use forums.slimdevices.com for support queries.

If you pleace Material inyou Cache/InstalledPlugins/Plugins/ folder then this is how LSM works. Use another location to prevent this, eg. "Plugins/" from LMS root.
