### ISSUE TITLE
Prefs: "Mobile layout now playing bar"  custom setting not stored/restored

### ISSUE THREAD

**Issue by klslz** [CDrummond/lms-material#808]
Once more: iOS17 /Safari

Similar to the volume step width, the  "Mobile layout now playing bar"  "thin" setting defaults
after being changed to "none", being "saved as default" and browser cookies removed.

Just verified on the latest master branch.

**Comment by CDrummond** [comment]
Don't know what's happening on your system, but it works here. Tried all 3 settings, confirmed in material-skin.prefs that value is saved in server, deleted the relevant config item in browser's 'Local storage', used Chromiums 'Empty cache and reload', confirmed default was as saved.

Note that LMS can take a few seconds to actually persist changes, they are not immediate.

**Comment by klslz** [comment]
In the afternoon I installed the official 4.1.1 from the LMS Repo. Now the problem disappeared. Looks good now.

Thx for your efforts. Very productive last couple of days. Nice progress. MS is now stable running on iPhone 13 and 15 and iOS17.
