### ISSUE TITLE
List/Grid view

### ISSUE THREAD

**Issue by Sunseaexo** [CDrummond/lms-material#809]
With Daphile when using play from RAM drive, the play list do not respect the list view.

Before RAM
![Capture1](https://github.com/CDrummond/lms-material/assets/105716279/1efb0f38-dff4-4a65-ac8d-128fea56ef27)

After RAM Button

![Capture2](https://github.com/CDrummond/lms-material/assets/105716279/91a6fa3d-062e-4f2b-98cc-cf3fee2169c2)

**Comment by CDrummond** [comment]
Sorry - but this a Daphile issue. I'm guessing the ramdisk causes the album_id to change per track.
