### ISSUE TITLE
Unable to access extra files

### ISSUE THREAD

**Issue by markbaaijens** [CDrummond/lms-material#814]
I'm using the LMS docker-image in combination with the Material-skin. I'm not shure if my problem (described below) is due to using the docker-image or the skin, but this is a way to find out....

In the Material-skin, you can click on 'More' on an album. Then a menu is displayed with 'Show text- and PDF-files'. When clicked, the (extra) files in the album-folder are shown, in my case dr14.txt, so far so good. 

But when that file is clicked (to show the contents), an error is shown:
`http://172.17.0.2:9002/mai/localfile/88ade47bd6cdb7ce00bd57a6bb6d86da/dr14.txt is not accessible.`

Note the address 172.17.0.2 which happens to be the main entry for (internal) docker-images. This address is only reachable on the host it self, so not from the outside, hence the error occurring. The following command returns nothing when executed on a local PC:
`wget http://172.17.0.2:9002/mai/localfile/88ade47bd6cdb7ce00bd57a6bb6d86da/dr14.txt`

My 'real' ip-ddress is 192.168.2.164. The following command returns a valid result:
`wget http://192.168.2.164:9002/mai/localfile/88ade47bd6cdb7ce00bd57a6bb6d86da/dr14.txt`

So maybe it is possible for Material-skin to look at the 'real' address? Then this problem is probably solved.

Note that the option 'Local pictures' works as expected, the (extra) picture in the album-folder is shown correctly.

**Comment by CDrummond** [comment]
The complete URL for these files comes from LMS, sorry. I would have no way of knowing when this address should be modified, so can't automatically do this.

**Comment by markbaaijens** [comment]
OK, I can see the url for local pictures is something ike this:
`http://rpms:9002/imageproxy/mai/localartwork/69607d506c1705e3ba62f44e976408b4/image.png`
So it is a different mechanism, in which there is no local ip-address involved.

Do you suggest I'll better post this issue in the LMS docker project?

**Comment by CDrummond** [comment]
Sorry, not sure, I don't run LMS in docker.

**Comment by markbaaijens** [comment]
I've reposted the issue here: https://github.com/logicwar/logitechmediaserver/issues/3
Hoping on any progress ;)
