### ISSUE TITLE
option: playing-badge in player's menu

### ISSUE THREAD

**Issue by czodroid** [CDrummond/lms-material#816]
Hi,

and happy new year !

I really don't like the playing-badge in the player menu, in my opinion it's too heavy:

![Screenshot from 2023-12-22 12-38-38](https://github.com/CDrummond/lms-material/assets/2365874/596a4df0-4ab6-4655-ac44-83676743724b)

Maybe there should be an option, like the new "Show artist context" (by XXX from YYY), so I can disable it.

Thanks !

**Comment by CDrummond** [comment]
No, sorry - not adding options for every single little item.
