### ISSUE TITLE
Did the song Infos + Lyrics disappear?

### ISSUE THREAD

**Issue by brannou** [CDrummond/lms-material#828]
Hi Craig,
I no longer have access to this menu!
Is this normal? 
Thanks for all
brannou

**Comment by CDrummond** [comment]
What menu? Material shows, and still does, artist, album, and song (lyrics) in separate view accessed via the "(i)" button - same as always.

**Comment by brannou** [comment]
The button is now grey. Not sure what happened on my side... Thanks
![image](https://github.com/CDrummond/lms-material/assets/157162210/a5b133a9-9a03-4d46-bfa0-2ade22fbc2ad)

**Comment by CDrummond** [comment]
Then you don't have "Music and artist information" installed.

Please, use forums.slimdevices.com for support queries.

**Comment by brannou** [comment]
It is installed and works on iPeng ( I checked before informing you). Sorry for the annoyance!

**Comment by CDrummond** [comment]
Sorry, but I do not have the time to debug everyone's system - hence directing you to the LMS forums. This feature does work, I use it and multiple others do so. Why its not working for you is an issue with your system. I suggest you 100% confirm that its the "Music and Artist information" plugin that is installed - this is required.

**Comment by brannou** [comment]
My mistake sorry, I deleted it and I don't even know how... have a great day!
