### ISSUE TITLE
Feature Suggestion : Live Radio indication and progress bar live edge indication

### ISSUE THREAD

**Issue by expectingtofly** [CDrummond/lms-material#830]
LMS 8.4 Now Supports a new query tag 'V' that returns whether a track is continuous live radio 

https://github.com/Logitech/slimserver/blob/e225575dcf0d2af7f3e85e28683ad1388bdb181f/HTML/EN/html/docs/cli-api.html#L5587

it returns in a {live_edge} tag : 

-  -1  :  Meaning it is not live radio
-   0   : Meaning it is live radio and at the live edge (normal live radio stream)
-   greater than 0  : The number of seconds from the live edge (If they have paused or rewound live radio or simply  a large buffer).  This will only be supported by 3rd party plugins that handle dynamic adaptive protocols like, mpeg dash or hls.

So basically >=0 means live radio.

BBC sounds live radio will support this by providing the distance from the live edge.

So, I wonder if it would be useful to visually show this in Material on the time progress bar.  I.e. show the maximum seek point and also show how far they are from live.
It looks like the vuetify linear progress bar supports this nicely as a buffer value : https://v2.vuetifyjs.com/en/components/progress-linear/#buffer-value

Or you might now want that, but might want a simple indication that the current track is live radio.

Am I making sense?

Now, I'm happy to have a go at this and submit a pull request.  But I thought you might not be happy with the hassle of dealing with a vuetify amateur,  or you might want to do it the way you would like it, or you might not want it in Material at all

Happy to take whatever your view is.

**Comment by CDrummond** [comment]
The only issue with your suggestion is that Material already colours the unused part of the progress. Still, some other method could be used. Is it already implemented in BBC Sounds? If so I'll have a look.

**Comment by expectingtofly** [comment]
Yes, its in today's release of BBC Sounds 2.35.8.
However, the LMS change for the 'V' tag query was only merged today, so won't be in the nightly build until tomorrow.

**Comment by CDrummond** [comment]
I'm already using LMS from git :)

Initial work in the 830-liveEdge branch. Not too sure on the 3 colour look, not sure if that's confusing or not - so will need to play. Also needs work for coloured toolbars.

**Comment by expectingtofly** [comment]
> I'm already using LMS from git :)
> 
> Initial work in the 830-liveEdge branch. Not too sure on the 3 colour look, not sure if that's confusing or not - so will need to play. Also needs work for coloured toolbars.

Wow, that was quick.  I like it, it's not confusing for me.

I can see that it's a work in progress, and just the first pass,  but just in case you want functional feedback : 

- it's working on pause and seek back for me, and looks good (although the buffer calc is probably not correct).
- It doesn't show correctly on seek forward again to before the live edge.
- I don't think the progress bar is working on first start of the live stream.

**Comment by expectingtofly** [comment]
Actually, buffer calculation (live_edge) is being incorrectly calculated in BBC Sounds.  The playingsongelapsed doesn't seem to be being updated in time.  I'll get that fixed.
