### ISSUE TITLE
Suspected incorrected calculation of buffer value for live edge

### ISSUE THREAD

**Issue by expectingtofly** [CDrummond/lms-material#831]
https://github.com/CDrummond/lms-material/blob/691accf0d045e5592929f05c2e1b3f7ea050d89b/MaterialSkin/HTML/material/html/js/nowplaying-functions.js#L86

I believe the current time should be included in the calc, so shouldn't that be? :

```
   let pc = view.playerStatus.current && undefined!=view.playerStatus.current.duration && view.playerStatus.current.liveEdge && view.playerStatus.current.duration>0
                 ? 100*Math.floor((view.playerStatus.current.liveEdge+view.playerStatus.current.time)*1000/view.playerStatus.current.duration)/1000 : 100.0;

        if (pc!=view.playerStatus.current.bufpc) {
            view.playerStatus.current.bufpc = pc < 100 ? pc : 100.0;
        }
```

**Comment by CDrummond** [comment]
Ah, thought live_edge was from 0. Code updated. Is it correct now?

**Comment by expectingtofly** [comment]
Yeah, it;s a bit confusing, I know.  Its the distance from the live edge.   So for the buffer on the progress bar  needs to include the elapsed time as its total buffer, not just additional buffer..

Therefore its also possible for it to be over 100 percent,  so I added : 
`
         view.playerStatus.current.bufpc = pc < 100 ? pc : 100.0;`

**Comment by CDrummond** [comment]
All OK now? Seems to work for me. Slight oddity when seeking, but only for a second or so - probably things slightly out of sync.

**Comment by expectingtofly** [comment]
Yes, all looks good.

BBC Sounds was a bit odd as well, so I've fixed that and will be doing another release.  The 2 changes together make it work well👍

**Comment by expectingtofly** [comment]
Ah,  the buffer value doesn't appear to be updating at the same time as the time is updating.  
Does it need to be triggered as the time updates?

**Comment by CDrummond** [comment]
live_edge is only updated on status messages. But Material has a timer that fires every second to update the playback position. I've updated the code to also set buffer % every second.

However, I've noticed that live_edge is not updated when not playing? I would expect it to be. I tested by pausing a stream and refreshing Material in the browser - live_edge is always same value. But if I the press play a new value is sent.

**Comment by CDrummond** [comment]
I've added a timer to refresh status every 10seconds if stream has live edge and not currently playing. This is when I would expect to see the buffer grow - but it does not.

**Comment by expectingtofly** [comment]
Ah yes,  good point, thanks.  I'll see about correcting that.

**Comment by CDrummond** [comment]
Let me know when you do, and I'll close this. If its not something you can do I'll remove the 10second timer.

**Comment by expectingtofly** [comment]
Yes, that's fine, I can make that change.

**Comment by expectingtofly** [comment]
This is now working with BBC Sounds 2.35.12.  Closing.
