### ISSUE TITLE
[Feature request] Optional "tabbed" view for players in desktop mode?

### ISSUE THREAD

**Issue by edgar-vincent** [CDrummond/lms-material#840]
Hi Craig,

I was thinking it might be a good thing to allow users to display the list of players in "tabs" when there is enough space for them (i.e. in desktop mode).
Instead of having to click on the name of the current player to toggle a menu containing the list of players, the available players (or a subset of them)  would be displayed in the same row, adjacent to the current player, with the latter being somewhat emphasised.

Naturally, this could be a togglable option rather than the default.

I believe this would make it easier to quickly switch between players, while making use of the currently empty space.

What do you think?

Thanks a lot!

Edgar

**Comment by CDrummond** [comment]
No, sorry. Would complicate code too much, having to keep track of queue for N players, etc.

**Comment by edgar-vincent** [comment]
I understand. Thanks!
