### ISSUE TITLE
playlists - click to access albums artists

### ISSUE THREAD

**Issue by th2j** [CDrummond/lms-material#841]
In the playlist tracks, i can click on artist to browse to the artists albums (or click on album)

But this does not work with the tracks already played or the current track.
It work only for next tracks.

This happens for Qobuz tracks. Local tracks are OK.

Thanks
Thomas

**Comment by CDrummond** [comment]
Sorry but, from Matreial's perspective it does not know, or care, if tracks have been played or not. Material's click to browse is intended for local tracks, and I do not subscribe to streaming services.

**Comment by th2j** [comment]
ok thanks

it is a really small issue so it doesn't mind
