### ISSUE TITLE
MaterialSkin 4.3.2 vs MaterialSkin 4.2.2

### ISSUE THREAD

**Issue by Eltom61** [CDrummond/lms-material#842]
Hello Craig. I use Daphile which has integrated LMS 8.3.1. Unfortunately, I had set the “automatic plugin update” option in Daphile. Now Daphile has updated the installed MaterialSkin 4.2.2 to version 4.3.2. Since then, the web interface no longer shows me "Album" and "Zufällige Albums" but rather "Releases" and "Random Releases". In the German setting this is quite confusing. I tried to go back to MaterialSkin 4.2.2, but I couldn't. Is there another way to restore the display as in version 4.2.2?

**Comment by CDrummond** [comment]
German translations updated for next release.

**Comment by Eltom61** [comment]
Thanks for the reply
