### ISSUE TITLE
Lyrics Font Size

### ISSUE THREAD

**Issue by s-timm** [CDrummond/lms-material#844]
Hi Craig, thanks again for your wonderful Material-skin!
I noticed recently that the long-press on "Track" to change the size of the song lyrics is no longer working (maybe with the update to v4?). Before, I could select a bigger font size to read the lyrics from a distance (as I am getting older I have problem with the small font).
Is there any chance that you could bring that feature back? That would be awesome! :-)

![image](https://github.com/CDrummond/lms-material/assets/12531230/6976defd-cf83-471e-afb6-344bd273c5ea)

Something else: do you know, why I get different information when I use Material skin and when I use the traditional view in LMS?
See the two Klangraum-CDs:
![image](https://github.com/CDrummond/lms-material/assets/12531230/3c00d478-d7c4-4ca5-8c05-c3435c2e0487)
![image](https://github.com/CDrummond/lms-material/assets/12531230/56735e57-e37f-4a16-b8a7-c84174f2740b)

Thanks for any help!

**Comment by CDrummond** [comment]
This was removed as the font size matches the rest of the UI. If its too small here it'd be too small elsewhere, so just increase the zoom of the page.

**Comment by s-timm** [comment]
Okay, I didn't know that if it was on purpose. However, that doesn't really work - at least not in my case:
I use a tablet in the kitchen to select and control my Squeezebox radio. I go and select a playlist or album to listen to (with the regular font size, as I am in front of the screen when I am doing it and like to see as much as possible). 
Then I switch to the lyrics view, step away from the tablet and start cooking or cleaning the kitchen. Now I am further away from the screen and the font size is too small to read the lyrics from a distance.
Unfortunately, I can't just pinch and zoom to change the font size in the lyrics view (and I don't want to change the font size for the whole UI) - so to have a specific font size for the lyrics view would be sooo much better. And if possible larger than the "Large" font size.

**Comment by CDrummond** [comment]
Re-added for 4.4.0

**Comment by s-timm** [comment]
Thank you!
