### ISSUE TITLE
Feature request: Sort Artist by Role

### ISSUE THREAD

**Issue by koldinger** [CDrummond/lms-material#845]
Not sure if this is a skin issue, or a core server issue.

I'd love to see an ability to sort an artists albums by their role.   For instance, in the attached screenshot, we can see that Miles Davis has performed or composed on a large number of albums, some of them his, some of them other artists.   On the first album, Sonny Rollins' "A Night at the Village Vanguard", Davis is the composer of track 5.  The second album, "Bag's Groove" is a Miles Davis album.   On "Blue Note Perfect Takes", he is the principal artist on one track of a compilation. 

It would be great if we could get some sort of Role sort, such as:
- Albums:
    - Bags Groove
    - Blue Haze
    - etc
- Composer: 
  - A Night at the Village Vanguard
  - Bass on Top
- Performer:
  - Some other album
  - Yet another Album

![Miles](https://github.com/CDrummond/lms-material/assets/5994872/0457c7bd-bf2c-4c99-948c-c770586918b1)

**Comment by CDrummond** [comment]
This should be somewhat possible via LMS 8.4's release type support.
