### ISSUE TITLE
[Feature Request] Alarm indicator/info in Player Dialog/Name

### ISSUE THREAD

**Issue by cirdanlunae** [CDrummond/lms-material#847]
Currently, the sleep timer can be seen in the Player dialog, and an indicator shows that sleep is active for a player.

Is such a feature possible for alarms? An indicator beside the player name, much like the sleep indicator, would be a useful sanity check that an alarm is set. Having the upcoming alarm(s) listed in the same area the sleep timer is on the Player dialog would save time checking active alarms.

(((POSTED RELEVANT SLEEP SCREENSHOTS FOR REFERENCE IN CASE I'M NOT NAMING UI ELEMENTS CORRECTLY)))

![Screenshot_20240227-002858_1_1](https://github.com/CDrummond/lms-material/assets/5956790/b42ac941-1a75-45da-b609-aa7357ea783d)
![Screenshot_20240227-002906_1_1](https://github.com/CDrummond/lms-material/assets/5956790/57000b48-470d-4a8d-9eaf-8338ee463a58)

**Comment by CDrummond** [comment]
Unfortunately the 'next alarm' is not part of a player's status message - so Material would have to periodically check for this (as happens in Material's screensaver). I don;t really want to add polling for this, so I cannot implement this feature.

I personally think this is a reasonable idea, but first you need to create an issue on LMS's github page asking for a player's 'next alarm' to be part of either 'severstatus' (in which case I could show for all players), or plain 'status' (which would be the status of a specific player). When this info is available in a status message then I can implement this.

**Comment by cirdanlunae** [comment]
Gotcha. Yeah, I agree with you--adding polling for this feature would not be a smart move.

Submitting an issue now for LMS. Thanks for the direction!

**Comment by cirdanlunae** [comment]
michaelherger replied to my issue, saying it might be possible currently? Let me know if more changes are needed to make it happen so I can forward that info

https://github.com/Logitech/slimserver/issues/1003#issuecomment-1968482659

**Comment by CDrummond** [comment]
Implemented in the 4.4 branch. Requires Michael's patch as described in LMS issue, so will be LMS 8.5 onwards (assuming its applied).

**Comment by cirdanlunae** [comment]
You all are amazing. Thank you!
