### ISSUE TITLE
Cannot add favorite from queue items.

### ISSUE THREAD

**Issue by bobold** [CDrummond/lms-material#85]
There seems to be no way to add to favourites...?  am I missing something...?
Standard LMS skin has an option to add a radio stream or file to favourites but there appears to be no way to do this in this skin...I have to revert to the default skin for this option.

Otherwise... yes ! this skin is wonderful..!

**Comment by CDrummond** [comment]
Use the vertical "..." button, selcet "Add to favourites"

**Comment by CDrummond** [comment]
To be honest, I could add 'Add to favorites' to queue - but the station cover would be missing. Adding the favourite from the browse page will correctly add cover.

Would not be possible to add artist/album/genre favorites (unless poluting the menu with too many options).

So, closing.

**Comment by bobold** [comment]
Fine, your code your choice. :)

I'll go back to the default skin where that option is available.
It might not be 'pretty' but it works and balances form and function.

When you've browsed through the radio lists and added several to the
queue to sample  it is counter-intuitive to not be able to add the one
you like from the queue to favourites.
 Instead, having to traverse the browser and find the station just to
add it so it looks pretty is not my idea of fun.

As a user that's more important than function being abrogated in favour of form.

Regards,
bob.

**Comment by CDrummond** [comment]
I have stated my reasons for not implementing this - none of which have to do with being "pretty". I have looked at the default skin - the only way I can save a favourite from the queue is to press the "M" button, this shows more info on the left, and on there is a heart button. I press that button, and a favourite is added - BUT it has neither the station name nor logo. Now neither may be important to you, but I do not find these being missing to be very user friendly. If I could get the station logo, then I'd quite happily add a "Save to favorites" - I'd even written 1/2 the code. But this missing logo stopped me.

However, I'm glad the default skin works for you. I have no issues with it either - apart from it not working on mobile devices.

**Comment by bobold** [comment]
"I'd even written 1/2 the code. But this missing logo stopped me."

See, you even thought it a useful addition....until it wouldn't look good...

That's "pretty" in my book.

Still, thanks for considering my request and enjoy your day.

Cheers,
bob.

**Comment by CDrummond** [comment]
Wow! You really have "issues". I'm sorry I don't want to spend my free time implementing a feature for you that would look 1/2 baked. If looks are so not important, why even consider using this skin? The default web UI actually looks OK to me, and provides what you want - so please use that and leave me alone.
