### ISSUE TITLE
Issues with Material skin in Fully Kiosk Browser

### ISSUE THREAD

**Issue by pwm802** [CDrummond/lms-material#858]
I have been trying to use Fully Kiosk browser on Android 8.1 to view the Material Skin and it will eventually freeze or have rendering errors.

08:39:12.791 -- [ERROR] Uncaught ReferenceError: storeClickOrTouchPos is not defined -- on line 762 of http://192.168.1.170:9000/html/js/material.min.js?r=4.3.3

08:39:12.847 -- [ERROR] Uncaught ReferenceError: storeClickOrTouchPos is not defined -- on line 761 of http://192.168.1.170:9000/html/js/material.min.js?r=4.3.3

08:40:55.412 -- [ERROR] Uncaught ReferenceError: storeClickOrTouchPos is not defined -- on line 762 of http://192.168.1.170:9000/html/js/material.min.js?r=4.3.3

08:40:55.466 -- [ERROR] Uncaught ReferenceError: storeClickOrTouchPos is not defined -- on line 761 of http://192.168.1.170:9000/html/js/material.min.js?r=4.3.3

08:45:45.942 -- [ERROR] Uncaught ReferenceError: storeClickOrTouchPos is not defined -- on line 762 of http://192.168.1.170:9000/html/js/material.min.js?r=4.3.3

08:45:46.001 -- [ERROR] Uncaught ReferenceError: storeClickOrTouchPos is not defined -- on line 761 of http://192.168.1.170:9000/html/js/material.min.js?r=4.3.3

08:46:45.060 -- [ERROR] Uncaught ReferenceError: storeClickOrTouchPos is not defined -- on line 762 of http://192.168.1.170:9000/html/js/material.min.js?r=4.3.3

08:46:45.108 -- [ERROR] Uncaught ReferenceError: storeClickOrTouchPos is not defined -- on line 761 of http://192.168.1.170:9000/html/js/material.min.js?r=4.3.3

08:47:36.020 -- [ERROR] Uncaught ReferenceError: storeClickOrTouchPos is not defined -- on line 762 of http://192.168.1.170:9000/html/js/material.min.js?r=4.3.3

08:47:36.143 -- [ERROR] Uncaught ReferenceError: storeClickOrTouchPos is not defined -- on line 761 of http://192.168.1.170:9000/html/js/material.min.js?r=4.3.3

**Comment by CDrummond** [comment]
And why is the issue with the skin not the browser? Works everywhere else.

**Comment by pwm802** [comment]
I’m not saying the issue is with Material Skin, it’s very likely in the browser.  I am just trying to understand the error in the java script.
