### ISSUE TITLE
Don't close until solved !!

### ISSUE THREAD

**Issue by bobold** [CDrummond/lms-material#86]
what 'save to favourites' option ???  on a desktop ? there is not that option in the "..." vertical menu
![screenshot from 2019-02-28 21 24 23](https://user-images.githubusercontent.com/33737871/53552202-ae341b00-3b9f-11e9-841e-107f7d2d3338.png)

Perhaps you could refrain from closing issues until they're resolved ?

**Comment by CDrummond** [comment]
Please do not open new issues for existing ones! I get notified when you add a comment.

It would have been helpful if you had stated that you want to add favorite from the queue!

**Comment by bobold** [comment]
If **you** **close** an issue then the only way to comment is to open anew...???
There is no way to add a favourite from anywhere, let alone the queue... but yes from a queue is desired... just like happens in the default skin options.

**Comment by CDrummond** [comment]
**You** cannot re-open issues, but **you can** comment on closed ones.

I don't know what is broken on your system but I can 100% assure you that you can add favourites. I know, as I use that and have added code for this.

**Comment by OneB1t** [comment]
Actually this is also not working for me but its not a big deal.
![image](https://user-images.githubusercontent.com/320479/56622971-70e58a00-6632-11e9-844a-785b7d7ddc8c.png)

but i can do it on left side of UI without problems
![image](https://user-images.githubusercontent.com/320479/56622994-95d9fd00-6632-11e9-90ff-94d7dd0269b5.png)

**Comment by CDrummond** [comment]
Please, before commenting on ramdom issues - look at the other issues.

This "feature" is not implemented for reasons give.
