### ISSUE TITLE
Bug: Drag'n'Drop in Now Playing not working anymore

### ISSUE THREAD

**Issue by schnillerman** [CDrummond/lms-material#865]
Hi,

I L.O.V.E. your skin !!!

Currently, drag & drop does not seem to work anymore in _Now Playing_ list. Long press on an item in an Android browser (no matter if latest Chrome or Firefox) does not do anything anymore.

Version info:

![Screenshot_20240328_203652_Chrome.jpg](https://github.com/CDrummond/lms-material/assets/17252473/3ff59a08-2ea6-4042-b738-f08d56103e0e)

![Screenshot_20240328_204450_Firefox.jpg](https://github.com/CDrummond/lms-material/assets/17252473/8c80da11-af9b-4b7e-b682-5d5f019da4b3)

Or does it work differently now?

**Comment by CDrummond** [comment]
Drag'n'drop works on Android Chrome for me - just tried. Not sure if Firefox has ever worked - see #27

**Comment by CDrummond** [comment]
...and I assume you mean in the _Queue_ **not** _Now Playing_ ??? Now playing has never had and drag'n'drop.

**Comment by CDrummond** [comment]
As stated, Firefox never worked.
