### ISSUE TITLE
[FR] Make the skin OLED safe. 

### ISSUE THREAD

**Issue by barolo** [CDrummond/lms-material#871]
Currently one of my devices have an always-on OLED screen connected with Material skin on it and there's a real concern of possible burn in of static elements.
The skin already has a pure black variant so it is quite friendly but my idea to move it further would be to trigger Now Playing screen [if it isn't on already] after x amount of time and auto-hide the top/bottom toolbars.

**Comment by CDrummond** [comment]
But the now-playing still has static elements (playback controls).

**Comment by CDrummond** [comment]
I've implemented this in the `dev` branch, for a future 4.6.0 release. I want to release 4.5.0 soon, and this is too close to release to add this feature now.

**Comment by CDrummond** [comment]
Closing, as implemented in master for next (4.6.0) release.
