### ISSUE TITLE
Add option to import favorites

### ISSUE THREAD

**Issue by ZubaZ21** [CDrummond/lms-material#873]
See https://forums.slimdevices.com/forum/user-forums/logitech-media-server/1699632-new-lms-on-raspberry-can-i-migrate-settings-favorites-from-windows10?p=1699813#post1699813

The default skin allows for importing an opml file for favorites.  There is no corresponding option in Material skin.

Perhaps an enhancement?

**Comment by CDrummond** [comment]
Sorry, tried - but there is no API for this. The code that the Default skin uses is very specific to it.
