### ISSUE TITLE
Works - Jumplist does not appear when only 1 release group not including works

### ISSUE THREAD

**Issue by darrell-k** [CDrummond/lms-material#878]
I think this is the reason - in any case, changing `>1` to `>0` in the code below fixes it (I know that is not the real solution!).

https://github.com/CDrummond/lms-material/blob/1edca4e8b694b925141f941babd736f134f50f2c/MaterialSkin/HTML/material/html/js/browse-resp.js#L1079-L1082

**Comment by CDrummond** [comment]
Hopefully fixed now.

**Comment by darrell-k** [comment]
Confirmed fixed. Thanks.
