### ISSUE TITLE
Works: Problem with Extended Browse Mode

### ISSUE THREAD

**Issue by darrell-k** [CDrummond/lms-material#879]
I've added code to LMS to allow users to create Works-based Extended Browse Modes (for Genres) - for example set up a extended mode for String Quartets, browse by Works, Genres "String Quartet".

There are two problems:

1. The code below forces listworks to true when the new item is enabled in Material settings, even if the Works item is disabled. I fixed this by making the listWorks assignment only if `c.id == "myMusicWorks"`. This is a useful combination of settings because it allows the user to suppress the main Works category, therefore not showing Works in the main release type listing, at the same time allowing them to set up their own genre-based Works menu items.

https://github.com/CDrummond/lms-material/blob/1edca4e8b694b925141f941babd736f134f50f2c/MaterialSkin/HTML/material/html/js/browse-functions.js#L2100-L2103

2. The new Works Extended Browse Mode menu does not show the multiple album covers.

**Comment by CDrummond** [comment]
Hopefully fixed now.

**Comment by darrell-k** [comment]
Confirmed fixed. Thanks.
