### ISSUE TITLE
Works - LMS efficiency changes

### ISSUE THREAD

**Issue by darrell-k** [CDrummond/lms-material#880]
There will be some changes on the LMS side shortly, which will mean you need to additionally request tags `b`, `h` and `z` to get back full track information, anywhere you are requesting track data (tracks command, status command, are there others?)

**Comment by CDrummond** [comment]
What are each of these for?

**Comment by darrell-k** [comment]
b is work, h is grouping, z is subtitle. Michael didn't want the tracks(titles) query returning them unconditionally, as has been the case.

**Comment by CDrummond** [comment]
Code updated. Is this now OK?

**Comment by darrell-k** [comment]
It's working in the album listing and the MAI screen, but not in the playlist and now playing (status request, I think).

**Comment by CDrummond** [comment]
Yeah, I thought about that last night - but was too late. Should be resolved now.

**Comment by darrell-k** [comment]
Works in now playing but not for queued tracks before they are played.

**Comment by CDrummond** [comment]
And now?

**Comment by darrell-k** [comment]
Yes, that looks good. closing the issue, thanks.
