### ISSUE TITLE
Hover buttons hard to read and don't match light skin

### ISSUE THREAD

**Issue by spfenwick** [CDrummond/lms-material#881]
The buttons that appear when you hover over the browse view (Append, Play Next, Play Now) look odd on the light skin. They are hard to make out and look very different from the other buttons up the top:
![image](https://github.com/CDrummond/lms-material/assets/101789313/ab9da4a2-da2d-4349-9bc4-0021481b22f0)

The same buttons on a dark skin work much better as they are much more readable and generally blend in much better:
![image](https://github.com/CDrummond/lms-material/assets/101789313/285b34f5-01d9-4165-9202-3558cf2a3694)

It would be better if on the light skin the hover buttons were dark on a light background to better match the rest of the skin and had more contrast to make them more readable.

**Comment by CDrummond** [comment]
What OS, OS Dark/light setting, browser, and Material theme is this? As I've just tried all light themes (Light, Breeze, Adwaita, Windows-10, Mojave) that Material has with Chromium on Linux and the _list_ hover buttons have dark borders - so as you are suggesting, and not like your screenshot.

**Comment by spfenwick** [comment]
It looks like this was a problem with my LMS install. I don't know the exact cause but I've deleted the whole LMS config directory and now I'm seeing the same thing as you - which looks much better. I'm now judiciously restoring individual config files to get back to my old setup.

Thank you for your help.

BTW I'm using Windows 11 and Edge for the client with Windows-10 theme and docker for the server, though I don't think any of those were causing the problem.
