### ISSUE TITLE
library_id when playing remote albums

### ISSUE THREAD

**Issue by darrell-k** [CDrummond/lms-material#882]
I've noticed that LMS is not finding the tracks for a remote album playlistcontrol command from Material when the LMS Library view for the current player is "local tracks only" and the Material "My Music" setting is "All".

My testing indicates that this can be corrected by Material passing "-1" instead of "0" as the library_id when the "My Music" setting is "All".

**Comment by CDrummond** [comment]
Should be resolved now.

**Comment by darrell-k** [comment]
Looks good, thanks.

**Comment by CDrummond** [comment]
@darrell-k For 4.6.0 I was using this "-1" everywhere, but this breaks randommix (and probably more). For 4.6.1 I've changed the code to use "-1" _only_ for `playlistcontrol` and `playlist` commands. Can you please confirm this still resolves this issue?

**Comment by darrell-k** [comment]
Seems to be passing 0 to playlistcontrol now. But let me see if I can fix this on the LMS side. You're right, this is an LMS bug in that the albums query is behaving differently to playlistcontrol. I'll find out why.

**Comment by CDrummond** [comment]
@darrel-k I've reverted the last change. Now "0" is used as default library ID for RandomMix on LMS<9.0, and "-1" from 9.0 onwards.

**Comment by darrell-k** [comment]
I think with the change Michael is proposing  (see forum thread) we'll be fine using -1 in all cases (if the fix is applied to 8.5 and 9.0) so Material can remain unchanged from the 4.6.0 release.

**Comment by darrell-k** [comment]
Michael has merged the fix into 9.0 and 8.5, so -1 should now be fine for all commands, for those versions of LMS.
