### ISSUE TITLE
Filter toggle for `noGenreFilter` & `noRoleFilter` views

### ISSUE THREAD

**Issue by bb010g** [CDrummond/lms-material#885]
This issue is a sort of follow-up to #147. With `useUnifiedArtistsList => 0, groupArtistAlbumsByReleaseType => 0, noGenreFilter => 0, noRoleFilter => 0`, I can confirm that, under All Artists → [An Artist] → [An Album] - [Another Artist], LMS's default UI shows only the tracks that [An Artist] featured in for [An Album], and under All Artists → [An Artist] → No Album - Various Artists, LMS's default UI shows only [An Artist]'s singles. In contrast, Material skin shows all tracks, highlighting the tracks the artist features in. Sometimes, there are hundreds of tracks on an album (e.g. No Album), and the highlighting isn't much help. A toggle in the browse panel to switch between filtering & just highlighting would be great.

Additionally, with `groupArtistAlbumsByReleaseType => 1`, the default UI offers Album Artists → [An Artist] → All Releases. While I appreciate Material skin's grouping of releases into one big list without having to navigate extra menus, a similar toggle in the browse panel to switch to & from an All Releases style ungrouped view would also be great. It sucks having to switch a global setting before & after every time you want to look chronologically at the middle of a large discography of thoroughly mixed released types.

**Comment by CDrummond** [comment]
Use Material's 'Filter album tracks' setting to change this behaviour.

**Comment by CDrummond** [comment]
FYI the next (4.6.0) release will contain an "All releases" entry in the "..." menu which will shown a combined list/grid.
