### ISSUE TITLE
Another library_id issue

### ISSUE THREAD

**Issue by darrell-k** [CDrummond/lms-material#893]
From the album pop-up "More" option, clicking the resulting Album link uses the LMS Player library_id, not the Material one, which results in an empty track list when using this option for an online library item when the LMS player option is set to "local tracks only".

You may ask what is the point of browsing from the album to the album via the "More" menu, but it is useful when displaying a Works, to get to the album containing the work.

**Comment by CDrummond** [comment]
Should be fixed in 4.6.1

**Comment by darrell-k** [comment]
Thanks, confirmed fixed.
