### ISSUE TITLE
problem with shuffle play titles or years

### ISSUE THREAD

**Issue by oliklausch** [CDrummond/lms-material#894]
i am using daphile 24.05 as LMS, with the updated material skin. if i try to use shuffle play, the selection title does not work....nothing happens. the same problem if you use years as selection for shuffle play. if you use the other selections....they work properly. the tile and years selection works propery on the original daphile surface and even with squeezer, squeezelite, squeeze ctrl. the problem comes only by using material skin. in the last version there was no problem at all. i can see the problem on 3 Daphile-LMS with people use Material-Skin.

**Comment by CDrummond** [comment]
This is an LMS issue - see https://forums.slimdevices.com/forum/user-forums/3rd-party-software/1708082-random-mix-stopped-working

However, I have just tried on LMS9.0 with Material - and RandomPlay works with Tracks and Years.

**Comment by oliklausch** [comment]
Yes you are right - it could be an issue from LMS directly.....but the thing ist: randomplay (Tracks/Title) works directly without problems on the daphile web gui, when i use squeezelite raspberry pi as control interface it works too, it only does not work with the material skin. So maybe ift its working as you say, it could be a problem that daphile is a little different/specialised LMS solution?

**Comment by CDrummond** [comment]
It **is/was** an LMS issue. Material is different to the Default skin. However, the issue was in LMS, and now fixed.

**Comment by oliklausch** [comment]
sorry man - i forgot to say....i will not annoy you with that problem - your skin is really the best web gui ever seen for that system man!!! i like it very much....maybe it is only a problem with the daphile lms. but thanks for your geat work !
