### ISSUE TITLE
Android+Chrome problem when attempting to add a play queue track to a playlist

### ISSUE THREAD

**Issue by chrober** [CDrummond/lms-material#896]
On my Android mobile I get some strange behaviour when attampting to add a track from the play queue to a playlist. Please see the attached screen recording. The dialog box with the drop-down selection does not let me select a playlist but changes its position whenever I tap on it.

I could verify this problem only with the Chrome browser on my Android mobile phone. It does not happen with Firefox on the same phone. And it does not happen with Chrome on an iPhone.

https://github.com/CDrummond/lms-material/assets/26856218/2ef4f856-f16a-47ee-afdd-6aec79ad84fa

**Comment by CDrummond** [comment]
Confirmed! Most odd. As a work-around you can use the Material APK - https://f-droid.org/en/packages/com.craigd.lmsmaterial.app/ - which does not seem to suffer from this. Odd, as the APK uses the chrome-wrapper, so I've always thought it should be the same.

Looks like when the keyboard is shown the bottom navbar is not hidden - but it is for other browsers.

Thanks for reporting, I'll look into this.

**Comment by chrober** [comment]
> As a work-around you can use the Material APK - https://f-droid.org/en/packages/com.craigd.lmsmaterial.app/ - which does not seem to suffer from this.

I did not even know you are doing an apk for this! Great! It definitely solves the problem mentioned above.

I guess this app will finally solve another inconenience I am suffering: Whenever I travel and connect my Raspberry PI (running the server and player via piCorePlayer) to my mobile phone's WiFi hotspot I need to create a new LMS homescreen shortcut (for the PI's new IP adress) on my mobile phone. With the server discovery of this app I will no longer need to create those shortcuts.

Many thanks!!!

**Comment by CDrummond** [comment]
I _think_ this is now resolved - seems to be for me. Any chance you can try git/master? If not change will be in 4.6.3

**Comment by chrober** [comment]
I can give it try. What's the best way to do that? Shall I just apply the changes from https://github.com/CDrummond/lms-material/commit/f15728f9eb7cd1f9415449856a3f0a95b19945cd to my installation?

**Comment by CDrummond** [comment]
Could do, its a simple change. If you do test please ensure you fully reload - ie. clear Chrome's cache, etc.

**Comment by chrober** [comment]
I can confirm the fix introduced with https://github.com/CDrummond/lms-material/commit/f15728f9eb7cd1f9415449856a3f0a95b19945cd is working, thanks!
