### ISSUE TITLE
Load interface on specific player or module using http GET method?

### ISSUE THREAD

**Issue by ronluna** [CDrummond/lms-material#90]
Would it be possible to load an specific player screen by sending an http get (instead of using POST) command to the jsonrpc.js ?

It would be very handy if the theme would allow  to to something like:

http://server_ip:server_port/?player:player_mac

**Comment by CDrummond** [comment]
You cannot change Material's UI via a JSONRPC call. But you can specify player when starting/re-loading material.

e.g. `http://127.0.01:9000/material/desktop.html?player=00:00:00:00:00:00` or `http://127.0.01:9000/material/desktop.html?player=Kitchen`

**Comment by ronluna** [comment]
More than enough!!! 
Amazing UI! hands down!!!
