### ISSUE TITLE
Desktop mode not working 

### ISSUE THREAD

**Issue by MCMXD** [CDrummond/lms-material#903]
After the update my PC is stuck in a mobile browser version of the page. 

Appending /Material/?layout=desktop does not help. 
Distressingly the settings button dropped the item for server and I was unable to return to the default skin. 

My iPad using Chrome did not have that issue and was able to swap to default. 

I have changed back and forwarth since then but still only a mobile version. 

Setup
LMS on a Ubuntu Server VM - ProxMox host 
Windows 11 + Chrome 

Many thanks for an excellent product.

**Comment by CDrummond** [comment]
Sorry but this is an issue on your system, I use desktop layout on my Laptop and can confirm it still works.

Perhaps you need to refresh your cache?

**Comment by cucko** [comment]
i also have the same problem, lms opened in dark theme, there is no Server item in the settings menu, and this js error
```
material.min.js?r=5.0.0:75 ReferenceError: defaultTheme is not defined
    at s.initUiSettings (material.min.js?r=5.0.0:741:268)
    at material.min.js?r=5.0.0:87:5905
    at material.min.js?r=5.0.0:87:7403
    at Array.forEach (<anonymous>)
    at material.min.js?r=5.0.0:87:7382
    at s._withCommit (material.min.js?r=5.0.0:87:9209)
    at s.commit (material.min.js?r=5.0.0:87:7356)
    at s.commit (material.min.js?r=5.0.0:87:3371)
    at kr.created (material.min.js?r=5.0.0:756:339)
    at pn (material.min.js?r=5.0.0:75:22030)
```

**Comment by MCMXD** [comment]
> Perhaps you need to refresh your cache?

This worked for me perfectly. Give it a go.
