### ISSUE TITLE
need advise on notifications usage

### ISSUE THREAD

**Issue by bungh0l10** [CDrummond/lms-material#916]
I just found your [notifications feature](https://github.com/CDrummond/lms-material/wiki/09-Notifications) and tried to play with it. Unfortunately the example you provided doesn't work for me.

> curl 'http://localhost:9000/jsonrpc.js' --data-raw '{"id":0,"method":"slim.request","params":["",["material-skin", "send-notif", "type:alert", "msg:The message"]]}'

returns `curl: (52) Empty reply from server` while LMS logs `[24-06-30 10:28:07.0192] Slim::Web::JSONRPC::requestMethod (480) Request failed with error: Bad params!`

Not sure what I'm missing here but I would be happy for an advise, thanks :) .

**Comment by CDrummond** [comment]
Sorry, but this functionality was removed in v4.0.0  Why do you want this?

**Comment by bungh0l10** [comment]
Oh I see, I haven't had a real use case for it yet, actually just went curious about it and wanted to see how it works / looks like.
But thanks for your swift reply :)
