### ISSUE TITLE
Sort TuneIn podcasts by most recent episode first

### ISSUE THREAD

**Issue by kjeacle** [CDrummond/lms-material#923]
Is it possible to have TuneIn podcast episodes sorted with the most recent episode first?

In the Default skin, it's pretty good, it looks like this:

    Favourites = LMS server order                       (want)
    Radio / My Presets = TuneIn server order            (would prefer alphabetical but ok)
    Radio / My Presets / Podcast = newest episode first (definitely want)

When I use Material Skin 5.0.4, I can't replicate this. I see there is a "Sort favourites list" option but neither setting helps:

    Sort favourites list = No
        Favourites = server order                           (want)
        Radio / My Presets = TuneIn server order            (would prefer alphabetical but ok)
        Radio / My Presets / Podcast = oldest episode first (don't want)
    
    Sort favourites list = Yes
        Favourites = alphabetical                   (don't want)
        Radio / My Presets = alphabetical           (want)
        Radio / My Presets / Podcast = alphabetical (makes no sense)

So I suppose I am looking for three things:

1. Don't sort Favourites
2. Sort podcasts alphabetically
3. Sort podcast episodes with most recent episode first   

If I am missing a configuration option, please let me know. Thanks!

**Comment by CDrummond** [comment]
Not sure what you are asking for. The option to 'sort favourites' should **only** affect items under 'Favourites' not 'Radio' - the option should have no effect there, but you seem to be implying it does?

Material should be adding **no** sorting to "Radio / My Presets / <anything >"

**Comment by kjeacle** [comment]
Thanks for looking at this. Here's what it looks like when Sort is enabled. It's sorting alphabetically which doesn't make any sense:

![sorted](https://github.com/user-attachments/assets/e2ef448d-8d98-48bf-a7df-33a3b022e00d)

With Sort disabled, it's in order of podcast episode release date but this is the opposite of the default skin which shows the most recent episode first:

![unsorted](https://github.com/user-attachments/assets/3697220d-3184-487b-b317-772a6e61cc28)

I would like to disable Sort so that my Favourites are in my order, but I'd like the podcast episode list to mirror the default skin i.e. most recent episode first. Thanks!

**Comment by CDrummond** [comment]
But **where** is that list coming from **exactly** ??? Is it "Radios / My Presets /" ??? What is the **path** that Material is using?

As stated the option to **sort** favourites should **only** affect items in favourites.

**Comment by kjeacle** [comment]
Radio
My Presets
Inside Politics
Recent Episodes

Subscribe to any podcast on TuneIn and you get the same thing.

**Comment by CDrummond** [comment]
Ah, think I might know what the issue is. However, this will only stop alphabetical sorting - the oldest/newest sorting is provided by LMS.
