### ISSUE TITLE
Issue with the view from Telegram

### ISSUE THREAD

**Issue by Steinchen68** [CDrummond/lms-material#929]
when I call up the lms url from telegram, the lower toolbars are not displayed or are overlaid. This has only been the case since 5.1.1, at least I think so.
This is not the case in Safari.
it's a great plugin

**Comment by CDrummond** [comment]
What? Why would you be opening this from Telegram (a messenger app)????

**Comment by Steinchen68** [comment]
yes i know, it's not easy to understand, many things are possible with lms.
i can switch on my esp32 with telegram, and control it with a link to lms with material skin
![telegram](https://github.com/user-attachments/assets/3369c3f5-ee86-4598-b261-a5c6faa5bf0e)

**Comment by CDrummond** [comment]
Sorry, but this is a Telegram issue - its drawing its controls over the web viewport.

**Comment by Steinchen68** [comment]
I have read that a padding can be transferred in 5.2, which should perhaps solve the problem.

http://server:9000/material/?topPad=32&botPad=12
