### ISSUE TITLE
Random mix no longer working after updating to 5.2.0

### ISSUE THREAD

**Issue by webby1972** [CDrummond/lms-material#932]
I have "Random Mix" pinned on my homepage as this is my preferred way to start listening to music. After updating to MS 5.2.0, the "Random Mix" option stopped working.

Is there a way to make this option work again or otherwise revert to a previous version of MS?

Action: click on "Random Mix" menu option to start listening to music
Expected result: a config popup opens up allowing configuration of mix and start of playback.

**Comment by CDrummond** [comment]
Random Mix does work, as confirmed by posting on slimdevices forum.

I have also just restored 5.0.0, pinned 'Random Mix', reverted to 5.2.0, and my pinned 'Random Mix' still works.

I suggest you un-pin 'Random Mix', fully refresh your browser, and pin 'Random Mix' again. Note however, that 'Random Mix' no longer shows a dialog allowing to start a mix but instead will show a list of saved mixes, with a button in the toolbar to start/save a mix.

**Comment by webby1972** [comment]
I don't have and use "saved mixes" And why change something that works for a lot of people.
