### ISSUE TITLE
Feature Request - Use full screen for background for Browse and Queue

### ISSUE THREAD

**Issue by cirdanlunae** [CDrummond/lms-material#934]
Love how the Playback screen looks on mobile with the fullscreen background. Are there plans in the works for having that same sleak look on Browse and Queue? If there's technical limitations, I understand.

**Comment by CDrummond** [comment]
I had thought about this before, and tried. However, for some (unknown to me) reason the toolbars in the browse/queue view became blurred!

Also, if I did this then it'd always have to be the same image across all 3 views - so always current playing track - and I'm not sure I want that for the browse view. I also kind-of like the browse/queue views being different.

When creating this new look I took inspiration for PowerAmp (an Android music player). With this only the now-playing has the blurred cover, and browse/queue use solid colours.

**Comment by CDrummond** [comment]
With browse I also set the background to that of the current artist/album/etc. So, with that in mind what I _might_ do is:

If using coloured toolbars
  - colour sub-toolbars too
  - colour mobile now-playing bar
If using colour from cover, and using full-screen now-playing, then adjust saturation, etc. of toolbar colour - i.e. get a better colour match.

So this will colour the top toolbars, and bottom navigation when in browse/queue based upon the colour of the current track. This should make things more integrated.

**Comment by cirdanlunae** [comment]
I understand wanting all 3 views to be different. I guess having the same background would make everything very "same-y". 

Sorry if I make you do a bunch of extra experimenting with no real outcome! Appreciate you trying though.

**Comment by CDrummond** [comment]
For 5.3.0 I've added tinting of background colours - which is enough for me.
