### ISSUE TITLE
Make skip backwards/forwards optional

### ISSUE THREAD

**Issue by hmaki** [CDrummond/lms-material#938]
I like using the up and down swipe to control the volume in now playing screen.

On my iPhone this interferes with the skip forward and backward feature as often when I want to control the volume by swiping the skip overlay pops up and I have to wait for it to disappear.

Could the skipping feature be disabled or could there be another way to avoid the overlay popping up inadvertently?

**Comment by CDrummond** [comment]
Not sure about yet another option. Overlay is shown on click, and volume control is on swipe - not sure how you are getting them to conflict. My guess is that you are tapping before starting the swipe, which shows the overlay. I've updated the code, for 5.2.3, so tat you can dismiss the overlay with a click on it - but not of near a button.

**Comment by hmaki** [comment]
I ”studied” my swiping gesture. I seem to have developed a habit of swiping with bit of drag gesture. If I carefully avoided the drag part the overlay doesn’t show up.

I agree, it was a user error, trying to learn away from that bad habit.

Anyways, thanks for allowing to dismiss the overlay.

**Comment by CDrummond** [comment]
Closing, as 5.2.3 will allow tap to close overlay.
