### ISSUE TITLE
Vonerability: "<" and ">" are enterprited as HTML symbols in song titles 

### ISSUE THREAD

**Issue by dryusername** [CDrummond/lms-material#941]
Hi, I noted that Kim Petras song "<demons>" is enteprited as HTML code in the play queue view. This opens up for HTML injections through the play queue view. This is probably not a real issue, but there is a weird special case where someone may queue a podcast episode where the title is a HTML injection, and it being rendered active by the play queue view.

This is probably mainly an inconveniens for all of us with song with "<" and ">" brackets in the title.

The issue only exists in the play queue view.

![Screenshot_20240828-135246](https://github.com/user-attachments/assets/373014e7-ad16-43c9-a35b-dc5242780e3c)
![Screenshot_20240828-135858](https://github.com/user-attachments/assets/a4f73ef3-154f-4004-a793-289848341ce4)
![Screenshot_20240828-135909](https://github.com/user-attachments/assets/ef0a5b95-5270-4255-8f23-bb415b6af9b2)

**Comment by CDrummond** [comment]
Actually this does affect other views. If artist, or album, had HTML tags you would see this in now-playing, and also in browse.

For 5.2.5 I've replaced `>`  and `<` with _similar_ looking unicode characters.
