### ISSUE TITLE
Feature Request - Shortcut to synchronize

### ISSUE THREAD

**Issue by mikeboren** [CDrummond/lms-material#945]
I find myself using synchronize A LOT. Pretty much every day whenever I'm using the system. It would be nice and convenient if there was an icon to go directly to the players synchronize screen. Maybe at the top next to the player name. This would be instead of having to select player > Manage players > player settings (from the 3 dots) > Synchronize

**Comment by CDrummond** [comment]
Long-press on 'Manage players' in player menu will show sync dialog.

If you use sync that much why not use the group players plugin?

**Comment by mikeboren** [comment]
Didn't know about the long press. That's much better. Thanks.

**Comment by CDrummond** [comment]
I assume this is sufficient, so closing.
