### ISSUE TITLE
Feature Request: Additional "details" row for album grid items (i.e "Year" repositioning, "Release type", etc..)

### ISSUE THREAD

**Issue by KaLam1tyAC** [CDrummond/lms-material#947]
Hi CDrummond,

With release types gaining more feature support, I was wondering if it might be a useful option to display an "additional info" row under album grid items -- something that aligns release type with release year and potentially other information. (Could even be clickable?):

_**Proposed functionality:**_
![image](https://github.com/user-attachments/assets/1c47442e-a34b-4a3c-be86-fdf6f497bf80)

Perhaps useful for displaying other potential items like technical info, format/resolution badges, genre, etc... 

Of note, one thing that always bothered me was how the (Year) would often get cut off when aligned with the album name. At least having it on a new row, similar to browsing under an Artist, would allow (Year) to be visible and visually consistent:

_**Current functionality (Under Artists):**_
![image](https://github.com/user-attachments/assets/df2442eb-d98b-4b6d-95dd-90f403e83ce0)

It would inflate the grid items a bit, hence it would be best as a Interface toggle. Text line-height or font size might also be tweaked? Just some thoughts.

----

I got the idea from a few other apps, which we could take inspiration from:
**Spotify:**
![image](https://github.com/user-attachments/assets/617a54a7-f283-4d91-846f-904c3f67a358)
 
**Jplay:**
![image](https://github.com/user-attachments/assets/500a1d54-823b-446d-a1d0-ce106890bdcc)

**Comment by CDrummond** [comment]
If release type is important you can configure Material (via LMS's settings) to always group by release type - and this will affect 'New Releases', 'Releases', etc.

Sorry, but not too keen on adding a 3rd row of text just for release year.
