### ISSUE TITLE
Non-optimal screen layout

### ISSUE THREAD

**Issue by s-timm** [CDrummond/lms-material#948]
Hi!
Again, let me tell you that your Material skin is great! Thank you for the great work!

I have a small issue, and I think it started this summer: the screen layout on my tablet has slightly changed, the left side now has only two columns of album covers and the playlist takes up a lot of screen space (see photo 1). I am using the app on the tablet.

On my laptop, in a browser tab, the screen layout is better (see photo 2). 

Both have different screen resolutions, the tablet has 1920x1200px and the laptop has 1920x1080px.
Is there anything I can do to improve the layout on my tablet?

Thanks!

![20240910_215343](https://github.com/user-attachments/assets/e15ac94f-c38c-46b0-b734-0948db721dc3)
![20240910_215635](https://github.com/user-attachments/assets/b9c1f3e7-d2f7-4f0c-a3c2-91cca0d21f6e)

**Comment by s-timm** [comment]
I just figured out that probably it has something to do with the app, because if I use a browser on the tablet the layout looks correct:
![Uploading 20240910_222403.jpg…]()

**Comment by CDrummond** [comment]
Nothing todo with the app. Use the splitter between queue and browse to resize the views - or simply 'un-pin' the queue (via the '...' menu button in the queue's toolbar).
