### ISSUE TITLE
Minor display issue Now Playing (Desktop)

### ISSUE THREAD

**Issue by d6jg** [CDrummond/lms-material#95]
![image](https://user-images.githubusercontent.com/47001366/55328433-3e59ce80-5484-11e9-9ab3-69b16a6e0ed2.png)

The above image is CORRECT but only after I have edited the album name.

Originally the album in question was tagged as "Take 1, Take 2 ..." - where critically there is a space between the 2 and the three dots

The resultant display when tagged this way was as follows

![image](https://user-images.githubusercontent.com/47001366/55328705-e40d3d80-5484-11e9-8cd1-1f4aa3fef376.png)

I suspect the space followed by the three dots causes some kind of parsing error

**Comment by CDrummond** [comment]
I _think_ those three dots you are seeing are **not** the three periods at the end of your tag. These dots are shown if there is a title, but no artist and no album reported by LMS in the playback status.

They are not 3 period characters, but1 unicode character which is 3 dots (https://graphemica.com/%E2%8B%AF)

**Comment by CDrummond** [comment]
99.9999% sure this is an issue with your files, or info sent from LMS.

**Comment by d6jg** [comment]
Having done some more tests I think you are correct. There was no Artist tag only AlbumArtist but slightly odd the track name didn’t appear either in such circumstances.

Sent from my iPhone





> On 3 Apr 2019, at 17:10, CraigD <notifications@github.com> wrote:
> 
> 99.9999% sure this is an issue with your files, or info sent from LMS.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
Jim Gooch   Director   Double 6 Ltd  Office 0845 508 1950 Mobile 07802 550302 VOIP 8120540@draytel.org Skype double6jg  www.double6.net 

This e-mail may contain information confidential to the addressee(s) only. If a transmission error has misdirected the e-mail, please notify us immediately and then destroy the communication. You should not use, disclose, distribute or copy this communication. Nothing contained in this e-mail shall constitute a legally binding contract unless expressly so stated in which case any contract is subject to Double 6 Limited's General Terms & Conditions. Please ensure that you carry out your own virus checks before opening any attachments contained within this e-mail as, although checked internally before distribution, Double 6 cannot accept responsibility for any damage caused by any software viruses contained in the message or attachments.  All contracts and services provided are subject to Double 6 Limited's  General Terms & Conditions.  Please note that by entering into a contract with Double 6 you accept these General Terms & Conditions in full. ©: Double 6 Ltd - Specialist Lotus Notes and Domino Development & Consultancy : Registered in England No: 3932411   All business is conducted in accordance with Double 6's  General Terms & Conditions.  Purchase and renewal of .UK domains are subject to  Nominet's Terms & Conditions.
