### ISSUE TITLE
Dynamic Playlist used with Material: strange selection text

### ISSUE THREAD

**Issue by the-other-martin** [CDrummond/lms-material#951]
Hi Craig,
using **Material** Plugin together with **Dynamic Playlist** Plugin. 

When trying to start Dynamic Playlist (coming from non Dynamic Playlist playing), the selection Text for the Dynamic Playlist shows
**<div style="margin-top:16px;.....**
instead of
**Custom Dynamic Playlists**
see screenshots. It still is working to use Dynamic Playlist but the slection text is weird.
![grafik](https://github.com/user-attachments/assets/9a7fb136-d447-4ca0-bf0b-376e76938494)

![grafik](https://github.com/user-attachments/assets/d542d214-b08e-4ade-a786-66f53a00d8ef)

PS: this doesn't happen when coming from Dynamic PLaylist already:
![grafik](https://github.com/user-attachments/assets/e0c7aa52-0f07-41b5-887f-fe2aa5e4f001)

**Comment by CDrummond** [comment]
Which version of MaterialSkin is this? If its 5.3.x have you fully refreshed the cache? As a similar issue was fixed.

Also, which dynamic playlists plugin? Erland's old version, or the newer DPL4? And how do I navigate to "Custom Dynamic Playlists"? I'm not a user of either plugin.

**Comment by the-other-martin** [comment]
Material Skin version is 5.3.1Dynamic Playlist version is 4.4.6Tested this issue both on firefox on win10 and Safari on iOSNavigation is throughMy Music/Dynamic PlaylistsMit freundlichem GrußMartin GrossAm 15.09.2024 um 18:05 schrieb CraigD ***@***.***>:﻿
Which version of MaterialSkin is this? If its 5.3.x have you fully refreshed the cache? As a similar issue was fixed.
Also, which dynamic playlists plugin? Erland's old version, or the newer DPL4? And how do I navigate to "Custom Dynamic Playlists"? I'm not a user of either plugin.

**Comment by CDrummond** [comment]
So, DPL4. But I **need** more info on how to show this menu. I do not use this plugin, so have no mixes - do I need some?

When I navigate "My Music/Dynamic Playlists" all I see is "Songs/", "Artists/", etc. No "Custom Dynamic Playlists"

**Comment by CDrummond** [comment]
p.s. I don't doubt there is a problem, and I think I know how to fix - but until I can recreate the issue its hard to tell if the change actually fixes this. But I'm 99.9% sure...

**Comment by the-other-martin** [comment]
Hi Craig,

 

I recognised the following:

I’ve only one active group for dynamic playlists which is “Custom Dynamic Playlist” – everything else de-activated.

I’ve tried to activate one other, in my case “Songs” – and the the entry for “Custom Dynamic Playlist” did show up as expected.

After de-activation of “Songs” again the weird entry is showing up…

 

mit freundlichen Grüßen
Martin Gross

**Comment by CDrummond** [comment]
Ah, so all I needed to trigger this issue was to have a single dynamic playlist group. Can now recreate the issue.

**Comment by the-other-martin** [comment]
many thanks Craig!Mit freundlichem GrußMartin GrossAm 16.09.2024 um 13:17 schrieb CraigD ***@***.***>:﻿
Closed #951 as completed via ff486ca.
