### ISSUE TITLE
Search configuration option

### ISSUE THREAD

**Issue by gstalnaker** [CDrummond/lms-material#959]
Now, by default, when I search my 120,000 track library, the search uses "contains" for its search method. With a library this large that is not optimal. I can go to Advanced Search and with a field's dropdown select "Begins with" which works as expected, for example, with Title. It would be advantageous if I could tell the UI that I'd like searches to use a specific option like 'Begins With" or "Contains." rather than having to go into Advanced Search every time to select such an option.

Thanks

**Comment by CDrummond** [comment]
Sorry, but Material is just using the search function provided by Lyrion. This does not have the controls you are looking for. I suggest you file a feature request with Lyrion.
