### ISSUE TITLE
Drag-and-drop in Favorites not possible

### ISSUE THREAD

**Issue by BeActivated** [CDrummond/lms-material#966]
'Drag-and-drop' an Album or a Folder in Favorites is not possible anymore.

**Comment by CDrummond** [comment]
Yes it is. Disable sorting of favourites. As to being able to drag favourites into folders whilst sort is enabled, that is fixed for 5.4.1

**Comment by BeActivated** [comment]
With update 5.4.1 drag and drop in Favorites is fixed, thank you.
Kind regards,
Wessel Koster

Op ma 21 okt 2024 om 09:06 schreef CraigD ***@***.***>:

**Comment by BeActivated** [comment]
Sorry I made a mistake, albums can be moved by drag and drop but folders
can not be moved.
Kind regards,
Wessel Koster

Op di 22 okt 2024 om 08:34 schreef ***@***.***>:

**Comment by CDrummond** [comment]
**Yes** they can. Disable sorting of favourites.
