### ISSUE TITLE
media keys not working in firefox ?

### ISSUE THREAD

**Issue by czodroid** [CDrummond/lms-material#970]
Hi,

I've gone back to using firefox instead of chrome. I work under linux/debian with firefox 131.0.3.

But the multimedia keys, Play/Pause and Next/Previous songs don't work in firefox.

First, does this work?

I tried to debug the problem... but I couldn't find an answer. It works under youtube, so I checked if silence.ogg was faulty, and the firefox configuration...

I hope it works, and I also hope you can give me a hint?

Thanks!

**Comment by CDrummond** [comment]
Sorry, but I cannot test all combinations. This mediasession support is by its very nature a massive hack. If it works, great, if not that's just the way it is. For WebApps, Chrome is better, for general browsing Firefox 100%.

**Comment by czodroid** [comment]
Can anyone else who has read this issue answer this question?
Does linux/firefox support multimedia play/pause (MPRIS) in lms-material?
