### ISSUE TITLE
synchronize on mobile dos not work

### ISSUE THREAD

**Issue by czodroid** [CDrummond/lms-material#971]
Hi,

In mobile, the "synchronize" view does not work.

If I press a on check_box, it first goes OFF, then on...
If I press Select All, all is OFF, and if I press something on, that goes to OFF...

Thanks

**Comment by CDrummond** [comment]
Already reported on forums.slimdevices.com, and fixed in git for 5.4.2

**Comment by czodroid** [comment]
thanks
