### ISSUE TITLE
Centralisé button

### ISSUE THREAD

**Issue by jcor29** [CDrummond/lms-material#977]
Hi
I have two very large display 2560x1080
Would it bé possible to group all action
present in the upper bar  bar, as such
Left centre or right
It would make thé lms expérience even better
Jacques

**Comment by CDrummond** [comment]
You will need to write some custom CSS for this, see https://github.com/CDrummond/lms-material/wiki/07-Customisation

**Comment by jcor29** [comment]
Ok, thanks for your Reply
Regards
Jacques
