### ISSUE TITLE
5.5.0: Add option to show home-screen shortcuts in navigation drawer.

### ISSUE THREAD

**Issue by TerDale** [CDrummond/lms-material#985]
> 5.5.0: Add option to show home-screen shortcuts in navigation drawer.

Sorry for such a basic question, but I can't find this new option, where is it please?

**Comment by CDrummond** [comment]
Located in "Interface" settings.

GitHub issues are for _issues_, not support requests. Please use forums.slimdevices.com for such questions in future.

**Comment by TerDale** [comment]
Thanks, checked here though missed it...
