### ISSUE TITLE
Make settings more easily reachable

### ISSUE THREAD

**Issue by CDrummond** [CDrummond/lms-material#986]
If a user has lots of players, then all settings items could be off-screen. Need to think how to make these easier to reach;

- Make settings position static, and only scroll player's part?
- Add a 'scroll to settings' button top-right of menu (where logo is) to scroll to settings?
- Have a row of icons for settings at bottom, shown when settings menu entries not visible?

**Comment by czodroid** [comment]
for me:

- Make settings position static, and only scroll player's part?

NO! for people who have a lot of players, like me, I don't often make the settings, but I need to have the maximum number of players available...

- Add a 'scroll to settings' button top-right of menu (where logo is) to scroll to settings?

Why not...

- Have a row of icons for settings at bottom, shown when settings menu entries not visible?

But, one player less...

**Comment by czodroid** [comment]
And because power button is available in menu, It's difficult to me to turn off one player...  
Because you removed Show power button (Replace player's icon in toolbar with a power button.)...
