### ISSUE TITLE
Suggestion: Hotkeys Interaction - Search Library / Advanced Search

### ISSUE THREAD

**Issue by KaLam1tyAC** [CDrummond/lms-material#989]
Maybe it was due to implementation of **_'Search within list'_** or some default behavior change, but I seem to recall that **[Ctrl+F]** was the immediate hotkey to activate **_'Search library'_** in the main 'Music sources' page. The current functionality on web browser (tested with Edge and Chrome) activates as **_'Search within list'_**. 

That's totally valid and working nicely in other pages; but is there some option we could have for the main 'Music sources' page or an alternative hotkey to activate 'Search library' instead of having to click on icon? It also looks like the hotkey tooltip is in conflict with the current behavior anyways (Side note - the current interaction is labeled correctly in other pages):

_Note the 'Music sources' page tooltip is showing **'Search library - Ctrl+F'**..._
![image](https://github.com/user-attachments/assets/5b2b7a8a-2b34-4dce-88f3-7f4f4360aeaa)
_...but it brings up **'Search within list'**, instead._
![image](https://github.com/user-attachments/assets/c12189ac-2434-427e-b051-2df76814caab)

On an additional note, I think it would be useful to have a hotkey for **_'Advanced Search'_** pop-up itself, instead of having to click multiple times and navigate through **... > _'Search library'_** > **_'Advanced Search'_**
![image](https://github.com/user-attachments/assets/099c04dd-60a2-4657-bfcc-9784258a8e7d)

FWIW, Material Skin on Squeezelite-X activates _**'Search Library'**_ as how I remembered. If not an alternative hotkey, maybe repeated **[Ctrl+F]** inputs could cycle through the different search options as if clicking the button multiple times?

**Comment by CDrummond** [comment]
The 'Ctrl+F' issue is fixed for 5.5.2, and I've added 'Alt+F' as shortcut for advanced search for 5.6.0
