### ISSUE TITLE
My music lists does not show all utf-8 letters correctly

### ISSUE THREAD

**Issue by patapovich** [CDrummond/lms-material#99]
My music library contains artists and albums with cyrillic and and scandic(ö,å,ä) letters in names.
There seems to be encoding error for all lists views (a-z) for names containing specific letters.

![image](https://user-images.githubusercontent.com/6716511/55679579-ba399800-5916-11e9-8a5e-f709eacef3ac.png)
![image](https://user-images.githubusercontent.com/6716511/55679595-ece39080-5916-11e9-9701-d02ceeb5b082.png)

Logitech Media Server Version: 7.9.1 - 0.6.20170928git1508251793 @ Tue Oct 17 20:32:23 EDT 2017
Hostname: lms
Server IP Address: 192.168.1.217
Server HTTP Port Number: 9000
Operating system: Red Hat - EN - utf8
Platform Architecture: x86_64-linux
Perl Version: 5.22.2 - x86_64-linux-thread-multi
Audio::Scan: 0.95
Database Version: DBD::SQLite 1.34_01 (sqlite 3.7.7.1)
Total Players Recognized: 2

**Comment by CDrummond** [comment]
These 'letters' are provided by LMS. This looks like the issue mentioned in https://forums.slimdevices.com/showthread.php?109624-Announce-Material-Skin/ pages 27, 29, etc. LMS was fixed to properly encode the characters, so you need to update your LMS install.
