### ISSUE TITLE
Works grouping for play queue

### ISSUE THREAD

**Issue by darrell-k** [CDrummond/lms-material#992]
Could the toggled version of the play queue group by Work within Album?

**Comment by CDrummond** [comment]
Implemented in master using work_id + performance. Seems to work for me, can you test?

**Comment by darrell-k** [comment]
Yes, it's working, but could we incorporate the work name into the title (maybe before the Album name)? And I have a work which continues onto disc 2 of a 2 disc release, so the heading appears twice. Can you do anything about that, or is the answer to tell people to tag the release as a single disc? (in the Qobuz plugin album browse, I ignore disc 1/disc 2 etc if we've got works).

**Comment by darrell-k** [comment]
Thinking about this with respect to classical works like operas and ballets, where there's a 3 level hierarchy: 

Work -- Act -- track

instead of 

Work -- track

Post LMS9.0 we're going to attempt to handle this, but it's too late for the 9.0 release. For now there's a workaround:

The user can ignore the physical discs and instead number each act of the opera or scene of the ballet as a separate disc, and then use DISCSUBTITLE for the text.

So maybe not include the disc number ignore for now? We can tell people who hit the split work issue I described to retag the album as all one disc.

**Comment by darrell-k** [comment]
Or even better, keep https://github.com/CDrummond/lms-material/commit/fb461ff397f567d19415d116f519c4066dcae31a but also implement a split in the play queue and tracks browse on the GROUPING tag which I'm pretty sure we're already providing in the tracks command response. (As I said, implementing this for the Default Skin UI is going to have to wait).

**Comment by CDrummond** [comment]
Sorry - but what? Split on work_id, performance, **and** grouping? 3 extra tags just for Classical stuff????

**Comment by darrell-k** [comment]
Well, yes. Classical music is inherently more complicated than album/track (especially when most classical discs contain multiple works and career-spanning box sets for well-known artists will only get more common as the record companies keep repackaging their ever-growing back catalogues...)  

I'm pretty sure that when LMS9 is released, though, we'll slowly build up an enthusiastic user base amongst classical collectors, because although I say it myself, we've created something really good here.

The Grouping thing could also be used for other genres: Side1/Side2 or Original Album/Bonus Tracks, etc.

**Comment by CDrummond** [comment]
And as stated, I have no such music, hence why this is getting tedious - too many changes for an area I have no need for.

Anyhow, I've added splitting on grouping. So, is this done now?

**Comment by darrell-k** [comment]
Thanks, Craig. I'll test it and if I find any issues I'll try to create PRs.

**Comment by darrell-k** [comment]
Needs tweaking a bit, will get a PR in ASAP
